begin;select plan(23);
select ok(to_regclass('public.business_workspaces') is not null,'business workspaces exist');
select ok(to_regclass('public.business_workspace_memberships') is not null,'workspace memberships exist');
select ok(to_regclass('public.business_workspace_events') is not null,'workspace evidence exists');
select ok((select relrowsecurity from pg_class where oid='public.business_workspaces'::regclass),'workspaces use RLS');
select ok((select relrowsecurity from pg_class where oid='public.business_workspace_memberships'::regclass),'memberships use RLS');
select ok((select relrowsecurity from pg_class where oid='public.business_workspace_events'::regclass),'workspace evidence uses RLS');
select ok(not has_table_privilege('authenticated','public.business_workspaces','INSERT'),'browser cannot forge workspaces');
select ok(not has_table_privilege('authenticated','public.business_workspace_memberships','INSERT'),'browser cannot forge membership');
select ok(not has_table_privilege('authenticated','public.business_workspace_memberships','UPDATE'),'browser cannot elevate roles');
select ok(has_function_privilege('authenticated','public.create_business_workspace(text,text)','EXECUTE'),'authenticated customer may create bounded workspace');
select ok(not has_function_privilege('anon','public.create_business_workspace(text,text)','EXECUTE'),'anonymous workspace creation is blocked');
select ok(exists(select 1 from pg_trigger where tgname='business_workspace_events_append_only' and not tgisinternal),'workspace evidence is append-only');
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values('00000000-0000-4000-8000-000000000051','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase4q@example.test','',now(),now(),now(),'{}','{}');
select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000051',true);
select is((public.create_business_workspace('TradePulse Research','tradepulse-research')).status,'setup','workspace begins in setup');
select is((select role from public.business_workspace_memberships where user_id=auth.uid()),'owner','creator becomes owner');
select is((select seat_limit from public.business_workspaces where owner_user_id=auth.uid()),3::smallint,'workspace begins with bounded seats');
select is((select count(*) from public.business_workspace_events where actor_user_id=auth.uid() and event_type='workspace_created'),1::bigint,'creation evidence is recorded');
select throws_ok($$select public.create_business_workspace('Another Workspace','another-workspace')$$,'P0001','An owned workspace already exists','one owned workspace is enforced');
select throws_ok($$update public.business_workspace_events set event_type='membership_changed' where actor_user_id=auth.uid()$$,'P0001','Business workspace evidence is append-only','evidence cannot be rewritten');
select ok(to_regclass('public.workspace_invitations') is null,'invitations remain disabled');
select ok(to_regclass('public.organization_billing_accounts') is null,'organization billing remains absent');
select ok(to_regclass('public.payment_transactions') is null,'payment execution remains absent');
select is((select count(*) from public.broker_provider_registry where live_order_routing_enabled),0::bigint,'live broker routes remain disabled');
select is((select execution_enabled from public.brokerage_execution_controls where control_key='global-live-orders'),false,'global execution remains disabled');
select * from finish();rollback;
