begin;
select plan(50);

select ok(to_regclass('public.controlled_live_rollout_controls') is not null,'controls exist');
select ok(to_regclass('public.controlled_live_rollout_cohorts') is not null,'cohorts exist');
select ok(to_regclass('public.controlled_live_rollout_limit_policies') is not null,'limits exist');
select ok(to_regclass('public.controlled_live_rollout_scope_decisions') is not null,'scope decisions exist');
select ok(to_regclass('public.controlled_live_rollout_requirements') is not null,'requirements exist');
select ok(to_regclass('public.controlled_live_rollout_gate_reviews') is not null,'gate reviews exist');
select ok(to_regclass('public.controlled_live_rollout_drill_templates') is not null,'drill templates exist');
select ok(to_regclass('public.controlled_live_rollout_drill_observations') is not null,'drill evidence exists');
select ok(to_regclass('public.controlled_live_rollout_decision_ledger') is not null,'decision ledger exists');
select ok(to_regclass('public.controlled_live_rollout_status') is not null,'status view exists');
select ok(to_regclass('public.controlled_live_rollout_cohort_catalog') is not null,'cohort view exists');
select ok(to_regclass('public.controlled_live_rollout_limit_catalog') is not null,'limit view exists');
select ok(to_regclass('public.controlled_live_rollout_gate_catalog') is not null,'gate view exists');
select ok(to_regclass('public.controlled_live_rollout_drill_catalog') is not null,'drill view exists');
select is((select count(*) from public.controlled_live_rollout_controls),1::bigint,'one policy');
select is((select rollout_status from public.controlled_live_rollout_controls),'approval_required','approval required');
select is((select live_cohort_count from public.controlled_live_rollout_controls),0,'zero live cohorts');
select ok((select manual_signed_activation_required from public.controlled_live_rollout_controls),'signed activation required');
select ok(not exists(select 1 from public.controlled_live_rollout_controls where broker_connectivity_enabled or exchange_connectivity_enabled or live_market_data_enabled or live_order_routing_enabled or customer_funding_enabled or custody_enabled or settlement_enabled or margin_enabled or options_enabled or automatic_activation_enabled),'all production paths disabled');
select is((select count(*) from public.controlled_live_rollout_cohorts),3::bigint,'three candidates');
select is((select count(distinct residency_country) from public.controlled_live_rollout_cohorts),3::bigint,'three residencies');
select is((select count(distinct mic_code) from public.controlled_live_rollout_cohorts),3::bigint,'three venues');
select ok((select bool_and(account_type='cash' and asset_class='equity') from public.controlled_live_rollout_cohorts),'cash equities only');
select ok((select bool_and(activation_status='blocked' and not production_enabled) from public.controlled_live_rollout_cohorts),'all cohorts blocked');
select ok((select bool_and(maximum_customer_count<=25) from public.controlled_live_rollout_cohorts),'small cohorts');
select is((select count(*) from public.controlled_live_rollout_limit_policies),3::bigint,'three limit policies');
select ok((select bool_and(maximum_order_notional<=3000 and maximum_daily_notional<=15000) from public.controlled_live_rollout_limit_policies),'conservative notionals');
select ok((select bool_and(maximum_position_concentration_pct<=10) from public.controlled_live_rollout_limit_policies),'concentration capped');
select ok((select bool_and(maximum_funding_credit=0 and enforcement_mode='rehearsal_only' and not production_effect) from public.controlled_live_rollout_limit_policies),'limits cannot fund or execute');
select is((select count(*) from public.controlled_live_rollout_scope_decisions),30::bigint,'ten decisions per cohort');
select is((select count(distinct scope_dimension) from public.controlled_live_rollout_scope_decisions),10::bigint,'ten dimensions');
select ok((select bool_and(decision_status='review_required' and not approval_inherited and not production_effect) from public.controlled_live_rollout_scope_decisions),'decisions do not propagate');
select is((select count(*) from public.controlled_live_rollout_requirements),18::bigint,'eighteen gates');
select ok((select bool_and(written_approval_required and expiring_evidence_required and independently_blocking) from public.controlled_live_rollout_requirements),'all gates independently blocking');
select is((select count(*) from public.controlled_live_rollout_gate_reviews),54::bigint,'every gate per cohort');
select ok((select bool_and(review_status='evidence_missing' and evidence_count=0 and not approval_effect) from public.controlled_live_rollout_gate_reviews),'no approval fabricated');
select is((select count(*) from public.controlled_live_rollout_drill_templates),4::bigint,'four drills');
select is((select count(*) from public.controlled_live_rollout_drill_observations),0::bigint,'no observed drill fabricated');
select is((select count(*) from public.controlled_live_rollout_decision_ledger),3::bigint,'blocked candidate decisions recorded');
select ok((select bool_and(decision_status='blocked' and signed_approval_reference is null and not activation_effect) from public.controlled_live_rollout_decision_ledger),'ledger cannot activate');
select is((select candidate_cohort_count from public.controlled_live_rollout_status),3,'status counts candidates');
select is((select requirement_count from public.controlled_live_rollout_status),18,'status counts gates');
select is((select observed_drill_count from public.controlled_live_rollout_status),0,'status reports no drills');
select ok((select bool_and(open_scope_decision_count=10 and blocking_gate_count=18) from public.controlled_live_rollout_cohort_catalog),'catalog shows gaps');
select ok((select bool_and(observed_count=0) from public.controlled_live_rollout_drill_catalog),'drill catalog honest');
select ok(has_table_privilege('anon','public.controlled_live_rollout_cohort_catalog','SELECT'),'public cohort transparency');
select ok(not has_column_privilege('anon','public.controlled_live_rollout_drill_observations','evidence_digest','SELECT'),'digest remains private');
select ok(not has_table_privilege('authenticated','public.controlled_live_rollout_decision_ledger','INSERT'),'browser cannot forge decisions');
select ok(to_regprocedure('public.activate_controlled_live_rollout(jsonb)') is null,'no activation RPC');
select ok(to_regprocedure('public.route_controlled_live_order(jsonb)') is null,'no routing RPC');

select * from finish();
rollback;
