begin;
select plan(18);
select ok(to_regclass('public.customer_support_requests') is not null,'support intake exists');
select ok((select relrowsecurity from pg_class where oid='public.customer_support_requests'::regclass),'support intake uses RLS');
select ok(exists(select 1 from pg_trigger where tgname='customer_support_requests_protected' and not tgisinternal),'support history is protected');
select ok(not has_table_privilege('authenticated','public.customer_support_requests','INSERT'),'browser cannot directly forge requests');
select ok(not has_table_privilege('authenticated','public.customer_support_requests','UPDATE'),'browser cannot change support status');
select ok(has_function_privilege('authenticated','public.submit_customer_support_request(text,text,text,smallint)','EXECUTE'),'authenticated customer may submit bounded request');
select ok(not has_function_privilege('anon','public.submit_customer_support_request(text,text,text,smallint)','EXECUTE'),'anonymous support submission is blocked');
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values('00000000-0000-4000-8000-000000000050','00000000-0000-0000-0000-000000000000','authenticated','authenticated','phase4p@example.test','',now(),now(),now(),'{}','{}');
select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000050',true);
select is((public.submit_customer_support_request('product_feedback','Useful dashboard','Please add more comparison controls.',5)).status,'submitted','feedback is submitted');
select like((select support_reference from public.customer_support_requests where user_id=auth.uid()),'TP-%','customer receives support reference');
select is((select customer_rating from public.customer_support_requests where user_id=auth.uid()),5::smallint,'optional rating is retained');
select throws_ok($$select public.submit_customer_support_request('unknown','Valid subject','This message is long enough.',null)$$,'P0001','Unsupported support request type','unsupported type is rejected');
select throws_ok($$select public.submit_customer_support_request('bug','No','This message is long enough.',null)$$,'P0001','Support request content is outside allowed limits','short subject is rejected');
select throws_ok($$update public.customer_support_requests set status='resolved' where user_id=auth.uid()$$,'P0001','Customer support history is protected','customer cannot mutate history');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='customer_support_requests' and column_name ~ '(password|credential|api_key|ip_address|user_agent|device_id|attachment|payload)'),'support table excludes credentials and tracking fields');
select ok(to_regclass('public.payment_transactions') is null,'payment execution remains absent');
select is((select count(*) from public.broker_provider_registry where live_order_routing_enabled),0::bigint,'live broker routes remain disabled');
select is((select execution_enabled from public.brokerage_execution_controls where control_key='global-live-orders'),false,'global execution remains disabled');
select is((select count(*) from public.investment_instruments where live_execution_enabled),0::bigint,'instrument execution remains disabled');
select * from finish();rollback;
