import { supabase } from '../supabase/client'
import { getBusinessTeamAccess,type WorkspaceRole } from './businessWorkspaces'
export type ResearchInstrument={id:number;symbol:string;name:string}
export type SharedResearchItem={id:string;collectionId:string;instrumentId:number;thesis:string;stance:'watch'|'positive'|'neutral'|'cautious';instrument:ResearchInstrument|null}
export type SharedResearchCollection={id:string;workspaceId:string;name:string;description:string;revision:number;items:SharedResearchItem[]}
type CollectionRow={id:string;workspace_id:string;name:string;description:string;revision:number}
type ItemRow={id:string;collection_id:string;instrument_id:number;thesis:string;research_stance:SharedResearchItem['stance'];investment_instruments:{id:number;display_symbol:string;name:string}|null}
export async function getBusinessResearch(){const access=await getBusinessTeamAccess();const workspace=access.workspaces[0]??null;if(!workspace)return{workspace:null,collections:[],instruments:[]};const[collectionsResult,itemsResult,instrumentsResult]=await Promise.all([supabase.from('business_research_collections').select('id,workspace_id,name,description,revision').eq('workspace_id',workspace.id).order('updated_at',{ascending:false}),supabase.from('business_research_items').select('id,collection_id,instrument_id,thesis,research_stance,investment_instruments(id,display_symbol,name)').order('updated_at',{ascending:false}),supabase.from('investment_instruments').select('id,display_symbol,name').eq('research_enabled',true).order('display_symbol').limit(100)]);if(collectionsResult.error)throw collectionsResult.error;if(itemsResult.error)throw itemsResult.error;if(instrumentsResult.error)throw instrumentsResult.error;const items=(itemsResult.data as unknown as ItemRow[]).map(row=>({id:row.id,collectionId:row.collection_id,instrumentId:row.instrument_id,thesis:row.thesis,stance:row.research_stance,instrument:row.investment_instruments?{id:row.investment_instruments.id,symbol:row.investment_instruments.display_symbol,name:row.investment_instruments.name}:null}));return{workspace,collections:(collectionsResult.data as CollectionRow[]).map(row=>({id:row.id,workspaceId:row.workspace_id,name:row.name,description:row.description,revision:row.revision,items:items.filter(item=>item.collectionId===row.id)})),instruments:(instrumentsResult.data??[]).map(row=>({id:row.id,symbol:row.display_symbol,name:row.name})) as ResearchInstrument[]}}
export function canEditResearch(role:WorkspaceRole){return['owner','admin','analyst'].includes(role)}
export async function createSharedResearchCollection(workspaceId:string,name:string,description:string){const{error}=await supabase.rpc('create_business_research_collection',{p_workspace_id:workspaceId,p_name:name,p_description:description});if(error)throw error}
export async function saveSharedResearchItem(collectionId:string,instrumentId:number,thesis:string,stance:SharedResearchItem['stance']){const{error}=await supabase.rpc('upsert_business_research_item',{p_collection_id:collectionId,p_instrument_id:instrumentId,p_thesis:thesis,p_research_stance:stance});if(error)throw error}
