import { Building2,CheckCircle2,ShieldCheck,UserMinus,UserPlus,Users } from 'lucide-react'
import { useCallback,useEffect,useState } from 'react'
import { useAuth } from '../lib/auth/AuthProvider'
import { acceptBusinessInvitation,createBusinessWorkspace,getBusinessTeamAccess,inviteBusinessMember,removeBusinessMember,type BusinessWorkspace,type WorkspaceInvitation,type WorkspaceMember } from '../lib/queries/businessWorkspaces'

export function BusinessWorkspacePanel(){
  const{session}=useAuth();const[items,setItems]=useState<BusinessWorkspace[]>([]);const[invitations,setInvitations]=useState<WorkspaceInvitation[]>([]);const[members,setMembers]=useState<WorkspaceMember[]>([]);const[userId,setUserId]=useState('');const[email,setEmail]=useState('');const[name,setName]=useState('');const[slug,setSlug]=useState('');const[inviteEmail,setInviteEmail]=useState('');const[inviteRole,setInviteRole]=useState<WorkspaceInvitation['role']>('analyst');const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null)
  const refresh=useCallback(async()=>{if(!session)return;try{const data=await getBusinessTeamAccess();setItems(data.workspaces);setInvitations(data.invitations);setMembers(data.members);setUserId(data.userId);setEmail(data.email);setError(null)}catch{setError('Business team access could not be loaded.')}},[session]);useEffect(()=>{void refresh()},[refresh]);if(!session)return null
  const act=async(action:()=>Promise<void>,success:string)=>{setLoading(true);setError(null);setNotice(null);try{await action();setNotice(success);await refresh()}catch{setError('The team-access change could not be completed safely.')}finally{setLoading(false)}}
  const incoming=invitations.filter(invite=>invite.email===email&&invite.status==='pending'&&new Date(invite.expiresAt)>new Date());const workspace=items[0];const canAdmin=workspace&&['owner','admin'].includes(workspace.role);const workspaceMembers=workspace?members.filter(member=>member.workspaceId===workspace.id):[];const outgoing=workspace?invitations.filter(invite=>invite.workspaceId===workspace.id):[]
  return <section className="panel business-workspace-panel"><div className="panel-header"><div><p className="eyebrow">Team access · Phase 4R</p><h2>Business workspace</h2></div><span className="status-badge"><ShieldCheck size={14}/> Role protected</span></div><p className="panel-description">Manage bounded, in-app team access. Invitations match the exact signed-in email; TradePulse does not send external invitation email yet.</p>{error&&<p className="error-message" role="alert">{error}</p>}{notice&&<p className="success-message" role="status">{notice}</p>}
    {incoming.map(invite=><div className="workspace-invite" key={invite.id}><UserPlus size={18}/><div><strong>{invite.workspace?.name??'Business workspace'}</strong><span>Invited as {invite.role}</span></div><button className="secondary-button" disabled={loading} onClick={()=>void act(()=>acceptBusinessInvitation(invite.id),'Invitation accepted.')}>Accept</button></div>)}
    {!workspace?<div className="workspace-create"><label><span>Organization name</span><input value={name} minLength={3} maxLength={80} onChange={event=>{setName(event.target.value);if(!slug)setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48))}}/></label><label><span>Workspace slug</span><input value={slug} minLength={3} maxLength={48} pattern="[a-z0-9][a-z0-9-]{2,47}" onChange={event=>setSlug(event.target.value.toLowerCase())}/></label><button className="primary-button" disabled={loading||name.trim().length<3||slug.length<3} onClick={()=>void act(()=>createBusinessWorkspace(name,slug),'Business workspace created with you as owner.')}><Building2 size={16}/> Create workspace</button></div>:<><div className="workspace-list"><article><Building2 size={20}/><div><strong>{workspace.name}</strong><span>{workspace.slug} · {workspace.role}</span></div><span className="workspace-seats"><Users size={15}/> {workspaceMembers.filter(member=>member.status==='active').length} / {workspace.seatLimit} seats</span><CheckCircle2 size={18}/></article></div>{canAdmin&&<div className="workspace-invite-form"><label><span>Member email</span><input type="email" value={inviteEmail} maxLength={254} onChange={event=>setInviteEmail(event.target.value)}/></label><label><span>Role</span><select value={inviteRole} onChange={event=>setInviteRole(event.target.value as WorkspaceInvitation['role'])}><option value="admin">Admin</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option></select></label><button className="secondary-button" disabled={loading||!inviteEmail.includes('@')} onClick={()=>void act(()=>inviteBusinessMember(workspace.id,inviteEmail,inviteRole),'In-app invitation created for seven days.')}><UserPlus size={16}/> Create invitation</button></div>}<div className="workspace-members"><h3>Members and invitations</h3>{workspaceMembers.map(member=><div key={member.userId}><span>{member.userId===userId?'You':`Member ${member.userId.slice(0,8)}`}</span><strong>{member.role}</strong>{canAdmin&&member.role!=='owner'&&<button aria-label="Remove member" disabled={loading} onClick={()=>void act(()=>removeBusinessMember(workspace.id,member.userId),'Member access removed.')}><UserMinus size={15}/></button>}</div>)}{outgoing.filter(invite=>invite.status==='pending').map(invite=><div key={invite.id}><span>{invite.email}</span><strong>{invite.role} · pending</strong></div>)}</div></>}
    <p className="data-source-note"><ShieldCheck size={14}/> Seat limits and role changes are enforced by authenticated database functions. Organization billing, shared portfolios and trading remain disabled.</p></section>
}
