-- TradePulse AI
-- Migration 001: Core database foundation
-- Phase 3: Database foundation

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  iso_code text not null unique,
  name text not null,
  region text,
  created_at timestamptz not null default now()
);

create table if not exists public.market_assets (
  id bigint generated by default as identity primary key,
  symbol text not null unique,
  name text not null,
  asset_type text not null,
  currency text,
  created_at timestamptz not null default now()
);

create index if not exists idx_countries_region
  on public.countries(region);

create index if not exists idx_market_assets_type
  on public.market_assets(asset_type);

alter table public.countries enable row level security;
alter table public.market_assets enable row level security;

create policy "Public can read countries"
  on public.countries
  for select
  to anon, authenticated
  using (true);

create policy "Public can read market assets"
  on public.market_assets
  for select
  to anon, authenticated
  using (true);
