-- TradePulse AI
-- Migration 002: Market and trade data foundation

create table if not exists public.trade_observations (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  period_date date not null,
  exports_usd numeric(20,2),
  imports_usd numeric(20,2),
  trade_balance_usd numeric(20,2),
  source text,
  created_at timestamptz not null default now(),
  unique(country_id, period_date)
);

create table if not exists public.market_observations (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  observed_at timestamptz not null,
  price numeric(20,8),
  change_percent numeric(12,6),
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.data_sources (
  id bigint generated by default as identity primary key,
  name text not null unique,
  source_type text not null,
  base_url text,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_trade_observations_country_date
  on public.trade_observations(country_id, period_date desc);

create index if not exists idx_market_observations_asset_time
  on public.market_observations(asset_id, observed_at desc);

create index if not exists idx_data_sources_enabled
  on public.data_sources(enabled);

alter table public.trade_observations enable row level security;
alter table public.market_observations enable row level security;
alter table public.data_sources enable row level security;

create policy "Public can read trade observations"
  on public.trade_observations
  for select
  to anon, authenticated
  using (true);

create policy "Public can read market observations"
  on public.market_observations
  for select
  to anon, authenticated
  using (true);

create policy "Public can read data sources"
  on public.data_sources
  for select
  to anon, authenticated
  using (true);
