-- TradePulse AI
-- Migration 005: Phase 1 product and operations foundation

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  plan text not null default 'free' check (plan in ('free', 'pro', 'business')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.watchlist_items (
  id bigint generated by default as identity primary key,
  watchlist_id bigint not null references public.watchlists(id) on delete cascade,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (watchlist_id, asset_id)
);

create table if not exists public.market_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  condition text not null check (
    condition in ('price_above', 'price_below', 'change_above', 'change_below')
  ),
  target_value numeric(20,8) not null,
  enabled boolean not null default true,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.data_sync_runs (
  id bigint generated by default as identity primary key,
  source_name text not null,
  dataset text not null,
  status text not null check (status in ('running', 'completed', 'failed', 'partial')),
  records_read integer not null default 0 check (records_read >= 0),
  records_written integer not null default 0 check (records_written >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_summary text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_watchlists_user
  on public.watchlists(user_id);

create index if not exists idx_watchlist_items_watchlist
  on public.watchlist_items(watchlist_id);

create index if not exists idx_market_alerts_user_enabled
  on public.market_alerts(user_id, enabled);

create index if not exists idx_data_sync_runs_source_started
  on public.data_sync_runs(source_name, started_at desc);

create unique index if not exists idx_market_observations_source_timestamp
  on public.market_observations(asset_id, observed_at, source);

create unique index if not exists idx_watchlists_one_default_per_user
  on public.watchlists(user_id)
  where is_default;

alter table public.profiles enable row level security;
alter table public.watchlists enable row level security;
alter table public.watchlist_items enable row level security;
alter table public.market_alerts enable row level security;
alter table public.data_sync_runs enable row level security;

create policy "Users can read their profile"
  on public.profiles for select to authenticated
  using (id = auth.uid());

create policy "Users can update their profile"
  on public.profiles for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

revoke update on public.profiles from authenticated;
grant update (display_name) on public.profiles to authenticated;

create policy "Users manage their watchlists"
  on public.watchlists for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "Users manage their watchlist items"
  on public.watchlist_items for all to authenticated
  using (
    exists (
      select 1
      from public.watchlists
      where watchlists.id = watchlist_items.watchlist_id
        and watchlists.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.watchlists
      where watchlists.id = watchlist_items.watchlist_id
        and watchlists.user_id = auth.uid()
    )
  );

create policy "Users manage their market alerts"
  on public.market_alerts for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create or replace function public.enforce_watchlist_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_plan text;
  current_count integer;
  allowed_count integer;
begin
  select plan into current_plan
  from public.profiles
  where id = new.user_id
  for update;

  if current_plan is null then
    raise exception 'A user profile is required before creating a watchlist';
  end if;

  allowed_count := case current_plan
    when 'business' then 50
    when 'pro' then 10
    else 1
  end;

  select count(*) into current_count
  from public.watchlists
  where user_id = new.user_id;

  if current_count >= allowed_count then
    raise exception 'Watchlist limit reached for the current plan';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_watchlist_item_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid;
  current_plan text;
  current_count integer;
  allowed_count integer;
begin
  select user_id into owner_id
  from public.watchlists
  where id = new.watchlist_id;

  select plan into current_plan
  from public.profiles
  where id = owner_id
  for update;

  allowed_count := case current_plan
    when 'business' then 250
    when 'pro' then 50
    else 5
  end;

  select count(*) into current_count
  from public.watchlist_items item
  join public.watchlists watchlist on watchlist.id = item.watchlist_id
  where watchlist.user_id = owner_id;

  if current_count >= allowed_count then
    raise exception 'Watchlist asset limit reached for the current plan';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_market_alert_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_plan text;
  current_count integer;
  allowed_count integer;
begin
  select plan into current_plan
  from public.profiles
  where id = new.user_id
  for update;

  allowed_count := case current_plan
    when 'business' then 100
    when 'pro' then 25
    else 3
  end;

  select count(*) into current_count
  from public.market_alerts
  where user_id = new.user_id;

  if current_count >= allowed_count then
    raise exception 'Market alert limit reached for the current plan';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_watchlist_limit_trigger on public.watchlists;
create trigger enforce_watchlist_limit_trigger
  before insert on public.watchlists
  for each row execute function public.enforce_watchlist_limit();

drop trigger if exists enforce_watchlist_item_limit_trigger on public.watchlist_items;
create trigger enforce_watchlist_item_limit_trigger
  before insert on public.watchlist_items
  for each row execute function public.enforce_watchlist_item_limit();

drop trigger if exists enforce_market_alert_limit_trigger on public.market_alerts;
create trigger enforce_market_alert_limit_trigger
  before insert on public.market_alerts
  for each row execute function public.enforce_market_alert_limit();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;

  insert into public.watchlists (user_id, name, is_default)
  values (new.id, 'My Watchlist', true)
  on conflict (user_id, name) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, display_name)
select
  users.id,
  coalesce(users.raw_user_meta_data ->> 'full_name', '')
from auth.users users
on conflict (id) do nothing;

insert into public.watchlists (user_id, name, is_default)
select profiles.id, 'My Watchlist', true
from public.profiles profiles
where not exists (
  select 1
  from public.watchlists
  where watchlists.user_id = profiles.id
)
on conflict (user_id, name) do nothing;

create or replace view public.latest_market_snapshot
with (security_invoker = true)
as
select distinct on (asset.id)
  asset.id as asset_id,
  asset.symbol,
  asset.name,
  asset.asset_type,
  asset.currency,
  observation.observed_at,
  observation.price,
  observation.change_percent,
  observation.source
from public.market_assets asset
left join public.market_observations observation
  on observation.asset_id = asset.id
order by asset.id, observation.observed_at desc nulls last;

grant select on public.latest_market_snapshot to anon, authenticated;

comment on table public.data_sync_runs is
  'Operational audit trail for server-side provider ingestion. Never store provider secrets here.';

comment on view public.latest_market_snapshot is
  'Most recent verified observation per configured market asset.';

insert into public.data_sources (name, source_type, base_url, enabled)
values ('Frankfurter', 'fx_reference_rates', 'https://api.frankfurter.dev/v2', true)
on conflict (name) do update
set
  source_type = excluded.source_type,
  base_url = excluded.base_url;
