-- TradePulse AI
-- Migration 006: Phase 2 forecasting and cross-border payment foundations
-- Payment execution remains disabled until licensed providers and compliance controls exist.

create table if not exists public.forecast_runs (
  id bigint generated by default as identity primary key,
  model_name text not null,
  model_version text not null,
  status text not null check (status in ('running', 'completed', 'failed', 'partial')),
  training_window integer not null check (training_window > 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_summary text,
  metrics jsonb not null default '{}'::jsonb
);

create table if not exists public.market_forecasts (
  id bigint generated by default as identity primary key,
  forecast_run_id bigint not null references public.forecast_runs(id) on delete cascade,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  model_name text not null,
  horizon_hours integer not null check (horizon_hours > 0),
  generated_at timestamptz not null default now(),
  target_at timestamptz not null,
  predicted_price numeric(20,8) not null check (predicted_price >= 0),
  lower_bound numeric(20,8),
  upper_bound numeric(20,8),
  confidence_score numeric(5,4) check (
    confidence_score is null or confidence_score between 0 and 1
  ),
  direction text not null check (direction in ('up', 'down', 'flat')),
  is_latest boolean not null default true,
  feature_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (
    lower_bound is null
    or upper_bound is null
    or lower_bound <= predicted_price and predicted_price <= upper_bound
  )
);

create table if not exists public.payment_corridors (
  id bigint generated by default as identity primary key,
  code text not null unique,
  source_currency text not null check (source_currency ~ '^[A-Z]{3}$'),
  destination_currency text not null check (destination_currency ~ '^[A-Z]{3}$'),
  fx_symbol text not null references public.market_assets(symbol),
  rate_operation text not null default 'direct' check (
    rate_operation in ('direct', 'inverse')
  ),
  spread_bps numeric(8,2) not null default 0 check (spread_bps >= 0),
  variable_fee_bps numeric(8,2) not null default 0 check (variable_fee_bps >= 0),
  fixed_fee numeric(20,2) not null default 0 check (fixed_fee >= 0),
  minimum_fee numeric(20,2) not null default 0 check (minimum_fee >= 0),
  settlement_minutes integer not null default 1440 check (settlement_minutes > 0),
  enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (source_currency <> destination_currency)
);

create table if not exists public.payment_quotes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  corridor_id bigint not null references public.payment_corridors(id),
  source_amount numeric(20,2) not null check (source_amount > 0),
  reference_rate numeric(20,8) not null check (reference_rate > 0),
  customer_rate numeric(20,8) not null check (customer_rate > 0),
  variable_fee numeric(20,2) not null check (variable_fee >= 0),
  fixed_fee numeric(20,2) not null check (fixed_fee >= 0),
  total_fee numeric(20,2) not null check (total_fee >= 0),
  destination_amount numeric(20,2) not null check (destination_amount >= 0),
  status text not null default 'indicative' check (
    status in ('indicative', 'expired', 'accepted', 'cancelled')
  ),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_intents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  quote_id uuid not null unique references public.payment_quotes(id),
  idempotency_key text not null unique,
  provider_name text,
  provider_reference text,
  status text not null default 'disabled' check (
    status in (
      'disabled',
      'compliance_review',
      'ready',
      'submitted',
      'settled',
      'failed',
      'cancelled'
    )
  ),
  compliance_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_forecast_runs_started
  on public.forecast_runs(started_at desc);

create index if not exists idx_market_forecasts_asset_generated
  on public.market_forecasts(asset_id, generated_at desc);

create unique index if not exists idx_market_forecasts_latest
  on public.market_forecasts(asset_id, horizon_hours)
  where is_latest;

create index if not exists idx_payment_quotes_user_created
  on public.payment_quotes(user_id, created_at desc);

create index if not exists idx_payment_intents_user_created
  on public.payment_intents(user_id, created_at desc);

alter table public.forecast_runs enable row level security;
alter table public.market_forecasts enable row level security;
alter table public.payment_corridors enable row level security;
alter table public.payment_quotes enable row level security;
alter table public.payment_intents enable row level security;

create policy "Public can read completed forecast runs"
  on public.forecast_runs for select to anon, authenticated
  using (status = 'completed');

create policy "Public can read completed market forecasts"
  on public.market_forecasts for select to anon, authenticated
  using (
    exists (
      select 1
      from public.forecast_runs
      where forecast_runs.id = market_forecasts.forecast_run_id
        and forecast_runs.status = 'completed'
    )
  );

create policy "Public can read enabled payment corridors"
  on public.payment_corridors for select to anon, authenticated
  using (enabled);

create policy "Users can read their payment quotes"
  on public.payment_quotes for select to authenticated
  using (user_id = auth.uid());

create policy "Users can read their payment intents"
  on public.payment_intents for select to authenticated
  using (user_id = auth.uid());

insert into public.payment_corridors (
  code,
  source_currency,
  destination_currency,
  fx_symbol,
  rate_operation,
  spread_bps,
  variable_fee_bps,
  fixed_fee,
  minimum_fee,
  settlement_minutes,
  enabled
)
values
  ('USD-INR', 'USD', 'INR', 'USDINR', 'direct', 35, 45, 0.50, 1.00, 60, true),
  ('EUR-USD', 'EUR', 'USD', 'EURUSD', 'direct', 30, 40, 0.50, 1.00, 45, true),
  ('INR-USD', 'INR', 'USD', 'USDINR', 'inverse', 45, 55, 25.00, 50.00, 120, true),
  ('USD-EUR', 'USD', 'EUR', 'EURUSD', 'inverse', 30, 40, 0.50, 1.00, 45, true)
on conflict (code) do update
set
  fx_symbol = excluded.fx_symbol,
  rate_operation = excluded.rate_operation,
  spread_bps = excluded.spread_bps,
  variable_fee_bps = excluded.variable_fee_bps,
  fixed_fee = excluded.fixed_fee,
  minimum_fee = excluded.minimum_fee,
  settlement_minutes = excluded.settlement_minutes;

comment on table public.market_forecasts is
  'Versioned probabilistic decision-support output. Never treat as guaranteed performance or financial advice.';

comment on table public.payment_intents is
  'Future orchestration boundary for licensed payment providers. Client-side writes are intentionally blocked.';
