-- TradePulse AI
-- Migration 008: Jurisdiction-aware global investing and paper-trading foundation
-- No table in this migration can route a live order or hold customer funds.

create table if not exists public.jurisdictions (
  country_code text primary key references public.countries(iso_code),
  availability_status text not null default 'research_only' check (
    availability_status in (
      'research_only',
      'paper_trading',
      'execution_pending',
      'execution_enabled',
      'blocked'
    )
  ),
  retail_investing_enabled boolean not null default false,
  cross_border_payments_enabled boolean not null default false,
  legal_reviewed_at timestamptz,
  policy_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.investment_venues (
  id bigint generated by default as identity primary key,
  mic_code text not null unique,
  name text not null,
  country_code text not null references public.jurisdictions(country_code),
  venue_type text not null check (
    venue_type in ('exchange', 'broker', 'crypto_exchange', 'fund_platform')
  ),
  timezone text not null default 'UTC',
  execution_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.investment_instruments (
  id bigint generated by default as identity primary key,
  canonical_symbol text not null unique,
  display_symbol text not null,
  name text not null,
  asset_class text not null check (
    asset_class in (
      'equity',
      'etf',
      'bond',
      'fund',
      'forex',
      'commodity',
      'index',
      'crypto'
    )
  ),
  venue_id bigint references public.investment_venues(id),
  isin text,
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  research_enabled boolean not null default true,
  paper_trading_enabled boolean not null default false,
  live_execution_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not live_execution_enabled or venue_id is not null)
);

create table if not exists public.instrument_eligibility (
  instrument_id bigint not null references public.investment_instruments(id) on delete cascade,
  jurisdiction_code text not null references public.jurisdictions(country_code),
  investor_type text not null default 'retail' check (
    investor_type in ('retail', 'professional', 'accredited', 'institutional')
  ),
  availability text not null default 'review_required' check (
    availability in ('allowed', 'restricted', 'blocked', 'review_required')
  ),
  reason_code text,
  effective_from timestamptz not null default now(),
  effective_until timestamptz,
  policy_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (instrument_id, jurisdiction_code, investor_type),
  check (effective_until is null or effective_until > effective_from)
);

create table if not exists public.user_investor_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  declared_residency_country text references public.jurisdictions(country_code),
  verified_residency_country text references public.jurisdictions(country_code),
  tax_residency_country text references public.jurisdictions(country_code),
  base_currency text not null default 'USD' check (base_currency ~ '^[A-Z]{3}$'),
  investor_type text not null default 'retail' check (
    investor_type in ('retail', 'professional', 'accredited', 'institutional')
  ),
  risk_tolerance text check (risk_tolerance in ('conservative', 'moderate', 'aggressive')),
  kyc_status text not null default 'not_started' check (
    kyc_status in ('not_started', 'pending', 'verified', 'rejected', 'expired')
  ),
  suitability_status text not null default 'not_assessed' check (
    suitability_status in ('not_assessed', 'pending', 'suitable', 'restricted')
  ),
  sanctions_status text not null default 'not_screened' check (
    sanctions_status in ('not_screened', 'clear', 'review', 'blocked')
  ),
  onboarding_state text not null default 'research_only' check (
    onboarding_state in ('research_only', 'paper_ready', 'execution_review', 'execution_ready', 'blocked')
  ),
  compliance_reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.investment_portfolios (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  base_currency text not null default 'USD' check (base_currency ~ '^[A-Z]{3}$'),
  portfolio_type text not null default 'paper' check (portfolio_type = 'paper'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.paper_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  instrument_id bigint not null references public.investment_instruments(id),
  client_order_id text not null,
  side text not null check (side in ('buy', 'sell')),
  order_type text not null check (order_type in ('market', 'limit', 'stop', 'stop_limit')),
  time_in_force text not null default 'day' check (time_in_force in ('day', 'gtc', 'ioc')),
  quantity numeric(24,8) not null check (quantity > 0),
  limit_price numeric(20,8) check (limit_price is null or limit_price > 0),
  stop_price numeric(20,8) check (stop_price is null or stop_price > 0),
  status text not null default 'pending' check (
    status in ('pending', 'risk_rejected', 'accepted', 'partially_filled', 'filled', 'cancelled')
  ),
  execution_mode text not null default 'paper' check (execution_mode = 'paper'),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_order_id),
  check (order_type not in ('limit', 'stop_limit') or limit_price is not null),
  check (order_type not in ('stop', 'stop_limit') or stop_price is not null)
);

create table if not exists public.paper_fills (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.paper_orders(id) on delete cascade,
  quantity numeric(24,8) not null check (quantity > 0),
  price numeric(20,8) not null check (price > 0),
  fee numeric(20,8) not null default 0 check (fee >= 0),
  filled_at timestamptz not null default now()
);

create table if not exists public.paper_positions (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  instrument_id bigint not null references public.investment_instruments(id),
  quantity numeric(24,8) not null default 0,
  average_cost numeric(20,8) not null default 0 check (average_cost >= 0),
  realized_pnl numeric(20,8) not null default 0,
  updated_at timestamptz not null default now(),
  unique (portfolio_id, instrument_id)
);

create table if not exists public.order_risk_checks (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.paper_orders(id) on delete cascade,
  check_type text not null,
  outcome text not null check (outcome in ('passed', 'failed', 'review')),
  rule_version text not null,
  details jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);

create table if not exists public.financial_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  resource_type text not null,
  resource_id text,
  actor_type text not null check (actor_type in ('user', 'system', 'provider', 'administrator')),
  correlation_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_instrument_eligibility_jurisdiction
  on public.instrument_eligibility(jurisdiction_code, availability);

create index if not exists idx_investment_portfolios_user
  on public.investment_portfolios(user_id);

create index if not exists idx_paper_orders_portfolio_submitted
  on public.paper_orders(portfolio_id, submitted_at desc);

create index if not exists idx_paper_fills_order
  on public.paper_fills(order_id, filled_at);

create index if not exists idx_paper_positions_portfolio
  on public.paper_positions(portfolio_id);

create index if not exists idx_order_risk_checks_order
  on public.order_risk_checks(order_id, checked_at);

create index if not exists idx_financial_audit_user_created
  on public.financial_audit_events(user_id, created_at desc);

alter table public.jurisdictions enable row level security;
alter table public.investment_venues enable row level security;
alter table public.investment_instruments enable row level security;
alter table public.instrument_eligibility enable row level security;
alter table public.user_investor_profiles enable row level security;
alter table public.investment_portfolios enable row level security;
alter table public.paper_orders enable row level security;
alter table public.paper_fills enable row level security;
alter table public.paper_positions enable row level security;
alter table public.order_risk_checks enable row level security;
alter table public.financial_audit_events enable row level security;

create policy "Public can read jurisdiction availability"
  on public.jurisdictions for select to anon, authenticated
  using (true);

create policy "Public can read investment venues"
  on public.investment_venues for select to anon, authenticated
  using (true);

create policy "Public can read investment instruments"
  on public.investment_instruments for select to anon, authenticated
  using (research_enabled);

create policy "Public can read instrument eligibility"
  on public.instrument_eligibility for select to anon, authenticated
  using (true);

create policy "Users can read their investor profile"
  on public.user_investor_profiles for select to authenticated
  using (user_id = auth.uid());

create policy "Users manage their paper portfolios"
  on public.investment_portfolios for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and portfolio_type = 'paper');

create policy "Users can read their paper orders"
  on public.paper_orders for select to authenticated
  using (user_id = auth.uid());

create policy "Users can submit pending paper orders"
  on public.paper_orders for insert to authenticated
  with check (
    user_id = auth.uid()
    and status = 'pending'
    and execution_mode = 'paper'
    and exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = paper_orders.portfolio_id
        and investment_portfolios.user_id = auth.uid()
        and investment_portfolios.portfolio_type = 'paper'
    )
    and exists (
      select 1
      from public.investment_instruments
      where investment_instruments.id = paper_orders.instrument_id
        and investment_instruments.paper_trading_enabled
    )
  );

create policy "Users can read their paper fills"
  on public.paper_fills for select to authenticated
  using (
    exists (
      select 1
      from public.paper_orders
      where paper_orders.id = paper_fills.order_id
        and paper_orders.user_id = auth.uid()
    )
  );

create policy "Users can read their paper positions"
  on public.paper_positions for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = paper_positions.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their order risk checks"
  on public.order_risk_checks for select to authenticated
  using (
    exists (
      select 1
      from public.paper_orders
      where paper_orders.id = order_risk_checks.order_id
        and paper_orders.user_id = auth.uid()
    )
  );

create policy "Users can read their financial audit events"
  on public.financial_audit_events for select to authenticated
  using (user_id = auth.uid());

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger jurisdictions_set_updated_at
  before update on public.jurisdictions
  for each row execute function public.set_updated_at();

create trigger investment_venues_set_updated_at
  before update on public.investment_venues
  for each row execute function public.set_updated_at();

create trigger investment_instruments_set_updated_at
  before update on public.investment_instruments
  for each row execute function public.set_updated_at();

create trigger instrument_eligibility_set_updated_at
  before update on public.instrument_eligibility
  for each row execute function public.set_updated_at();

create trigger user_investor_profiles_set_updated_at
  before update on public.user_investor_profiles
  for each row execute function public.set_updated_at();

create trigger investment_portfolios_set_updated_at
  before update on public.investment_portfolios
  for each row execute function public.set_updated_at();

create trigger paper_orders_set_updated_at
  before update on public.paper_orders
  for each row execute function public.set_updated_at();

insert into public.jurisdictions (country_code, availability_status)
select countries.iso_code, 'research_only'
from public.countries
on conflict (country_code) do nothing;

comment on table public.instrument_eligibility is
  'Versioned product availability by verified investor jurisdiction and type.';

comment on table public.paper_orders is
  'Simulation-only orders. The execution_mode constraint intentionally prevents live routing.';

comment on table public.user_investor_profiles is
  'Compliance-managed investor eligibility state. Browser clients have read-only access.';
