-- TradePulse AI
-- Migration 009: Transactional paper-investing engine
-- All balances, orders and fills created here are simulations with no cash value.

alter table public.investment_instruments
  add column if not exists market_asset_id bigint unique
    references public.market_assets(id);

alter table public.paper_orders
  add column if not exists reference_price numeric(20,8),
  add column if not exists average_fill_price numeric(20,8),
  add column if not exists total_fees numeric(20,8) not null default 0
    check (total_fees >= 0);

create table if not exists public.paper_cash_balances (
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  balance numeric(24,8) not null default 0 check (balance >= 0),
  available_balance numeric(24,8) not null default 0 check (available_balance >= 0),
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, currency),
  check (available_balance <= balance)
);

create table if not exists public.portfolio_risk_limits (
  portfolio_id uuid primary key references public.investment_portfolios(id) on delete cascade,
  max_order_notional numeric(24,8) not null default 10000 check (max_order_notional > 0),
  max_position_notional numeric(24,8) not null default 25000 check (max_position_notional > 0),
  daily_loss_limit numeric(24,8) not null default 5000 check (daily_loss_limit > 0),
  max_open_orders integer not null default 20 check (max_open_orders between 1 and 100),
  rule_version text not null default 'paper-risk-v1',
  updated_at timestamptz not null default now()
);

create table if not exists public.paper_ledger_entries (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  entry_type text not null check (
    entry_type in ('initial_credit', 'trade_debit', 'trade_credit', 'fee', 'adjustment')
  ),
  amount numeric(24,8) not null,
  balance_after numeric(24,8) not null check (balance_after >= 0),
  order_id uuid references public.paper_orders(id) on delete set null,
  correlation_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_nav_snapshots (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  observed_at timestamptz not null,
  cash_value numeric(24,8) not null,
  position_value numeric(24,8) not null,
  total_value numeric(24,8) not null,
  daily_pnl numeric(24,8),
  drawdown_percent numeric(12,8),
  source text not null default 'paper-engine',
  unique (portfolio_id, observed_at)
);

create index if not exists idx_paper_ledger_portfolio_created
  on public.paper_ledger_entries(portfolio_id, created_at desc);

create index if not exists idx_portfolio_nav_portfolio_observed
  on public.portfolio_nav_snapshots(portfolio_id, observed_at desc);

alter table public.paper_cash_balances enable row level security;
alter table public.portfolio_risk_limits enable row level security;
alter table public.paper_ledger_entries enable row level security;
alter table public.portfolio_nav_snapshots enable row level security;

drop policy if exists "Users manage their paper portfolios"
  on public.investment_portfolios;

drop policy if exists "Users can submit pending paper orders"
  on public.paper_orders;

create policy "Users can read their paper portfolios"
  on public.investment_portfolios for select to authenticated
  using (user_id = auth.uid());

create policy "Users can read their paper cash balances"
  on public.paper_cash_balances for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = paper_cash_balances.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their portfolio risk limits"
  on public.portfolio_risk_limits for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = portfolio_risk_limits.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their paper ledger"
  on public.paper_ledger_entries for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = paper_ledger_entries.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their portfolio NAV"
  on public.portfolio_nav_snapshots for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = portfolio_nav_snapshots.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create trigger paper_cash_balances_set_updated_at
  before update on public.paper_cash_balances
  for each row execute function public.set_updated_at();

create trigger portfolio_risk_limits_set_updated_at
  before update on public.portfolio_risk_limits
  for each row execute function public.set_updated_at();

insert into public.investment_instruments (
  canonical_symbol,
  display_symbol,
  name,
  asset_class,
  market_asset_id,
  quote_currency,
  research_enabled,
  paper_trading_enabled,
  live_execution_enabled
)
select
  'TP:' || market_assets.symbol,
  market_assets.symbol,
  market_assets.name,
  case market_assets.asset_type
    when 'forex' then 'forex'
    when 'commodity' then 'commodity'
    when 'index' then 'index'
    else 'equity'
  end,
  market_assets.id,
  coalesce(market_assets.currency, 'USD'),
  true,
  true,
  false
from public.market_assets
on conflict (canonical_symbol) do update
set
  market_asset_id = excluded.market_asset_id,
  name = excluded.name,
  quote_currency = excluded.quote_currency,
  research_enabled = true,
  paper_trading_enabled = true,
  live_execution_enabled = false;

create or replace function public.create_paper_portfolio(
  p_user_id uuid,
  p_name text,
  p_base_currency text default 'USD',
  p_starting_balance numeric default 100000
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_portfolio public.investment_portfolios%rowtype;
  current_plan text;
  portfolio_count integer;
  portfolio_limit integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the paper-trading service';
  end if;

  if p_user_id is null or length(trim(p_name)) < 2 or length(trim(p_name)) > 60 then
    raise exception 'A valid user and portfolio name are required';
  end if;

  p_base_currency := upper(trim(p_base_currency));
  if p_base_currency !~ '^[A-Z]{3}$' then
    raise exception 'A valid three-letter base currency is required';
  end if;

  if p_starting_balance < 1000 or p_starting_balance > 1000000 then
    raise exception 'Starting paper balance must be between 1,000 and 1,000,000';
  end if;

  select plan into current_plan
  from public.profiles
  where id = p_user_id
  for update;

  if current_plan is null then
    raise exception 'A user profile is required';
  end if;

  portfolio_limit := case current_plan
    when 'business' then 20
    when 'pro' then 5
    else 1
  end;

  select count(*) into portfolio_count
  from public.investment_portfolios
  where user_id = p_user_id;

  if portfolio_count >= portfolio_limit then
    raise exception 'Paper portfolio limit reached for the current plan';
  end if;

  insert into public.investment_portfolios (
    user_id,
    name,
    base_currency,
    portfolio_type
  )
  values (p_user_id, trim(p_name), p_base_currency, 'paper')
  returning * into new_portfolio;

  insert into public.paper_cash_balances (
    portfolio_id,
    currency,
    balance,
    available_balance
  )
  values (
    new_portfolio.id,
    p_base_currency,
    p_starting_balance,
    p_starting_balance
  );

  insert into public.portfolio_risk_limits (portfolio_id)
  values (new_portfolio.id);

  insert into public.paper_ledger_entries (
    portfolio_id,
    currency,
    entry_type,
    amount,
    balance_after,
    correlation_id,
    metadata
  )
  values (
    new_portfolio.id,
    p_base_currency,
    'initial_credit',
    p_starting_balance,
    p_starting_balance,
    'portfolio:' || new_portfolio.id::text,
    jsonb_build_object('simulation', true)
  );

  insert into public.financial_audit_events (
    user_id,
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  )
  values (
    p_user_id,
    'paper_portfolio_created',
    'investment_portfolio',
    new_portfolio.id::text,
    'user',
    'portfolio:' || new_portfolio.id::text,
    jsonb_build_object(
      'base_currency', p_base_currency,
      'starting_balance', p_starting_balance,
      'simulation', true
    )
  );

  return jsonb_build_object(
    'id', new_portfolio.id,
    'name', new_portfolio.name,
    'base_currency', new_portfolio.base_currency,
    'starting_balance', p_starting_balance,
    'portfolio_type', 'paper'
  );
end;
$$;

create or replace function public.execute_paper_market_order(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_instrument_id bigint,
  p_client_order_id text,
  p_side text,
  p_quantity numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_portfolio public.investment_portfolios%rowtype;
  selected_instrument public.investment_instruments%rowtype;
  selected_cash public.paper_cash_balances%rowtype;
  selected_limits public.portfolio_risk_limits%rowtype;
  selected_position public.paper_positions%rowtype;
  existing_order public.paper_orders%rowtype;
  new_order public.paper_orders%rowtype;
  reference_price numeric(20,8);
  reference_observed_at timestamptz;
  execution_price numeric(20,8);
  order_notional numeric(24,8);
  fee numeric(20,8);
  cash_delta numeric(24,8);
  new_cash_balance numeric(24,8);
  current_position_notional numeric(24,8);
  projected_position_notional numeric(24,8);
  new_position_quantity numeric(24,8);
  new_average_cost numeric(20,8);
  realized_delta numeric(20,8);
  rejection_reason text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the paper-trading service';
  end if;

  if p_user_id is null or p_portfolio_id is null or p_instrument_id is null then
    raise exception 'User, portfolio and instrument are required';
  end if;

  if p_side not in ('buy', 'sell') then
    raise exception 'Paper market orders support buy or sell';
  end if;

  if p_quantity <= 0 or p_quantity > 1000000 then
    raise exception 'Paper order quantity is outside the allowed range';
  end if;

  if length(trim(p_client_order_id)) < 8 or length(trim(p_client_order_id)) > 100 then
    raise exception 'A valid idempotency key is required';
  end if;

  -- Serialize duplicate submissions before the lookup so concurrent retries
  -- return the original result instead of racing the unique constraint.
  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || trim(p_client_order_id), 0)
  );

  select * into existing_order
  from public.paper_orders
  where user_id = p_user_id
    and client_order_id = trim(p_client_order_id);

  if found then
    return jsonb_build_object(
      'id', existing_order.id,
      'status', existing_order.status,
      'idempotent_replay', true,
      'average_fill_price', existing_order.average_fill_price,
      'total_fees', existing_order.total_fees
    );
  end if;

  select * into selected_portfolio
  from public.investment_portfolios
  where id = p_portfolio_id
    and user_id = p_user_id
    and portfolio_type = 'paper'
  for update;

  if not found then
    raise exception 'Paper portfolio was not found';
  end if;

  select * into selected_instrument
  from public.investment_instruments
  where id = p_instrument_id
    and paper_trading_enabled
    and market_asset_id is not null;

  if not found then
    raise exception 'Instrument is not enabled for paper trading';
  end if;

  if selected_instrument.quote_currency <> selected_portfolio.base_currency then
    raise exception 'Instrument quote currency must match the paper portfolio base currency';
  end if;

  select price, observed_at
  into reference_price, reference_observed_at
  from public.market_observations
  where asset_id = selected_instrument.market_asset_id
    and price is not null
  order by observed_at desc
  limit 1;

  if reference_price is null then
    raise exception 'No synchronized market price is available';
  end if;

  if reference_observed_at < now() - interval '7 days' then
    raise exception 'The synchronized market price is stale';
  end if;

  select * into selected_cash
  from public.paper_cash_balances
  where portfolio_id = p_portfolio_id
    and currency = selected_portfolio.base_currency
  for update;

  if not found then
    raise exception 'Paper cash balance was not found';
  end if;

  select * into selected_limits
  from public.portfolio_risk_limits
  where portfolio_id = p_portfolio_id
  for update;

  if not found then
    raise exception 'Portfolio risk limits were not found';
  end if;

  select * into selected_position
  from public.paper_positions
  where portfolio_id = p_portfolio_id
    and instrument_id = p_instrument_id
  for update;

  execution_price := case p_side
    when 'buy' then reference_price * 1.0002
    else reference_price * 0.9998
  end;
  order_notional := execution_price * p_quantity;
  fee := greatest(0.01, order_notional * 0.0005);
  current_position_notional := coalesce(abs(selected_position.quantity) * reference_price, 0);
  projected_position_notional := case p_side
    when 'buy' then current_position_notional + order_notional
    else greatest(0, current_position_notional - order_notional)
  end;

  insert into public.paper_orders (
    user_id,
    portfolio_id,
    instrument_id,
    client_order_id,
    side,
    order_type,
    time_in_force,
    quantity,
    status,
    execution_mode,
    reference_price
  )
  values (
    p_user_id,
    p_portfolio_id,
    p_instrument_id,
    trim(p_client_order_id),
    p_side,
    'market',
    'day',
    p_quantity,
    'pending',
    'paper',
    reference_price
  )
  returning * into new_order;

  if order_notional > selected_limits.max_order_notional then
    rejection_reason := 'max_order_notional';
  elsif projected_position_notional > selected_limits.max_position_notional then
    rejection_reason := 'max_position_notional';
  elsif p_side = 'buy' and selected_cash.available_balance < order_notional + fee then
    rejection_reason := 'insufficient_paper_cash';
  elsif p_side = 'sell' and coalesce(selected_position.quantity, 0) < p_quantity then
    rejection_reason := 'insufficient_paper_position';
  end if;

  if rejection_reason is not null then
    update public.paper_orders
    set status = 'risk_rejected'
    where id = new_order.id;

    insert into public.order_risk_checks (
      order_id,
      check_type,
      outcome,
      rule_version,
      details
    )
    values (
      new_order.id,
      'pre_trade_aggregate',
      'failed',
      selected_limits.rule_version,
      jsonb_build_object(
        'reason', rejection_reason,
        'order_notional', order_notional,
        'available_cash', selected_cash.available_balance,
        'projected_position_notional', projected_position_notional,
        'simulation', true
      )
    );

    insert into public.financial_audit_events (
      user_id,
      event_type,
      resource_type,
      resource_id,
      actor_type,
      correlation_id,
      details
    )
    values (
      p_user_id,
      'paper_order_risk_rejected',
      'paper_order',
      new_order.id::text,
      'system',
      trim(p_client_order_id),
      jsonb_build_object('reason', rejection_reason, 'simulation', true)
    );

    return jsonb_build_object(
      'id', new_order.id,
      'status', 'risk_rejected',
      'reason', rejection_reason,
      'idempotent_replay', false
    );
  end if;

  insert into public.order_risk_checks (
    order_id,
    check_type,
    outcome,
    rule_version,
    details
  )
  values (
    new_order.id,
    'pre_trade_aggregate',
    'passed',
    selected_limits.rule_version,
    jsonb_build_object(
      'order_notional', order_notional,
      'available_cash', selected_cash.available_balance,
      'projected_position_notional', projected_position_notional,
      'simulation', true
    )
  );

  if p_side = 'buy' then
    cash_delta := -(order_notional + fee);
    new_position_quantity := coalesce(selected_position.quantity, 0) + p_quantity;
    new_average_cost := (
      coalesce(selected_position.quantity, 0) * coalesce(selected_position.average_cost, 0)
      + order_notional
      + fee
    ) / new_position_quantity;
    realized_delta := 0;
  else
    cash_delta := order_notional - fee;
    new_position_quantity := selected_position.quantity - p_quantity;
    new_average_cost := case
      when new_position_quantity = 0 then 0
      else selected_position.average_cost
    end;
    realized_delta := (execution_price - selected_position.average_cost) * p_quantity - fee;
  end if;

  new_cash_balance := selected_cash.balance + cash_delta;

  update public.paper_cash_balances
  set
    balance = new_cash_balance,
    available_balance = new_cash_balance
  where portfolio_id = p_portfolio_id
    and currency = selected_portfolio.base_currency;

  insert into public.paper_positions (
    portfolio_id,
    instrument_id,
    quantity,
    average_cost,
    realized_pnl
  )
  values (
    p_portfolio_id,
    p_instrument_id,
    new_position_quantity,
    new_average_cost,
    realized_delta
  )
  on conflict (portfolio_id, instrument_id) do update
  set
    quantity = excluded.quantity,
    average_cost = excluded.average_cost,
    realized_pnl = paper_positions.realized_pnl + excluded.realized_pnl,
    updated_at = now();

  insert into public.paper_fills (
    order_id,
    quantity,
    price,
    fee
  )
  values (new_order.id, p_quantity, execution_price, fee);

  update public.paper_orders
  set
    status = 'filled',
    average_fill_price = execution_price,
    total_fees = fee
  where id = new_order.id;

  insert into public.paper_ledger_entries (
    portfolio_id,
    currency,
    entry_type,
    amount,
    balance_after,
    order_id,
    correlation_id,
    metadata
  )
  values (
    p_portfolio_id,
    selected_portfolio.base_currency,
    case p_side when 'buy' then 'trade_debit' else 'trade_credit' end,
    cash_delta,
    new_cash_balance,
    new_order.id,
    trim(p_client_order_id),
    jsonb_build_object(
      'execution_price', execution_price,
      'reference_price', reference_price,
      'fee', fee,
      'simulation', true
    )
  );

  insert into public.financial_audit_events (
    user_id,
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  )
  values (
    p_user_id,
    'paper_order_filled',
    'paper_order',
    new_order.id::text,
    'system',
    trim(p_client_order_id),
    jsonb_build_object(
      'side', p_side,
      'quantity', p_quantity,
      'execution_price', execution_price,
      'fee', fee,
      'simulation', true
    )
  );

  return jsonb_build_object(
    'id', new_order.id,
    'status', 'filled',
    'side', p_side,
    'quantity', p_quantity,
    'reference_price', reference_price,
    'average_fill_price', execution_price,
    'total_fees', fee,
    'cash_balance', new_cash_balance,
    'idempotent_replay', false,
    'simulation', true
  );
end;
$$;

revoke all on function public.create_paper_portfolio(uuid, text, text, numeric)
  from public, anon, authenticated;
grant execute on function public.create_paper_portfolio(uuid, text, text, numeric)
  to service_role;

revoke all on function public.execute_paper_market_order(uuid, uuid, bigint, text, text, numeric)
  from public, anon, authenticated;
grant execute on function public.execute_paper_market_order(uuid, uuid, bigint, text, text, numeric)
  to service_role;

comment on function public.execute_paper_market_order is
  'Atomic simulation engine with idempotency, price freshness, slippage, fees, risk checks, cash accounting and positions. Service role only.';
