-- TradePulse AI
-- Migration 010: Portfolio risk command center and paper reconciliation
-- These controls monitor simulation portfolios only. They cannot route live orders.

alter table public.portfolio_risk_limits
  add column if not exists max_concentration_percent numeric(8,4) not null default 40
    check (max_concentration_percent > 0 and max_concentration_percent <= 100),
  add column if not exists max_drawdown_percent numeric(8,4) not null default 15
    check (max_drawdown_percent > 0 and max_drawdown_percent <= 100),
  add column if not exists var_limit numeric(24,8) not null default 7500
    check (var_limit > 0),
  add column if not exists minimum_cash_percent numeric(8,4) not null default 5
    check (minimum_cash_percent >= 0 and minimum_cash_percent <= 100),
  add column if not exists auto_kill_switch boolean not null default true;

create table if not exists public.portfolio_control_states (
  portfolio_id uuid primary key references public.investment_portfolios(id) on delete cascade,
  trading_enabled boolean not null default true,
  kill_switch_active boolean not null default false,
  trigger_source text check (trigger_source in ('user', 'system', 'administrator')),
  reason text,
  requires_review boolean not null default false,
  activated_at timestamptz,
  updated_at timestamptz not null default now(),
  check (trading_enabled <> kill_switch_active)
);

create table if not exists public.portfolio_risk_snapshots (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  observed_at timestamptz not null,
  total_value numeric(24,8) not null,
  cash_value numeric(24,8) not null,
  gross_exposure numeric(24,8) not null,
  net_exposure numeric(24,8) not null,
  daily_pnl numeric(24,8),
  concentration_percent numeric(12,8) not null default 0,
  cash_percent numeric(12,8) not null default 0,
  drawdown_percent numeric(12,8) not null default 0,
  var_95_one_day numeric(24,8) not null default 0,
  scenario_count integer not null default 0,
  position_count integer not null default 0,
  stale_price_count integer not null default 0,
  breaches jsonb not null default '[]'::jsonb,
  breach_count integer not null default 0,
  model_version text not null default 'paper-risk-v2',
  created_at timestamptz not null default now(),
  unique (portfolio_id, observed_at)
);

create table if not exists public.paper_reconciliation_runs (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  status text not null default 'running' check (
    status in ('running', 'completed', 'exception', 'failed')
  ),
  recorded_cash numeric(24,8),
  ledger_cash numeric(24,8),
  cash_difference numeric(24,8),
  positions_checked integer not null default 0,
  issues_found integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.paper_reconciliation_issues (
  id bigint generated by default as identity primary key,
  reconciliation_run_id uuid not null
    references public.paper_reconciliation_runs(id) on delete cascade,
  issue_type text not null check (
    issue_type in ('cash_mismatch', 'position_mismatch', 'missing_price')
  ),
  severity text not null check (severity in ('warning', 'critical')),
  resource_id text,
  expected_value numeric(24,8),
  actual_value numeric(24,8),
  status text not null default 'open' check (status in ('open', 'resolved')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists idx_risk_snapshots_portfolio_observed
  on public.portfolio_risk_snapshots(portfolio_id, observed_at desc);

create index if not exists idx_reconciliation_runs_portfolio_started
  on public.paper_reconciliation_runs(portfolio_id, started_at desc);

create index if not exists idx_reconciliation_issues_run
  on public.paper_reconciliation_issues(reconciliation_run_id, status);

alter table public.portfolio_control_states enable row level security;
alter table public.portfolio_risk_snapshots enable row level security;
alter table public.paper_reconciliation_runs enable row level security;
alter table public.paper_reconciliation_issues enable row level security;

create policy "Users can read their portfolio controls"
  on public.portfolio_control_states for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = portfolio_control_states.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their portfolio risk snapshots"
  on public.portfolio_risk_snapshots for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = portfolio_risk_snapshots.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their reconciliation runs"
  on public.paper_reconciliation_runs for select to authenticated
  using (
    exists (
      select 1
      from public.investment_portfolios
      where investment_portfolios.id = paper_reconciliation_runs.portfolio_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

create policy "Users can read their reconciliation issues"
  on public.paper_reconciliation_issues for select to authenticated
  using (
    exists (
      select 1
      from public.paper_reconciliation_runs
      join public.investment_portfolios
        on investment_portfolios.id = paper_reconciliation_runs.portfolio_id
      where paper_reconciliation_runs.id = paper_reconciliation_issues.reconciliation_run_id
        and investment_portfolios.user_id = auth.uid()
    )
  );

drop trigger if exists portfolio_control_states_set_updated_at
  on public.portfolio_control_states;
create trigger portfolio_control_states_set_updated_at
  before update on public.portfolio_control_states
  for each row execute function public.set_updated_at();

insert into public.portfolio_control_states (portfolio_id)
select id
from public.investment_portfolios
where portfolio_type = 'paper'
on conflict (portfolio_id) do nothing;

create or replace function public.initialize_paper_control_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.portfolio_type = 'paper' then
    insert into public.portfolio_control_states (portfolio_id)
    values (new.id)
    on conflict (portfolio_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists initialize_paper_control_state_trigger
  on public.investment_portfolios;
create trigger initialize_paper_control_state_trigger
  after insert on public.investment_portfolios
  for each row execute function public.initialize_paper_control_state();

create or replace function public.enforce_paper_trading_control()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.portfolio_control_states
    where portfolio_id = new.portfolio_id
      and (kill_switch_active or not trading_enabled)
  ) then
    raise exception 'Paper trading kill switch is active';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_paper_trading_control_trigger
  on public.paper_orders;
create trigger enforce_paper_trading_control_trigger
  before insert on public.paper_orders
  for each row execute function public.enforce_paper_trading_control();

create or replace function public.set_paper_trading_control(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_trading_enabled boolean,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_control public.portfolio_control_states%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the paper-trading service';
  end if;

  if not exists (
    select 1
    from public.investment_portfolios
    where id = p_portfolio_id
      and user_id = p_user_id
      and portfolio_type = 'paper'
  ) then
    raise exception 'Paper portfolio was not found';
  end if;

  insert into public.portfolio_control_states (portfolio_id)
  values (p_portfolio_id)
  on conflict (portfolio_id) do nothing;

  select * into selected_control
  from public.portfolio_control_states
  where portfolio_id = p_portfolio_id
  for update;

  if p_trading_enabled and selected_control.requires_review then
    raise exception 'Risk review is required before paper trading can resume';
  end if;

  update public.portfolio_control_states
  set
    trading_enabled = p_trading_enabled,
    kill_switch_active = not p_trading_enabled,
    trigger_source = case when p_trading_enabled then null else 'user' end,
    reason = case
      when p_trading_enabled then null
      else left(coalesce(nullif(trim(p_reason), ''), 'Paused by user'), 200)
    end,
    requires_review = false,
    activated_at = case when p_trading_enabled then null else now() end
  where portfolio_id = p_portfolio_id
  returning * into selected_control;

  insert into public.financial_audit_events (
    user_id,
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  )
  values (
    p_user_id,
    case when p_trading_enabled
      then 'paper_trading_resumed'
      else 'paper_trading_paused'
    end,
    'investment_portfolio',
    p_portfolio_id::text,
    'user',
    'control:' || p_portfolio_id::text || ':' || extract(epoch from now())::bigint::text,
    jsonb_build_object(
      'trading_enabled', p_trading_enabled,
      'reason', selected_control.reason,
      'simulation', true
    )
  );

  return jsonb_build_object(
    'portfolio_id', selected_control.portfolio_id,
    'trading_enabled', selected_control.trading_enabled,
    'kill_switch_active', selected_control.kill_switch_active,
    'trigger_source', selected_control.trigger_source,
    'reason', selected_control.reason,
    'requires_review', selected_control.requires_review
  );
end;
$$;

create or replace function public.monitor_paper_portfolio(
  p_user_id uuid,
  p_portfolio_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_portfolio public.investment_portfolios%rowtype;
  selected_cash public.paper_cash_balances%rowtype;
  selected_limits public.portfolio_risk_limits%rowtype;
  snapshot_time timestamptz;
  total_value numeric(24,8);
  gross_exposure numeric(24,8);
  net_exposure numeric(24,8);
  largest_position numeric(24,8);
  concentration_percent numeric(12,8);
  cash_percent numeric(12,8);
  prior_day_value numeric(24,8);
  peak_value numeric(24,8);
  daily_pnl numeric(24,8);
  drawdown_percent numeric(12,8);
  var_95_one_day numeric(24,8);
  scenario_count integer;
  position_count integer;
  stale_price_count integer;
  risk_breaches jsonb := '[]'::jsonb;
  severe_breach boolean := false;
  reconciliation_id uuid;
  calculated_ledger_cash numeric(24,8);
  calculated_cash_difference numeric(24,8);
  reconciliation_issues integer := 0;
  position_mismatches integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the paper-risk service';
  end if;

  select * into selected_portfolio
  from public.investment_portfolios
  where id = p_portfolio_id
    and user_id = p_user_id
    and portfolio_type = 'paper'
  for update;

  if not found then
    raise exception 'Paper portfolio was not found';
  end if;

  snapshot_time := clock_timestamp();

  select * into selected_cash
  from public.paper_cash_balances
  where portfolio_id = p_portfolio_id
    and currency = selected_portfolio.base_currency;

  if not found then
    raise exception 'Paper cash balance was not found';
  end if;

  select * into selected_limits
  from public.portfolio_risk_limits
  where portfolio_id = p_portfolio_id;

  if not found then
    raise exception 'Portfolio risk limits were not found';
  end if;

  with latest_prices as (
    select distinct on (asset_id)
      asset_id,
      price,
      observed_at
    from public.market_observations
    where price is not null
    order by asset_id, observed_at desc
  ),
  valued_positions as (
    select
      position.instrument_id,
      position.quantity,
      price.price,
      price.observed_at,
      position.quantity * price.price as market_value
    from public.paper_positions position
    join public.investment_instruments instrument
      on instrument.id = position.instrument_id
    left join latest_prices price
      on price.asset_id = instrument.market_asset_id
    where position.portfolio_id = p_portfolio_id
      and position.quantity <> 0
  )
  select
    coalesce(sum(abs(market_value)), 0),
    coalesce(sum(market_value), 0),
    coalesce(max(abs(market_value)), 0),
    count(*)::integer,
    count(*) filter (
      where price is null or observed_at < now() - interval '7 days'
    )::integer
  into
    gross_exposure,
    net_exposure,
    largest_position,
    position_count,
    stale_price_count
  from valued_positions;

  total_value := selected_cash.balance + net_exposure;
  concentration_percent := case
    when total_value > 0 then largest_position / total_value * 100
    else 0
  end;
  cash_percent := case
    when total_value > 0 then selected_cash.balance / total_value * 100
    else 0
  end;

  select snapshot.total_value into prior_day_value
  from public.portfolio_nav_snapshots snapshot
  where snapshot.portfolio_id = p_portfolio_id
    and snapshot.observed_at <= snapshot_time - interval '24 hours'
  order by snapshot.observed_at desc
  limit 1;

  daily_pnl := case
    when prior_day_value is null then null
    else total_value - prior_day_value
  end;

  select max(snapshot.total_value) into peak_value
  from public.portfolio_nav_snapshots snapshot
  where snapshot.portfolio_id = p_portfolio_id;

  peak_value := greatest(coalesce(peak_value, total_value), total_value);
  drawdown_percent := case
    when peak_value > 0 then greatest(0, (peak_value - total_value) / peak_value * 100)
    else 0
  end;

  with held_assets as (
    select
      instrument.market_asset_id as asset_id,
      position.quantity * latest.price as market_value
    from public.paper_positions position
    join public.investment_instruments instrument
      on instrument.id = position.instrument_id
    join lateral (
      select observation.price
      from public.market_observations observation
      where observation.asset_id = instrument.market_asset_id
        and observation.price is not null
      order by observation.observed_at desc
      limit 1
    ) latest on true
    where position.portfolio_id = p_portfolio_id
      and position.quantity <> 0
  ),
  daily_prices as (
    select distinct on (observation.asset_id, observation.observed_at::date)
      observation.asset_id,
      observation.observed_at::date as price_date,
      observation.price
    from public.market_observations observation
    join held_assets held on held.asset_id = observation.asset_id
    where observation.price is not null
      and observation.observed_at >= now() - interval '180 days'
    order by observation.asset_id, observation.observed_at::date, observation.observed_at desc
  ),
  daily_returns as (
    select
      asset_id,
      price_date,
      price / nullif(lag(price) over (
        partition by asset_id order by price_date
      ), 0) - 1 as asset_return
    from daily_prices
  ),
  portfolio_scenarios as (
    select
      returns.price_date,
      sum(held.market_value * returns.asset_return) as scenario_pnl
    from daily_returns returns
    join held_assets held on held.asset_id = returns.asset_id
    where returns.asset_return is not null
    group by returns.price_date
  )
  select
    greatest(
      0,
      -coalesce(
        percentile_cont(0.05) within group (order by scenario_pnl),
        0
      )
    )::numeric(24,8),
    count(*)::integer
  into var_95_one_day, scenario_count
  from portfolio_scenarios;

  if stale_price_count > 0 then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'stale_market_price',
      'severity', 'critical',
      'actual', stale_price_count,
      'limit', 0
    ));
    severe_breach := true;
  end if;

  if largest_position > selected_limits.max_position_notional then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'max_position_notional',
      'severity', 'warning',
      'actual', largest_position,
      'limit', selected_limits.max_position_notional
    ));
  end if;

  if concentration_percent > selected_limits.max_concentration_percent then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'max_concentration',
      'severity', 'warning',
      'actual', concentration_percent,
      'limit', selected_limits.max_concentration_percent
    ));
  end if;

  if position_count > 0 and cash_percent < selected_limits.minimum_cash_percent then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'minimum_cash',
      'severity', 'warning',
      'actual', cash_percent,
      'limit', selected_limits.minimum_cash_percent
    ));
  end if;

  if drawdown_percent > selected_limits.max_drawdown_percent then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'max_drawdown',
      'severity', 'critical',
      'actual', drawdown_percent,
      'limit', selected_limits.max_drawdown_percent
    ));
    severe_breach := true;
  end if;

  if daily_pnl is not null and daily_pnl < -selected_limits.daily_loss_limit then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'daily_loss',
      'severity', 'critical',
      'actual', daily_pnl,
      'limit', -selected_limits.daily_loss_limit
    ));
    severe_breach := true;
  end if;

  if scenario_count >= 20 and var_95_one_day > selected_limits.var_limit then
    risk_breaches := risk_breaches || jsonb_build_array(jsonb_build_object(
      'code', 'var_limit',
      'severity', 'critical',
      'actual', var_95_one_day,
      'limit', selected_limits.var_limit
    ));
    severe_breach := true;
  end if;

  insert into public.portfolio_nav_snapshots (
    portfolio_id,
    observed_at,
    cash_value,
    position_value,
    total_value,
    daily_pnl,
    drawdown_percent,
    source
  )
  values (
    p_portfolio_id,
    snapshot_time,
    selected_cash.balance,
    net_exposure,
    total_value,
    daily_pnl,
    drawdown_percent,
    'paper-risk-v2'
  );

  insert into public.portfolio_risk_snapshots (
    portfolio_id,
    observed_at,
    total_value,
    cash_value,
    gross_exposure,
    net_exposure,
    daily_pnl,
    concentration_percent,
    cash_percent,
    drawdown_percent,
    var_95_one_day,
    scenario_count,
    position_count,
    stale_price_count,
    breaches,
    breach_count
  )
  values (
    p_portfolio_id,
    snapshot_time,
    total_value,
    selected_cash.balance,
    gross_exposure,
    net_exposure,
    daily_pnl,
    concentration_percent,
    cash_percent,
    drawdown_percent,
    var_95_one_day,
    scenario_count,
    position_count,
    stale_price_count,
    risk_breaches,
    jsonb_array_length(risk_breaches)
  );

  insert into public.portfolio_control_states (portfolio_id)
  values (p_portfolio_id)
  on conflict (portfolio_id) do nothing;

  if severe_breach and selected_limits.auto_kill_switch then
    update public.portfolio_control_states
    set
      trading_enabled = false,
      kill_switch_active = true,
      trigger_source = 'system',
      reason = 'Automatic risk limit breach',
      requires_review = true,
      activated_at = coalesce(activated_at, snapshot_time)
    where portfolio_id = p_portfolio_id;
  end if;

  insert into public.paper_reconciliation_runs (
    portfolio_id,
    recorded_cash,
    started_at
  )
  values (p_portfolio_id, selected_cash.balance, snapshot_time)
  returning id into reconciliation_id;

  select coalesce(sum(amount), 0) into calculated_ledger_cash
  from public.paper_ledger_entries
  where portfolio_id = p_portfolio_id
    and currency = selected_portfolio.base_currency;

  calculated_cash_difference := selected_cash.balance - calculated_ledger_cash;

  if abs(calculated_cash_difference) > 0.01 then
    insert into public.paper_reconciliation_issues (
      reconciliation_run_id,
      issue_type,
      severity,
      resource_id,
      expected_value,
      actual_value,
      details
    )
    values (
      reconciliation_id,
      'cash_mismatch',
      'critical',
      p_portfolio_id::text,
      calculated_ledger_cash,
      selected_cash.balance,
      jsonb_build_object('currency', selected_portfolio.base_currency)
    );
    reconciliation_issues := reconciliation_issues + 1;
  end if;

  with portfolio_positions as (
    select instrument_id, quantity
    from public.paper_positions
    where portfolio_id = p_portfolio_id
  ),
  fill_positions as (
    select
      orders.instrument_id,
      sum(case orders.side when 'buy' then fills.quantity else -fills.quantity end) as fill_quantity
    from public.paper_fills fills
    join public.paper_orders orders on orders.id = fills.order_id
    where orders.portfolio_id = p_portfolio_id
    group by orders.instrument_id
  ),
  position_comparison as (
    select
      coalesce(position.instrument_id, fills.instrument_id) as instrument_id,
      coalesce(fills.fill_quantity, 0) as expected_quantity,
      coalesce(position.quantity, 0) as actual_quantity
    from portfolio_positions position
    full join fill_positions fills
      on fills.instrument_id = position.instrument_id
  )
  insert into public.paper_reconciliation_issues (
    reconciliation_run_id,
    issue_type,
    severity,
    resource_id,
    expected_value,
    actual_value
  )
  select
    reconciliation_id,
    'position_mismatch',
    'critical',
    instrument_id::text,
    expected_quantity,
    actual_quantity
  from position_comparison
  where abs(expected_quantity - actual_quantity) > 0.00000001;

  get diagnostics position_mismatches = row_count;
  reconciliation_issues := reconciliation_issues + position_mismatches;

  insert into public.paper_reconciliation_issues (
    reconciliation_run_id,
    issue_type,
    severity,
    resource_id,
    details
  )
  select
    reconciliation_id,
    'missing_price',
    'warning',
    position.instrument_id::text,
    jsonb_build_object('symbol', instrument.display_symbol)
  from public.paper_positions position
  join public.investment_instruments instrument
    on instrument.id = position.instrument_id
  where position.portfolio_id = p_portfolio_id
    and position.quantity <> 0
    and not exists (
      select 1
      from public.market_observations observation
      where observation.asset_id = instrument.market_asset_id
        and observation.price is not null
        and observation.observed_at >= now() - interval '7 days'
    );

  get diagnostics position_mismatches = row_count;
  reconciliation_issues := reconciliation_issues + position_mismatches;

  if reconciliation_issues > 0 and selected_limits.auto_kill_switch then
    severe_breach := true;
    update public.portfolio_control_states
    set
      trading_enabled = false,
      kill_switch_active = true,
      trigger_source = 'system',
      reason = 'Automatic reconciliation exception',
      requires_review = true,
      activated_at = coalesce(activated_at, snapshot_time)
    where portfolio_id = p_portfolio_id;
  end if;

  update public.paper_reconciliation_runs
  set
    status = case when reconciliation_issues = 0 then 'completed' else 'exception' end,
    ledger_cash = calculated_ledger_cash,
    cash_difference = calculated_cash_difference,
    positions_checked = position_count,
    issues_found = reconciliation_issues,
    details = jsonb_build_object(
      'risk_model', 'paper-risk-v2',
      'simulation', true
    ),
    completed_at = clock_timestamp()
  where id = reconciliation_id;

  insert into public.financial_audit_events (
    user_id,
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  )
  values (
    p_user_id,
    'paper_portfolio_risk_monitored',
    'investment_portfolio',
    p_portfolio_id::text,
    'system',
    'risk:' || reconciliation_id::text,
    jsonb_build_object(
      'breach_count', jsonb_array_length(risk_breaches),
      'reconciliation_issues', reconciliation_issues,
      'kill_switch_triggered', severe_breach and selected_limits.auto_kill_switch,
      'simulation', true
    )
  );

  return jsonb_build_object(
    'portfolio_id', p_portfolio_id,
    'observed_at', snapshot_time,
    'total_value', total_value,
    'cash_value', selected_cash.balance,
    'gross_exposure', gross_exposure,
    'net_exposure', net_exposure,
    'daily_pnl', daily_pnl,
    'concentration_percent', concentration_percent,
    'cash_percent', cash_percent,
    'drawdown_percent', drawdown_percent,
    'var_95_one_day', var_95_one_day,
    'scenario_count', scenario_count,
    'position_count', position_count,
    'breaches', risk_breaches,
    'reconciliation_id', reconciliation_id,
    'reconciliation_issues', reconciliation_issues,
    'kill_switch_triggered', severe_breach and selected_limits.auto_kill_switch,
    'simulation', true
  );
end;
$$;

create or replace function public.monitor_paper_portfolio_after_ledger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid;
begin
  select user_id into owner_id
  from public.investment_portfolios
  where id = new.portfolio_id
    and portfolio_type = 'paper';

  if owner_id is not null then
    perform public.monitor_paper_portfolio(owner_id, new.portfolio_id);
  end if;

  return new;
end;
$$;

drop trigger if exists monitor_paper_portfolio_after_ledger_trigger
  on public.paper_ledger_entries;
create trigger monitor_paper_portfolio_after_ledger_trigger
  after insert on public.paper_ledger_entries
  for each row execute function public.monitor_paper_portfolio_after_ledger();

revoke all on function public.set_paper_trading_control(uuid, uuid, boolean, text)
  from public, anon, authenticated;
grant execute on function public.set_paper_trading_control(uuid, uuid, boolean, text)
  to service_role;

revoke all on function public.monitor_paper_portfolio(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.monitor_paper_portfolio(uuid, uuid)
  to service_role;

comment on table public.portfolio_risk_snapshots is
  'Simulation-only portfolio risk telemetry. VaR is a transparent 95% one-day historical scenario estimate and is not a loss guarantee.';

comment on table public.paper_reconciliation_runs is
  'Reconciles virtual cash to the paper ledger and positions to simulated fills.';
