-- TradePulse AI
-- Migration 011: Global equity research and forecast dashboard foundation
-- Research classifications are non-personalized decision support, never trade instructions.

create table if not exists public.billing_currencies (
  code text primary key check (code in ('USD', 'GBP')),
  name text not null,
  symbol text not null,
  enabled boolean not null default true,
  display_order smallint not null unique check (display_order > 0),
  created_at timestamptz not null default now()
);

insert into public.billing_currencies (code, name, symbol, enabled, display_order)
values
  ('USD', 'US Dollar', '$', true, 1),
  ('GBP', 'British Pound Sterling', '£', true, 2)
on conflict (code) do update
set
  name = excluded.name,
  symbol = excluded.symbol,
  enabled = excluded.enabled,
  display_order = excluded.display_order;

alter table public.profiles
  add column if not exists preferred_billing_currency text not null default 'USD'
    references public.billing_currencies(code);

create table if not exists public.equity_securities (
  id bigint generated by default as identity primary key,
  market_asset_id bigint not null unique references public.market_assets(id) on delete cascade,
  instrument_id bigint unique references public.investment_instruments(id) on delete set null,
  security_key text not null unique,
  display_symbol text not null,
  company_name text not null,
  asset_class text not null default 'equity' check (asset_class in ('equity', 'etf')),
  exchange_code text not null,
  exchange_name text,
  exchange_mic text,
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  sector text,
  industry text,
  cik text check (cik is null or cik ~ '^[0-9]{10}$'),
  isin text,
  provider_name text not null,
  provider_symbol text not null,
  research_enabled boolean not null default true,
  forecast_enabled boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_name, provider_symbol)
);

create table if not exists public.equity_data_coverage (
  id bigint generated by default as identity primary key,
  security_id bigint not null references public.equity_securities(id) on delete cascade,
  provider_name text not null,
  dataset text not null check (dataset in ('reference', 'prices', 'fundamentals', 'news')),
  coverage_status text not null default 'reference' check (
    coverage_status in ('reference', 'delayed', 'realtime', 'unavailable')
  ),
  delay_minutes integer check (delay_minutes is null or delay_minutes >= 0),
  license_status text not null default 'review_required' check (
    license_status in ('public_domain', 'licensed', 'review_required', 'restricted')
  ),
  last_synchronized_at timestamptz,
  last_observed_at timestamptz,
  error_summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (security_id, provider_name, dataset)
);

create table if not exists public.equity_fundamental_snapshots (
  id bigint generated by default as identity primary key,
  security_id bigint not null references public.equity_securities(id) on delete cascade,
  period_end date not null,
  filing_date date,
  fiscal_period text not null,
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  revenue numeric(28,4),
  net_income numeric(28,4),
  diluted_eps numeric(20,8),
  total_assets numeric(28,4),
  total_liabilities numeric(28,4),
  operating_cash_flow numeric(28,4),
  capital_expenditure numeric(28,4),
  shares_outstanding numeric(28,4),
  pe_ratio numeric(16,6),
  price_to_book numeric(16,6),
  dividend_yield numeric(12,8),
  source text not null,
  source_url text,
  display_allowed boolean not null default false,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (security_id, period_end, fiscal_period, source)
);

create table if not exists public.equity_research_scores (
  id bigint generated by default as identity primary key,
  security_id bigint not null references public.equity_securities(id) on delete cascade,
  generated_at timestamptz not null default now(),
  as_of_time timestamptz not null,
  score numeric(6,3) not null check (score between 0 and 100),
  classification text not null check (
    classification in ('research_positive', 'research_neutral', 'research_cautious', 'insufficient_data')
  ),
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  forecast_score numeric(6,3) not null check (forecast_score between 0 and 100),
  momentum_score numeric(6,3) not null check (momentum_score between 0 and 100),
  quality_score numeric(6,3) not null check (quality_score between 0 and 100),
  valuation_score numeric(6,3) not null check (valuation_score between 0 and 100),
  risk_score numeric(6,3) not null check (risk_score between 0 and 100),
  data_quality_score numeric(6,3) not null check (data_quality_score between 0 and 100),
  methodology_version text not null,
  reasons jsonb not null default '[]'::jsonb,
  risk_flags jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published', 'withdrawn')),
  is_latest boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_equity_securities_lookup
  on public.equity_securities(display_symbol, exchange_code, country_code, sector);

create index if not exists idx_equity_coverage_status
  on public.equity_data_coverage(dataset, coverage_status, license_status);

create index if not exists idx_equity_fundamentals_security_period
  on public.equity_fundamental_snapshots(security_id, period_end desc);

create index if not exists idx_equity_research_security_generated
  on public.equity_research_scores(security_id, generated_at desc);

create unique index if not exists idx_equity_research_latest
  on public.equity_research_scores(security_id)
  where is_latest;

alter table public.equity_securities enable row level security;
alter table public.equity_data_coverage enable row level security;
alter table public.equity_fundamental_snapshots enable row level security;
alter table public.equity_research_scores enable row level security;
alter table public.billing_currencies enable row level security;

create policy "Public can read enabled billing currencies"
  on public.billing_currencies for select to anon, authenticated
  using (enabled);

create policy "Public can read enabled equity securities"
  on public.equity_securities for select to anon, authenticated
  using (research_enabled and active);

create policy "Public can inspect equity data coverage"
  on public.equity_data_coverage for select to anon, authenticated
  using (true);

create policy "Public can read licensed equity fundamentals"
  on public.equity_fundamental_snapshots for select to anon, authenticated
  using (display_allowed);

create policy "Public can read published equity research"
  on public.equity_research_scores for select to anon, authenticated
  using (status = 'published');

create trigger equity_securities_set_updated_at
  before update on public.equity_securities
  for each row execute function public.set_updated_at();

create trigger equity_data_coverage_set_updated_at
  before update on public.equity_data_coverage
  for each row execute function public.set_updated_at();

create or replace view public.equity_research_dashboard
with (security_invoker = true)
as
select
  security.id as security_id,
  security.market_asset_id,
  security.display_symbol,
  security.company_name,
  security.asset_class,
  security.exchange_code,
  security.exchange_name,
  security.exchange_mic,
  security.country_code,
  security.quote_currency,
  security.sector,
  security.industry,
  security.provider_name,
  security.provider_symbol,
  security.forecast_enabled,
  coverage.coverage_status,
  coverage.delay_minutes,
  coverage.license_status,
  coverage.last_synchronized_at,
  observation.observed_at,
  observation.price,
  observation.change_percent,
  observation.source as price_source,
  forecast.id as forecast_id,
  forecast.generated_at as forecast_generated_at,
  forecast.target_at as forecast_target_at,
  forecast.horizon_hours,
  forecast.predicted_price,
  forecast.lower_bound,
  forecast.upper_bound,
  forecast.confidence_score as forecast_confidence,
  forecast.direction as forecast_direction,
  forecast.model_name,
  forecast.model_version,
  forecast.baseline_mae,
  forecast.model_mae,
  forecast.directional_accuracy,
  research.generated_at as research_generated_at,
  research.score as research_score,
  research.classification as research_classification,
  research.confidence as research_confidence,
  research.forecast_score,
  research.momentum_score,
  research.quality_score,
  research.valuation_score,
  research.risk_score,
  research.data_quality_score,
  research.methodology_version,
  research.reasons,
  research.risk_flags,
  fundamental.period_end as fundamental_period_end,
  fundamental.revenue,
  fundamental.net_income,
  fundamental.diluted_eps,
  fundamental.pe_ratio,
  fundamental.price_to_book,
  fundamental.dividend_yield
from public.equity_securities security
left join lateral (
  select item.*
  from public.equity_data_coverage item
  where item.security_id = security.id
    and item.dataset = 'prices'
  order by item.last_synchronized_at desc nulls last
  limit 1
) coverage on true
left join lateral (
  select item.*
  from public.market_observations item
  where item.asset_id = security.market_asset_id
  order by item.observed_at desc
  limit 1
) observation on true
left join lateral (
  select item.*
  from public.market_forecasts item
  where item.asset_id = security.market_asset_id
    and item.is_latest
    and item.validation_status = 'passed'
  order by item.generated_at desc
  limit 1
) forecast on true
left join lateral (
  select item.*
  from public.equity_research_scores item
  where item.security_id = security.id
    and item.is_latest
    and item.status = 'published'
  order by item.generated_at desc
  limit 1
) research on true
left join lateral (
  select item.*
  from public.equity_fundamental_snapshots item
  where item.security_id = security.id
    and item.display_allowed
  order by item.period_end desc
  limit 1
) fundamental on true;

grant select on public.equity_research_dashboard to anon, authenticated;

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'equity_research_scores'
  ) then
    execute 'alter publication supabase_realtime add table public.equity_research_scores';
  end if;
end;
$$;

insert into public.data_sources (name, source_type, base_url, enabled)
values (
  'Alpaca Market Data',
  'us_equity_reference_and_prices',
  'https://data.alpaca.markets/v2',
  false
)
on conflict (name) do update
set
  source_type = excluded.source_type,
  base_url = excluded.base_url;

insert into public.data_sources (name, source_type, base_url, enabled)
values (
  'SEC EDGAR',
  'us_company_fundamentals',
  'https://data.sec.gov/api/xbrl',
  true
)
on conflict (name) do update
set
  source_type = excluded.source_type,
  base_url = excluded.base_url;

comment on table public.equity_data_coverage is
  'Explicit provider, delay, and licensing state. Reference-only or partial feeds must never be labeled real-time.';

comment on table public.equity_research_scores is
  'Transparent, non-personalized research classifications. These rows are not buy, sell, or suitability advice.';

comment on table public.billing_currencies is
  'Commercial billing currencies. Initial global launch supports USD and GBP; this does not move or convert customer funds.';

comment on view public.equity_research_dashboard is
  'Public research surface combining only display-qualified forecasts, licensed fundamentals, and explicit coverage state.';
