-- TradePulse AI
-- Migration 012: Private watchlists, explainable research alerts, and daily briefs
-- The copilot summarizes verified research. It does not provide personalized advice.

alter table public.market_alerts
  drop constraint if exists market_alerts_condition_check;

alter table public.market_alerts
  alter column target_value drop not null,
  add column if not exists delivery_channels text[] not null default array['in_app']::text[],
  add column if not exists cooldown_minutes integer not null default 1440,
  add column if not exists last_evaluated_at timestamptz,
  add column if not exists last_evaluation_key text;

alter table public.market_alerts
  drop constraint if exists market_alerts_supported_condition,
  drop constraint if exists market_alerts_target_requirement,
  drop constraint if exists market_alerts_delivery_channels_check,
  drop constraint if exists market_alerts_cooldown_check;

alter table public.market_alerts
  add constraint market_alerts_supported_condition check (
    condition in (
      'price_above',
      'price_below',
      'change_above',
      'change_below',
      'research_score_above',
      'research_score_below',
      'classification_changed',
      'forecast_direction_changed',
      'risk_flags_changed'
    )
  ),
  add constraint market_alerts_target_requirement check (
    condition in (
      'classification_changed',
      'forecast_direction_changed',
      'risk_flags_changed'
    )
    or target_value is not null
  ),
  add constraint market_alerts_delivery_channels_check check (
    cardinality(delivery_channels) between 1 and 3
    and delivery_channels <@ array['in_app', 'email', 'push']::text[]
  ),
  add constraint market_alerts_cooldown_check check (
    cooldown_minutes between 5 and 43200
  );

create unique index if not exists idx_market_alerts_unique_enabled_rule
  on public.market_alerts (
    user_id,
    asset_id,
    condition,
    coalesce(target_value, -999999999::numeric)
  )
  where enabled;

create table if not exists public.research_brief_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  cadence text not null default 'weekdays' check (
    cadence in ('daily', 'weekdays', 'weekly')
  ),
  timezone text not null default 'UTC' check (char_length(timezone) between 1 and 64),
  delivery_hour smallint not null default 7 check (delivery_hour between 0 and 23),
  billing_currency text not null default 'USD'
    references public.billing_currencies(code),
  include_positive boolean not null default true,
  include_cautious boolean not null default true,
  include_risk_digest boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.research_briefs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  brief_date date not null,
  cadence text not null check (cadence in ('daily', 'weekdays', 'weekly', 'on_demand')),
  title text not null,
  executive_summary text not null,
  highlights jsonb not null default '[]'::jsonb,
  risk_digest jsonb not null default '[]'::jsonb,
  coverage_summary jsonb not null default '{}'::jsonb,
  methodology_version text not null,
  content_hash text not null,
  source_max_timestamp timestamptz,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, brief_date, cadence)
);

create table if not exists public.research_alert_events (
  id bigint generated by default as identity primary key,
  alert_id bigint not null references public.market_alerts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  triggered_at timestamptz not null default now(),
  event_type text not null,
  severity text not null default 'info' check (severity in ('info', 'warning', 'critical')),
  title text not null,
  message text not null,
  observed_value numeric(20,8),
  threshold_value numeric(20,8),
  evidence jsonb not null default '{}'::jsonb,
  delivery_status text not null default 'in_app' check (
    delivery_status in ('in_app', 'queued', 'sent', 'failed')
  ),
  deduplication_key text not null unique,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_research_briefs_user_generated
  on public.research_briefs(user_id, generated_at desc);

create index if not exists idx_research_alert_events_user_unread
  on public.research_alert_events(user_id, triggered_at desc)
  where read_at is null;

create index if not exists idx_research_alert_events_alert_triggered
  on public.research_alert_events(alert_id, triggered_at desc);

alter table public.research_brief_preferences enable row level security;
alter table public.research_briefs enable row level security;
alter table public.research_alert_events enable row level security;

create policy "Users manage their research brief preferences"
  on public.research_brief_preferences for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "Users read their research briefs"
  on public.research_briefs for select to authenticated
  using (user_id = auth.uid());

create policy "Users read their research alert events"
  on public.research_alert_events for select to authenticated
  using (user_id = auth.uid());

create policy "Users acknowledge their research alert events"
  on public.research_alert_events for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

revoke insert, update, delete on public.research_briefs from authenticated;
revoke insert, delete on public.research_alert_events from authenticated;
grant select on public.research_briefs to authenticated;
grant select on public.research_alert_events to authenticated;
grant update (read_at) on public.research_alert_events to authenticated;

create trigger research_brief_preferences_set_updated_at
  before update on public.research_brief_preferences
  for each row execute function public.set_updated_at();

insert into public.research_brief_preferences (user_id, billing_currency)
select profile.id, profile.preferred_billing_currency
from public.profiles profile
on conflict (user_id) do nothing;

create or replace function public.handle_research_profile_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.research_brief_preferences (user_id, billing_currency)
  values (new.id, new.preferred_billing_currency)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_research_profile_created on public.profiles;
create trigger on_research_profile_created
  after insert on public.profiles
  for each row execute function public.handle_research_profile_created();

create or replace view public.user_equity_watchlist_dashboard
with (security_invoker = true)
as
select
  watchlist.user_id,
  watchlist.id as watchlist_id,
  watchlist.name as watchlist_name,
  watchlist.is_default,
  item.id as watchlist_item_id,
  item.created_at as added_at,
  research.*
from public.watchlists watchlist
join public.watchlist_items item
  on item.watchlist_id = watchlist.id
join public.equity_research_dashboard research
  on research.market_asset_id = item.asset_id
where watchlist.user_id = auth.uid();

grant select on public.user_equity_watchlist_dashboard to authenticated;

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'research_briefs'
    ) then
      execute 'alter publication supabase_realtime add table public.research_briefs';
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'research_alert_events'
    ) then
      execute 'alter publication supabase_realtime add table public.research_alert_events';
    end if;
  end if;
end;
$$;

comment on table public.research_briefs is
  'Private, evidence-linked watchlist summaries generated from verified research inputs. Not personalized investment advice.';

comment on table public.research_alert_events is
  'Private alert evidence and delivery state. External channels remain disabled until a reviewed provider is configured.';

comment on view public.user_equity_watchlist_dashboard is
  'Authenticated users see only their own watchlist joined to display-qualified equity research.';
