-- TradePulse AI
-- Migration 013: TradePulse Academy, guided onboarding, quizzes, and progress
-- Academy content is education, not personalized investment advice.

create table if not exists public.academy_courses (
  slug text primary key check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null,
  short_title text not null,
  summary text not null,
  level text not null check (level in ('beginner', 'intermediate', 'advanced')),
  audience text not null,
  access_tier text not null default 'free' check (access_tier in ('free', 'pro', 'business')),
  language_code text not null default 'en' check (language_code ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),
  estimated_minutes integer not null check (estimated_minutes between 1 and 10000),
  display_order smallint not null unique check (display_order > 0),
  learning_objectives jsonb not null default '[]'::jsonb check (jsonb_typeof(learning_objectives) = 'array'),
  published boolean not null default false,
  version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_lessons (
  slug text primary key check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  course_slug text not null references public.academy_courses(slug) on delete cascade,
  title text not null,
  summary text not null,
  lesson_kind text not null default 'reading' check (
    lesson_kind in ('reading', 'guided_practice', 'quiz', 'video')
  ),
  content jsonb not null default '[]'::jsonb check (jsonb_typeof(content) = 'array'),
  estimated_minutes integer not null check (estimated_minutes between 1 and 240),
  display_order smallint not null check (display_order > 0),
  published boolean not null default false,
  version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_slug, display_order)
);

create table if not exists public.academy_quiz_questions (
  id bigint generated by default as identity primary key,
  lesson_slug text not null references public.academy_lessons(slug) on delete cascade,
  prompt text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) between 2 and 6),
  correct_option smallint not null check (correct_option >= 0),
  explanation text not null,
  display_order smallint not null check (display_order > 0),
  created_at timestamptz not null default now(),
  unique (lesson_slug, display_order)
);

create table if not exists public.academy_lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_slug text not null references public.academy_lessons(slug) on delete cascade,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed')),
  best_score numeric(5,2) check (best_score is null or best_score between 0 and 100),
  attempts integer not null default 0 check (attempts >= 0),
  last_position integer not null default 0 check (last_position >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_slug)
);

create table if not exists public.academy_onboarding_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tour_version text not null default 'product-tour-v1',
  current_step smallint not null default 0 check (current_step >= 0),
  completed_at timestamptz,
  skipped_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_course_completions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_slug text not null references public.academy_courses(slug) on delete cascade,
  course_version text not null,
  final_score numeric(5,2) not null check (final_score between 0 and 100),
  verification_code text not null unique,
  issued_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (user_id, course_slug, course_version)
);

create index if not exists idx_academy_lessons_course_order
  on public.academy_lessons(course_slug, display_order);

create index if not exists idx_academy_progress_user_updated
  on public.academy_lesson_progress(user_id, updated_at desc);

create index if not exists idx_academy_completions_user_issued
  on public.academy_course_completions(user_id, issued_at desc);

alter table public.academy_courses enable row level security;
alter table public.academy_lessons enable row level security;
alter table public.academy_quiz_questions enable row level security;
alter table public.academy_lesson_progress enable row level security;
alter table public.academy_onboarding_state enable row level security;
alter table public.academy_course_completions enable row level security;

create policy "Everyone reads published academy courses"
  on public.academy_courses for select to anon, authenticated
  using (published);

create policy "Everyone reads published academy lessons"
  on public.academy_lessons for select to anon, authenticated
  using (
    published and exists (
      select 1 from public.academy_courses course
      where course.slug = academy_lessons.course_slug and course.published
    )
  );

create policy "Users read their academy progress"
  on public.academy_lesson_progress for select to authenticated
  using (user_id = auth.uid());

create policy "Users create their academy progress"
  on public.academy_lesson_progress for insert to authenticated
  with check (user_id = auth.uid());

create policy "Users update their academy progress"
  on public.academy_lesson_progress for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "Users manage their onboarding state"
  on public.academy_onboarding_state for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "Users read their course completions"
  on public.academy_course_completions for select to authenticated
  using (user_id = auth.uid());

revoke all on public.academy_quiz_questions from anon, authenticated;
revoke insert, update, delete on public.academy_courses from anon, authenticated;
revoke insert, update, delete on public.academy_lessons from anon, authenticated;
revoke insert, update, delete on public.academy_course_completions from authenticated;

create trigger academy_courses_set_updated_at
  before update on public.academy_courses
  for each row execute function public.set_updated_at();

create trigger academy_lessons_set_updated_at
  before update on public.academy_lessons
  for each row execute function public.set_updated_at();

create trigger academy_progress_set_updated_at
  before update on public.academy_lesson_progress
  for each row execute function public.set_updated_at();

create trigger academy_onboarding_set_updated_at
  before update on public.academy_onboarding_state
  for each row execute function public.set_updated_at();

create or replace view public.academy_catalog
with (security_invoker = true)
as
select
  course.slug,
  course.title,
  course.short_title,
  course.summary,
  course.level,
  course.audience,
  course.access_tier,
  course.language_code,
  course.estimated_minutes,
  course.display_order,
  course.learning_objectives,
  course.version,
  count(lesson.slug)::integer as lesson_count
from public.academy_courses course
left join public.academy_lessons lesson
  on lesson.course_slug = course.slug and lesson.published
where course.published
group by course.slug;

create or replace view public.academy_quiz_questions_public as
select
  question.id,
  question.lesson_slug,
  question.prompt,
  question.options,
  question.display_order
from public.academy_quiz_questions question
join public.academy_lessons lesson on lesson.slug = question.lesson_slug
join public.academy_courses course on course.slug = lesson.course_slug
where lesson.published and course.published;

grant select on public.academy_catalog to anon, authenticated;
grant select on public.academy_quiz_questions_public to anon, authenticated;

create or replace function public.grade_academy_quiz(
  p_lesson_slug text,
  p_answers jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  question record;
  submitted_option integer;
  correct_count integer := 0;
  total_count integer := 0;
  score_value numeric(5,2) := 0;
  result_items jsonb := '[]'::jsonb;
  current_user uuid := auth.uid();
begin
  if jsonb_typeof(p_answers) <> 'object' then
    raise exception 'Quiz answers must be a JSON object';
  end if;

  if not exists (
    select 1
    from public.academy_lessons lesson
    join public.academy_courses course on course.slug = lesson.course_slug
    where lesson.slug = p_lesson_slug and lesson.published and course.published
  ) then
    raise exception 'Published lesson not found';
  end if;

  for question in
    select id, correct_option, explanation
    from public.academy_quiz_questions
    where lesson_slug = p_lesson_slug
    order by display_order
  loop
    total_count := total_count + 1;
    submitted_option := null;

    if p_answers ? question.id::text and (p_answers ->> question.id::text) ~ '^[0-9]+$' then
      submitted_option := (p_answers ->> question.id::text)::integer;
    end if;

    if submitted_option = question.correct_option then
      correct_count := correct_count + 1;
    end if;

    result_items := result_items || jsonb_build_array(jsonb_build_object(
      'questionId', question.id,
      'correct', submitted_option = question.correct_option,
      'correctOption', question.correct_option,
      'explanation', question.explanation
    ));
  end loop;

  if total_count = 0 then
    raise exception 'This lesson does not have a quiz';
  end if;

  score_value := round(correct_count::numeric / total_count * 100, 2);

  if current_user is not null then
    insert into public.academy_lesson_progress (
      user_id,
      lesson_slug,
      status,
      best_score,
      attempts,
      completed_at
    ) values (
      current_user,
      p_lesson_slug,
      case when score_value >= 70 then 'completed' else 'in_progress' end,
      score_value,
      1,
      case when score_value >= 70 then now() else null end
    )
    on conflict (user_id, lesson_slug) do update
    set
      status = case
        when academy_lesson_progress.status = 'completed' or score_value >= 70
          then 'completed'
        else 'in_progress'
      end,
      best_score = greatest(coalesce(academy_lesson_progress.best_score, 0), score_value),
      attempts = academy_lesson_progress.attempts + 1,
      completed_at = case
        when academy_lesson_progress.completed_at is not null
          then academy_lesson_progress.completed_at
        when score_value >= 70 then now()
        else null
      end,
      updated_at = now();
  end if;

  return jsonb_build_object(
    'lessonSlug', p_lesson_slug,
    'score', score_value,
    'passed', score_value >= 70,
    'correct', correct_count,
    'total', total_count,
    'results', result_items
  );
end;
$$;

revoke all on function public.grade_academy_quiz(text, jsonb) from public;
grant execute on function public.grade_academy_quiz(text, jsonb) to anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'academy_lesson_progress'
    ) then
      execute 'alter publication supabase_realtime add table public.academy_lesson_progress';
    end if;
  end if;
end;
$$;

insert into public.academy_courses (
  slug, title, short_title, summary, level, audience, access_tier,
  language_code, estimated_minutes, display_order, learning_objectives,
  published, version
)
values
  (
    'getting-started',
    'Getting started with TradePulse AI',
    'Getting started',
    'Learn the dashboard, data labels, navigation and safe first steps.',
    'beginner',
    'Every new TradePulse user',
    'free', 'en', 30, 1,
    '["Navigate the platform", "Identify source and freshness labels", "Separate research from execution"]'::jsonb,
    true, 'academy-v1.0.0'
  ),
  (
    'ai-forecast-literacy',
    'Understanding AI forecasts without the hype',
    'AI forecast literacy',
    'Read model direction, confidence, uncertainty and validation responsibly.',
    'beginner',
    'Investors and research users',
    'free', 'en', 40, 2,
    '["Interpret confidence and ranges", "Recognize model limits", "Check validation before conclusions"]'::jsonb,
    true, 'academy-v1.0.0'
  ),
  (
    'stock-research',
    'Stock research and evidence',
    'Stock research',
    'Use scores, fundamentals, provenance and risk flags as a research workflow.',
    'intermediate',
    'Users comparing covered equities',
    'free', 'en', 45, 3,
    '["Trace every research claim", "Compare score components", "Recognize missing or stale evidence"]'::jsonb,
    true, 'academy-v1.0.0'
  ),
  (
    'paper-trading-risk',
    'Paper trading and portfolio risk',
    'Paper trading and risk',
    'Practise orders, position sizing, diversification and kill-switch controls safely.',
    'beginner',
    'Users preparing to simulate a portfolio',
    'free', 'en', 45, 4,
    '["Place simulation-only orders", "Read portfolio risk measures", "Use limits before losses grow"]'::jsonb,
    true, 'academy-v1.0.0'
  ),
  (
    'research-copilot',
    'Watchlists, alerts and the research copilot',
    'Research copilot',
    'Create a focused watchlist, useful alert rules and an evidence-linked daily brief.',
    'intermediate',
    'Users building a repeatable research routine',
    'free', 'en', 35, 5,
    '["Build a useful watchlist", "Set non-noisy alert rules", "Review daily evidence and risks"]'::jsonb,
    true, 'academy-v1.0.0'
  )
on conflict (slug) do update
set
  title = excluded.title,
  short_title = excluded.short_title,
  summary = excluded.summary,
  level = excluded.level,
  audience = excluded.audience,
  access_tier = excluded.access_tier,
  language_code = excluded.language_code,
  estimated_minutes = excluded.estimated_minutes,
  display_order = excluded.display_order,
  learning_objectives = excluded.learning_objectives,
  published = excluded.published,
  version = excluded.version;

insert into public.academy_lessons (
  slug, course_slug, title, summary, lesson_kind, content,
  estimated_minutes, display_order, published, version
)
values
  ('platform-tour', 'getting-started', 'Your first platform tour', 'Understand the main product areas and what each one is for.', 'guided_practice',
   '[{"heading":"The research flow","body":"Move from verified market data to stock research, forecasts, a private watchlist and paper practice. Live trading and fund movement are intentionally unavailable."},{"heading":"Try it","body":"Open Stock Research, select a covered security, inspect its timestamp, then visit the Academy again.","callout":"A displayed score is research evidence—not an instruction to buy."}]'::jsonb, 10, 1, true, 'academy-v1.0.0'),
  ('data-trust-labels', 'getting-started', 'Data, timestamps and coverage labels', 'Learn why real-time, delayed, reference and unavailable are different.', 'reading',
   '[{"heading":"Coverage is a product feature","body":"TradePulse preserves provider, license, delay and observation timestamps. Unsupported or stale information stays visibly unavailable."},{"heading":"A safe habit","body":"Before comparing any stock, check the observed time, source and license state. Never assume a reference feed represents the full market."}]'::jsonb, 10, 2, true, 'academy-v1.0.0'),
  ('research-not-advice', 'getting-started', 'Research is not financial advice', 'Know the boundary between education, research and regulated advice.', 'reading',
   '[{"heading":"What TradePulse provides","body":"The platform provides non-personalized research, model outputs and simulation tools."},{"heading":"What it does not know","body":"It does not know your complete objectives, tax position, jurisdiction, liquidity needs or capacity for loss. Those facts matter before any real investment decision."}]'::jsonb, 10, 3, true, 'academy-v1.0.0'),

  ('forecast-direction-confidence', 'ai-forecast-literacy', 'Direction, confidence and horizon', 'Read a forecast as a time-bounded probability, not a promise.', 'reading',
   '[{"heading":"Three separate ideas","body":"Direction says up, down or flat. Horizon says when the estimate applies. Confidence expresses model certainty under its measured assumptions."},{"heading":"Avoid false precision","body":"A high confidence value does not eliminate market shocks, missing features or regime change."}]'::jsonb, 12, 1, true, 'academy-v1.0.0'),
  ('uncertainty-ranges', 'ai-forecast-literacy', 'Why uncertainty ranges matter', 'Use lower and upper bounds instead of focusing only on one predicted price.', 'reading',
   '[{"heading":"A distribution, not a point","body":"The predicted price is one summary. The uncertainty interval shows a plausible error range derived from validation residuals."},{"heading":"Decision habit","body":"If the range is wide relative to the expected move, the forecast may not support a strong conclusion."}]'::jsonb, 12, 2, true, 'academy-v1.0.0'),
  ('model-validation', 'ai-forecast-literacy', 'Validation, baselines and drift', 'Understand why models must beat simple alternatives out of sample.', 'reading',
   '[{"heading":"The baseline test","body":"TradePulse displays qualified ML forecasts only after they beat a named zero-return baseline and meet directional-accuracy gates."},{"heading":"Performance can decay","body":"Markets change. Walk-forward tests, drift monitoring and champion/challenger evaluation must continue after launch."}]'::jsonb, 16, 3, true, 'academy-v1.0.0'),

  ('research-score-components', 'stock-research', 'How the research score is built', 'Understand forecast, momentum, quality, valuation, risk and data quality.', 'reading',
   '[{"heading":"Six visible components","body":"A total score combines validated forecast, price momentum, company quality, valuation, risk resilience and data quality."},{"heading":"No hidden recommendation","body":"Read the component scores and reasons. Two companies can have similar totals for very different reasons."}]'::jsonb, 15, 1, true, 'academy-v1.0.0'),
  ('fundamentals-provenance', 'stock-research', 'Fundamentals and provenance', 'Trace reported company data to its licensed or public-domain source.', 'reading',
   '[{"heading":"Reported evidence","body":"Revenue, income, cash flow and ratios depend on filing period, accounting choices and source availability."},{"heading":"Check before comparing","body":"Compare the same reporting period and currency where possible. Missing fundamentals should reduce confidence, not be estimated silently."}]'::jsonb, 14, 2, true, 'academy-v1.0.0'),
  ('risk-flags-missing-data', 'stock-research', 'Risk flags and missing data', 'Treat missing, stale and volatile inputs as decision information.', 'guided_practice',
   '[{"heading":"Risk flags are evidence","body":"Elevated volatility, stale prices, missing forecasts or unavailable profitability data are retained beside the score."},{"heading":"Try it","body":"Open Stock Research and find the evidence and risk panels. Explain why the score would be less trustworthy if one input disappeared."}]'::jsonb, 16, 3, true, 'academy-v1.0.0'),

  ('paper-orders', 'paper-trading-risk', 'Simulation orders and virtual cash', 'Place a paper order and understand fees, slippage and idempotency.', 'guided_practice',
   '[{"heading":"Simulation only","body":"Paper orders use virtual cash and synchronized reference prices. They cannot reach a broker or move money."},{"heading":"Operational realism","body":"TradePulse records simulated fills, fees, slippage and duplicate-request protection so practice reflects real system constraints."}]'::jsonb, 14, 1, true, 'academy-v1.0.0'),
  ('position-sizing', 'paper-trading-risk', 'Position sizing and diversification', 'Use notional limits and concentration measures before submitting an order.', 'reading',
   '[{"heading":"Survival before returns","body":"Position size determines how much one mistake can damage a portfolio. Diversification reduces dependence on one company or risk factor."},{"heading":"Practical check","body":"Review maximum order notional, concentration and cash reserve together rather than treating any one limit as sufficient."}]'::jsonb, 14, 2, true, 'academy-v1.0.0'),
  ('risk-command-center', 'paper-trading-risk', 'Risk center, VaR and kill switches', 'Interpret drawdown, exposure, scenario VaR and reconciliation.', 'reading',
   '[{"heading":"Multiple risk lenses","body":"NAV, gross exposure, concentration, drawdown and historical scenario VaR describe different failure modes."},{"heading":"Control matters","body":"Critical breaches can pause paper trading. Reconciliation confirms virtual cash and positions match the recorded ledger and fills."}]'::jsonb, 17, 3, true, 'academy-v1.0.0'),

  ('build-watchlist', 'research-copilot', 'Build a focused watchlist', 'Choose covered securities for a repeatable research routine.', 'guided_practice',
   '[{"heading":"Purpose over quantity","body":"A useful watchlist is small enough to review and broad enough to compare sectors, risks or hypotheses."},{"heading":"Try it","body":"Add two covered stocks with different sectors or risk profiles, then compare their evidence and data quality."}]'::jsonb, 11, 1, true, 'academy-v1.0.0'),
  ('use-research-alerts', 'research-copilot', 'Create useful research alerts', 'Set thresholds that reveal meaningful change without creating noise.', 'reading',
   '[{"heading":"Alerts are prompts to review","body":"A score crossing a threshold does not mean trade. It means new evidence should be inspected."},{"heading":"Avoid alert fatigue","body":"Use a small number of meaningful rules and respect cooldowns. Retained evidence explains exactly why each event fired."}]'::jsonb, 12, 2, true, 'academy-v1.0.0'),
  ('daily-evidence-brief', 'research-copilot', 'Review the daily evidence brief', 'Use highlights, freshness and risk summaries consistently.', 'reading',
   '[{"heading":"A research routine","body":"Review top score changes, model confidence, source timestamps and new risk flags before opening detailed stock pages."},{"heading":"Deterministic first","body":"The first copilot narrates stored evidence without inventing news or market facts. Any future generative layer must cite the same evidence and preserve a safe fallback."}]'::jsonb, 12, 3, true, 'academy-v1.0.0')
on conflict (slug) do update
set
  course_slug = excluded.course_slug,
  title = excluded.title,
  summary = excluded.summary,
  lesson_kind = excluded.lesson_kind,
  content = excluded.content,
  estimated_minutes = excluded.estimated_minutes,
  display_order = excluded.display_order,
  published = excluded.published,
  version = excluded.version;

insert into public.academy_quiz_questions (
  lesson_slug, prompt, options, correct_option, explanation, display_order
)
values
  ('platform-tour', 'Which TradePulse feature can place a live broker order today?', '["Stock Research", "Paper Investing", "None of them", "AI Copilot"]'::jsonb, 2, 'Live brokerage execution is compliance-locked; Paper Investing is simulation only.', 1),
  ('data-trust-labels', 'What should you check before treating a displayed price as current?', '["Only the company name", "Source, timestamp and coverage state", "The screen color", "The research score alone"]'::jsonb, 1, 'Source, timestamp and coverage state explain what the price represents and how fresh it is.', 1),
  ('research-not-advice', 'Why is a research classification not personalized advice?', '["It has no data", "It does not know your complete circumstances and suitability", "It cannot show a score", "It is always wrong"]'::jsonb, 1, 'Personalized advice requires objectives, jurisdiction, tax, liquidity and capacity-for-loss context.', 1),
  ('forecast-direction-confidence', 'A high-confidence upward forecast means:', '["Profit is guaranteed", "The model is certain forever", "The model currently estimates upward direction within a stated horizon", "Risk controls are unnecessary"]'::jsonb, 2, 'Confidence is model evidence for a defined horizon, not a guarantee.', 1),
  ('uncertainty-ranges', 'What does a wide forecast interval suggest?', '["There is meaningful uncertainty around the point estimate", "The stock must rise", "The data is real-time", "Fees do not matter"]'::jsonb, 0, 'A wider interval indicates greater uncertainty relative to the central prediction.', 1),
  ('model-validation', 'Why compare an ML model with a simple baseline?', '["To make charts colorful", "To show the added complexity produces measurable out-of-sample value", "To remove all risk", "To enable live trading"]'::jsonb, 1, 'A complex model should demonstrate improvement over a simple alternative outside its training sample.', 1),
  ('research-score-components', 'What is the safest way to compare two similar total scores?', '["Assume they are identical", "Inspect component scores, reasons and risk flags", "Buy both", "Ignore data quality"]'::jsonb, 1, 'Similar totals can be produced by very different evidence and risk combinations.', 1),
  ('fundamentals-provenance', 'What should happen when a required fundamental is unavailable?', '["Invent an estimate", "Hide the company", "Show it as missing and reduce confidence", "Reuse another company value"]'::jsonb, 2, 'Missing evidence must remain missing and affect data-quality confidence.', 1),
  ('risk-flags-missing-data', 'A stale-price flag should cause you to:', '["Review freshness before relying on the score", "Assume real-time coverage", "Disable risk limits", "Treat the forecast as guaranteed"]'::jsonb, 0, 'Stale data changes the reliability and timing relevance of research.', 1),
  ('paper-orders', 'What has real cash value in a TradePulse paper portfolio?', '["Virtual cash", "Simulated fills", "Neither", "Simulated fees"]'::jsonb, 2, 'Paper portfolios are isolated simulations; virtual balances have no cash value.', 1),
  ('position-sizing', 'Why combine concentration and cash-reserve checks?', '["They describe different portfolio vulnerabilities", "They guarantee returns", "They replace reconciliation", "They enable payments"]'::jsonb, 0, 'Concentration and liquidity are distinct risks and should be reviewed together.', 1),
  ('risk-command-center', 'What is the purpose of reconciliation?', '["Predict tomorrow price", "Confirm balances and positions match recorded ledger and fills", "Create a payment", "Remove all losses"]'::jsonb, 1, 'Reconciliation detects operational inconsistencies between portfolio state and its source records.', 1),
  ('build-watchlist', 'What makes a watchlist useful?', '["Adding every available stock", "A focused set tied to a research purpose", "Only positive scores", "No risk flags"]'::jsonb, 1, 'A focused watchlist supports consistent review without unnecessary noise.', 1),
  ('use-research-alerts', 'A research-score alert is best treated as:', '["An automatic trade instruction", "A prompt to inspect new evidence", "A guaranteed profit signal", "A payment approval"]'::jsonb, 1, 'Alerts indicate that a rule matched; users must still inspect evidence, freshness and risk.', 1),
  ('daily-evidence-brief', 'Why does the first copilot use deterministic narration?', '["To avoid storing evidence", "To prevent invented facts and preserve traceability", "To guarantee market returns", "To enable brokerage execution"]'::jsonb, 1, 'Deterministic narration limits output to stored, traceable research inputs.', 1)
on conflict (lesson_slug, display_order) do update
set
  prompt = excluded.prompt,
  options = excluded.options,
  correct_option = excluded.correct_option,
  explanation = excluded.explanation;

comment on table public.academy_courses is
  'Published TradePulse Academy curriculum. Essential product and safety education remains free.';

comment on table public.academy_course_completions is
  'Service-issued completion records reserved for verified certificates; browser clients cannot create them.';

comment on function public.grade_academy_quiz(text, jsonb) is
  'Grades a published lesson quiz and persists authenticated progress. Passing threshold is 70 percent.';
