-- TradePulse AI
-- Migration 015: Broker sandbox certification control plane
-- Certification evidence is sandbox-only and cannot enable or route live orders.

create table if not exists public.broker_certification_test_catalog (
  code text primary key check (code ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  adapter_contract_version text not null,
  category text not null check (
    category in ('security', 'accounts', 'orders', 'webhooks', 'resilience', 'reconciliation')
  ),
  title text not null,
  description text not null,
  required boolean not null default true,
  sequence integer not null check (sequence > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (adapter_contract_version, sequence)
);

create table if not exists public.broker_certification_runs (
  id uuid primary key default gen_random_uuid(),
  provider_id bigint not null references public.broker_provider_registry(id),
  environment text not null default 'sandbox' check (environment = 'sandbox'),
  adapter_contract_version text not null,
  suite_version text not null,
  source_commit_sha text not null check (source_commit_sha ~ '^[0-9a-f]{7,40}$'),
  status text not null check (status in ('passed', 'failed')),
  required_tests integer not null check (required_tests > 0),
  passed_tests integer not null check (passed_tests >= 0),
  failed_tests integer not null check (failed_tests >= 0),
  live_order_routing_tested boolean not null default false check (not live_order_routing_tested),
  evidence_digest text check (evidence_digest is null or evidence_digest ~ '^[0-9a-f]{64}$'),
  started_at timestamptz not null,
  completed_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (completed_at >= started_at),
  check (passed_tests + failed_tests >= required_tests),
  check (status <> 'passed' or failed_tests = 0)
);

create table if not exists public.broker_certification_results (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.broker_certification_runs(id) on delete cascade,
  test_code text not null references public.broker_certification_test_catalog(code),
  status text not null check (status in ('passed', 'failed')),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  attempt_count integer not null default 1 check (attempt_count > 0),
  error_code text check (
    error_code is null or error_code ~ '^[A-Z0-9]+(?:_[A-Z0-9]+)*$'
  ),
  evidence_digest text check (evidence_digest is null or evidence_digest ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  unique (run_id, test_code),
  check (status <> 'passed' or error_code is null)
);

create index if not exists idx_broker_certification_runs_provider_completed
  on public.broker_certification_runs(provider_id, completed_at desc);

create index if not exists idx_broker_certification_results_run_status
  on public.broker_certification_results(run_id, status);

alter table public.broker_certification_test_catalog enable row level security;
alter table public.broker_certification_runs enable row level security;
alter table public.broker_certification_results enable row level security;

create policy "Public reads broker certification catalog"
  on public.broker_certification_test_catalog for select to anon, authenticated
  using (active);

create policy "Public reads sanitized broker certification runs"
  on public.broker_certification_runs for select to anon, authenticated
  using (true);

create policy "Public reads sanitized broker certification results"
  on public.broker_certification_results for select to anon, authenticated
  using (true);

revoke insert, update, delete on public.broker_certification_test_catalog from anon, authenticated;
revoke insert, update, delete on public.broker_certification_runs from anon, authenticated;
revoke insert, update, delete on public.broker_certification_results from anon, authenticated;
revoke update, delete on public.broker_certification_runs from service_role;
revoke update, delete on public.broker_certification_results from service_role;

create or replace function public.prevent_broker_certification_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Broker certification evidence is append-only';
end;
$$;

revoke all on function public.prevent_broker_certification_mutation() from public;

create trigger broker_certification_runs_append_only
  before update or delete on public.broker_certification_runs
  for each row execute function public.prevent_broker_certification_mutation();

create trigger broker_certification_results_append_only
  before update or delete on public.broker_certification_results
  for each row execute function public.prevent_broker_certification_mutation();

insert into public.broker_certification_test_catalog (
  code,
  adapter_contract_version,
  category,
  title,
  description,
  required,
  sequence
)
values
  (
    'sandbox-environment-attestation', 'broker-adapter-v1', 'security',
    'Sandbox environment attestation',
    'Proves the adapter targets a broker sandbox and cannot resolve a production endpoint.',
    true, 1
  ),
  (
    'secret-isolation-redaction', 'broker-adapter-v1', 'security',
    'Secret isolation and redaction',
    'Proves credentials remain server-side and logs, errors and evidence contain no secrets or account numbers.',
    true, 2
  ),
  (
    'account-snapshot-contract', 'broker-adapter-v1', 'accounts',
    'Account snapshot contract',
    'Validates normalized sandbox account, cash, buying-power and restriction states without exposing provider identifiers.',
    true, 3
  ),
  (
    'sandbox-order-idempotency', 'broker-adapter-v1', 'orders',
    'Sandbox order idempotency',
    'Confirms repeated sandbox requests with one idempotency key cannot create duplicate provider-side test orders.',
    true, 4
  ),
  (
    'sandbox-order-lifecycle', 'broker-adapter-v1', 'orders',
    'Sandbox order lifecycle mapping',
    'Maps accepted, partial, filled, cancelled, rejected and expired sandbox states into the broker-neutral contract.',
    true, 5
  ),
  (
    'webhook-signature-replay', 'broker-adapter-v1', 'webhooks',
    'Webhook signature and replay protection',
    'Rejects invalid signatures, stale timestamps and duplicate sandbox webhook event identifiers.',
    true, 6
  ),
  (
    'rate-limit-backoff', 'broker-adapter-v1', 'resilience',
    'Rate-limit backoff',
    'Uses bounded retries, jitter and provider retry hints without duplicating a sandbox action.',
    true, 7
  ),
  (
    'timeout-outage-recovery', 'broker-adapter-v1', 'resilience',
    'Timeout and outage recovery',
    'Fails closed on ambiguous responses and reconciles provider state before any retry decision.',
    true, 8
  ),
  (
    'cash-position-reconciliation', 'broker-adapter-v1', 'reconciliation',
    'Cash and position reconciliation',
    'Detects differences between TradePulse shadow records and broker sandbox cash, positions and activity.',
    true, 9
  ),
  (
    'production-route-lock', 'broker-adapter-v1', 'security',
    'Production route lock',
    'Proves certification never tests, resolves or enables a live-order route.',
    true, 10
  )
on conflict (code) do update
set
  adapter_contract_version = excluded.adapter_contract_version,
  category = excluded.category,
  title = excluded.title,
  description = excluded.description,
  required = excluded.required,
  sequence = excluded.sequence,
  active = true;

create or replace function public.persist_broker_certification_report(
  p_provider_code text,
  p_suite_version text,
  p_source_commit_sha text,
  p_started_at timestamptz,
  p_completed_at timestamptz,
  p_results jsonb,
  p_evidence_digest text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  provider_record public.broker_provider_registry%rowtype;
  run_record public.broker_certification_runs%rowtype;
  required_count integer;
  passed_count integer;
  failed_count integer;
  overall_status text;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the broker-certification service';
  end if;

  select * into provider_record
  from public.broker_provider_registry
  where code = p_provider_code;

  if provider_record.id is null then
    raise exception 'Broker provider contract not found';
  end if;

  if provider_record.live_order_routing_enabled then
    raise exception 'Certification refuses providers with live routing enabled';
  end if;

  if exists (
    select 1
    from public.brokerage_execution_controls
    where control_key = 'global-live-orders'
      and execution_enabled
  ) then
    raise exception 'Certification requires the global live-order lock';
  end if;

  if jsonb_typeof(p_results) <> 'array' or jsonb_array_length(p_results) = 0 then
    raise exception 'Certification results must be a non-empty array';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_results) item
    where case
      when jsonb_typeof(item) <> 'object' then true
      else
        (item ->> 'code') is null
        or (item ->> 'status') is null
        or (item ->> 'status') not in ('passed', 'failed')
        or exists (
          select 1
          from jsonb_object_keys(item) key
          where key not in ('code', 'status', 'latencyMs', 'attemptCount', 'errorCode', 'evidenceDigest')
        )
    end
  ) then
    raise exception 'Certification result shape is invalid';
  end if;

  if (
    select count(*) <> count(distinct item ->> 'code')
    from jsonb_array_elements(p_results) item
  ) then
    raise exception 'Certification test codes must be unique';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_results) item
    left join public.broker_certification_test_catalog test
      on test.code = item ->> 'code'
     and test.adapter_contract_version = provider_record.adapter_contract_version
     and test.active
    where test.code is null
  ) then
    raise exception 'Certification report contains an unknown or inactive test';
  end if;

  if exists (
    select 1
    from public.broker_certification_test_catalog test
    where test.adapter_contract_version = provider_record.adapter_contract_version
      and test.active
      and test.required
      and not exists (
        select 1
        from jsonb_array_elements(p_results) item
        where item ->> 'code' = test.code
      )
  ) then
    raise exception 'Certification report is missing a required test';
  end if;

  select count(*) into required_count
  from public.broker_certification_test_catalog
  where adapter_contract_version = provider_record.adapter_contract_version
    and active
    and required;

  select
    count(*) filter (where item ->> 'status' = 'passed'),
    count(*) filter (where item ->> 'status' = 'failed')
  into passed_count, failed_count
  from jsonb_array_elements(p_results) item;

  overall_status := case when failed_count = 0 then 'passed' else 'failed' end;

  insert into public.broker_certification_runs (
    provider_id,
    environment,
    adapter_contract_version,
    suite_version,
    source_commit_sha,
    status,
    required_tests,
    passed_tests,
    failed_tests,
    live_order_routing_tested,
    evidence_digest,
    started_at,
    completed_at
  ) values (
    provider_record.id,
    'sandbox',
    provider_record.adapter_contract_version,
    p_suite_version,
    p_source_commit_sha,
    overall_status,
    required_count,
    passed_count,
    failed_count,
    false,
    p_evidence_digest,
    p_started_at,
    p_completed_at
  ) returning * into run_record;

  insert into public.broker_certification_results (
    run_id,
    test_code,
    status,
    latency_ms,
    attempt_count,
    error_code,
    evidence_digest
  )
  select
    run_record.id,
    item ->> 'code',
    item ->> 'status',
    case when item ? 'latencyMs' then (item ->> 'latencyMs')::integer else null end,
    coalesce((item ->> 'attemptCount')::integer, 1),
    nullif(item ->> 'errorCode', ''),
    nullif(item ->> 'evidenceDigest', '')
  from jsonb_array_elements(p_results) item;

  insert into public.financial_audit_events (
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  ) values (
    'broker_sandbox_certification_recorded',
    'broker_certification_run',
    run_record.id::text,
    'system',
    p_source_commit_sha,
    jsonb_build_object(
      'providerCode', provider_record.code,
      'environment', 'sandbox',
      'status', overall_status,
      'passedTests', passed_count,
      'failedTests', failed_count,
      'liveOrderRoutingTested', false
    )
  );

  return jsonb_build_object(
    'id', run_record.id,
    'providerCode', provider_record.code,
    'environment', run_record.environment,
    'status', run_record.status,
    'passedTests', run_record.passed_tests,
    'failedTests', run_record.failed_tests,
    'completedAt', run_record.completed_at,
    'liveOrderRoutingTested', false
  );
end;
$$;

revoke all on function public.persist_broker_certification_report(
  text, text, text, timestamptz, timestamptz, jsonb, text
) from public;
grant execute on function public.persist_broker_certification_report(
  text, text, text, timestamptz, timestamptz, jsonb, text
) to service_role;

create or replace view public.broker_certification_readiness
with (security_invoker = true)
as
select
  provider.id as provider_id,
  provider.code as provider_code,
  provider.display_name,
  provider.adapter_contract_version,
  provider.regulatory_status,
  provider.integration_status,
  provider.live_order_routing_enabled,
  catalog.required_tests,
  latest.id as latest_run_id,
  latest.status as latest_status,
  latest.suite_version,
  latest.source_commit_sha,
  latest.passed_tests,
  latest.failed_tests,
  latest.completed_at,
  latest.live_order_routing_tested
from public.broker_provider_registry provider
join lateral (
  select count(*)::integer as required_tests
  from public.broker_certification_test_catalog test
  where test.adapter_contract_version = provider.adapter_contract_version
    and test.active
    and test.required
) catalog on true
left join lateral (
  select run.*
  from public.broker_certification_runs run
  where run.provider_id = provider.id
  order by run.completed_at desc, run.created_at desc
  limit 1
) latest on true;

create or replace view public.broker_certification_latest_results
with (security_invoker = true)
as
select
  provider.id as provider_id,
  provider.code as provider_code,
  test.code as test_code,
  test.category,
  test.title,
  test.description,
  test.required,
  test.sequence,
  latest.id as latest_run_id,
  coalesce(result.status, 'not_run') as status,
  result.latency_ms,
  result.attempt_count,
  result.error_code,
  latest.completed_at
from public.broker_provider_registry provider
join public.broker_certification_test_catalog test
  on test.adapter_contract_version = provider.adapter_contract_version
 and test.active
left join lateral (
  select run.*
  from public.broker_certification_runs run
  where run.provider_id = provider.id
  order by run.completed_at desc, run.created_at desc
  limit 1
) latest on true
left join public.broker_certification_results result
  on result.run_id = latest.id
 and result.test_code = test.code;

grant select on public.broker_certification_readiness to anon, authenticated;
grant select on public.broker_certification_latest_results to anon, authenticated;

comment on table public.broker_certification_test_catalog is
  'Versioned broker-neutral sandbox certification requirements.';
comment on table public.broker_certification_runs is
  'Immutable sanitized sandbox certification summaries. Live routing is never tested or enabled.';
comment on table public.broker_certification_results is
  'Per-control sandbox outcomes containing only bounded metadata and evidence digests.';
comment on function public.prevent_broker_certification_mutation() is
  'Rejects update and delete operations against append-only certification evidence.';
comment on function public.persist_broker_certification_report(
  text, text, text, timestamptz, timestamptz, jsonb, text
) is 'Service-only atomic certification report writer; cannot enable live routing.';
comment on view public.broker_certification_readiness is
  'Sanitized provider certification summary for the latest sandbox run.';
comment on view public.broker_certification_latest_results is
  'Current broker adapter certification matrix with explicit not-run states.';
