-- TradePulse AI
-- Migration 016: Alpaca Broker API sandbox adapter health plane
-- The adapter is provider-bound, read-only and database-locked away from live routing.

update public.broker_provider_registry
set
  code = 'alpaca-broker-sandbox',
  display_name = 'Alpaca Broker API sandbox',
  integration_status = 'sandbox',
  account_connection_enabled = false,
  live_order_routing_enabled = false,
  metadata = jsonb_build_object(
    'provider', 'alpaca',
    'environment', 'sandbox',
    'api_origin', 'https://broker-api.sandbox.alpaca.markets',
    'implementation_version', 'alpaca-broker-sandbox-v1',
    'authorization', 'server_side_basic',
    'capability', 'asset_read_probe_only',
    'custody', 'external_partner_required',
    'credentials', 'supabase_secrets_only'
  )
where code = 'broker-neutral-sandbox';

create table if not exists public.broker_adapter_probes (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.broker_provider_registry(id),
  environment text not null default 'sandbox' check (environment = 'sandbox'),
  adapter_version text not null check (
    adapter_version = 'alpaca-broker-sandbox-v1'
  ),
  api_origin text not null check (
    api_origin = 'https://broker-api.sandbox.alpaca.markets'
  ),
  probe_kind text not null default 'asset_read' check (probe_kind = 'asset_read'),
  status text not null check (status in ('passed', 'failed')),
  http_status integer check (http_status is null or http_status between 100 and 599),
  latency_ms integer not null check (latency_ms between 0 and 10000),
  attempt_count integer not null check (attempt_count between 0 and 2),
  error_code text check (
    error_code is null or error_code in (
      'CONFIGURATION_INVALID',
      'SANDBOX_ROUTE_REJECTED',
      'AUTHENTICATION_FAILED',
      'RATE_LIMITED',
      'PROVIDER_UNAVAILABLE',
      'PROVIDER_RESPONSE_INVALID',
      'REQUEST_TIMEOUT'
    )
  ),
  live_order_routing_tested boolean not null default false check (
    not live_order_routing_tested
  ),
  created_at timestamptz not null default now(),
  check (
    (status = 'passed' and http_status = 200 and attempt_count > 0 and error_code is null)
    or (status = 'failed' and error_code is not null)
  )
);

create index if not exists idx_broker_adapter_probes_provider_created
  on public.broker_adapter_probes(provider_id, created_at desc);

alter table public.broker_adapter_probes enable row level security;

create policy "Authenticated users read sanitized broker adapter probes"
  on public.broker_adapter_probes for select to authenticated
  using (true);

revoke all on public.broker_adapter_probes from anon;
revoke insert, update, delete on public.broker_adapter_probes from authenticated;
revoke update, delete on public.broker_adapter_probes from service_role;
grant select on public.broker_adapter_probes to authenticated;

create or replace function public.prevent_broker_adapter_probe_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Broker adapter probes are append-only';
end;
$$;

revoke all on function public.prevent_broker_adapter_probe_mutation() from public;

create trigger broker_adapter_probes_append_only
  before update or delete on public.broker_adapter_probes
  for each row execute function public.prevent_broker_adapter_probe_mutation();

create or replace function public.persist_broker_adapter_probe(
  p_provider_code text,
  p_adapter_version text,
  p_api_origin text,
  p_status text,
  p_http_status integer,
  p_latency_ms integer,
  p_attempt_count integer,
  p_error_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  provider_record public.broker_provider_registry%rowtype;
  probe_record public.broker_adapter_probes%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the broker-adapter service';
  end if;

  select * into provider_record
  from public.broker_provider_registry
  where code = p_provider_code;

  if provider_record.id is null or provider_record.code <> 'alpaca-broker-sandbox' then
    raise exception 'Alpaca sandbox provider contract not found';
  end if;

  if provider_record.live_order_routing_enabled or provider_record.account_connection_enabled then
    raise exception 'The read-only adapter requires all provider routing disabled';
  end if;

  if exists (
    select 1 from public.brokerage_execution_controls
    where control_key = 'global-live-orders' and execution_enabled
  ) then
    raise exception 'The read-only adapter requires the global live-order lock';
  end if;

  if p_adapter_version <> 'alpaca-broker-sandbox-v1'
    or p_api_origin <> 'https://broker-api.sandbox.alpaca.markets' then
    raise exception 'The adapter implementation or sandbox origin is invalid';
  end if;

  insert into public.broker_adapter_probes (
    provider_id,
    environment,
    adapter_version,
    api_origin,
    probe_kind,
    status,
    http_status,
    latency_ms,
    attempt_count,
    error_code,
    live_order_routing_tested
  ) values (
    provider_record.id,
    'sandbox',
    p_adapter_version,
    p_api_origin,
    'asset_read',
    p_status,
    p_http_status,
    p_latency_ms,
    p_attempt_count,
    p_error_code,
    false
  ) returning * into probe_record;

  insert into public.financial_audit_events (
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  ) values (
    'broker_adapter_probe_recorded',
    'broker_adapter_probe',
    probe_record.id::text,
    'system',
    probe_record.id::text,
    jsonb_build_object(
      'providerCode', provider_record.code,
      'environment', 'sandbox',
      'adapterVersion', probe_record.adapter_version,
      'probeKind', 'asset_read',
      'status', probe_record.status,
      'errorCode', probe_record.error_code,
      'liveOrderRoutingTested', false
    )
  );

  return jsonb_build_object(
    'id', probe_record.id,
    'providerCode', provider_record.code,
    'environment', probe_record.environment,
    'adapterVersion', probe_record.adapter_version,
    'apiOrigin', probe_record.api_origin,
    'probeKind', probe_record.probe_kind,
    'status', probe_record.status,
    'httpStatus', probe_record.http_status,
    'latencyMs', probe_record.latency_ms,
    'attemptCount', probe_record.attempt_count,
    'errorCode', probe_record.error_code,
    'createdAt', probe_record.created_at,
    'liveOrderRoutingTested', false
  );
end;
$$;

revoke all on function public.persist_broker_adapter_probe(
  text, text, text, text, integer, integer, integer, text
) from public;
grant execute on function public.persist_broker_adapter_probe(
  text, text, text, text, integer, integer, integer, text
) to service_role;

create or replace view public.broker_adapter_health
with (security_invoker = true)
as
select
  provider.id as provider_id,
  provider.code as provider_code,
  provider.display_name,
  provider.adapter_contract_version,
  'sandbox'::text as environment,
  'https://broker-api.sandbox.alpaca.markets'::text as api_origin,
  'asset_read'::text as probe_kind,
  coalesce(latest.status, 'not_run') as latest_status,
  latest.http_status,
  latest.latency_ms,
  latest.attempt_count,
  latest.error_code,
  latest.created_at as checked_at,
  false as accounts_read_enabled,
  false as orders_read_enabled,
  false as orders_write_enabled,
  provider.live_order_routing_enabled
from public.broker_provider_registry provider
left join lateral (
  select probe.*
  from public.broker_adapter_probes probe
  where probe.provider_id = provider.id
  order by probe.created_at desc, probe.id desc
  limit 1
) latest on true
where provider.code = 'alpaca-broker-sandbox';

grant select on public.broker_adapter_health to authenticated;

comment on table public.broker_adapter_probes is
  'Immutable sanitized health metadata from the read-only Alpaca Broker API sandbox adapter.';
comment on function public.persist_broker_adapter_probe(
  text, text, text, text, integer, integer, integer, text
) is 'Service-only writer that refuses any non-sandbox or execution-enabled provider state.';
comment on view public.broker_adapter_health is
  'Latest sanitized provider adapter status; no credentials, account data or provider payloads.';
