-- TradePulse AI
-- Migration 017: read-only Alpaca sandbox account inventory and reconciliation signal
-- No provider account identifiers, account numbers, contact data or order capability are stored.

update public.broker_provider_registry
set
  account_connection_enabled = false,
  live_order_routing_enabled = false,
  metadata = metadata || jsonb_build_object(
    'account_inventory_version', 'alpaca-broker-account-inventory-v1',
    'account_inventory_origin', 'https://broker-api.sandbox.alpaca.markets',
    'account_inventory_path', '/v1/accounts',
    'account_inventory_query', 'entities=trading_configurations',
    'account_inventory_mode', 'sanitized_aggregate_read_only',
    'provider_account_identifiers_stored', false,
    'orders_enabled', false
  )
where code = 'alpaca-broker-sandbox';

create table public.broker_account_inventory_runs (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.broker_provider_registry(id),
  environment text not null default 'sandbox' check (environment = 'sandbox'),
  adapter_version text not null check (
    adapter_version = 'alpaca-broker-account-inventory-v1'
  ),
  api_origin text not null check (
    api_origin = 'https://broker-api.sandbox.alpaca.markets'
  ),
  inventory_kind text not null default 'account_status_summary' check (
    inventory_kind = 'account_status_summary'
  ),
  status text not null check (status in ('passed', 'failed')),
  http_status integer check (http_status is null or http_status between 100 and 599),
  latency_ms integer not null check (latency_ms between 0 and 10000),
  attempt_count integer not null check (attempt_count between 0 and 2),
  total_accounts integer not null check (total_accounts between 0 and 1000),
  active_accounts integer not null check (active_accounts >= 0),
  pending_accounts integer not null check (pending_accounts >= 0),
  action_required_accounts integer not null check (action_required_accounts >= 0),
  rejected_accounts integer not null check (rejected_accounts >= 0),
  closed_accounts integer not null check (closed_accounts >= 0),
  restricted_accounts integer not null check (
    restricted_accounts between 0 and total_accounts
  ),
  currencies jsonb not null default '[]'::jsonb check (
    jsonb_typeof(currencies) = 'array'
  ),
  snapshot_digest text check (
    snapshot_digest is null or snapshot_digest ~ '^[0-9a-f]{64}$'
  ),
  changed_since_previous boolean not null default false,
  page_limit_reached boolean not null default false,
  error_code text check (
    error_code is null or error_code in (
      'CONFIGURATION_INVALID',
      'SANDBOX_ROUTE_REJECTED',
      'AUTHENTICATION_FAILED',
      'RATE_LIMITED',
      'PROVIDER_UNAVAILABLE',
      'PROVIDER_RESPONSE_INVALID',
      'REQUEST_TIMEOUT'
    )
  ),
  live_order_routing_tested boolean not null default false check (
    not live_order_routing_tested
  ),
  created_at timestamptz not null default now(),
  check (
    total_accounts = active_accounts + pending_accounts +
      action_required_accounts + rejected_accounts + closed_accounts
  ),
  check (
    (
      status = 'passed' and http_status = 200 and attempt_count > 0 and
      snapshot_digest is not null and error_code is null
    ) or (
      status = 'failed' and snapshot_digest is null and error_code is not null and
      total_accounts = 0
    )
  ),
  check (not page_limit_reached or total_accounts = 1000)
);

create index idx_broker_account_inventory_provider_created
  on public.broker_account_inventory_runs(provider_id, created_at desc);

alter table public.broker_account_inventory_runs enable row level security;

create policy "Authenticated users read sanitized broker account inventory"
  on public.broker_account_inventory_runs for select to authenticated
  using (true);

revoke all on public.broker_account_inventory_runs from anon;
revoke insert, update, delete on public.broker_account_inventory_runs from authenticated;
revoke update, delete on public.broker_account_inventory_runs from service_role;
grant select on public.broker_account_inventory_runs to authenticated;

create or replace function public.prevent_broker_account_inventory_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Broker account inventory evidence is append-only';
end;
$$;

revoke all on function public.prevent_broker_account_inventory_mutation() from public;

create trigger broker_account_inventory_append_only
  before update or delete on public.broker_account_inventory_runs
  for each row execute function public.prevent_broker_account_inventory_mutation();

create or replace function public.persist_broker_account_inventory(
  p_provider_code text,
  p_adapter_version text,
  p_api_origin text,
  p_status text,
  p_http_status integer,
  p_latency_ms integer,
  p_attempt_count integer,
  p_total_accounts integer,
  p_active_accounts integer,
  p_pending_accounts integer,
  p_action_required_accounts integer,
  p_rejected_accounts integer,
  p_closed_accounts integer,
  p_restricted_accounts integer,
  p_currencies text[],
  p_snapshot_digest text,
  p_page_limit_reached boolean,
  p_error_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  provider_record public.broker_provider_registry%rowtype;
  inventory_record public.broker_account_inventory_runs%rowtype;
  previous_digest text;
  inventory_changed boolean := false;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the broker-account inventory service';
  end if;

  select * into provider_record
  from public.broker_provider_registry
  where code = p_provider_code;

  if provider_record.id is null or provider_record.code <> 'alpaca-broker-sandbox' then
    raise exception 'Alpaca sandbox provider contract not found';
  end if;

  if provider_record.live_order_routing_enabled or provider_record.account_connection_enabled then
    raise exception 'Account inventory requires provider routing to remain disabled';
  end if;

  if exists (
    select 1 from public.brokerage_execution_controls
    where control_key = 'global-live-orders' and execution_enabled
  ) then
    raise exception 'Account inventory requires the global live-order lock';
  end if;

  if p_adapter_version <> 'alpaca-broker-account-inventory-v1'
    or p_api_origin <> 'https://broker-api.sandbox.alpaca.markets' then
    raise exception 'The account inventory implementation or sandbox origin is invalid';
  end if;

  if p_currencies is null or exists (
    select 1 from unnest(p_currencies) currency
    where currency !~ '^[A-Z]{3}$'
  ) then
    raise exception 'Account inventory currencies are invalid';
  end if;

  select snapshot_digest into previous_digest
  from public.broker_account_inventory_runs
  where provider_id = provider_record.id and status = 'passed'
  order by created_at desc, id desc
  limit 1;

  inventory_changed := previous_digest is not null
    and p_snapshot_digest is distinct from previous_digest;

  insert into public.broker_account_inventory_runs (
    provider_id,
    environment,
    adapter_version,
    api_origin,
    inventory_kind,
    status,
    http_status,
    latency_ms,
    attempt_count,
    total_accounts,
    active_accounts,
    pending_accounts,
    action_required_accounts,
    rejected_accounts,
    closed_accounts,
    restricted_accounts,
    currencies,
    snapshot_digest,
    changed_since_previous,
    page_limit_reached,
    error_code,
    live_order_routing_tested
  ) values (
    provider_record.id,
    'sandbox',
    p_adapter_version,
    p_api_origin,
    'account_status_summary',
    p_status,
    p_http_status,
    p_latency_ms,
    p_attempt_count,
    p_total_accounts,
    p_active_accounts,
    p_pending_accounts,
    p_action_required_accounts,
    p_rejected_accounts,
    p_closed_accounts,
    p_restricted_accounts,
    to_jsonb(p_currencies),
    p_snapshot_digest,
    inventory_changed,
    p_page_limit_reached,
    p_error_code,
    false
  ) returning * into inventory_record;

  insert into public.financial_audit_events (
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  ) values (
    'broker_account_inventory_recorded',
    'broker_account_inventory',
    inventory_record.id::text,
    'system',
    inventory_record.id::text,
    jsonb_build_object(
      'providerCode', provider_record.code,
      'environment', 'sandbox',
      'status', inventory_record.status,
      'totalAccounts', inventory_record.total_accounts,
      'restrictedAccounts', inventory_record.restricted_accounts,
      'changedSincePrevious', inventory_record.changed_since_previous,
      'pageLimitReached', inventory_record.page_limit_reached,
      'errorCode', inventory_record.error_code,
      'liveOrderRoutingTested', false
    )
  );

  return jsonb_build_object(
    'id', inventory_record.id,
    'providerCode', provider_record.code,
    'environment', inventory_record.environment,
    'adapterVersion', inventory_record.adapter_version,
    'inventoryKind', inventory_record.inventory_kind,
    'status', inventory_record.status,
    'httpStatus', inventory_record.http_status,
    'latencyMs', inventory_record.latency_ms,
    'attemptCount', inventory_record.attempt_count,
    'totalAccounts', inventory_record.total_accounts,
    'activeAccounts', inventory_record.active_accounts,
    'pendingAccounts', inventory_record.pending_accounts,
    'actionRequiredAccounts', inventory_record.action_required_accounts,
    'rejectedAccounts', inventory_record.rejected_accounts,
    'closedAccounts', inventory_record.closed_accounts,
    'restrictedAccounts', inventory_record.restricted_accounts,
    'currencies', inventory_record.currencies,
    'changedSincePrevious', inventory_record.changed_since_previous,
    'pageLimitReached', inventory_record.page_limit_reached,
    'errorCode', inventory_record.error_code,
    'createdAt', inventory_record.created_at,
    'ordersRead', false,
    'ordersWrite', false,
    'liveOrderRoutingTested', false
  );
end;
$$;

revoke all on function public.persist_broker_account_inventory(
  text, text, text, text, integer, integer, integer,
  integer, integer, integer, integer, integer, integer, integer,
  text[], text, boolean, text
) from public;
grant execute on function public.persist_broker_account_inventory(
  text, text, text, text, integer, integer, integer,
  integer, integer, integer, integer, integer, integer, integer,
  text[], text, boolean, text
) to service_role;

create or replace view public.broker_account_inventory_health
with (security_invoker = true)
as
select
  provider.id as provider_id,
  provider.code as provider_code,
  provider.display_name,
  'sandbox'::text as environment,
  'https://broker-api.sandbox.alpaca.markets'::text as api_origin,
  coalesce(latest.status, 'not_run') as latest_status,
  latest.http_status,
  latest.latency_ms,
  latest.attempt_count,
  latest.total_accounts,
  latest.active_accounts,
  latest.pending_accounts,
  latest.action_required_accounts,
  latest.rejected_accounts,
  latest.closed_accounts,
  latest.restricted_accounts,
  latest.currencies,
  latest.changed_since_previous,
  latest.page_limit_reached,
  latest.error_code,
  latest.created_at as checked_at,
  true as accounts_read_enabled,
  false as orders_read_enabled,
  false as orders_write_enabled,
  provider.live_order_routing_enabled
from public.broker_provider_registry provider
left join lateral (
  select inventory.*
  from public.broker_account_inventory_runs inventory
  where inventory.provider_id = provider.id
  order by inventory.created_at desc, inventory.id desc
  limit 1
) latest on true
where provider.code = 'alpaca-broker-sandbox';

grant select on public.broker_account_inventory_health to authenticated;

comment on table public.broker_account_inventory_runs is
  'Append-only aggregate Alpaca sandbox account status inventory; contains no provider account identifiers or customer PII.';
comment on function public.persist_broker_account_inventory(
  text, text, text, text, integer, integer, integer,
  integer, integer, integer, integer, integer, integer, integer,
  text[], text, boolean, text
) is 'Service-only aggregate account inventory writer that refuses enabled provider or live-order routing.';
comment on view public.broker_account_inventory_health is
  'Latest sanitized aggregate Alpaca sandbox account inventory for authenticated product users.';
