-- TradePulse AI
-- Migration 018: broker reconciliation monitoring and incident lifecycle
-- Signals are derived only from sanitized aggregate evidence. No customer or provider account identifiers are stored.

create table public.broker_operations_policies (
  provider_id bigint primary key references public.broker_provider_registry(id),
  environment text not null default 'sandbox' check (environment = 'sandbox'),
  inventory_warning_minutes integer not null default 1560 check (
    inventory_warning_minutes between 15 and 10080
  ),
  inventory_critical_minutes integer not null default 4320 check (
    inventory_critical_minutes > inventory_warning_minutes
    and inventory_critical_minutes <= 43200
  ),
  adapter_warning_minutes integer not null default 1560 check (
    adapter_warning_minutes between 15 and 10080
  ),
  adapter_critical_minutes integer not null default 4320 check (
    adapter_critical_minutes > adapter_warning_minutes
    and adapter_critical_minutes <= 43200
  ),
  action_required_warning_threshold integer not null default 1 check (
    action_required_warning_threshold between 1 and 1000
  ),
  restricted_warning_threshold integer not null default 1 check (
    restricted_warning_threshold between 1 and 1000
  ),
  created_at timestamptz not null default now()
);

insert into public.broker_operations_policies (provider_id)
select id
from public.broker_provider_registry
where code = 'alpaca-broker-sandbox'
on conflict (provider_id) do nothing;

alter table public.broker_operations_policies enable row level security;

create policy "Authenticated users read broker monitoring policy"
  on public.broker_operations_policies for select to authenticated
  using (true);

revoke all on public.broker_operations_policies from anon;
revoke insert, update, delete on public.broker_operations_policies from authenticated;
revoke insert, update, delete on public.broker_operations_policies from service_role;
grant select on public.broker_operations_policies to authenticated;

create table public.broker_operations_alerts (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.broker_provider_registry(id),
  environment text not null default 'sandbox' check (environment = 'sandbox'),
  alert_code text not null check (alert_code in (
    'inventory_not_run',
    'adapter_probe_not_run',
    'inventory_sync_failed',
    'adapter_probe_failed',
    'inventory_stale',
    'adapter_probe_stale',
    'inventory_page_limit_reached',
    'action_required_accounts',
    'restricted_accounts',
    'inventory_changed'
  )),
  severity text not null check (severity in ('warning', 'critical')),
  status text not null default 'open' check (status in ('open', 'resolved')),
  title text not null check (char_length(title) between 1 and 120),
  message text not null check (char_length(message) between 1 and 500),
  evidence jsonb not null default '{}'::jsonb check (
    jsonb_typeof(evidence) = 'object'
    and evidence::text !~* '"(account_id|account_number|customer_name|legal_name|first_name|last_name|email|phone|address|contact|identity|api_key|secret|password|access_token|provider_payload)"'
  ),
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  check (last_detected_at >= first_detected_at),
  check (
    (status = 'open' and resolved_at is null)
    or (status = 'resolved' and resolved_at is not null and resolved_at >= first_detected_at)
  )
);

create unique index idx_broker_operations_alerts_one_open_signal
  on public.broker_operations_alerts(provider_id, alert_code)
  where status = 'open';

create index idx_broker_operations_alerts_provider_detected
  on public.broker_operations_alerts(provider_id, last_detected_at desc);

alter table public.broker_operations_alerts enable row level security;

create policy "Authenticated users read sanitized broker operations alerts"
  on public.broker_operations_alerts for select to authenticated
  using (true);

revoke all on public.broker_operations_alerts from anon;
revoke insert, update, delete on public.broker_operations_alerts from authenticated;
revoke insert, update, delete on public.broker_operations_alerts from service_role;
grant select on public.broker_operations_alerts to authenticated;

create or replace view public.broker_operations_health
with (security_invoker = true)
as
with state as (
  select
    provider.id as provider_id,
    provider.code as provider_code,
    provider.display_name,
    provider.account_connection_enabled,
    provider.live_order_routing_enabled,
    policy.inventory_warning_minutes,
    policy.inventory_critical_minutes,
    policy.adapter_warning_minutes,
    policy.adapter_critical_minutes,
    policy.action_required_warning_threshold,
    policy.restricted_warning_threshold,
    inventory.latest_status as inventory_status,
    inventory.http_status as inventory_http_status,
    inventory.total_accounts,
    inventory.active_accounts,
    inventory.pending_accounts,
    inventory.action_required_accounts,
    inventory.restricted_accounts,
    case when inventory.latest_status = 'passed'
      then coalesce(inventory.changed_since_previous, false)
      else false
    end as changed_since_previous,
    inventory.page_limit_reached,
    inventory.checked_at as inventory_checked_at,
    adapter.latest_status as adapter_status,
    adapter.http_status as adapter_http_status,
    adapter.checked_at as adapter_checked_at
  from public.broker_provider_registry provider
  join public.broker_operations_policies policy on policy.provider_id = provider.id
  left join public.broker_account_inventory_health inventory
    on inventory.provider_id = provider.id
  left join public.broker_adapter_health adapter
    on adapter.provider_id = provider.id
  where provider.code = 'alpaca-broker-sandbox'
), ages as (
  select
    state.*,
    case when inventory_checked_at is null then null else
      greatest(0, floor(extract(epoch from (now() - inventory_checked_at)) / 60))::integer
    end as inventory_minutes_since_check,
    case when adapter_checked_at is null then null else
      greatest(0, floor(extract(epoch from (now() - adapter_checked_at)) / 60))::integer
    end as adapter_minutes_since_check
  from state
), signals as (
  select
    ages.*,
    array_remove(array[
      case when inventory_checked_at is null then 'inventory_not_run'::text end,
      case when adapter_checked_at is null then 'adapter_probe_not_run'::text end,
      case when inventory_status = 'failed' then 'inventory_sync_failed'::text end,
      case when adapter_status = 'failed' then 'adapter_probe_failed'::text end,
      case when inventory_checked_at is not null and inventory_minutes_since_check >= inventory_warning_minutes then 'inventory_stale'::text end,
      case when adapter_checked_at is not null and adapter_minutes_since_check >= adapter_warning_minutes then 'adapter_probe_stale'::text end,
      case when coalesce(page_limit_reached, false) then 'inventory_page_limit_reached'::text end,
      case when coalesce(action_required_accounts, 0) >= action_required_warning_threshold then 'action_required_accounts'::text end,
      case when coalesce(restricted_accounts, 0) >= restricted_warning_threshold then 'restricted_accounts'::text end,
      case when coalesce(changed_since_previous, false) then 'inventory_changed'::text end
    ]::text[], null) as alert_codes
  from ages
), ranked as (
  select
    signals.*,
    case
      when inventory_status = 'failed' or adapter_status = 'failed'
        or coalesce(inventory_minutes_since_check >= inventory_critical_minutes, false)
        or coalesce(adapter_minutes_since_check >= adapter_critical_minutes, false)
        then 'critical'
      when inventory_checked_at is null or adapter_checked_at is null then 'not_run'
      when cardinality(alert_codes) > 0 then 'warning'
      else 'healthy'
    end as operational_status
  from signals
)
select
  ranked.provider_id,
  ranked.provider_code,
  ranked.display_name,
  'sandbox'::text as environment,
  ranked.operational_status,
  ranked.alert_codes,
  cardinality(ranked.alert_codes) as signal_count,
  (
    select count(*)::integer
    from public.broker_operations_alerts alert
    where alert.provider_id = ranked.provider_id and alert.status = 'open'
  ) as open_alert_count,
  ranked.inventory_status,
  ranked.inventory_http_status,
  ranked.inventory_checked_at,
  ranked.inventory_minutes_since_check,
  ranked.inventory_warning_minutes,
  ranked.inventory_critical_minutes,
  ranked.total_accounts,
  ranked.active_accounts,
  ranked.pending_accounts,
  ranked.action_required_accounts,
  ranked.restricted_accounts,
  ranked.changed_since_previous,
  ranked.page_limit_reached,
  ranked.adapter_status,
  ranked.adapter_http_status,
  ranked.adapter_checked_at,
  ranked.adapter_minutes_since_check,
  ranked.adapter_warning_minutes,
  ranked.adapter_critical_minutes,
  case
    when ranked.operational_status = 'critical' and (
      ranked.inventory_status = 'failed' or ranked.adapter_status = 'failed'
    ) then 'Review server-side broker credentials and provider availability.'
    when ranked.operational_status = 'critical' then 'Run the protected broker probe and inventory sync immediately.'
    when ranked.operational_status = 'not_run' then 'Run the protected broker probe and inventory sync.'
    when 'action_required_accounts' = any(ranked.alert_codes)
      or 'restricted_accounts' = any(ranked.alert_codes)
      then 'Review aggregate sandbox restrictions in Alpaca BrokerDash.'
    when 'inventory_changed' = any(ranked.alert_codes)
      then 'Review the inventory change before continuing broker certification.'
    when ranked.operational_status = 'warning'
      then 'Review the reconciliation signals and refresh stale evidence.'
    else 'No broker operations action is required.'
  end as next_action,
  true as accounts_read_enabled,
  false as orders_read_enabled,
  false as orders_write_enabled,
  ranked.account_connection_enabled,
  ranked.live_order_routing_enabled
from ranked;

grant select on public.broker_operations_health to authenticated;

create or replace function public.evaluate_broker_operations_health(
  p_provider_code text default 'alpaca-broker-sandbox'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  health_record public.broker_operations_health%rowtype;
  current_code text;
  current_severity text;
  current_title text;
  current_message text;
  current_evidence jsonb;
  alert_existed boolean;
  alert_record public.broker_operations_alerts%rowtype;
  resolved_record public.broker_operations_alerts%rowtype;
  open_alerts integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the broker-operations monitoring service';
  end if;

  select * into health_record
  from public.broker_operations_health
  where provider_code = p_provider_code;

  if health_record.provider_id is null or p_provider_code <> 'alpaca-broker-sandbox' then
    raise exception 'Alpaca sandbox monitoring policy not found';
  end if;

  if health_record.account_connection_enabled or health_record.live_order_routing_enabled
    or health_record.orders_read_enabled or health_record.orders_write_enabled then
    raise exception 'Broker operations monitoring requires all execution routes disabled';
  end if;

  current_evidence := jsonb_strip_nulls(jsonb_build_object(
    'providerCode', health_record.provider_code,
    'environment', health_record.environment,
    'operationalStatus', health_record.operational_status,
    'inventoryStatus', health_record.inventory_status,
    'inventoryCheckedAt', health_record.inventory_checked_at,
    'inventoryMinutesSinceCheck', health_record.inventory_minutes_since_check,
    'adapterStatus', health_record.adapter_status,
    'adapterCheckedAt', health_record.adapter_checked_at,
    'adapterMinutesSinceCheck', health_record.adapter_minutes_since_check,
    'totalAccounts', health_record.total_accounts,
    'actionRequiredAccounts', health_record.action_required_accounts,
    'restrictedAccounts', health_record.restricted_accounts,
    'pageLimitReached', health_record.page_limit_reached,
    'changedSincePrevious', health_record.changed_since_previous,
    'ordersRead', false,
    'ordersWrite', false,
    'liveOrderRoutingEnabled', false
  ));

  foreach current_code in array health_record.alert_codes loop
    current_severity := case
      when current_code in ('inventory_sync_failed', 'adapter_probe_failed') then 'critical'
      when current_code = 'inventory_stale'
        and health_record.inventory_minutes_since_check >= health_record.inventory_critical_minutes then 'critical'
      when current_code = 'adapter_probe_stale'
        and health_record.adapter_minutes_since_check >= health_record.adapter_critical_minutes then 'critical'
      else 'warning'
    end;

    current_title := case current_code
      when 'inventory_not_run' then 'Account inventory has not run'
      when 'adapter_probe_not_run' then 'Broker adapter probe has not run'
      when 'inventory_sync_failed' then 'Account inventory sync failed'
      when 'adapter_probe_failed' then 'Broker adapter probe failed'
      when 'inventory_stale' then 'Account inventory is stale'
      when 'adapter_probe_stale' then 'Broker adapter evidence is stale'
      when 'inventory_page_limit_reached' then 'Account inventory reached its page limit'
      when 'action_required_accounts' then 'Sandbox accounts require action'
      when 'restricted_accounts' then 'Sandbox accounts are restricted'
      else 'Sandbox account inventory changed'
    end;

    current_message := case current_code
      when 'inventory_not_run' then 'Run the protected aggregate account inventory before relying on broker readiness.'
      when 'adapter_probe_not_run' then 'Run the protected read-only asset probe before relying on broker readiness.'
      when 'inventory_sync_failed' then 'Review the server-side sandbox credential and Alpaca availability, then retry the inventory.'
      when 'adapter_probe_failed' then 'Review the server-side sandbox credential and Alpaca availability, then retry the probe.'
      when 'inventory_stale' then 'Refresh the aggregate account inventory to restore current reconciliation evidence.'
      when 'adapter_probe_stale' then 'Refresh the read-only asset probe to restore current adapter evidence.'
      when 'inventory_page_limit_reached' then 'The aggregate may be incomplete; review pagination before relying on the totals.'
      when 'action_required_accounts' then 'Review the aggregate action-required count in Alpaca BrokerDash.'
      when 'restricted_accounts' then 'Review the aggregate restricted-account count in Alpaca BrokerDash.'
      else 'Review the aggregate account-state change before continuing broker certification.'
    end;

    select exists (
      select 1 from public.broker_operations_alerts
      where provider_id = health_record.provider_id
        and alert_code = current_code
        and status = 'open'
    ) into alert_existed;

    insert into public.broker_operations_alerts (
      provider_id,
      environment,
      alert_code,
      severity,
      status,
      title,
      message,
      evidence
    ) values (
      health_record.provider_id,
      'sandbox',
      current_code,
      current_severity,
      'open',
      current_title,
      current_message,
      current_evidence
    )
    on conflict (provider_id, alert_code) where status = 'open'
    do update set
      severity = excluded.severity,
      title = excluded.title,
      message = excluded.message,
      evidence = excluded.evidence,
      last_detected_at = now(),
      occurrence_count = public.broker_operations_alerts.occurrence_count + 1
    returning * into alert_record;

    if not alert_existed then
      insert into public.financial_audit_events (
        event_type, resource_type, resource_id, actor_type, correlation_id, details
      ) values (
        'broker_operations_alert_opened',
        'broker_operations_alert',
        alert_record.id::text,
        'system',
        alert_record.id::text,
        jsonb_build_object(
          'providerCode', health_record.provider_code,
          'environment', 'sandbox',
          'alertCode', alert_record.alert_code,
          'severity', alert_record.severity,
          'ordersWrite', false,
          'liveOrderRoutingEnabled', false
        )
      );
    end if;
  end loop;

  for resolved_record in
    update public.broker_operations_alerts
    set
      status = 'resolved',
      resolved_at = now(),
      last_detected_at = now()
    where provider_id = health_record.provider_id
      and status = 'open'
      and not (alert_code = any(health_record.alert_codes))
    returning *
  loop
    insert into public.financial_audit_events (
      event_type, resource_type, resource_id, actor_type, correlation_id, details
    ) values (
      'broker_operations_alert_resolved',
      'broker_operations_alert',
      resolved_record.id::text,
      'system',
      resolved_record.id::text,
      jsonb_build_object(
        'providerCode', health_record.provider_code,
        'environment', 'sandbox',
        'alertCode', resolved_record.alert_code,
        'severity', resolved_record.severity,
        'ordersWrite', false,
        'liveOrderRoutingEnabled', false
      )
    );
  end loop;

  select count(*)::integer into open_alerts
  from public.broker_operations_alerts
  where provider_id = health_record.provider_id and status = 'open';

  return jsonb_build_object(
    'providerCode', health_record.provider_code,
    'environment', health_record.environment,
    'operationalStatus', health_record.operational_status,
    'signalCodes', to_jsonb(health_record.alert_codes),
    'openAlerts', open_alerts,
    'evaluatedAt', now(),
    'nextAction', health_record.next_action,
    'accountsRead', true,
    'ordersRead', false,
    'ordersWrite', false,
    'accountConnectionEnabled', false,
    'liveOrderRoutingEnabled', false
  );
end;
$$;

revoke all on function public.evaluate_broker_operations_health(text) from public;
grant execute on function public.evaluate_broker_operations_health(text) to service_role;

create or replace view public.broker_operations_alert_feed
with (security_invoker = true)
as
select
  alert.id,
  provider.code as provider_code,
  provider.display_name,
  alert.environment,
  alert.alert_code,
  alert.severity,
  alert.status,
  alert.title,
  alert.message,
  alert.evidence,
  alert.occurrence_count,
  alert.first_detected_at,
  alert.last_detected_at,
  alert.resolved_at
from public.broker_operations_alerts alert
join public.broker_provider_registry provider on provider.id = alert.provider_id
where provider.code = 'alpaca-broker-sandbox';

grant select on public.broker_operations_alert_feed to authenticated;

comment on table public.broker_operations_policies is
  'Read-only freshness and aggregate reconciliation thresholds for the sandbox broker control plane.';
comment on table public.broker_operations_alerts is
  'Service-controlled broker operations alert lifecycle derived only from sanitized aggregate evidence.';
comment on view public.broker_operations_health is
  'Current broker operational health, freshness, aggregate signals and next action with execution routes locked.';
comment on function public.evaluate_broker_operations_health(text) is
  'Service-only idempotent evaluation that opens and resolves sanitized broker operations alerts.';
comment on view public.broker_operations_alert_feed is
  'Authenticated sanitized broker operations alert history with no provider account identifiers or customer PII.';
