-- TradePulse AI
-- Migration 019: Paper decision intelligence and forecast-attribution journal
-- This is a simulation learning layer. It cannot create a broker order or move funds.

create table public.paper_decision_contexts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.paper_orders(id) on delete cascade,
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  instrument_id bigint not null references public.investment_instruments(id),
  thesis text not null check (
    length(trim(thesis)) between 8 and 500
    and thesis = trim(thesis)
  ),
  conviction smallint not null check (conviction between 1 and 5),
  planned_horizon_hours integer not null check (
    planned_horizon_hours in (1, 24, 72, 168, 720)
  ),
  entry_price numeric(20,8) not null check (entry_price > 0),
  reference_observed_at timestamptz not null,
  forecast_id bigint references public.market_forecasts(id) on delete set null,
  forecast_direction text check (
    forecast_direction is null or forecast_direction in ('up', 'down', 'flat')
  ),
  forecast_predicted_price numeric(20,8) check (
    forecast_predicted_price is null or forecast_predicted_price >= 0
  ),
  forecast_lower_bound numeric(20,8),
  forecast_upper_bound numeric(20,8),
  forecast_confidence numeric(5,4) check (
    forecast_confidence is null or forecast_confidence between 0 and 1
  ),
  forecast_model_name text,
  forecast_model_version text,
  forecast_generated_at timestamptz,
  forecast_target_at timestamptz,
  research_score numeric(6,3) check (
    research_score is null or research_score between 0 and 100
  ),
  research_classification text check (
    research_classification is null
    or research_classification in (
      'research_positive',
      'research_neutral',
      'research_cautious',
      'insufficient_data'
    )
  ),
  research_confidence numeric(5,4) check (
    research_confidence is null or research_confidence between 0 and 1
  ),
  research_methodology_version text,
  research_risk_flags jsonb not null default '[]'::jsonb check (
    jsonb_typeof(research_risk_flags) = 'array'
    and jsonb_array_length(research_risk_flags) <= 20
  ),
  simulation boolean not null default true check (simulation),
  created_at timestamptz not null default now(),
  check (
    forecast_lower_bound is null
    or forecast_upper_bound is null
    or forecast_lower_bound <= forecast_upper_bound
  )
);

create table public.paper_decision_outcomes (
  id bigint generated by default as identity primary key,
  decision_context_id uuid not null unique
    references public.paper_decision_contexts(id) on delete cascade,
  portfolio_id uuid not null references public.investment_portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  evaluation_status text not null check (
    evaluation_status in ('evaluated', 'insufficient_data')
  ),
  due_at timestamptz not null,
  evaluated_at timestamptz not null default now(),
  outcome_price numeric(20,8) check (outcome_price is null or outcome_price > 0),
  outcome_observed_at timestamptz,
  asset_return_percent numeric(16,8),
  decision_return_percent numeric(16,8),
  forecast_error_percent numeric(16,8) check (
    forecast_error_percent is null or forecast_error_percent >= 0
  ),
  forecast_direction_correct boolean,
  evaluation_version text not null default 'paper-decision-v1',
  simulation boolean not null default true check (simulation),
  created_at timestamptz not null default now(),
  check (
    (evaluation_status = 'evaluated'
      and outcome_price is not null
      and outcome_observed_at is not null
      and asset_return_percent is not null
      and decision_return_percent is not null)
    or
    (evaluation_status = 'insufficient_data'
      and outcome_price is null
      and outcome_observed_at is null
      and asset_return_percent is null
      and decision_return_percent is null
      and forecast_error_percent is null
      and forecast_direction_correct is null)
  )
);

create index idx_paper_decisions_portfolio_created
  on public.paper_decision_contexts(portfolio_id, created_at desc);

create index idx_paper_decision_outcomes_portfolio_evaluated
  on public.paper_decision_outcomes(portfolio_id, evaluated_at desc);

alter table public.paper_decision_contexts enable row level security;
alter table public.paper_decision_outcomes enable row level security;

create policy "Users read their paper decision contexts"
  on public.paper_decision_contexts for select to authenticated
  using (user_id = auth.uid());

create policy "Users read their paper decision outcomes"
  on public.paper_decision_outcomes for select to authenticated
  using (user_id = auth.uid());

revoke all on public.paper_decision_contexts
  from public, anon, authenticated, service_role;
revoke all on public.paper_decision_outcomes
  from public, anon, authenticated, service_role;
revoke all on sequence public.paper_decision_outcomes_id_seq
  from public, anon, authenticated, service_role;
grant select on public.paper_decision_contexts to authenticated;
grant select on public.paper_decision_outcomes to authenticated;

create or replace function public.prevent_paper_decision_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Paper decision evidence is append-only';
end;
$$;

create trigger paper_decision_contexts_append_only
  before update or delete on public.paper_decision_contexts
  for each row execute function public.prevent_paper_decision_mutation();

create trigger paper_decision_outcomes_append_only
  before update or delete on public.paper_decision_outcomes
  for each row execute function public.prevent_paper_decision_mutation();

create or replace function public.execute_paper_market_order_with_context(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_instrument_id bigint,
  p_client_order_id text,
  p_side text,
  p_quantity numeric,
  p_thesis text,
  p_conviction integer,
  p_planned_horizon_hours integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  order_result jsonb;
  selected_order public.paper_orders%rowtype;
  selected_instrument public.investment_instruments%rowtype;
  selected_forecast public.market_forecasts%rowtype;
  selected_research public.equity_research_scores%rowtype;
  selected_observation public.market_observations%rowtype;
  decision_record public.paper_decision_contexts%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the paper-trading service';
  end if;

  p_thesis := trim(coalesce(p_thesis, ''));
  if length(p_thesis) < 8 or length(p_thesis) > 500 then
    raise exception 'A paper decision thesis between 8 and 500 characters is required';
  end if;

  if p_conviction not between 1 and 5 then
    raise exception 'Paper decision conviction must be between 1 and 5';
  end if;

  if p_planned_horizon_hours not in (1, 24, 72, 168, 720) then
    raise exception 'Paper decision horizon is not supported';
  end if;

  order_result := public.execute_paper_market_order(
    p_user_id,
    p_portfolio_id,
    p_instrument_id,
    p_client_order_id,
    p_side,
    p_quantity
  );

  select * into selected_order
  from public.paper_orders
  where id = (order_result ->> 'id')::uuid
    and user_id = p_user_id
    and portfolio_id = p_portfolio_id
    and instrument_id = p_instrument_id;

  if not found then
    raise exception 'The simulated paper order could not be journaled';
  end if;

  select * into decision_record
  from public.paper_decision_contexts
  where order_id = selected_order.id;

  if found then
    return order_result || jsonb_build_object(
      'decisionContext', jsonb_build_object(
        'id', decision_record.id,
        'captured', true,
        'idempotentReplay', true,
        'forecastAvailable', decision_record.forecast_id is not null,
        'researchAvailable', decision_record.research_classification is not null,
        'plannedHorizonHours', decision_record.planned_horizon_hours
      )
    );
  end if;

  select * into selected_instrument
  from public.investment_instruments
  where id = selected_order.instrument_id
    and paper_trading_enabled
    and not live_execution_enabled;

  if not found or selected_instrument.market_asset_id is null then
    raise exception 'The paper instrument is outside the simulation boundary';
  end if;

  select * into selected_observation
  from public.market_observations
  where asset_id = selected_instrument.market_asset_id
    and observed_at <= selected_order.submitted_at
    and price is not null
  order by observed_at desc
  limit 1;

  if not found then
    raise exception 'The paper order reference observation is unavailable';
  end if;

  select * into selected_forecast
  from public.market_forecasts
  where asset_id = selected_instrument.market_asset_id
    and validation_status = 'passed'
    and generated_at <= selected_order.submitted_at
  order by
    abs(horizon_hours - p_planned_horizon_hours),
    generated_at desc
  limit 1;

  select research.* into selected_research
  from public.equity_securities security
  join public.equity_research_scores research
    on research.security_id = security.id
  where security.instrument_id = selected_instrument.id
    and research.status = 'published'
    and research.generated_at <= selected_order.submitted_at
  order by research.generated_at desc
  limit 1;

  insert into public.paper_decision_contexts (
    order_id,
    portfolio_id,
    user_id,
    instrument_id,
    thesis,
    conviction,
    planned_horizon_hours,
    entry_price,
    reference_observed_at,
    forecast_id,
    forecast_direction,
    forecast_predicted_price,
    forecast_lower_bound,
    forecast_upper_bound,
    forecast_confidence,
    forecast_model_name,
    forecast_model_version,
    forecast_generated_at,
    forecast_target_at,
    research_score,
    research_classification,
    research_confidence,
    research_methodology_version,
    research_risk_flags
  ) values (
    selected_order.id,
    selected_order.portfolio_id,
    selected_order.user_id,
    selected_order.instrument_id,
    p_thesis,
    p_conviction,
    p_planned_horizon_hours,
    coalesce(selected_order.average_fill_price, selected_order.reference_price),
    selected_observation.observed_at,
    selected_forecast.id,
    selected_forecast.direction,
    selected_forecast.predicted_price,
    selected_forecast.lower_bound,
    selected_forecast.upper_bound,
    selected_forecast.confidence_score,
    selected_forecast.model_name,
    selected_forecast.model_version,
    selected_forecast.generated_at,
    selected_forecast.target_at,
    selected_research.score,
    selected_research.classification,
    selected_research.confidence,
    selected_research.methodology_version,
    coalesce(selected_research.risk_flags, '[]'::jsonb)
  ) returning * into decision_record;

  insert into public.financial_audit_events (
    user_id,
    event_type,
    resource_type,
    resource_id,
    actor_type,
    correlation_id,
    details
  ) values (
    p_user_id,
    'paper_decision_context_captured',
    'paper_decision_context',
    decision_record.id::text,
    'user',
    trim(p_client_order_id),
    jsonb_build_object(
      'orderId', selected_order.id,
      'conviction', p_conviction,
      'plannedHorizonHours', p_planned_horizon_hours,
      'forecastId', selected_forecast.id,
      'researchClassification', selected_research.classification,
      'thesisStoredPrivately', true,
      'simulation', true,
      'liveOrderRouting', false
    )
  );

  return order_result || jsonb_build_object(
    'decisionContext', jsonb_build_object(
      'id', decision_record.id,
      'captured', true,
      'idempotentReplay', false,
      'forecastAvailable', decision_record.forecast_id is not null,
      'researchAvailable', decision_record.research_classification is not null,
      'plannedHorizonHours', decision_record.planned_horizon_hours
    )
  );
end;
$$;

revoke all on function public.execute_paper_market_order_with_context(
  uuid, uuid, bigint, text, text, numeric, text, integer, integer
) from public, anon, authenticated;
grant execute on function public.execute_paper_market_order_with_context(
  uuid, uuid, bigint, text, text, numeric, text, integer, integer
) to service_role;

create or replace function public.evaluate_paper_decision_outcomes(
  p_user_id uuid,
  p_portfolio_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  decision_record record;
  outcome_observation public.market_observations%rowtype;
  asset_return numeric(16,8);
  decision_return numeric(16,8);
  forecast_error numeric(16,8);
  direction_correct boolean;
  evaluated_count integer := 0;
  insufficient_count integer := 0;
  pending_count integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'This operation requires the paper-trading service';
  end if;

  if not exists (
    select 1
    from public.investment_portfolios
    where id = p_portfolio_id
      and user_id = p_user_id
      and portfolio_type = 'paper'
  ) then
    raise exception 'Paper portfolio was not found';
  end if;

  for decision_record in
    select
      context.*,
      orders.side,
      orders.status as order_status,
      instrument.market_asset_id,
      orders.submitted_at + make_interval(hours => context.planned_horizon_hours) as due_at
    from public.paper_decision_contexts context
    join public.paper_orders orders on orders.id = context.order_id
    join public.investment_instruments instrument on instrument.id = context.instrument_id
    left join public.paper_decision_outcomes outcome
      on outcome.decision_context_id = context.id
    where context.user_id = p_user_id
      and context.portfolio_id = p_portfolio_id
      and orders.status = 'filled'
      and outcome.id is null
    order by context.created_at
  loop
    if decision_record.due_at > now() then
      pending_count := pending_count + 1;
      continue;
    end if;

    select * into outcome_observation
    from public.market_observations
    where asset_id = decision_record.market_asset_id
      and observed_at >= decision_record.due_at
      and observed_at <= decision_record.due_at + interval '7 days'
      and price is not null
    order by observed_at
    limit 1;

    if not found then
      if now() <= decision_record.due_at + interval '7 days' then
        pending_count := pending_count + 1;
        continue;
      end if;

      insert into public.paper_decision_outcomes (
        decision_context_id,
        portfolio_id,
        user_id,
        evaluation_status,
        due_at
      ) values (
        decision_record.id,
        p_portfolio_id,
        p_user_id,
        'insufficient_data',
        decision_record.due_at
      );
      insufficient_count := insufficient_count + 1;
      continue;
    end if;

    asset_return := round(
      ((outcome_observation.price - decision_record.entry_price)
        / decision_record.entry_price * 100)::numeric,
      8
    );
    decision_return := case decision_record.side
      when 'buy' then asset_return
      else -asset_return
    end;
    forecast_error := case
      when decision_record.forecast_predicted_price is null
        or outcome_observation.price = 0 then null
      else round(
        (abs(decision_record.forecast_predicted_price - outcome_observation.price)
          / outcome_observation.price * 100)::numeric,
        8
      )
    end;
    direction_correct := case decision_record.forecast_direction
      when 'up' then asset_return > 0.1
      when 'down' then asset_return < -0.1
      when 'flat' then abs(asset_return) <= 0.1
      else null
    end;

    insert into public.paper_decision_outcomes (
      decision_context_id,
      portfolio_id,
      user_id,
      evaluation_status,
      due_at,
      outcome_price,
      outcome_observed_at,
      asset_return_percent,
      decision_return_percent,
      forecast_error_percent,
      forecast_direction_correct
    ) values (
      decision_record.id,
      p_portfolio_id,
      p_user_id,
      'evaluated',
      decision_record.due_at,
      outcome_observation.price,
      outcome_observation.observed_at,
      asset_return,
      decision_return,
      forecast_error,
      direction_correct
    );

    insert into public.financial_audit_events (
      user_id,
      event_type,
      resource_type,
      resource_id,
      actor_type,
      correlation_id,
      details
    ) values (
      p_user_id,
      'paper_decision_outcome_evaluated',
      'paper_decision_context',
      decision_record.id::text,
      'system',
      decision_record.order_id::text,
      jsonb_build_object(
        'evaluationVersion', 'paper-decision-v1',
        'forecastDirectionCorrect', direction_correct,
        'simulation', true,
        'liveOrderRouting', false
      )
    );

    evaluated_count := evaluated_count + 1;
  end loop;

  return jsonb_build_object(
    'evaluated', evaluated_count,
    'insufficientData', insufficient_count,
    'pending', pending_count,
    'simulation', true,
    'ordersWrite', false,
    'liveOrderRouting', false
  );
end;
$$;

revoke all on function public.evaluate_paper_decision_outcomes(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.evaluate_paper_decision_outcomes(uuid, uuid)
  to service_role;

create or replace view public.paper_decision_journal
with (security_invoker = true)
as
select
  context.id,
  context.order_id,
  context.portfolio_id,
  context.instrument_id,
  instrument.display_symbol as symbol,
  instrument.name as instrument_name,
  orders.side,
  orders.quantity,
  orders.status as order_status,
  orders.submitted_at,
  context.thesis,
  context.conviction,
  context.planned_horizon_hours,
  context.entry_price,
  context.reference_observed_at,
  context.forecast_direction,
  context.forecast_predicted_price,
  context.forecast_confidence,
  context.forecast_model_name,
  context.forecast_model_version,
  context.research_score,
  context.research_classification,
  context.research_confidence,
  context.research_methodology_version,
  context.research_risk_flags,
  orders.submitted_at + make_interval(hours => context.planned_horizon_hours) as due_at,
  coalesce(outcome.evaluation_status, 'pending') as evaluation_status,
  outcome.evaluated_at,
  outcome.outcome_price,
  outcome.outcome_observed_at,
  outcome.asset_return_percent,
  outcome.decision_return_percent,
  outcome.forecast_error_percent,
  outcome.forecast_direction_correct,
  true as simulation,
  false as orders_write_enabled,
  false as live_order_routing_enabled
from public.paper_decision_contexts context
join public.paper_orders orders on orders.id = context.order_id
join public.investment_instruments instrument on instrument.id = context.instrument_id
left join public.paper_decision_outcomes outcome
  on outcome.decision_context_id = context.id;

create or replace view public.paper_decision_scorecard
with (security_invoker = true)
as
select
  context.portfolio_id,
  count(*)::integer as total_decisions,
  count(outcome.id)::integer as completed_decisions,
  count(*) filter (where outcome.evaluation_status = 'insufficient_data')::integer
    as insufficient_data_decisions,
  count(*) filter (where outcome.forecast_direction_correct)::integer
    as correct_forecast_directions,
  round(
    100 * count(*) filter (where outcome.forecast_direction_correct)::numeric
      / nullif(count(*) filter (where outcome.forecast_direction_correct is not null), 0),
    2
  ) as forecast_directional_accuracy_percent,
  round(
    100 * count(*) filter (where outcome.decision_return_percent > 0)::numeric
      / nullif(count(*) filter (where outcome.evaluation_status = 'evaluated'), 0),
    2
  ) as profitable_decision_rate_percent,
  round(avg(outcome.decision_return_percent), 4) as average_decision_return_percent,
  round(avg(outcome.forecast_error_percent), 4) as average_forecast_error_percent,
  max(outcome.evaluated_at) as last_evaluated_at,
  true as simulation,
  false as orders_write_enabled,
  false as live_order_routing_enabled
from public.paper_decision_contexts context
left join public.paper_decision_outcomes outcome
  on outcome.decision_context_id = context.id
group by context.portfolio_id;

grant select on public.paper_decision_journal to authenticated;
grant select on public.paper_decision_scorecard to authenticated;

comment on table public.paper_decision_contexts is
  'Private append-only paper-trade theses with point-in-time forecast and published research snapshots.';
comment on table public.paper_decision_outcomes is
  'Private append-only paper-decision learning outcomes evaluated from synchronized market observations.';
comment on function public.execute_paper_market_order_with_context is
  'Service-only wrapper that atomically journals a simulation order and its point-in-time decision evidence.';
comment on function public.evaluate_paper_decision_outcomes is
  'Service-only paper-learning evaluator. It cannot place orders or call a broker.';
comment on view public.paper_decision_journal is
  'Authenticated private journal joining simulation orders, captured AI context and later learning outcomes.';
comment on view public.paper_decision_scorecard is
  'Authenticated private paper-decision and forecast-attribution learning metrics.';
