-- TradePulse AI
-- Migration 020: Forecast reliability, production evaluation and model governance
-- Forecasts remain non-personalized decision support and cannot route orders.

alter table public.market_forecasts
  add column if not exists reference_price numeric(20,8)
    check (reference_price is null or reference_price > 0),
  add column if not exists validation_interval_coverage numeric(5,4)
    check (
      validation_interval_coverage is null
      or validation_interval_coverage between 0 and 1
    ),
  add column if not exists cost_adjusted_return numeric(16,8),
  add column if not exists cost_adjusted_max_drawdown numeric(16,8)
    check (
      cost_adjusted_max_drawdown is null
      or cost_adjusted_max_drawdown between 0 and 1
    ),
  add column if not exists estimated_turnover numeric(20,8)
    check (estimated_turnover is null or estimated_turnover >= 0);

alter table public.forecast_evaluations
  add column if not exists actual_observed_at timestamptz,
  add column if not exists reference_price numeric(20,8)
    check (reference_price is null or reference_price > 0),
  add column if not exists baseline_absolute_error numeric(20,8)
    check (
      baseline_absolute_error is null
      or baseline_absolute_error >= 0
    ),
  add column if not exists interval_covered boolean;

create table public.forecast_governance_policies (
  id bigint generated by default as identity primary key,
  policy_key text not null unique,
  policy_version text not null,
  lookback_days integer not null check (lookback_days between 7 and 3650),
  minimum_evaluations integer not null check (minimum_evaluations between 5 and 10000),
  qualified_mae_improvement_pct numeric(8,4) not null,
  qualified_directional_accuracy numeric(5,4) not null check (
    qualified_directional_accuracy between 0 and 1
  ),
  interval_coverage_min numeric(5,4) not null check (
    interval_coverage_min between 0 and 1
  ),
  interval_coverage_max numeric(5,4) not null check (
    interval_coverage_max between 0 and 1
  ),
  suspension_mae_degradation_pct numeric(8,4) not null check (
    suspension_mae_degradation_pct >= 0
  ),
  suspension_directional_accuracy numeric(5,4) not null check (
    suspension_directional_accuracy between 0 and 1
  ),
  suspension_interval_coverage numeric(5,4) not null check (
    suspension_interval_coverage between 0 and 1
  ),
  observation_grace_hours integer not null check (
    observation_grace_hours between 1 and 720
  ),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  check (interval_coverage_min <= interval_coverage_max),
  check (
    suspension_directional_accuracy <= qualified_directional_accuracy
  ),
  check (suspension_interval_coverage <= interval_coverage_min)
);

create unique index forecast_governance_one_active_policy
  on public.forecast_governance_policies(active)
  where active;

insert into public.forecast_governance_policies (
  policy_key,
  policy_version,
  lookback_days,
  minimum_evaluations,
  qualified_mae_improvement_pct,
  qualified_directional_accuracy,
  interval_coverage_min,
  interval_coverage_max,
  suspension_mae_degradation_pct,
  suspension_directional_accuracy,
  suspension_interval_coverage,
  observation_grace_hours,
  active
)
values (
  'default-production-reliability',
  'forecast-governance-v1',
  90,
  20,
  2.0000,
  0.5200,
  0.7500,
  0.9800,
  5.0000,
  0.4500,
  0.6000,
  72,
  true
);

create table public.forecast_reliability_snapshots (
  id bigint generated by default as identity primary key,
  policy_id bigint not null references public.forecast_governance_policies(id),
  policy_version text not null,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  model_name text not null,
  model_version text not null,
  horizon_hours integer not null check (horizon_hours > 0),
  evaluation_count integer not null check (evaluation_count > 0),
  source_evaluation_max_id bigint not null references public.forecast_evaluations(id),
  evaluation_window_start timestamptz not null,
  evaluation_window_end timestamptz not null,
  model_mae numeric(20,8) not null check (model_mae >= 0),
  baseline_mae numeric(20,8) not null check (baseline_mae >= 0),
  mae_improvement_pct numeric(12,6),
  mean_absolute_percentage_error numeric(12,8) check (
    mean_absolute_percentage_error is null
    or mean_absolute_percentage_error >= 0
  ),
  directional_accuracy numeric(5,4) check (
    directional_accuracy is null
    or directional_accuracy between 0 and 1
  ),
  interval_coverage numeric(5,4) check (
    interval_coverage is null
    or interval_coverage between 0 and 1
  ),
  reliability_status text not null check (
    reliability_status in (
      'insufficient_evidence',
      'qualified',
      'watch',
      'suspended'
    )
  ),
  display_eligible boolean not null,
  reason_codes jsonb not null default '[]'::jsonb check (
    jsonb_typeof(reason_codes) = 'array'
    and jsonb_array_length(reason_codes) between 1 and 10
  ),
  evaluated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (evaluation_window_start <= evaluation_window_end),
  check (display_eligible = (reliability_status <> 'suspended')),
  unique (
    policy_id,
    asset_id,
    model_name,
    model_version,
    horizon_hours,
    source_evaluation_max_id
  )
);

create index forecast_reliability_asset_model_created
  on public.forecast_reliability_snapshots (
    asset_id,
    model_name,
    model_version,
    horizon_hours,
    created_at desc
  );

alter table public.model_drift_events
  add column if not exists asset_id bigint
    references public.market_assets(id) on delete cascade,
  add column if not exists horizon_hours integer
    check (horizon_hours is null or horizon_hours > 0),
  add column if not exists reliability_snapshot_id bigint
    references public.forecast_reliability_snapshots(id) on delete set null,
  add column if not exists deduplication_key text;

create unique index if not exists model_drift_events_deduplication_key
  on public.model_drift_events(deduplication_key)
  where deduplication_key is not null;

alter table public.forecast_governance_policies enable row level security;
alter table public.forecast_reliability_snapshots enable row level security;

create policy "Public can read the active forecast governance policy"
  on public.forecast_governance_policies for select to anon, authenticated
  using (active);

create policy "Public can read forecast reliability snapshots"
  on public.forecast_reliability_snapshots for select to anon, authenticated
  using (true);

revoke all on public.forecast_governance_policies
  from public, anon, authenticated, service_role;
revoke all on public.forecast_reliability_snapshots
  from public, anon, authenticated, service_role;
revoke all on sequence public.forecast_governance_policies_id_seq
  from public, anon, authenticated, service_role;
revoke all on sequence public.forecast_reliability_snapshots_id_seq
  from public, anon, authenticated, service_role;
grant select on public.forecast_governance_policies to anon, authenticated;
grant select on public.forecast_reliability_snapshots to anon, authenticated;

revoke insert, update, delete on public.forecast_evaluations
  from public, anon, authenticated, service_role;
revoke usage, select on sequence public.forecast_evaluations_id_seq
  from public, anon, authenticated, service_role;
revoke insert, update, delete on public.model_drift_events
  from public, anon, authenticated, service_role;
revoke usage, select on sequence public.model_drift_events_id_seq
  from public, anon, authenticated, service_role;

create or replace function public.prevent_forecast_reliability_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Forecast reliability evidence is append-only';
end;
$$;

create trigger forecast_reliability_snapshots_append_only
  before update or delete on public.forecast_reliability_snapshots
  for each row execute function public.prevent_forecast_reliability_mutation();

create trigger forecast_evaluations_append_only
  before update or delete on public.forecast_evaluations
  for each row execute function public.prevent_forecast_reliability_mutation();

create or replace function public.evaluate_forecast_governance(
  p_as_of timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_policy public.forecast_governance_policies%rowtype;
  evaluated_count integer := 0;
  snapshot_count integer := 0;
  qualified_count integer := 0;
  watch_count integer := 0;
  suspended_count integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Forecast governance evaluation requires the forecasting service';
  end if;

  if p_as_of is null or p_as_of > now() + interval '5 minutes' then
    raise exception 'Forecast governance evaluation time is invalid';
  end if;

  select * into selected_policy
  from public.forecast_governance_policies
  where active
  order by created_at desc
  limit 1;

  if not found then
    raise exception 'No active forecast governance policy is configured';
  end if;

  with due_forecasts as (
    select
      forecast.*,
      observation.price as actual_price,
      observation.observed_at as actual_observed_at
    from public.market_forecasts forecast
    join public.forecast_runs run
      on run.id = forecast.forecast_run_id
      and run.status = 'completed'
    join lateral (
      select item.price, item.observed_at
      from public.market_observations item
      where item.asset_id = forecast.asset_id
        and item.price is not null
        and item.observed_at >= forecast.target_at
        and item.observed_at <= forecast.target_at
          + make_interval(hours => selected_policy.observation_grace_hours)
        and item.observed_at <= p_as_of
      order by item.observed_at, item.id
      limit 1
    ) observation on true
    where forecast.target_at <= p_as_of
      and forecast.reference_price is not null
      and not exists (
        select 1
        from public.forecast_evaluations existing
        where existing.forecast_id = forecast.id
      )
  ), inserted_evaluations as (
    insert into public.forecast_evaluations (
      forecast_id,
      actual_price,
      absolute_error,
      absolute_percentage_error,
      directional_correct,
      evaluated_at,
      actual_observed_at,
      reference_price,
      baseline_absolute_error,
      interval_covered
    )
    select
      forecast.id,
      forecast.actual_price,
      abs(forecast.actual_price - forecast.predicted_price),
      case
        when forecast.actual_price = 0 then null
        else abs(forecast.actual_price - forecast.predicted_price)
          / forecast.actual_price * 100
      end,
      case forecast.direction
        when 'up' then forecast.actual_price > forecast.reference_price
        when 'down' then forecast.actual_price < forecast.reference_price
        else abs(
          (forecast.actual_price / forecast.reference_price - 1) * 100
        ) <= 0.15
      end,
      p_as_of,
      forecast.actual_observed_at,
      forecast.reference_price,
      abs(forecast.actual_price - forecast.reference_price),
      case
        when forecast.lower_bound is null or forecast.upper_bound is null then null
        else forecast.actual_price between forecast.lower_bound and forecast.upper_bound
      end
    from due_forecasts forecast
    on conflict (forecast_id) do nothing
    returning id
  )
  select count(*) into evaluated_count from inserted_evaluations;

  with aggregate_metrics as (
    select
      selected_policy.id as policy_id,
      selected_policy.policy_version,
      forecast.asset_id,
      forecast.model_name,
      forecast.model_version,
      forecast.horizon_hours,
      count(*)::integer as evaluation_count,
      max(evaluation.id) as source_evaluation_max_id,
      min(forecast.target_at) as evaluation_window_start,
      max(forecast.target_at) as evaluation_window_end,
      avg(evaluation.absolute_error)::numeric(20,8) as model_mae,
      avg(evaluation.baseline_absolute_error)::numeric(20,8) as baseline_mae,
      avg(evaluation.absolute_percentage_error)::numeric(12,8)
        as mean_absolute_percentage_error,
      avg(evaluation.directional_correct::integer)::numeric(5,4)
        as directional_accuracy,
      avg(evaluation.interval_covered::integer) filter (
        where evaluation.interval_covered is not null
      )::numeric(5,4) as interval_coverage
    from public.forecast_evaluations evaluation
    join public.market_forecasts forecast on forecast.id = evaluation.forecast_id
    where forecast.target_at >= p_as_of
        - make_interval(days => selected_policy.lookback_days)
      and forecast.target_at <= p_as_of
      and evaluation.baseline_absolute_error is not null
    group by
      forecast.asset_id,
      forecast.model_name,
      forecast.model_version,
      forecast.horizon_hours
  ), classified as (
    select
      metrics.*,
      case
        when metrics.baseline_mae = 0 then null
        else (
          (metrics.baseline_mae - metrics.model_mae) / metrics.baseline_mae
        ) * 100
      end as mae_improvement_pct,
      case
        when metrics.evaluation_count < selected_policy.minimum_evaluations
          then 'insufficient_evidence'
        when (
          metrics.baseline_mae > 0
          and metrics.model_mae > metrics.baseline_mae * (
            1 + selected_policy.suspension_mae_degradation_pct / 100
          )
        )
          or coalesce(metrics.directional_accuracy, 0)
            < selected_policy.suspension_directional_accuracy
          or (
            metrics.interval_coverage is not null
            and metrics.interval_coverage
              < selected_policy.suspension_interval_coverage
          ) then 'suspended'
        when (
          metrics.baseline_mae > 0
          and (
            (metrics.baseline_mae - metrics.model_mae) / metrics.baseline_mae
          ) * 100 >= selected_policy.qualified_mae_improvement_pct
          and coalesce(metrics.directional_accuracy, 0)
            >= selected_policy.qualified_directional_accuracy
          and metrics.interval_coverage between
            selected_policy.interval_coverage_min
            and selected_policy.interval_coverage_max
        ) then 'qualified'
        else 'watch'
      end as reliability_status
    from aggregate_metrics metrics
  ), prepared as (
    select
      classified.*,
      to_jsonb(array_remove(array[
        case
          when classified.evaluation_count < selected_policy.minimum_evaluations
            then 'insufficient_evidence'
        end,
        case
          when classified.baseline_mae = 0
            then 'baseline_error_zero'
          when classified.mae_improvement_pct
            < selected_policy.qualified_mae_improvement_pct
            then 'baseline_underperformance'
        end,
        case
          when coalesce(classified.directional_accuracy, 0)
            < selected_policy.qualified_directional_accuracy
            then 'directional_accuracy_low'
        end,
        case
          when classified.interval_coverage is null
            then 'interval_coverage_unavailable'
          when classified.interval_coverage
            < selected_policy.interval_coverage_min
            then 'interval_undercoverage'
          when classified.interval_coverage
            > selected_policy.interval_coverage_max
            then 'interval_overcoverage'
        end,
        case
          when classified.reliability_status = 'qualified'
            then 'production_thresholds_passed'
        end
      ]::text[], null)) as reason_codes
    from classified
  ), inserted_snapshots as (
    insert into public.forecast_reliability_snapshots (
      policy_id,
      policy_version,
      asset_id,
      model_name,
      model_version,
      horizon_hours,
      evaluation_count,
      source_evaluation_max_id,
      evaluation_window_start,
      evaluation_window_end,
      model_mae,
      baseline_mae,
      mae_improvement_pct,
      mean_absolute_percentage_error,
      directional_accuracy,
      interval_coverage,
      reliability_status,
      display_eligible,
      reason_codes,
      evaluated_at
    )
    select
      prepared.policy_id,
      prepared.policy_version,
      prepared.asset_id,
      prepared.model_name,
      prepared.model_version,
      prepared.horizon_hours,
      prepared.evaluation_count,
      prepared.source_evaluation_max_id,
      prepared.evaluation_window_start,
      prepared.evaluation_window_end,
      prepared.model_mae,
      prepared.baseline_mae,
      prepared.mae_improvement_pct,
      prepared.mean_absolute_percentage_error,
      prepared.directional_accuracy,
      prepared.interval_coverage,
      prepared.reliability_status,
      prepared.reliability_status <> 'suspended',
      prepared.reason_codes,
      p_as_of
    from prepared
    on conflict (
      policy_id,
      asset_id,
      model_name,
      model_version,
      horizon_hours,
      source_evaluation_max_id
    ) do nothing
    returning *
  ), inserted_events as (
    insert into public.model_drift_events (
      forecast_run_id,
      model_name,
      model_version,
      metric_name,
      observed_value,
      threshold_value,
      severity,
      status,
      details,
      detected_at,
      asset_id,
      horizon_hours,
      reliability_snapshot_id,
      deduplication_key
    )
    select
      null,
      snapshot.model_name,
      snapshot.model_version,
      'production_reliability_state',
      coalesce(snapshot.mae_improvement_pct, 0),
      selected_policy.qualified_mae_improvement_pct,
      case
        when snapshot.reliability_status = 'suspended' then 'critical'
        else 'warning'
      end,
      'open',
      jsonb_build_object(
        'reliabilityStatus', snapshot.reliability_status,
        'evaluationCount', snapshot.evaluation_count,
        'directionalAccuracy', snapshot.directional_accuracy,
        'intervalCoverage', snapshot.interval_coverage,
        'reasonCodes', snapshot.reason_codes,
        'policyVersion', snapshot.policy_version
      ),
      p_as_of,
      snapshot.asset_id,
      snapshot.horizon_hours,
      snapshot.id,
      concat_ws(
        ':',
        snapshot.asset_id,
        snapshot.model_name,
        snapshot.model_version,
        snapshot.horizon_hours,
        snapshot.reliability_status,
        snapshot.source_evaluation_max_id
      )
    from inserted_snapshots snapshot
    where snapshot.reliability_status in ('watch', 'suspended')
    on conflict (deduplication_key) where deduplication_key is not null
      do nothing
    returning id
  )
  select
    count(*),
    count(*) filter (where reliability_status = 'qualified'),
    count(*) filter (where reliability_status = 'watch'),
    count(*) filter (where reliability_status = 'suspended')
  into snapshot_count, qualified_count, watch_count, suspended_count
  from inserted_snapshots;

  update public.model_drift_events event
  set
    status = 'resolved',
    resolved_at = p_as_of,
    details = event.details || jsonb_build_object(
      'resolvedBy', 'forecast_governance_v1'
    )
  where event.status in ('open', 'acknowledged')
    and event.metric_name = 'production_reliability_state'
    and exists (
      select 1
      from public.forecast_reliability_snapshots snapshot
      where snapshot.asset_id = event.asset_id
        and snapshot.model_name = event.model_name
        and snapshot.model_version = event.model_version
        and snapshot.horizon_hours = event.horizon_hours
        and snapshot.reliability_status = 'qualified'
        and snapshot.id = (
          select latest.id
          from public.forecast_reliability_snapshots latest
          where latest.asset_id = event.asset_id
            and latest.model_name = event.model_name
            and latest.model_version = event.model_version
            and latest.horizon_hours = event.horizon_hours
          order by latest.evaluated_at desc, latest.id desc
          limit 1
        )
    );

  return jsonb_build_object(
    'evaluatedForecasts', evaluated_count,
    'snapshotsPublished', snapshot_count,
    'qualifiedModels', qualified_count,
    'watchModels', watch_count,
    'suspendedModels', suspended_count,
    'policyVersion', selected_policy.policy_version,
    'liveOrderRoutingEnabled', false
  );
end;
$$;

revoke all on function public.evaluate_forecast_governance(timestamptz)
  from public, anon, authenticated;
grant execute on function public.evaluate_forecast_governance(timestamptz)
  to service_role;

create or replace view public.forecast_reliability_latest
with (security_invoker = true)
as
select distinct on (
  snapshot.asset_id,
  snapshot.model_name,
  snapshot.model_version,
  snapshot.horizon_hours
)
  snapshot.*
from public.forecast_reliability_snapshots snapshot
order by
  snapshot.asset_id,
  snapshot.model_name,
  snapshot.model_version,
  snapshot.horizon_hours,
  snapshot.evaluated_at desc,
  snapshot.id desc;

grant select on public.forecast_reliability_latest to anon, authenticated;

create or replace view public.display_qualified_market_forecasts
with (security_invoker = true)
as
select
  forecast.*,
  asset.symbol,
  asset.name as asset_name,
  coalesce(reliability.reliability_status, 'insufficient_evidence')
    as reliability_status,
  coalesce(reliability.evaluation_count, 0) as reliability_evaluation_count,
  reliability.model_mae as production_model_mae,
  reliability.baseline_mae as production_baseline_mae,
  reliability.mae_improvement_pct as production_mae_improvement_pct,
  reliability.mean_absolute_percentage_error as production_mape,
  reliability.directional_accuracy as production_directional_accuracy,
  reliability.interval_coverage as production_interval_coverage,
  coalesce(
    reliability.reason_codes,
    '["insufficient_evidence"]'::jsonb
  ) as reliability_reason_codes,
  coalesce(reliability.display_eligible, true) as governance_display_eligible
from public.market_forecasts forecast
join public.forecast_runs run
  on run.id = forecast.forecast_run_id
  and run.status = 'completed'
join public.market_assets asset on asset.id = forecast.asset_id
left join public.forecast_reliability_latest reliability
  on reliability.asset_id = forecast.asset_id
  and reliability.model_name = forecast.model_name
  and reliability.model_version = forecast.model_version
  and reliability.horizon_hours = forecast.horizon_hours
where forecast.is_latest
  and forecast.validation_status = 'passed'
  and coalesce(reliability.display_eligible, true);

grant select on public.display_qualified_market_forecasts to anon, authenticated;

create or replace view public.equity_research_dashboard
with (security_invoker = true)
as
select
  security.id as security_id,
  security.market_asset_id,
  security.display_symbol,
  security.company_name,
  security.asset_class,
  security.exchange_code,
  security.exchange_name,
  security.exchange_mic,
  security.country_code,
  security.quote_currency,
  security.sector,
  security.industry,
  security.provider_name,
  security.provider_symbol,
  security.forecast_enabled,
  coverage.coverage_status,
  coverage.delay_minutes,
  coverage.license_status,
  coverage.last_synchronized_at,
  observation.observed_at,
  observation.price,
  observation.change_percent,
  observation.source as price_source,
  forecast.id as forecast_id,
  forecast.generated_at as forecast_generated_at,
  forecast.target_at as forecast_target_at,
  forecast.horizon_hours,
  forecast.predicted_price,
  forecast.lower_bound,
  forecast.upper_bound,
  forecast.confidence_score as forecast_confidence,
  forecast.direction as forecast_direction,
  forecast.model_name,
  forecast.model_version,
  forecast.baseline_mae,
  forecast.model_mae,
  forecast.directional_accuracy,
  research.generated_at as research_generated_at,
  research.score as research_score,
  research.classification as research_classification,
  research.confidence as research_confidence,
  research.forecast_score,
  research.momentum_score,
  research.quality_score,
  research.valuation_score,
  research.risk_score,
  research.data_quality_score,
  research.methodology_version,
  research.reasons,
  research.risk_flags,
  fundamental.period_end as fundamental_period_end,
  fundamental.revenue,
  fundamental.net_income,
  fundamental.diluted_eps,
  fundamental.pe_ratio,
  fundamental.price_to_book,
  fundamental.dividend_yield,
  forecast.reliability_status,
  forecast.reliability_evaluation_count,
  forecast.production_model_mae,
  forecast.production_baseline_mae,
  forecast.production_mae_improvement_pct,
  forecast.production_mape,
  forecast.production_directional_accuracy,
  forecast.production_interval_coverage,
  forecast.reliability_reason_codes
from public.equity_securities security
left join lateral (
  select item.*
  from public.equity_data_coverage item
  where item.security_id = security.id
    and item.dataset = 'prices'
  order by item.last_synchronized_at desc nulls last
  limit 1
) coverage on true
left join lateral (
  select item.*
  from public.market_observations item
  where item.asset_id = security.market_asset_id
  order by item.observed_at desc
  limit 1
) observation on true
left join lateral (
  select item.*
  from public.display_qualified_market_forecasts item
  where item.asset_id = security.market_asset_id
  order by item.generated_at desc
  limit 1
) forecast on true
left join lateral (
  select item.*
  from public.equity_research_scores item
  where item.security_id = security.id
    and item.is_latest
    and item.status = 'published'
  order by item.generated_at desc
  limit 1
) research on true
left join lateral (
  select item.*
  from public.equity_fundamental_snapshots item
  where item.security_id = security.id
    and item.display_allowed
  order by item.period_end desc
  limit 1
) fundamental on true;

grant select on public.equity_research_dashboard to anon, authenticated;

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'forecast_reliability_snapshots'
  ) then
    execute 'alter publication supabase_realtime add table public.forecast_reliability_snapshots';
  end if;
end;
$$;

comment on table public.forecast_reliability_snapshots is
  'Append-only production forecast evidence. Suspended models are excluded from display-qualified views.';

comment on function public.evaluate_forecast_governance(timestamptz) is
  'Service-only deterministic evaluator for due forecasts, reliability snapshots and sanitized drift state.';
