-- TradePulse AI
-- Migration 045: Phase 8A global venue and instrument intelligence
-- Reference metadata only. No feed credential, customer entitlement, order route,
-- broker connection, funding, custody or settlement capability is introduced.

create table public.global_market_intelligence_controls (
  control_key text primary key check (control_key = 'global-venue-instrument-intelligence'),
  reference_workspace_enabled boolean not null default true check (reference_workspace_enabled),
  policy_version text not null,
  live_market_data_connectivity_enabled boolean not null default false check (not live_market_data_connectivity_enabled),
  customer_entitlement_assignment_enabled boolean not null default false check (not customer_entitlement_assignment_enabled),
  automatic_jurisdiction_approval_enabled boolean not null default false check (not automatic_jurisdiction_approval_enabled),
  order_preview_enabled boolean not null default false check (not order_preview_enabled),
  order_routing_enabled boolean not null default false check (not order_routing_enabled),
  broker_connectivity_enabled boolean not null default false check (not broker_connectivity_enabled),
  customer_funding_enabled boolean not null default false check (not customer_funding_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  settlement_enabled boolean not null default false check (not settlement_enabled),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.global_market_venues (
  id bigint generated by default as identity primary key,
  mic_code text not null unique check (mic_code ~ '^[A-Z0-9]{4}$'),
  venue_name text not null check (char_length(venue_name) between 3 and 120),
  country_code text not null references public.countries(iso_code),
  timezone text not null check (char_length(timezone) between 3 and 80),
  primary_currency text not null check (primary_currency ~ '^[A-Z]{3}$'),
  venue_type text not null check (venue_type in ('exchange', 'regulated_market')),
  availability_status text not null default 'reference_only' check (
    availability_status in ('reference_only', 'unavailable')
  ),
  source_name text not null,
  source_as_of date not null,
  metadata_version text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.global_market_calendars (
  id bigint generated by default as identity primary key,
  venue_id bigint not null unique references public.global_market_venues(id) on delete cascade,
  calendar_status text not null default 'review_required' check (
    calendar_status in ('verified_reference', 'review_required', 'unavailable')
  ),
  regular_session_open time,
  regular_session_close time,
  session_timezone text not null,
  holiday_calendar_status text not null default 'review_required' check (
    holiday_calendar_status in ('verified_reference', 'review_required', 'unavailable')
  ),
  settlement_convention text not null default 'source_review_required' check (
    settlement_convention in ('T+1', 'T+2', 'same_day', 'source_review_required')
  ),
  session_use_enabled boolean not null default false check (not session_use_enabled),
  source_name text not null,
  source_as_of date not null,
  calendar_version text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    calendar_status <> 'verified_reference'
    or (regular_session_open is not null and regular_session_close is not null)
  )
);

create table public.global_instrument_listings (
  id bigint generated by default as identity primary key,
  listing_key text not null unique,
  canonical_instrument_key text not null,
  venue_id bigint not null references public.global_market_venues(id),
  display_symbol text not null check (char_length(display_symbol) between 1 and 32),
  instrument_name text not null check (char_length(instrument_name) between 3 and 160),
  instrument_type text not null check (instrument_type in ('equity', 'etf', 'depositary_receipt')),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  primary_listing boolean not null default true,
  listing_status text not null default 'reference_only' check (
    listing_status in ('reference_only', 'suspended', 'delisted', 'unavailable')
  ),
  identifier_status text not null default 'review_required' check (
    identifier_status in ('verified_reference', 'review_required', 'unavailable')
  ),
  provider_mapping_status text not null default 'review_required' check (
    provider_mapping_status in ('verified_reference', 'review_required', 'unavailable')
  ),
  corporate_action_status text not null default 'review_required' check (
    corporate_action_status in ('current_reference', 'review_required', 'stale', 'unavailable')
  ),
  tick_size numeric(20,8) check (tick_size is null or tick_size > 0),
  lot_size numeric(20,8) check (lot_size is null or lot_size > 0),
  fractional_reference_status text not null default 'review_required' check (
    fractional_reference_status in ('supported_reference', 'not_supported_reference', 'review_required')
  ),
  source_name text not null,
  source_as_of date not null,
  listing_version text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (venue_id, display_symbol),
  check (listing_key = upper(listing_key)),
  check (canonical_instrument_key = upper(canonical_instrument_key))
);

create table public.global_market_data_entitlements (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references public.global_market_venues(id) on delete cascade,
  dataset text not null check (dataset in ('reference', 'prices', 'corporate_actions')),
  audience_region text not null default 'GLOBAL' check (
    audience_region = 'GLOBAL' or audience_region ~ '^[A-Z]{2}$'
  ),
  display_status text not null check (
    display_status in ('reference_only', 'delayed', 'realtime', 'unavailable')
  ),
  delay_minutes integer check (delay_minutes is null or delay_minutes >= 0),
  license_status text not null check (
    license_status in ('licensed', 'public_domain', 'review_required', 'restricted')
  ),
  redistribution_allowed boolean not null default false check (not redistribution_allowed),
  browser_feed_credentials_enabled boolean not null default false check (not browser_feed_credentials_enabled),
  source_name text not null,
  source_as_of date not null,
  entitlement_version text not null,
  created_at timestamptz not null default now(),
  unique (venue_id, dataset, audience_region),
  check (display_status <> 'delayed' or delay_minutes is not null),
  check (display_status <> 'realtime' or license_status = 'licensed')
);

create table public.global_market_access_policies (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references public.global_market_venues(id) on delete cascade,
  residency_country text not null references public.jurisdictions(country_code),
  customer_type text not null default 'individual' check (customer_type in ('individual', 'business')),
  investor_type text not null default 'retail' check (
    investor_type in ('retail', 'professional', 'accredited', 'institutional')
  ),
  access_status text not null check (
    access_status in ('research_only', 'review_required', 'unavailable')
  ),
  reason_code text not null,
  disclosure_status text not null default 'not_assessed' check (
    disclosure_status in ('not_assessed', 'review_required', 'complete_reference')
  ),
  legal_review_status text not null default 'review_required' check (
    legal_review_status in ('review_required', 'reference_complete')
  ),
  policy_version text not null,
  effective_from date not null,
  effective_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (venue_id, residency_country, customer_type, investor_type),
  check (effective_until is null or effective_until > effective_from),
  check (access_status <> 'research_only' or disclosure_status <> 'complete_reference')
);

create index idx_global_market_venues_country
  on public.global_market_venues(country_code, availability_status);
create index idx_global_instrument_listings_lookup
  on public.global_instrument_listings(venue_id, instrument_type, listing_status);
create index idx_global_market_entitlements_lookup
  on public.global_market_data_entitlements(venue_id, dataset, audience_region);
create index idx_global_market_access_lookup
  on public.global_market_access_policies(residency_country, access_status, venue_id);

alter table public.global_market_intelligence_controls enable row level security;
alter table public.global_market_venues enable row level security;
alter table public.global_market_calendars enable row level security;
alter table public.global_instrument_listings enable row level security;
alter table public.global_market_data_entitlements enable row level security;
alter table public.global_market_access_policies enable row level security;

create policy "Public reads global market intelligence locks"
  on public.global_market_intelligence_controls for select to anon, authenticated
  using (reference_workspace_enabled);
create policy "Public reads enabled global market venues"
  on public.global_market_venues for select to anon, authenticated
  using (enabled);
create policy "Public reads enabled global market calendars"
  on public.global_market_calendars for select to anon, authenticated
  using (enabled);
create policy "Public reads enabled global instrument listings"
  on public.global_instrument_listings for select to anon, authenticated
  using (enabled);
create policy "Public reads sanitized global market entitlements"
  on public.global_market_data_entitlements for select to anon, authenticated
  using (true);
create policy "Public reads global market access references"
  on public.global_market_access_policies for select to anon, authenticated
  using (true);

create trigger global_market_intelligence_controls_set_updated_at
  before update on public.global_market_intelligence_controls
  for each row execute function public.set_updated_at();
create trigger global_market_venues_set_updated_at
  before update on public.global_market_venues
  for each row execute function public.set_updated_at();
create trigger global_market_calendars_set_updated_at
  before update on public.global_market_calendars
  for each row execute function public.set_updated_at();
create trigger global_instrument_listings_set_updated_at
  before update on public.global_instrument_listings
  for each row execute function public.set_updated_at();
create trigger global_market_access_policies_set_updated_at
  before update on public.global_market_access_policies
  for each row execute function public.set_updated_at();

insert into public.global_market_intelligence_controls (
  control_key, policy_version
) values (
  'global-venue-instrument-intelligence',
  'global-venue-instrument-intelligence-v1'
);

insert into public.global_market_venues (
  mic_code, venue_name, country_code, timezone, primary_currency,
  venue_type, source_name, source_as_of, metadata_version
) values
  ('XNAS', 'The Nasdaq Stock Market', 'US', 'America/New_York', 'USD', 'exchange', 'TradePulse reference registry', '2026-09-08', 'venue-reference-v1'),
  ('XNYS', 'New York Stock Exchange', 'US', 'America/New_York', 'USD', 'exchange', 'TradePulse reference registry', '2026-09-08', 'venue-reference-v1'),
  ('XLON', 'London Stock Exchange', 'GB', 'Europe/London', 'GBP', 'regulated_market', 'TradePulse reference registry', '2026-09-08', 'venue-reference-v1'),
  ('XNSE', 'National Stock Exchange of India', 'IN', 'Asia/Kolkata', 'INR', 'exchange', 'TradePulse reference registry', '2026-09-08', 'venue-reference-v1'),
  ('XETR', 'Deutsche Börse Xetra', 'DE', 'Europe/Berlin', 'EUR', 'regulated_market', 'TradePulse reference registry', '2026-09-08', 'venue-reference-v1'),
  ('XTSE', 'Toronto Stock Exchange', 'CA', 'America/Toronto', 'CAD', 'exchange', 'TradePulse reference registry', '2026-09-08', 'venue-reference-v1');

insert into public.global_market_calendars (
  venue_id, session_timezone, source_name, source_as_of, calendar_version
)
select id, timezone, 'TradePulse reference registry', '2026-09-08', 'calendar-reference-v1'
from public.global_market_venues;

insert into public.global_instrument_listings (
  listing_key, canonical_instrument_key, venue_id, display_symbol,
  instrument_name, instrument_type, quote_currency, source_name,
  source_as_of, listing_version
) values
  ('XNAS:AAPL', 'US:AAPL', (select id from public.global_market_venues where mic_code = 'XNAS'), 'AAPL', 'Apple common equity reference', 'equity', 'USD', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XNAS:QQQ', 'US:QQQ', (select id from public.global_market_venues where mic_code = 'XNAS'), 'QQQ', 'Nasdaq-100 ETF reference', 'etf', 'USD', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XNYS:IBM', 'US:IBM', (select id from public.global_market_venues where mic_code = 'XNYS'), 'IBM', 'IBM common equity reference', 'equity', 'USD', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XNYS:BABA', 'CN:BABA', (select id from public.global_market_venues where mic_code = 'XNYS'), 'BABA', 'Alibaba depositary receipt reference', 'depositary_receipt', 'USD', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XLON:ULVR', 'GB:ULVR', (select id from public.global_market_venues where mic_code = 'XLON'), 'ULVR', 'Unilever common equity reference', 'equity', 'GBP', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XLON:VUSA', 'IE:VUSA', (select id from public.global_market_venues where mic_code = 'XLON'), 'VUSA', 'S&P 500 UCITS ETF reference', 'etf', 'GBP', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XNSE:RELIANCE', 'IN:RELIANCE', (select id from public.global_market_venues where mic_code = 'XNSE'), 'RELIANCE', 'Reliance Industries equity reference', 'equity', 'INR', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XNSE:NIFTYBEES', 'IN:NIFTYBEES', (select id from public.global_market_venues where mic_code = 'XNSE'), 'NIFTYBEES', 'Nifty 50 ETF reference', 'etf', 'INR', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XETR:SAP', 'DE:SAP', (select id from public.global_market_venues where mic_code = 'XETR'), 'SAP', 'SAP common equity reference', 'equity', 'EUR', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XETR:EXS1', 'DE:EXS1', (select id from public.global_market_venues where mic_code = 'XETR'), 'EXS1', 'DAX UCITS ETF reference', 'etf', 'EUR', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XTSE:SHOP', 'CA:SHOP', (select id from public.global_market_venues where mic_code = 'XTSE'), 'SHOP', 'Shopify common equity reference', 'equity', 'CAD', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1'),
  ('XTSE:XIU', 'CA:XIU', (select id from public.global_market_venues where mic_code = 'XTSE'), 'XIU', 'S&P/TSX 60 ETF reference', 'etf', 'CAD', 'TradePulse reference registry', '2026-09-08', 'listing-reference-v1');

insert into public.global_market_data_entitlements (
  venue_id, dataset, display_status, license_status, source_name,
  source_as_of, entitlement_version
)
select
  venue.id,
  dataset.name,
  case when dataset.name = 'reference' then 'reference_only' else 'unavailable' end,
  'review_required',
  'TradePulse entitlement registry',
  '2026-09-08',
  'entitlement-reference-v1'
from public.global_market_venues venue
cross join (values ('reference'), ('prices'), ('corporate_actions')) as dataset(name);

insert into public.global_market_access_policies (
  venue_id, residency_country, access_status, reason_code,
  policy_version, effective_from
)
select
  venue.id,
  residency.country_code,
  case
    when venue.country_code = residency.country_code then 'research_only'
    else 'review_required'
  end,
  case
    when venue.country_code = residency.country_code then 'DOMESTIC_REFERENCE_ONLY_NOT_ELIGIBILITY'
    else 'CROSS_BORDER_LEGAL_REVIEW_REQUIRED'
  end,
  'global-access-reference-v1',
  '2026-09-08'
from public.global_market_venues venue
cross join (values ('US'), ('GB'), ('IN'), ('CA')) as residency(country_code);

revoke all on table public.global_market_intelligence_controls from anon, authenticated;
revoke all on table public.global_market_venues from anon, authenticated;
revoke all on table public.global_market_calendars from anon, authenticated;
revoke all on table public.global_instrument_listings from anon, authenticated;
revoke all on table public.global_market_data_entitlements from anon, authenticated;
revoke all on table public.global_market_access_policies from anon, authenticated;

grant select on table public.global_market_intelligence_controls to anon, authenticated;
grant select on table public.global_market_venues to anon, authenticated;
grant select on table public.global_market_calendars to anon, authenticated;
grant select on table public.global_instrument_listings to anon, authenticated;
grant select on table public.global_market_data_entitlements to anon, authenticated;
grant select on table public.global_market_access_policies to anon, authenticated;

create view public.global_venue_instrument_reference
with (security_invoker = true)
as
select
  venue.id as venue_id,
  venue.mic_code,
  venue.venue_name,
  venue.country_code as venue_country_code,
  venue.timezone,
  venue.primary_currency,
  venue.availability_status as venue_availability,
  calendar.calendar_status,
  calendar.holiday_calendar_status,
  calendar.settlement_convention,
  listing.id as listing_id,
  listing.listing_key,
  listing.canonical_instrument_key,
  listing.display_symbol,
  listing.instrument_name,
  listing.instrument_type,
  listing.quote_currency,
  listing.primary_listing,
  listing.listing_status,
  listing.identifier_status,
  listing.provider_mapping_status,
  listing.corporate_action_status,
  listing.fractional_reference_status,
  access.residency_country,
  access.customer_type,
  access.investor_type,
  access.access_status,
  access.reason_code,
  access.disclosure_status,
  access.legal_review_status,
  coalesce(reference_right.display_status, 'unavailable') as reference_display_status,
  coalesce(price_right.display_status, 'unavailable') as price_display_status,
  coalesce(action_right.display_status, 'unavailable') as corporate_action_display_status,
  coalesce(reference_right.license_status, 'review_required') as reference_license_status,
  greatest(
    venue.source_as_of,
    calendar.source_as_of,
    listing.source_as_of,
    reference_right.source_as_of,
    price_right.source_as_of,
    action_right.source_as_of
  ) as reference_as_of,
  control.policy_version,
  false as live_market_data_connectivity_enabled,
  false as customer_entitlement_assignment_enabled,
  false as automatic_jurisdiction_approval_enabled,
  false as order_preview_enabled,
  false as order_routing_enabled,
  false as broker_connectivity_enabled,
  false as customer_funding_enabled,
  false as custody_enabled,
  false as settlement_enabled
from public.global_instrument_listings listing
join public.global_market_venues venue on venue.id = listing.venue_id
join public.global_market_calendars calendar on calendar.venue_id = venue.id
join public.global_market_access_policies access on access.venue_id = venue.id
cross join public.global_market_intelligence_controls control
left join public.global_market_data_entitlements reference_right
  on reference_right.venue_id = venue.id
  and reference_right.dataset = 'reference'
  and reference_right.audience_region = 'GLOBAL'
left join public.global_market_data_entitlements price_right
  on price_right.venue_id = venue.id
  and price_right.dataset = 'prices'
  and price_right.audience_region = 'GLOBAL'
left join public.global_market_data_entitlements action_right
  on action_right.venue_id = venue.id
  and action_right.dataset = 'corporate_actions'
  and action_right.audience_region = 'GLOBAL'
where venue.enabled
  and listing.enabled
  and calendar.enabled
  and control.reference_workspace_enabled;

grant select on public.global_venue_instrument_reference to anon, authenticated;

do $$
begin
  if exists (
    select 1 from public.global_market_intelligence_controls where
      live_market_data_connectivity_enabled or
      customer_entitlement_assignment_enabled or
      automatic_jurisdiction_approval_enabled or
      order_preview_enabled or order_routing_enabled or broker_connectivity_enabled or
      customer_funding_enabled or custody_enabled or settlement_enabled
  ) then
    raise exception 'Phase 8A global market controls must remain fail-closed';
  end if;

  if to_regclass('public.live_global_orders') is not null
    or to_regclass('public.global_custody_accounts') is not null
    or to_regclass('public.global_settlement_ledger') is not null
    or to_regprocedure('public.submit_global_order(jsonb)') is not null
    or to_regprocedure('public.activate_global_market(text)') is not null then
    raise exception 'Phase 8A cannot deploy while a global execution, custody or settlement path exists';
  end if;
end;
$$;

comment on table public.global_market_intelligence_controls is
  'Phase 8A hard locks. Reference metadata cannot enable market data, eligibility, routing, funding, custody or settlement.';
comment on table public.global_market_venues is
  'Canonical venue reference metadata. Session use remains disabled until calendar evidence is verified.';
comment on table public.global_instrument_listings is
  'Venue-qualified listing identities that prevent symbols and similarly named instruments from being treated as interchangeable.';
comment on table public.global_market_data_entitlements is
  'Sanitized display-rights states. Provider credentials and contract terms are not stored.';
comment on table public.global_market_access_policies is
  'Hypothetical reference scenarios, not customer eligibility or regulated approval.';
comment on view public.global_venue_instrument_reference is
  'Public Phase 8A venue, listing, entitlement and residency reference with every operational capability false.';
