-- TradePulse AI
-- Migration 046: Phase 8B international multi-asset paper trading
-- All quotes, FX rates, cash, orders, fills, positions, lots and journals in
-- this migration are deterministic simulations with no cash value and no
-- broker, market-data, custody, funding or settlement connection.

create table public.international_paper_trading_controls (
  control_key text primary key check (control_key = 'international-paper-trading'),
  simulation_enabled boolean not null default true check (simulation_enabled),
  user_initiated_simulation_enabled boolean not null default true check (user_initiated_simulation_enabled),
  policy_version text not null,
  live_market_data_enabled boolean not null default false check (not live_market_data_enabled),
  live_order_routing_enabled boolean not null default false check (not live_order_routing_enabled),
  broker_connectivity_enabled boolean not null default false check (not broker_connectivity_enabled),
  real_customer_funds_enabled boolean not null default false check (not real_customer_funds_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  real_settlement_enabled boolean not null default false check (not real_settlement_enabled),
  margin_enabled boolean not null default false check (not margin_enabled),
  short_selling_enabled boolean not null default false check (not short_selling_enabled),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.international_paper_venue_rules (
  id bigint generated by default as identity primary key,
  venue_id bigint not null unique references public.global_market_venues(id) on delete cascade,
  session_state text not null check (session_state in ('open_scenario', 'closed_scenario', 'halted_scenario')),
  tick_size numeric(20,8) not null check (tick_size > 0),
  lot_size numeric(20,8) not null check (lot_size > 0),
  fractional_simulation_enabled boolean not null default false,
  partial_fill_simulation_enabled boolean not null default true,
  settlement_days integer not null check (settlement_days between 0 and 5),
  day_order_expiry_hours integer not null default 8 check (day_order_expiry_hours between 1 and 24),
  rules_status text not null default 'modeled_scenario' check (rules_status = 'modeled_scenario'),
  rule_version text not null,
  source_name text not null,
  source_as_of date not null,
  simulation_only boolean not null default true check (simulation_only),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.international_paper_quotes (
  id bigint generated by default as identity primary key,
  listing_id bigint not null unique references public.global_instrument_listings(id) on delete cascade,
  scenario_price numeric(20,8) not null check (scenario_price > 0),
  available_quantity numeric(24,8) not null check (available_quantity >= 0),
  quote_status text not null check (quote_status in ('available_scenario', 'halted_scenario', 'unavailable')),
  observed_at timestamptz not null,
  scenario_version text not null,
  source_name text not null,
  source_type text not null default 'deterministic_fixture' check (source_type = 'deterministic_fixture'),
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.international_paper_fx_rates (
  currency_code text primary key check (currency_code ~ '^[A-Z]{3}$'),
  usd_value_per_unit numeric(24,10) not null check (usd_value_per_unit > 0),
  conversion_spread_bps numeric(10,4) not null check (conversion_spread_bps between 0 and 1000),
  rate_status text not null default 'modeled_scenario' check (rate_status = 'modeled_scenario'),
  scenario_version text not null,
  source_name text not null,
  source_as_of date not null,
  simulation_only boolean not null default true check (simulation_only),
  updated_at timestamptz not null default now()
);

create table public.international_paper_cost_rules (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references public.global_market_venues(id) on delete cascade,
  instrument_type text not null check (instrument_type in ('equity', 'etf', 'depositary_receipt')),
  commission_bps numeric(10,4) not null check (commission_bps >= 0),
  minimum_commission numeric(20,8) not null check (minimum_commission >= 0),
  exchange_fee_bps numeric(10,4) not null check (exchange_fee_bps >= 0),
  tax_assumption_bps numeric(10,4) not null check (tax_assumption_bps >= 0),
  cost_status text not null default 'modeled_scenario' check (cost_status in ('modeled_scenario', 'unavailable')),
  rule_version text not null,
  source_name text not null,
  source_as_of date not null,
  simulation_only boolean not null default true check (simulation_only),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (venue_id, instrument_type)
);

create table public.international_paper_accounts (
  portfolio_id uuid primary key references public.investment_portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  base_currency text not null check (base_currency ~ '^[A-Z]{3}$'),
  account_status text not null default 'active' check (account_status in ('active', 'paused')),
  max_order_value_usd numeric(24,8) not null default 25000 check (max_order_value_usd > 0),
  simulation_only boolean not null default true check (simulation_only),
  live_account_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (live_account_id is null),
  unique (user_id, portfolio_id)
);

create table public.international_paper_cash_balances (
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  currency text not null references public.international_paper_fx_rates(currency_code),
  balance numeric(24,8) not null default 0 check (balance >= 0),
  available_balance numeric(24,8) not null default 0 check (available_balance >= 0),
  simulation_only boolean not null default true check (simulation_only),
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, currency),
  check (available_balance <= balance)
);

create table public.international_paper_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  listing_id bigint not null references public.global_instrument_listings(id),
  client_order_id text not null check (char_length(client_order_id) between 8 and 100),
  side text not null check (side in ('buy', 'sell')),
  order_type text not null check (order_type in ('market', 'limit', 'stop', 'stop_limit')),
  time_in_force text not null check (time_in_force in ('day', 'gtc', 'ioc')),
  quantity numeric(24,8) not null check (quantity > 0),
  limit_price numeric(20,8) check (limit_price is null or limit_price > 0),
  stop_price numeric(20,8) check (stop_price is null or stop_price > 0),
  status text not null check (status in ('accepted', 'risk_rejected', 'partially_filled', 'filled', 'halted', 'expired')),
  filled_quantity numeric(24,8) not null default 0 check (filled_quantity between 0 and quantity),
  average_fill_price numeric(20,8) check (average_fill_price is null or average_fill_price > 0),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  commission numeric(20,8) not null default 0 check (commission >= 0),
  exchange_fee numeric(20,8) not null default 0 check (exchange_fee >= 0),
  tax_assumption numeric(20,8) not null default 0 check (tax_assumption >= 0),
  total_cost numeric(20,8) not null default 0 check (total_cost >= 0),
  rejection_reason text,
  quote_observed_at timestamptz,
  expires_at timestamptz,
  simulation_rule_version text not null,
  simulation_only boolean not null default true check (simulation_only),
  live_order_id text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_order_id),
  check (live_order_id is null),
  check (order_type not in ('limit', 'stop_limit') or limit_price is not null),
  check (order_type not in ('stop', 'stop_limit') or stop_price is not null)
);

create table public.international_paper_fills (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.international_paper_orders(id) on delete cascade,
  quantity numeric(24,8) not null check (quantity > 0),
  price numeric(20,8) not null check (price > 0),
  notional numeric(24,8) not null check (notional > 0),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  commission numeric(20,8) not null check (commission >= 0),
  exchange_fee numeric(20,8) not null check (exchange_fee >= 0),
  tax_assumption numeric(20,8) not null check (tax_assumption >= 0),
  settles_on date not null,
  simulation_only boolean not null default true check (simulation_only),
  filled_at timestamptz not null default now()
);

create table public.international_paper_positions (
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  listing_id bigint not null references public.global_instrument_listings(id),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  quantity numeric(24,8) not null default 0 check (quantity >= 0),
  average_cost numeric(20,8) not null default 0 check (average_cost >= 0),
  realized_pnl numeric(24,8) not null default 0,
  simulation_only boolean not null default true check (simulation_only),
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, listing_id)
);

create table public.international_paper_tax_lots (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  listing_id bigint not null references public.global_instrument_listings(id),
  source_fill_id uuid not null unique references public.international_paper_fills(id) on delete cascade,
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  original_quantity numeric(24,8) not null check (original_quantity > 0),
  remaining_quantity numeric(24,8) not null check (remaining_quantity >= 0),
  unit_cost numeric(20,8) not null check (unit_cost > 0),
  acquired_at timestamptz not null,
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now(),
  check (remaining_quantity <= original_quantity)
);

create table public.international_paper_journal_entries (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  source_type text not null check (source_type in ('initial_credit', 'fx_conversion', 'trade', 'corporate_action', 'settlement')),
  source_id text not null,
  status text not null default 'posted' check (status = 'posted'),
  correlation_id text not null,
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now(),
  unique (portfolio_id, correlation_id)
);

create table public.international_paper_journal_lines (
  id bigint generated by default as identity primary key,
  journal_entry_id uuid not null references public.international_paper_journal_entries(id) on delete cascade,
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  account_type text not null check (account_type in ('cash', 'position_cost', 'fee_expense', 'tax_expense', 'fx_bridge', 'virtual_capital', 'dividend_income', 'settlement')),
  amount numeric(24,8) not null check (amount <> 0),
  memo text not null,
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now()
);

create table public.international_paper_fx_conversions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  client_conversion_id text not null check (char_length(client_conversion_id) between 8 and 100),
  from_currency text not null check (from_currency ~ '^[A-Z]{3}$'),
  to_currency text not null check (to_currency ~ '^[A-Z]{3}$'),
  from_amount numeric(24,8) not null check (from_amount > 0),
  to_amount numeric(24,8) not null check (to_amount > 0),
  scenario_rate numeric(24,10) not null check (scenario_rate > 0),
  spread_bps numeric(10,4) not null check (spread_bps >= 0),
  scenario_version text not null,
  simulation_only boolean not null default true check (simulation_only),
  converted_at timestamptz not null default now(),
  unique (user_id, client_conversion_id),
  check (from_currency <> to_currency)
);

create table public.international_paper_route_evidence (
  order_id uuid primary key references public.international_paper_orders(id) on delete cascade,
  selected_mic text not null check (selected_mic ~ '^[A-Z0-9]{4}$'),
  candidate_quotes jsonb not null check (jsonb_typeof(candidate_quotes) = 'array'),
  selection_reason text not null,
  quote_observed_at timestamptz not null,
  best_execution_claim boolean not null default false check (not best_execution_claim),
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now()
);

create table public.international_paper_reconciliations (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.international_paper_accounts(portfolio_id) on delete cascade,
  status text not null check (status in ('passed', 'exception')),
  unbalanced_journals integer not null check (unbalanced_journals >= 0),
  cash_mismatches integer not null check (cash_mismatches >= 0),
  position_mismatches integer not null check (position_mismatches >= 0),
  tax_lot_mismatches integer not null check (tax_lot_mismatches >= 0),
  details jsonb not null default '{}'::jsonb,
  simulation_only boolean not null default true check (simulation_only),
  reconciled_at timestamptz not null default now()
);

create table public.international_paper_corporate_action_scenarios (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.global_instrument_listings(id) on delete cascade,
  action_type text not null check (action_type in ('split', 'cash_dividend')),
  scenario_label text not null,
  split_ratio numeric(20,8) check (split_ratio is null or split_ratio > 0),
  cash_per_share numeric(20,8) check (cash_per_share is null or cash_per_share > 0),
  effective_on date not null,
  application_status text not null default 'rehearsal_only' check (application_status = 'rehearsal_only'),
  scenario_version text not null,
  simulation_only boolean not null default true check (simulation_only),
  applied_to_real_account boolean not null default false check (not applied_to_real_account),
  created_at timestamptz not null default now(),
  check (
    (action_type = 'split' and split_ratio is not null and cash_per_share is null)
    or (action_type = 'cash_dividend' and cash_per_share is not null and split_ratio is null)
  )
);

create index idx_international_paper_orders_portfolio on public.international_paper_orders(portfolio_id, submitted_at desc);
create index idx_international_paper_fills_order on public.international_paper_fills(order_id, filled_at);
create index idx_international_paper_positions_portfolio on public.international_paper_positions(portfolio_id, updated_at desc);
create index idx_international_paper_lots_position on public.international_paper_tax_lots(portfolio_id, listing_id, acquired_at);
create index idx_international_paper_journal_portfolio on public.international_paper_journal_entries(portfolio_id, created_at desc);
create index idx_international_paper_lines_entry on public.international_paper_journal_lines(journal_entry_id, currency);
create index idx_international_paper_reconciliations_portfolio on public.international_paper_reconciliations(portfolio_id, reconciled_at desc);

alter table public.international_paper_trading_controls enable row level security;
alter table public.international_paper_venue_rules enable row level security;
alter table public.international_paper_quotes enable row level security;
alter table public.international_paper_fx_rates enable row level security;
alter table public.international_paper_cost_rules enable row level security;
alter table public.international_paper_accounts enable row level security;
alter table public.international_paper_cash_balances enable row level security;
alter table public.international_paper_orders enable row level security;
alter table public.international_paper_fills enable row level security;
alter table public.international_paper_positions enable row level security;
alter table public.international_paper_tax_lots enable row level security;
alter table public.international_paper_journal_entries enable row level security;
alter table public.international_paper_journal_lines enable row level security;
alter table public.international_paper_fx_conversions enable row level security;
alter table public.international_paper_route_evidence enable row level security;
alter table public.international_paper_reconciliations enable row level security;
alter table public.international_paper_corporate_action_scenarios enable row level security;

create policy "Public reads international paper controls" on public.international_paper_trading_controls for select to anon, authenticated using (simulation_enabled);
create policy "Public reads international paper venue rules" on public.international_paper_venue_rules for select to anon, authenticated using (enabled and simulation_only);
create policy "Public reads international paper quotes" on public.international_paper_quotes for select to anon, authenticated using (simulation_only);
create policy "Public reads international paper FX scenarios" on public.international_paper_fx_rates for select to anon, authenticated using (simulation_only);
create policy "Public reads international paper cost rules" on public.international_paper_cost_rules for select to anon, authenticated using (enabled and simulation_only);
create policy "Public reads corporate action scenarios" on public.international_paper_corporate_action_scenarios for select to anon, authenticated using (simulation_only);

create policy "Users read their international paper account" on public.international_paper_accounts for select to authenticated using (user_id = auth.uid());
create policy "Users read their international paper cash" on public.international_paper_cash_balances for select to authenticated using (exists (select 1 from public.international_paper_accounts account where account.portfolio_id = international_paper_cash_balances.portfolio_id and account.user_id = auth.uid()));
create policy "Users read their international paper orders" on public.international_paper_orders for select to authenticated using (user_id = auth.uid());
create policy "Users read their international paper fills" on public.international_paper_fills for select to authenticated using (exists (select 1 from public.international_paper_orders orders where orders.id = international_paper_fills.order_id and orders.user_id = auth.uid()));
create policy "Users read their international paper positions" on public.international_paper_positions for select to authenticated using (exists (select 1 from public.international_paper_accounts account where account.portfolio_id = international_paper_positions.portfolio_id and account.user_id = auth.uid()));
create policy "Users read their international paper lots" on public.international_paper_tax_lots for select to authenticated using (exists (select 1 from public.international_paper_accounts account where account.portfolio_id = international_paper_tax_lots.portfolio_id and account.user_id = auth.uid()));
create policy "Users read their international paper journals" on public.international_paper_journal_entries for select to authenticated using (exists (select 1 from public.international_paper_accounts account where account.portfolio_id = international_paper_journal_entries.portfolio_id and account.user_id = auth.uid()));
create policy "Users read their international paper journal lines" on public.international_paper_journal_lines for select to authenticated using (exists (select 1 from public.international_paper_accounts account where account.portfolio_id = international_paper_journal_lines.portfolio_id and account.user_id = auth.uid()));
create policy "Users read their international FX conversions" on public.international_paper_fx_conversions for select to authenticated using (user_id = auth.uid());
create policy "Users read their international route evidence" on public.international_paper_route_evidence for select to authenticated using (exists (select 1 from public.international_paper_orders orders where orders.id = international_paper_route_evidence.order_id and orders.user_id = auth.uid()));
create policy "Users read their international reconciliations" on public.international_paper_reconciliations for select to authenticated using (exists (select 1 from public.international_paper_accounts account where account.portfolio_id = international_paper_reconciliations.portfolio_id and account.user_id = auth.uid()));

create trigger international_paper_controls_set_updated_at before update on public.international_paper_trading_controls for each row execute function public.set_updated_at();
create trigger international_paper_venue_rules_set_updated_at before update on public.international_paper_venue_rules for each row execute function public.set_updated_at();
create trigger international_paper_quotes_set_updated_at before update on public.international_paper_quotes for each row execute function public.set_updated_at();
create trigger international_paper_fx_rates_set_updated_at before update on public.international_paper_fx_rates for each row execute function public.set_updated_at();
create trigger international_paper_cost_rules_set_updated_at before update on public.international_paper_cost_rules for each row execute function public.set_updated_at();
create trigger international_paper_accounts_set_updated_at before update on public.international_paper_accounts for each row execute function public.set_updated_at();
create trigger international_paper_cash_set_updated_at before update on public.international_paper_cash_balances for each row execute function public.set_updated_at();
create trigger international_paper_orders_set_updated_at before update on public.international_paper_orders for each row execute function public.set_updated_at();
create trigger international_paper_positions_set_updated_at before update on public.international_paper_positions for each row execute function public.set_updated_at();

insert into public.international_paper_trading_controls (control_key, policy_version)
values ('international-paper-trading', 'international-paper-trading-v1');

insert into public.international_paper_venue_rules (
  venue_id, session_state, tick_size, lot_size, fractional_simulation_enabled,
  partial_fill_simulation_enabled, settlement_days, rule_version, source_name, source_as_of
)
select id, 'open_scenario', 0.01, 1, false, true,
  case when mic_code in ('XNAS', 'XNYS', 'XTSE') then 1 else 2 end,
  'international-paper-venue-v1', 'Deterministic Phase 8B scenario', '2026-09-09'
from public.global_market_venues;

insert into public.international_paper_quotes (
  listing_id, scenario_price, available_quantity, quote_status,
  observed_at, scenario_version, source_name
)
select listing.id,
  case listing.listing_key
    when 'XNAS:AAPL' then 250 when 'XNAS:QQQ' then 600
    when 'XNYS:IBM' then 250 when 'XNYS:BABA' then 170
    when 'XLON:ULVR' then 50 when 'XLON:VUSA' then 100
    when 'XNSE:RELIANCE' then 1400 when 'XNSE:NIFTYBEES' then 300
    when 'XETR:SAP' then 250 when 'XETR:EXS1' then 200
    when 'XTSE:SHOP' then 200 when 'XTSE:XIU' then 40
  end,
  1000, 'available_scenario', '2026-09-09T00:00:00Z',
  'international-paper-quote-v1', 'Deterministic Phase 8B scenario'
from public.global_instrument_listings listing;

insert into public.international_paper_fx_rates (
  currency_code, usd_value_per_unit, conversion_spread_bps,
  scenario_version, source_name, source_as_of
) values
  ('USD', 1.0000000000, 5, 'international-paper-fx-v1', 'Deterministic Phase 8B scenario', '2026-09-09'),
  ('GBP', 1.3000000000, 5, 'international-paper-fx-v1', 'Deterministic Phase 8B scenario', '2026-09-09'),
  ('INR', 0.0120000000, 5, 'international-paper-fx-v1', 'Deterministic Phase 8B scenario', '2026-09-09'),
  ('EUR', 1.1000000000, 5, 'international-paper-fx-v1', 'Deterministic Phase 8B scenario', '2026-09-09'),
  ('CAD', 0.7300000000, 5, 'international-paper-fx-v1', 'Deterministic Phase 8B scenario', '2026-09-09');

insert into public.international_paper_cost_rules (
  venue_id, instrument_type, commission_bps, minimum_commission,
  exchange_fee_bps, tax_assumption_bps, rule_version, source_name, source_as_of
)
select distinct listing.venue_id, listing.instrument_type, 5, 0.01, 1, 2,
  'international-paper-cost-v1', 'Deterministic Phase 8B scenario', '2026-09-09'
from public.global_instrument_listings listing;

insert into public.international_paper_corporate_action_scenarios (
  listing_id, action_type, scenario_label, split_ratio, cash_per_share,
  effective_on, scenario_version
)
values
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:AAPL'), 'split', 'Scenario-only 2-for-1 split drill', 2, null, '2030-01-15', 'international-paper-action-v1'),
  ((select id from public.global_instrument_listings where listing_key = 'XLON:ULVR'), 'cash_dividend', 'Scenario-only cash dividend drill', null, 0.50, '2030-02-15', 'international-paper-action-v1');

revoke all on table public.international_paper_trading_controls, public.international_paper_venue_rules,
  public.international_paper_quotes, public.international_paper_fx_rates,
  public.international_paper_cost_rules, public.international_paper_corporate_action_scenarios
  from anon, authenticated;
grant select on table public.international_paper_trading_controls, public.international_paper_venue_rules,
  public.international_paper_quotes, public.international_paper_fx_rates,
  public.international_paper_cost_rules, public.international_paper_corporate_action_scenarios
  to anon, authenticated;

revoke all on table public.international_paper_accounts, public.international_paper_cash_balances,
  public.international_paper_orders, public.international_paper_fills,
  public.international_paper_positions, public.international_paper_tax_lots,
  public.international_paper_journal_entries, public.international_paper_journal_lines,
  public.international_paper_fx_conversions, public.international_paper_route_evidence,
  public.international_paper_reconciliations from anon, authenticated, service_role;
grant select on table public.international_paper_accounts, public.international_paper_cash_balances,
  public.international_paper_orders, public.international_paper_fills,
  public.international_paper_positions, public.international_paper_tax_lots,
  public.international_paper_journal_entries, public.international_paper_journal_lines,
  public.international_paper_fx_conversions, public.international_paper_route_evidence,
  public.international_paper_reconciliations to authenticated;

create view public.international_paper_market_catalog
with (security_invoker = true)
as
select
  listing.id as listing_id, listing.listing_key, listing.canonical_instrument_key,
  listing.display_symbol, listing.instrument_name, listing.instrument_type,
  listing.quote_currency, venue.mic_code, venue.venue_name,
  venue.country_code as venue_country_code, venue.timezone,
  rules.session_state, rules.tick_size, rules.lot_size,
  rules.fractional_simulation_enabled, rules.partial_fill_simulation_enabled,
  rules.settlement_days, rules.day_order_expiry_hours, rules.rule_version,
  quote.scenario_price, quote.available_quantity, quote.quote_status,
  quote.observed_at as quote_observed_at, quote.scenario_version as quote_version,
  costs.commission_bps, costs.minimum_commission, costs.exchange_fee_bps,
  costs.tax_assumption_bps, costs.cost_status, costs.rule_version as cost_rule_version,
  false as live_market_data_enabled, false as live_order_routing_enabled,
  false as broker_connectivity_enabled, false as real_customer_funds_enabled,
  false as custody_enabled, false as real_settlement_enabled,
  true as simulation_only
from public.global_instrument_listings listing
join public.global_market_venues venue on venue.id = listing.venue_id
join public.international_paper_venue_rules rules on rules.venue_id = venue.id
join public.international_paper_quotes quote on quote.listing_id = listing.id
join public.international_paper_cost_rules costs
  on costs.venue_id = venue.id and costs.instrument_type = listing.instrument_type
where listing.enabled and venue.enabled and rules.enabled and costs.enabled;

create view public.international_paper_order_history
with (security_invoker = true)
as
select orders.id, orders.user_id, orders.portfolio_id, orders.client_order_id,
  listing.listing_key, listing.display_symbol, listing.instrument_name,
  venue.mic_code, orders.side, orders.order_type, orders.time_in_force,
  orders.quantity, orders.filled_quantity, orders.status,
  orders.average_fill_price, orders.quote_currency, orders.commission,
  orders.exchange_fee, orders.tax_assumption, orders.total_cost,
  orders.rejection_reason, orders.quote_observed_at, orders.expires_at,
  orders.simulation_rule_version, orders.submitted_at,
  true as simulation_only, false as live_order_routing_enabled
from public.international_paper_orders orders
join public.global_instrument_listings listing on listing.id = orders.listing_id
join public.global_market_venues venue on venue.id = listing.venue_id;

create view public.international_paper_position_summary
with (security_invoker = true)
as
select position.portfolio_id, position.listing_id, listing.listing_key,
  listing.display_symbol, listing.instrument_name, listing.instrument_type,
  venue.mic_code, position.quote_currency, position.quantity,
  position.average_cost, position.realized_pnl,
  coalesce(sum(lot.remaining_quantity), 0) as open_tax_lot_quantity,
  count(lot.id) filter (where lot.remaining_quantity > 0)::integer as open_tax_lot_count,
  true as simulation_only
from public.international_paper_positions position
join public.global_instrument_listings listing on listing.id = position.listing_id
join public.global_market_venues venue on venue.id = listing.venue_id
left join public.international_paper_tax_lots lot
  on lot.portfolio_id = position.portfolio_id and lot.listing_id = position.listing_id
group by position.portfolio_id, position.listing_id, listing.listing_key,
  listing.display_symbol, listing.instrument_name, listing.instrument_type,
  venue.mic_code, position.quote_currency, position.quantity,
  position.average_cost, position.realized_pnl;

grant select on public.international_paper_market_catalog to anon, authenticated;
grant select on public.international_paper_order_history to authenticated;
grant select on public.international_paper_position_summary to authenticated;

create or replace function public.initialize_international_paper_account(
  p_user_id uuid, p_portfolio_id uuid, p_starting_balance numeric default 100000
)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  selected_portfolio public.investment_portfolios%rowtype;
  journal_id uuid;
begin
  if auth.role() <> 'service_role' then raise exception 'International paper trading requires the simulation service'; end if;
  if p_user_id is null or p_portfolio_id is null or p_starting_balance is null or p_starting_balance < 1000 or p_starting_balance > 1000000 then raise exception 'International virtual balance must be between 1,000 and 1,000,000'; end if;
  select * into selected_portfolio from public.investment_portfolios
    where id = p_portfolio_id and user_id = p_user_id and portfolio_type = 'paper' for update;
  if not found then raise exception 'Paper portfolio was not found'; end if;
  if not exists (select 1 from public.international_paper_fx_rates where currency_code = selected_portfolio.base_currency) then
    raise exception 'Portfolio base currency is not modeled for international paper trading';
  end if;
  insert into public.international_paper_accounts (portfolio_id, user_id, base_currency)
    values (p_portfolio_id, p_user_id, selected_portfolio.base_currency)
    on conflict (portfolio_id) do nothing;
  if not found then
    return jsonb_build_object('portfolio_id', p_portfolio_id, 'status', 'existing', 'simulation', true);
  end if;
  insert into public.international_paper_cash_balances (portfolio_id, currency, balance, available_balance)
    values (p_portfolio_id, selected_portfolio.base_currency, p_starting_balance, p_starting_balance);
  insert into public.international_paper_journal_entries (portfolio_id, source_type, source_id, correlation_id)
    values (p_portfolio_id, 'initial_credit', p_portfolio_id::text, 'international-account:' || p_portfolio_id::text)
    returning id into journal_id;
  insert into public.international_paper_journal_lines (journal_entry_id, portfolio_id, currency, account_type, amount, memo)
    values
      (journal_id, p_portfolio_id, selected_portfolio.base_currency, 'cash', p_starting_balance, 'Initial virtual cash'),
      (journal_id, p_portfolio_id, selected_portfolio.base_currency, 'virtual_capital', -p_starting_balance, 'Offsetting virtual capital');
  return jsonb_build_object('portfolio_id', p_portfolio_id, 'status', 'created', 'base_currency', selected_portfolio.base_currency, 'starting_balance', p_starting_balance, 'simulation', true);
end;
$$;

create or replace function public.convert_international_paper_cash(
  p_user_id uuid, p_portfolio_id uuid, p_from_currency text,
  p_to_currency text, p_from_amount numeric, p_client_conversion_id text
)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  account_row public.international_paper_accounts%rowtype;
  existing public.international_paper_fx_conversions%rowtype;
  from_rate public.international_paper_fx_rates%rowtype;
  to_rate public.international_paper_fx_rates%rowtype;
  source_cash public.international_paper_cash_balances%rowtype;
  target_balance numeric(24,8);
  conversion_rate numeric(24,10);
  converted_amount numeric(24,8);
  conversion_id uuid;
  journal_id uuid;
begin
  if auth.role() <> 'service_role' then raise exception 'International paper FX requires the simulation service'; end if;
  p_from_currency := upper(trim(p_from_currency)); p_to_currency := upper(trim(p_to_currency));
  if p_user_id is null or p_portfolio_id is null or p_from_currency is null or p_to_currency is null
    or p_from_currency = p_to_currency or p_from_amount is null or p_from_amount <= 0
    or p_client_conversion_id is null or char_length(trim(p_client_conversion_id)) not between 8 and 100 then
    raise exception 'Invalid international paper FX request';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || trim(p_client_conversion_id), 0));
  select * into existing from public.international_paper_fx_conversions where user_id = p_user_id and client_conversion_id = trim(p_client_conversion_id);
  if found then return jsonb_build_object('id', existing.id, 'status', 'converted', 'from_amount', existing.from_amount, 'to_amount', existing.to_amount, 'idempotent_replay', true, 'simulation', true); end if;
  select * into account_row from public.international_paper_accounts where portfolio_id = p_portfolio_id and user_id = p_user_id and account_status = 'active' for update;
  if not found then raise exception 'International paper account was not found or is paused'; end if;
  select * into from_rate from public.international_paper_fx_rates where currency_code = p_from_currency and rate_status = 'modeled_scenario';
  select * into to_rate from public.international_paper_fx_rates where currency_code = p_to_currency and rate_status = 'modeled_scenario';
  if from_rate.currency_code is null or to_rate.currency_code is null then raise exception 'A required paper FX scenario is unavailable'; end if;
  select * into source_cash from public.international_paper_cash_balances where portfolio_id = p_portfolio_id and currency = p_from_currency for update;
  if not found or source_cash.available_balance < p_from_amount then raise exception 'Insufficient virtual cash for paper FX conversion'; end if;
  conversion_rate := (from_rate.usd_value_per_unit / to_rate.usd_value_per_unit) * (1 - greatest(from_rate.conversion_spread_bps, to_rate.conversion_spread_bps) / 10000);
  converted_amount := round(p_from_amount * conversion_rate, 8);
  if converted_amount <= 0 then raise exception 'Paper FX conversion rounded to zero'; end if;
  update public.international_paper_cash_balances set balance = balance - p_from_amount, available_balance = available_balance - p_from_amount where portfolio_id = p_portfolio_id and currency = p_from_currency;
  insert into public.international_paper_cash_balances (portfolio_id, currency, balance, available_balance)
    values (p_portfolio_id, p_to_currency, converted_amount, converted_amount)
    on conflict (portfolio_id, currency) do update set balance = international_paper_cash_balances.balance + excluded.balance, available_balance = international_paper_cash_balances.available_balance + excluded.available_balance, updated_at = now()
    returning balance into target_balance;
  insert into public.international_paper_fx_conversions (user_id, portfolio_id, client_conversion_id, from_currency, to_currency, from_amount, to_amount, scenario_rate, spread_bps, scenario_version)
    values (p_user_id, p_portfolio_id, trim(p_client_conversion_id), p_from_currency, p_to_currency, p_from_amount, converted_amount, conversion_rate, greatest(from_rate.conversion_spread_bps, to_rate.conversion_spread_bps), from_rate.scenario_version)
    returning id into conversion_id;
  insert into public.international_paper_journal_entries (portfolio_id, source_type, source_id, correlation_id)
    values (p_portfolio_id, 'fx_conversion', conversion_id::text, trim(p_client_conversion_id)) returning id into journal_id;
  insert into public.international_paper_journal_lines (journal_entry_id, portfolio_id, currency, account_type, amount, memo)
    values
      (journal_id, p_portfolio_id, p_from_currency, 'cash', -p_from_amount, 'Virtual FX source cash'),
      (journal_id, p_portfolio_id, p_from_currency, 'fx_bridge', p_from_amount, 'Virtual FX source bridge'),
      (journal_id, p_portfolio_id, p_to_currency, 'cash', converted_amount, 'Virtual FX destination cash'),
      (journal_id, p_portfolio_id, p_to_currency, 'fx_bridge', -converted_amount, 'Virtual FX destination bridge');
  return jsonb_build_object('id', conversion_id, 'status', 'converted', 'from_currency', p_from_currency, 'to_currency', p_to_currency, 'from_amount', p_from_amount, 'to_amount', converted_amount, 'rate', conversion_rate, 'destination_balance', target_balance, 'idempotent_replay', false, 'simulation', true);
end;
$$;

create or replace function public.execute_international_paper_order(
  p_user_id uuid, p_portfolio_id uuid, p_listing_id bigint,
  p_client_order_id text, p_side text, p_order_type text,
  p_time_in_force text, p_quantity numeric,
  p_limit_price numeric default null, p_stop_price numeric default null
)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  account_row public.international_paper_accounts%rowtype;
  existing public.international_paper_orders%rowtype;
  listing_row public.global_instrument_listings%rowtype;
  venue_row public.global_market_venues%rowtype;
  rule_row public.international_paper_venue_rules%rowtype;
  quote_row public.international_paper_quotes%rowtype;
  cost_row public.international_paper_cost_rules%rowtype;
  fx_row public.international_paper_fx_rates%rowtype;
  cash_row public.international_paper_cash_balances%rowtype;
  position_row public.international_paper_positions%rowtype;
  order_id uuid;
  fill_id uuid;
  journal_id uuid;
  condition_met boolean := false;
  execution_price numeric(20,8);
  fill_quantity numeric(24,8);
  notional numeric(24,8);
  commission_value numeric(20,8);
  exchange_value numeric(20,8);
  tax_value numeric(20,8);
  total_cost_value numeric(20,8);
  order_value_usd numeric(24,8);
  new_cash numeric(24,8);
  new_quantity numeric(24,8);
  new_average numeric(20,8);
  realized_delta numeric(24,8) := 0;
  cost_basis numeric(24,8) := 0;
  remaining_to_sell numeric(24,8);
  consumed numeric(24,8);
  lot_row record;
  final_status text;
  rejection text;
  expiry timestamptz;
begin
  if auth.role() <> 'service_role' then raise exception 'International paper orders require the simulation service'; end if;
  if p_user_id is null or p_portfolio_id is null or p_listing_id is null
    or p_side is null or p_side not in ('buy', 'sell')
    or p_order_type is null or p_order_type not in ('market', 'limit', 'stop', 'stop_limit')
    or p_time_in_force is null or p_time_in_force not in ('day', 'gtc', 'ioc')
    or p_quantity is null or p_quantity <= 0 or p_quantity > 1000000
    or p_client_order_id is null or char_length(trim(p_client_order_id)) not between 8 and 100 then
    raise exception 'Invalid international paper order';
  end if;
  if (p_order_type in ('limit', 'stop_limit') and p_limit_price is null) or (p_order_type in ('stop', 'stop_limit') and p_stop_price is null) then raise exception 'Required paper order trigger price is missing'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || trim(p_client_order_id), 0));
  select * into existing from public.international_paper_orders where user_id = p_user_id and client_order_id = trim(p_client_order_id);
  if found then return jsonb_build_object('id', existing.id, 'status', existing.status, 'filled_quantity', existing.filled_quantity, 'average_fill_price', existing.average_fill_price, 'total_cost', existing.total_cost, 'idempotent_replay', true, 'simulation', true); end if;
  select * into account_row from public.international_paper_accounts where portfolio_id = p_portfolio_id and user_id = p_user_id and account_status = 'active' for update;
  if not found then raise exception 'International paper account was not found or is paused'; end if;
  select * into listing_row from public.global_instrument_listings where id = p_listing_id and enabled and listing_status = 'reference_only';
  if not found then raise exception 'International paper listing is unavailable'; end if;
  select * into venue_row from public.global_market_venues where id = listing_row.venue_id and enabled;
  select * into rule_row from public.international_paper_venue_rules where venue_id = listing_row.venue_id and enabled and simulation_only;
  select * into quote_row from public.international_paper_quotes where listing_id = p_listing_id and simulation_only;
  select * into cost_row from public.international_paper_cost_rules where venue_id = listing_row.venue_id and instrument_type = listing_row.instrument_type and enabled and simulation_only;
  select * into fx_row from public.international_paper_fx_rates where currency_code = listing_row.quote_currency and rate_status = 'modeled_scenario';
  if venue_row.id is null or rule_row.id is null or quote_row.id is null or cost_row.id is null or fx_row.currency_code is null then raise exception 'International paper scenario evidence is incomplete'; end if;
  if cost_row.cost_status <> 'modeled_scenario' then raise exception 'International paper costs are unavailable'; end if;
  if not rule_row.fractional_simulation_enabled and mod(p_quantity, rule_row.lot_size) <> 0 then raise exception 'Paper order quantity does not match the modeled lot size'; end if;
  if p_limit_price is not null and mod(p_limit_price, rule_row.tick_size) <> 0 then raise exception 'Paper limit price does not match the modeled tick size'; end if;
  if p_stop_price is not null and mod(p_stop_price, rule_row.tick_size) <> 0 then raise exception 'Paper stop price does not match the modeled tick size'; end if;
  expiry := case p_time_in_force when 'day' then now() + make_interval(hours => rule_row.day_order_expiry_hours) when 'gtc' then now() + interval '30 days' else now() end;
  if rule_row.session_state = 'halted_scenario' or quote_row.quote_status = 'halted_scenario' then final_status := 'halted'; rejection := 'simulated_market_halt';
  elsif rule_row.session_state = 'closed_scenario' or quote_row.quote_status = 'unavailable' then final_status := case when p_time_in_force = 'ioc' then 'expired' else 'accepted' end; rejection := 'simulated_session_unavailable';
  else
    condition_met := case p_order_type
      when 'market' then true
      when 'limit' then case p_side when 'buy' then quote_row.scenario_price <= p_limit_price else quote_row.scenario_price >= p_limit_price end
      when 'stop' then case p_side when 'buy' then quote_row.scenario_price >= p_stop_price else quote_row.scenario_price <= p_stop_price end
      when 'stop_limit' then
        (case p_side when 'buy' then quote_row.scenario_price >= p_stop_price else quote_row.scenario_price <= p_stop_price end)
        and (case p_side when 'buy' then quote_row.scenario_price <= p_limit_price else quote_row.scenario_price >= p_limit_price end)
    end;
    if not condition_met then final_status := case when p_time_in_force = 'ioc' then 'expired' else 'accepted' end; rejection := 'simulated_trigger_not_met'; end if;
  end if;
  execution_price := case p_side when 'buy' then ceil((quote_row.scenario_price * 1.0005) / rule_row.tick_size) * rule_row.tick_size else floor((quote_row.scenario_price * 0.9995) / rule_row.tick_size) * rule_row.tick_size end;
  if p_order_type in ('limit', 'stop_limit') then
    execution_price := case p_side when 'buy' then least(execution_price, p_limit_price) else greatest(execution_price, p_limit_price) end;
  end if;
  fill_quantity := case when condition_met and final_status is null then least(p_quantity, quote_row.available_quantity) else 0 end;
  notional := round(execution_price * fill_quantity, 8);
  commission_value := case when fill_quantity > 0 then greatest(cost_row.minimum_commission, round(notional * cost_row.commission_bps / 10000, 8)) else 0 end;
  exchange_value := round(notional * cost_row.exchange_fee_bps / 10000, 8);
  tax_value := round(notional * cost_row.tax_assumption_bps / 10000, 8);
  total_cost_value := commission_value + exchange_value + tax_value;
  order_value_usd := notional * fx_row.usd_value_per_unit;
  select * into cash_row from public.international_paper_cash_balances where portfolio_id = p_portfolio_id and currency = listing_row.quote_currency for update;
  select * into position_row from public.international_paper_positions where portfolio_id = p_portfolio_id and listing_id = p_listing_id for update;
  if fill_quantity > 0 and order_value_usd > account_row.max_order_value_usd then final_status := 'risk_rejected'; rejection := 'max_order_value_usd'; fill_quantity := 0;
  elsif fill_quantity > 0 and p_side = 'buy' and (cash_row.portfolio_id is null or cash_row.available_balance < notional + total_cost_value) then final_status := 'risk_rejected'; rejection := 'insufficient_virtual_cash'; fill_quantity := 0;
  elsif fill_quantity > 0 and p_side = 'sell' and coalesce(position_row.quantity, 0) < fill_quantity then final_status := 'risk_rejected'; rejection := 'insufficient_virtual_position'; fill_quantity := 0;
  end if;
  if fill_quantity = 0 then
    notional := 0; commission_value := 0; exchange_value := 0; tax_value := 0; total_cost_value := 0;
  end if;
  if fill_quantity = 0 and final_status is null then final_status := case when p_time_in_force = 'ioc' then 'expired' else 'accepted' end; rejection := coalesce(rejection, 'no_simulated_liquidity'); end if;
  if fill_quantity > 0 then final_status := case when fill_quantity < p_quantity then 'partially_filled' else 'filled' end; end if;
  insert into public.international_paper_orders (user_id, portfolio_id, listing_id, client_order_id, side, order_type, time_in_force, quantity, limit_price, stop_price, status, filled_quantity, average_fill_price, quote_currency, commission, exchange_fee, tax_assumption, total_cost, rejection_reason, quote_observed_at, expires_at, simulation_rule_version)
    values (p_user_id, p_portfolio_id, p_listing_id, trim(p_client_order_id), p_side, p_order_type, p_time_in_force, p_quantity, p_limit_price, p_stop_price, final_status, fill_quantity, case when fill_quantity > 0 then execution_price end, listing_row.quote_currency, commission_value, exchange_value, tax_value, total_cost_value, rejection, quote_row.observed_at, expiry, rule_row.rule_version)
    returning id into order_id;
  insert into public.international_paper_route_evidence (order_id, selected_mic, candidate_quotes, selection_reason, quote_observed_at)
    values (order_id, venue_row.mic_code, jsonb_build_array(jsonb_build_object('mic', venue_row.mic_code, 'price', quote_row.scenario_price, 'available_quantity', quote_row.available_quantity, 'source', 'deterministic_scenario')), 'single_simulated_listing_no_live_route_claim', quote_row.observed_at);
  if fill_quantity = 0 then return jsonb_build_object('id', order_id, 'status', final_status, 'reason', rejection, 'filled_quantity', 0, 'idempotent_replay', false, 'simulation', true); end if;
  insert into public.international_paper_fills (order_id, quantity, price, notional, quote_currency, commission, exchange_fee, tax_assumption, settles_on)
    values (order_id, fill_quantity, execution_price, notional, listing_row.quote_currency, commission_value, exchange_value, tax_value, current_date + rule_row.settlement_days)
    returning id into fill_id;
  if p_side = 'buy' then
    new_cash := cash_row.balance - notional - total_cost_value;
    new_quantity := coalesce(position_row.quantity, 0) + fill_quantity;
    new_average := round((coalesce(position_row.quantity, 0) * coalesce(position_row.average_cost, 0) + notional + total_cost_value) / new_quantity, 8);
    update public.international_paper_cash_balances set balance = new_cash, available_balance = new_cash where portfolio_id = p_portfolio_id and currency = listing_row.quote_currency;
    insert into public.international_paper_positions (portfolio_id, listing_id, quote_currency, quantity, average_cost)
      values (p_portfolio_id, p_listing_id, listing_row.quote_currency, new_quantity, new_average)
      on conflict (portfolio_id, listing_id) do update set quantity = excluded.quantity, average_cost = excluded.average_cost, updated_at = now();
    insert into public.international_paper_tax_lots (portfolio_id, listing_id, source_fill_id, quote_currency, original_quantity, remaining_quantity, unit_cost, acquired_at)
      values (p_portfolio_id, p_listing_id, fill_id, listing_row.quote_currency, fill_quantity, fill_quantity, (notional + total_cost_value) / fill_quantity, now());
  else
    remaining_to_sell := fill_quantity;
    for lot_row in select id, remaining_quantity, unit_cost from public.international_paper_tax_lots where portfolio_id = p_portfolio_id and listing_id = p_listing_id and remaining_quantity > 0 order by acquired_at, id for update loop
      consumed := least(remaining_to_sell, lot_row.remaining_quantity);
      cost_basis := cost_basis + consumed * lot_row.unit_cost;
      update public.international_paper_tax_lots set remaining_quantity = remaining_quantity - consumed where id = lot_row.id;
      remaining_to_sell := remaining_to_sell - consumed;
      exit when remaining_to_sell <= 0;
    end loop;
    if remaining_to_sell > 0 then raise exception 'Paper tax lots do not reconcile with the simulated position'; end if;
    new_cash := cash_row.balance + notional - total_cost_value;
    new_quantity := position_row.quantity - fill_quantity;
    realized_delta := notional - total_cost_value - cost_basis;
    update public.international_paper_cash_balances set balance = new_cash, available_balance = new_cash where portfolio_id = p_portfolio_id and currency = listing_row.quote_currency;
    update public.international_paper_positions set quantity = new_quantity, average_cost = case when new_quantity = 0 then 0 else average_cost end, realized_pnl = realized_pnl + realized_delta where portfolio_id = p_portfolio_id and listing_id = p_listing_id;
  end if;
  insert into public.international_paper_journal_entries (portfolio_id, source_type, source_id, correlation_id)
    values (p_portfolio_id, 'trade', order_id::text, trim(p_client_order_id)) returning id into journal_id;
  insert into public.international_paper_journal_lines (journal_entry_id, portfolio_id, currency, account_type, amount, memo)
    values
      (journal_id, p_portfolio_id, listing_row.quote_currency, 'cash', case p_side when 'buy' then -(notional + total_cost_value) else notional - total_cost_value end, 'Virtual trade cash'),
      (journal_id, p_portfolio_id, listing_row.quote_currency, 'position_cost', case p_side when 'buy' then notional else -notional end, 'Simulated position notional'),
      (journal_id, p_portfolio_id, listing_row.quote_currency, 'fee_expense', commission_value + exchange_value, 'Modeled commission and exchange fee'),
      (journal_id, p_portfolio_id, listing_row.quote_currency, 'tax_expense', tax_value, 'Modeled tax assumption');
  return jsonb_build_object('id', order_id, 'status', final_status, 'side', p_side, 'filled_quantity', fill_quantity, 'average_fill_price', execution_price, 'commission', commission_value, 'exchange_fee', exchange_value, 'tax_assumption', tax_value, 'total_cost', total_cost_value, 'cash_balance', new_cash, 'settles_on', current_date + rule_row.settlement_days, 'idempotent_replay', false, 'simulation', true);
end;
$$;

create or replace function public.reconcile_international_paper_portfolio(
  p_user_id uuid, p_portfolio_id uuid
)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  unbalanced_count integer;
  cash_count integer;
  position_count integer;
  lot_count integer;
  reconciliation_status text;
  reconciliation_id bigint;
begin
  if auth.role() <> 'service_role' then raise exception 'International paper reconciliation requires the simulation service'; end if;
  if not exists (select 1 from public.international_paper_accounts where portfolio_id = p_portfolio_id and user_id = p_user_id) then raise exception 'International paper account was not found'; end if;
  select count(*) into unbalanced_count from (
    select lines.journal_entry_id, lines.currency from public.international_paper_journal_lines lines
    join public.international_paper_journal_entries entry on entry.id = lines.journal_entry_id
    where entry.portfolio_id = p_portfolio_id group by lines.journal_entry_id, lines.currency
    having abs(sum(lines.amount)) > 0.00000001
  ) imbalance;
  with account_cash as (
    select currency, balance from public.international_paper_cash_balances where portfolio_id = p_portfolio_id
  ), ledger_cash as (
    select lines.currency, sum(lines.amount) as amount from public.international_paper_journal_lines lines
    join public.international_paper_journal_entries entry on entry.id = lines.journal_entry_id
    where entry.portfolio_id = p_portfolio_id and lines.account_type = 'cash' group by lines.currency
  ), comparison as (
    select coalesce(cash.currency, ledger.currency) currency, coalesce(cash.balance, 0) actual, coalesce(ledger.amount, 0) expected
    from account_cash cash full join ledger_cash ledger on ledger.currency = cash.currency
  ) select count(*) into cash_count from comparison where abs(actual - expected) > 0.00000001;
  with account_positions as (
    select listing_id, quantity from public.international_paper_positions where portfolio_id = p_portfolio_id
  ), fill_positions as (
    select orders.listing_id, sum(case orders.side when 'buy' then fills.quantity else -fills.quantity end) quantity
    from public.international_paper_fills fills join public.international_paper_orders orders on orders.id = fills.order_id
    where orders.portfolio_id = p_portfolio_id group by orders.listing_id
  ), comparison as (
    select coalesce(position.listing_id, fills.listing_id) listing_id, coalesce(position.quantity, 0) actual, coalesce(fills.quantity, 0) expected
    from account_positions position full join fill_positions fills on fills.listing_id = position.listing_id
  ) select count(*) into position_count from comparison where abs(actual - expected) > 0.00000001;
  with lot_totals as (
    select listing_id, sum(remaining_quantity) quantity from public.international_paper_tax_lots where portfolio_id = p_portfolio_id group by listing_id
  ) select count(*) into lot_count from public.international_paper_positions position left join lot_totals lots on lots.listing_id = position.listing_id
    where position.portfolio_id = p_portfolio_id and abs(position.quantity - coalesce(lots.quantity, 0)) > 0.00000001;
  reconciliation_status := case when unbalanced_count + cash_count + position_count + lot_count = 0 then 'passed' else 'exception' end;
  insert into public.international_paper_reconciliations (portfolio_id, status, unbalanced_journals, cash_mismatches, position_mismatches, tax_lot_mismatches, details)
    values (p_portfolio_id, reconciliation_status, unbalanced_count, cash_count, position_count, lot_count, jsonb_build_object('simulation', true, 'rule_version', 'international-paper-reconciliation-v1')) returning id into reconciliation_id;
  return jsonb_build_object('id', reconciliation_id, 'status', reconciliation_status, 'unbalanced_journals', unbalanced_count, 'cash_mismatches', cash_count, 'position_mismatches', position_count, 'tax_lot_mismatches', lot_count, 'simulation', true);
end;
$$;

revoke all on function public.initialize_international_paper_account(uuid, uuid, numeric) from public, anon, authenticated;
revoke all on function public.convert_international_paper_cash(uuid, uuid, text, text, numeric, text) from public, anon, authenticated;
revoke all on function public.execute_international_paper_order(uuid, uuid, bigint, text, text, text, text, numeric, numeric, numeric) from public, anon, authenticated;
revoke all on function public.reconcile_international_paper_portfolio(uuid, uuid) from public, anon, authenticated;
grant execute on function public.initialize_international_paper_account(uuid, uuid, numeric) to service_role;
grant execute on function public.convert_international_paper_cash(uuid, uuid, text, text, numeric, text) to service_role;
grant execute on function public.execute_international_paper_order(uuid, uuid, bigint, text, text, text, text, numeric, numeric, numeric) to service_role;
grant execute on function public.reconcile_international_paper_portfolio(uuid, uuid) to service_role;

do $$
begin
  if exists (select 1 from public.international_paper_trading_controls where live_market_data_enabled or live_order_routing_enabled or broker_connectivity_enabled or real_customer_funds_enabled or custody_enabled or real_settlement_enabled or margin_enabled or short_selling_enabled) then
    raise exception 'Phase 8B operational controls must remain fail-closed';
  end if;
  if to_regclass('public.live_international_orders') is not null or to_regclass('public.international_custody_accounts') is not null or to_regprocedure('public.route_international_order(jsonb)') is not null then
    raise exception 'Phase 8B cannot deploy with a live international execution path';
  end if;
end;
$$;

comment on table public.international_paper_trading_controls is 'Phase 8B simulation controls. Every live market-data, broker, funding, custody, settlement, margin and short-selling path remains false.';
comment on table public.international_paper_quotes is 'Deterministic scenario quotes for paper education; not live, delayed or executable market data.';
comment on table public.international_paper_fx_rates is 'Deterministic FX assumptions for virtual conversion; not a customer rate or payment quote.';
comment on table public.international_paper_journal_lines is 'Balanced per-currency simulation lines with no financial-ledger or cash value.';
comment on table public.international_paper_route_evidence is 'Single-listing simulated route evidence that explicitly makes no best-execution claim.';
comment on function public.execute_international_paper_order is 'Service-only deterministic international paper execution. It cannot call a broker or route a live order.';
