-- TradePulse AI
-- Migration 047: Phase 8C options education and defined-risk paper trading
-- Every chain, premium, payoff, exercise and assignment record is a
-- deterministic educational simulation. No live market-data, broker, margin,
-- funding, custody or settlement connection is introduced.

create table public.options_paper_controls (
  control_key text primary key check (control_key = 'options-education-paper-trading'),
  education_workspace_enabled boolean not null default true check (education_workspace_enabled),
  single_leg_simulation_enabled boolean not null default true check (single_leg_simulation_enabled),
  defined_risk_spread_simulation_enabled boolean not null default true check (defined_risk_spread_simulation_enabled),
  payoff_simulation_enabled boolean not null default true check (payoff_simulation_enabled),
  assignment_simulation_enabled boolean not null default true check (assignment_simulation_enabled),
  policy_version text not null,
  live_market_data_enabled boolean not null default false check (not live_market_data_enabled),
  live_options_routing_enabled boolean not null default false check (not live_options_routing_enabled),
  broker_connectivity_enabled boolean not null default false check (not broker_connectivity_enabled),
  real_customer_funds_enabled boolean not null default false check (not real_customer_funds_enabled),
  real_positions_enabled boolean not null default false check (not real_positions_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  real_settlement_enabled boolean not null default false check (not real_settlement_enabled),
  margin_enabled boolean not null default false check (not margin_enabled),
  uncovered_short_options_enabled boolean not null default false check (not uncovered_short_options_enabled),
  automatic_options_permission_enabled boolean not null default false check (not automatic_options_permission_enabled),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.options_chain_entitlements (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references public.global_market_venues(id) on delete cascade,
  audience_region text not null default 'GLOBAL' check (
    audience_region = 'GLOBAL' or audience_region ~ '^[A-Z]{2}$'
  ),
  display_status text not null check (display_status in ('deterministic_education', 'unavailable')),
  educational_display_permitted boolean not null default false,
  live_display_rights_confirmed boolean not null default false check (not live_display_rights_confirmed),
  source_name text not null,
  source_as_of date not null,
  entitlement_version text not null,
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now(),
  unique (venue_id, audience_region),
  check (display_status <> 'deterministic_education' or educational_display_permitted)
);

create table public.options_chain_scenarios (
  id bigint generated by default as identity primary key,
  underlying_listing_id bigint not null references public.global_instrument_listings(id) on delete cascade,
  entitlement_id bigint not null references public.options_chain_entitlements(id),
  contract_symbol text not null unique check (contract_symbol = upper(contract_symbol)),
  option_type text not null check (option_type in ('call', 'put')),
  expires_on date not null,
  strike numeric(20,8) not null check (strike > 0),
  contract_multiplier integer not null default 100 check (contract_multiplier = 100),
  bid numeric(20,8) not null check (bid >= 0),
  ask numeric(20,8) not null check (ask >= bid and ask > 0),
  volume integer not null check (volume >= 0),
  open_interest integer not null check (open_interest >= 0),
  implied_volatility numeric(12,8) not null check (implied_volatility between 0 and 5),
  delta numeric(12,8) not null check (delta between -1 and 1),
  gamma numeric(12,8) not null check (gamma between 0 and 1),
  theta numeric(12,8) not null check (theta between -10 and 0),
  vega numeric(12,8) not null check (vega between 0 and 10),
  quote_observed_at timestamptz not null,
  freshness_status text not null check (freshness_status in ('scenario_current', 'scenario_stale', 'unavailable')),
  scenario_version text not null,
  source_name text not null,
  source_type text not null default 'deterministic_fixture' check (source_type = 'deterministic_fixture'),
  corporate_action_adjusted boolean not null default false,
  simulation_only boolean not null default true check (simulation_only),
  live_contract_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (underlying_listing_id, expires_on, strike, option_type),
  check (live_contract_id is null)
);

create table public.options_paper_accounts (
  portfolio_id uuid primary key references public.investment_portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  currency text not null default 'USD' check (currency = 'USD'),
  starting_cash numeric(24,8) not null check (starting_cash between 1000 and 1000000),
  cash_balance numeric(24,8) not null check (cash_balance >= 0),
  account_status text not null default 'active' check (account_status in ('active', 'paused')),
  simulation_only boolean not null default true check (simulation_only),
  live_options_account_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, portfolio_id),
  check (live_options_account_id is null)
);

create table public.options_paper_appropriateness_profiles (
  portfolio_id uuid primary key references public.options_paper_accounts(portfolio_id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  experience_level text not null check (experience_level in ('none', 'beginner', 'intermediate', 'advanced')),
  objective text not null check (objective in ('education', 'hedging', 'income', 'growth')),
  loss_tolerance text not null check (loss_tolerance in ('low', 'medium', 'high')),
  jurisdiction_code text not null check (jurisdiction_code ~ '^[A-Z]{2}$'),
  assessment_status text not null default 'education_only' check (assessment_status = 'education_only'),
  simulation_access_enabled boolean not null default true check (simulation_access_enabled),
  live_options_permission_enabled boolean not null default false check (not live_options_permission_enabled),
  forecast_permission_override_enabled boolean not null default false check (not forecast_permission_override_enabled),
  assessment_version text not null default 'options-appropriateness-v1',
  assessed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, portfolio_id)
);

create table public.options_paper_strategies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.options_paper_accounts(portfolio_id) on delete cascade,
  client_strategy_id text not null check (char_length(client_strategy_id) between 8 and 100),
  strategy_type text not null check (
    strategy_type in ('long_call', 'long_put', 'bull_call_spread', 'bear_put_spread')
  ),
  underlying_listing_id bigint not null references public.global_instrument_listings(id),
  expires_on date not null,
  contracts integer not null check (contracts between 1 and 100),
  contract_multiplier integer not null default 100 check (contract_multiplier = 100),
  net_debit_per_share numeric(20,8) not null check (net_debit_per_share > 0),
  collateral_amount numeric(24,8) not null check (collateral_amount >= 0),
  max_profit numeric(24,8) check (max_profit is null or max_profit >= 0),
  max_loss numeric(24,8) not null check (max_loss >= 0),
  break_even_price numeric(20,8) not null check (break_even_price >= 0),
  profit_potential text not null check (profit_potential in ('bounded', 'unbounded')),
  loss_risk text not null default 'bounded' check (loss_risk = 'bounded'),
  defined_risk boolean not null default true check (defined_risk),
  lifecycle_status text not null default 'open' check (
    lifecycle_status in ('open', 'adjusted', 'expired', 'exercised', 'assigned', 'early_assigned', 'closed')
  ),
  realized_pnl numeric(24,8),
  rule_version text not null default 'options-defined-risk-v1',
  simulation_only boolean not null default true check (simulation_only),
  live_order_group_id text,
  opened_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_strategy_id),
  check (collateral_amount >= max_loss),
  check (live_order_group_id is null),
  check (profit_potential <> 'unbounded' or strategy_type = 'long_call')
);

create table public.options_paper_legs (
  id bigint generated by default as identity primary key,
  strategy_id uuid not null references public.options_paper_strategies(id) on delete cascade,
  contract_id bigint not null references public.options_chain_scenarios(id),
  side text not null check (side in ('long', 'short')),
  ratio integer not null default 1 check (ratio between 1 and 10),
  opening_price numeric(20,8) not null check (opening_price >= 0),
  protective_long_leg_required boolean not null default false,
  simulation_only boolean not null default true check (simulation_only),
  unique (strategy_id, contract_id, side),
  check (side <> 'short' or protective_long_leg_required)
);

create table public.options_paper_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.options_paper_accounts(portfolio_id) on delete cascade,
  strategy_id uuid not null references public.options_paper_strategies(id) on delete cascade,
  client_event_id text not null check (char_length(client_event_id) between 8 and 100),
  event_type text not null check (
    event_type in ('expiration', 'exercise', 'assignment', 'early_assignment', 'corporate_action')
  ),
  settlement_price numeric(20,8) check (settlement_price is null or settlement_price >= 0),
  cash_effect numeric(24,8) not null default 0 check (cash_effect >= 0),
  realized_pnl numeric(24,8),
  settlement_mode text not null default 'virtual_cash' check (settlement_mode = 'virtual_cash'),
  event_note text not null,
  simulation_only boolean not null default true check (simulation_only),
  applied_to_real_position boolean not null default false check (not applied_to_real_position),
  occurred_at timestamptz not null default now(),
  unique (user_id, client_event_id)
);

create table public.options_paper_journal_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.options_paper_accounts(portfolio_id) on delete cascade,
  strategy_id uuid references public.options_paper_strategies(id) on delete set null,
  event_id uuid references public.options_paper_events(id) on delete set null,
  entry_type text not null check (entry_type in ('initial_credit', 'strategy_open', 'virtual_settlement')),
  correlation_id text not null,
  simulation_only boolean not null default true check (simulation_only),
  created_at timestamptz not null default now(),
  unique (user_id, correlation_id)
);

create table public.options_paper_journal_lines (
  id bigint generated by default as identity primary key,
  journal_entry_id uuid not null references public.options_paper_journal_entries(id) on delete cascade,
  account_code text not null check (account_code in ('virtual_cash', 'simulation_equity', 'option_premium_asset', 'option_settlement')),
  currency text not null default 'USD' check (currency = 'USD'),
  amount numeric(24,8) not null check (amount <> 0),
  created_at timestamptz not null default now()
);

create table public.options_paper_reconciliations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_id uuid not null references public.options_paper_accounts(portfolio_id) on delete cascade,
  status text not null check (status in ('passed', 'exception')),
  unbalanced_journals integer not null check (unbalanced_journals >= 0),
  uncovered_short_legs integer not null check (uncovered_short_legs >= 0),
  risk_boundary_exceptions integer not null check (risk_boundary_exceptions >= 0),
  cash_mismatches integer not null check (cash_mismatches >= 0),
  reconciliation_version text not null default 'options-reconciliation-v1',
  reconciled_at timestamptz not null default now()
);

create index idx_options_chain_underlying_expiry
  on public.options_chain_scenarios(underlying_listing_id, expires_on, strike, option_type);
create index idx_options_strategy_portfolio_opened
  on public.options_paper_strategies(portfolio_id, opened_at desc);
create index idx_options_event_strategy_occurred
  on public.options_paper_events(strategy_id, occurred_at desc);
create index idx_options_journal_portfolio_created
  on public.options_paper_journal_entries(portfolio_id, created_at desc);
create index idx_options_reconciliation_portfolio
  on public.options_paper_reconciliations(portfolio_id, reconciled_at desc);

alter table public.options_paper_controls enable row level security;
alter table public.options_chain_entitlements enable row level security;
alter table public.options_chain_scenarios enable row level security;
alter table public.options_paper_accounts enable row level security;
alter table public.options_paper_appropriateness_profiles enable row level security;
alter table public.options_paper_strategies enable row level security;
alter table public.options_paper_legs enable row level security;
alter table public.options_paper_events enable row level security;
alter table public.options_paper_journal_entries enable row level security;
alter table public.options_paper_journal_lines enable row level security;
alter table public.options_paper_reconciliations enable row level security;

create policy "Public reads options simulation locks"
  on public.options_paper_controls for select to anon, authenticated using (true);
create policy "Public reads educational options entitlements"
  on public.options_chain_entitlements for select to anon, authenticated using (true);
create policy "Public reads permitted deterministic option chains"
  on public.options_chain_scenarios for select to anon, authenticated
  using (
    simulation_only and source_type = 'deterministic_fixture'
    and exists (
      select 1 from public.options_chain_entitlements entitlement
      where entitlement.id = options_chain_scenarios.entitlement_id
        and entitlement.educational_display_permitted
        and entitlement.display_status = 'deterministic_education'
    )
  );

create policy "Users read their options paper accounts"
  on public.options_paper_accounts for select to authenticated using (user_id = auth.uid());
create policy "Users read their options appropriateness profile"
  on public.options_paper_appropriateness_profiles for select to authenticated using (user_id = auth.uid());
create policy "Users read their options paper strategies"
  on public.options_paper_strategies for select to authenticated using (user_id = auth.uid());
create policy "Users read their options paper legs"
  on public.options_paper_legs for select to authenticated using (
    exists (
      select 1 from public.options_paper_strategies strategy
      where strategy.id = options_paper_legs.strategy_id and strategy.user_id = auth.uid()
    )
  );
create policy "Users read their options paper events"
  on public.options_paper_events for select to authenticated using (user_id = auth.uid());
create policy "Users read their options paper journals"
  on public.options_paper_journal_entries for select to authenticated using (user_id = auth.uid());
create policy "Users read their options paper journal lines"
  on public.options_paper_journal_lines for select to authenticated using (
    exists (
      select 1 from public.options_paper_journal_entries journal
      where journal.id = options_paper_journal_lines.journal_entry_id and journal.user_id = auth.uid()
    )
  );
create policy "Users read their options paper reconciliations"
  on public.options_paper_reconciliations for select to authenticated using (user_id = auth.uid());

create trigger options_paper_controls_set_updated_at before update on public.options_paper_controls
  for each row execute function public.set_updated_at();
create trigger options_chain_scenarios_set_updated_at before update on public.options_chain_scenarios
  for each row execute function public.set_updated_at();
create trigger options_paper_accounts_set_updated_at before update on public.options_paper_accounts
  for each row execute function public.set_updated_at();
create trigger options_appropriateness_set_updated_at before update on public.options_paper_appropriateness_profiles
  for each row execute function public.set_updated_at();
create trigger options_strategies_set_updated_at before update on public.options_paper_strategies
  for each row execute function public.set_updated_at();

insert into public.options_paper_controls (control_key, policy_version)
values ('options-education-paper-trading', 'options-education-paper-v1');

insert into public.options_chain_entitlements (
  venue_id, audience_region, display_status, educational_display_permitted,
  source_name, source_as_of, entitlement_version
) values (
  (select id from public.global_market_venues where mic_code = 'XNAS'),
  'GLOBAL', 'deterministic_education', true,
  'Deterministic Phase 8C scenario', date '2026-09-09', 'options-chain-entitlement-v1'
);

insert into public.options_chain_scenarios (
  underlying_listing_id, entitlement_id, contract_symbol, option_type, expires_on,
  strike, bid, ask, volume, open_interest, implied_volatility,
  delta, gamma, theta, vega, quote_observed_at, freshness_status,
  scenario_version, source_name
) values
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:AAPL'), (select id from public.options_chain_entitlements), 'AAPL301220C00240000', 'call', date '2030-12-20', 240, 13, 14, 1200, 8400, 0.28000000, 0.68000000, 0.01800000, -0.07000000, 0.21000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:AAPL'), (select id from public.options_chain_entitlements), 'AAPL301220C00260000', 'call', date '2030-12-20', 260, 7, 8, 980, 7200, 0.30000000, 0.43000000, 0.02000000, -0.06500000, 0.22000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:AAPL'), (select id from public.options_chain_entitlements), 'AAPL301220P00240000', 'put', date '2030-12-20', 240, 6, 7, 760, 6100, 0.29000000, -0.32000000, 0.01800000, -0.06000000, 0.20000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:AAPL'), (select id from public.options_chain_entitlements), 'AAPL301220P00260000', 'put', date '2030-12-20', 260, 12, 13, 890, 6900, 0.31000000, -0.57000000, 0.02000000, -0.06800000, 0.23000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:QQQ'), (select id from public.options_chain_entitlements), 'QQQ301220C00580000', 'call', date '2030-12-20', 580, 34, 36, 1500, 9200, 0.24000000, 0.70000000, 0.00900000, -0.16000000, 0.42000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:QQQ'), (select id from public.options_chain_entitlements), 'QQQ301220C00620000', 'call', date '2030-12-20', 620, 16, 18, 1310, 8100, 0.26000000, 0.39000000, 0.01000000, -0.15000000, 0.44000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:QQQ'), (select id from public.options_chain_entitlements), 'QQQ301220P00580000', 'put', date '2030-12-20', 580, 15, 17, 1050, 7400, 0.25000000, -0.30000000, 0.00900000, -0.14000000, 0.41000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario'),
  ((select id from public.global_instrument_listings where listing_key = 'XNAS:QQQ'), (select id from public.options_chain_entitlements), 'QQQ301220P00620000', 'put', date '2030-12-20', 620, 32, 35, 1180, 7900, 0.27000000, -0.61000000, 0.01000000, -0.15500000, 0.45000000, '2026-09-09T00:00:00Z', 'scenario_current', 'options-chain-v1', 'Deterministic Phase 8C scenario');

revoke all on table public.options_paper_controls, public.options_chain_entitlements,
  public.options_chain_scenarios, public.options_paper_accounts,
  public.options_paper_appropriateness_profiles, public.options_paper_strategies,
  public.options_paper_legs, public.options_paper_events,
  public.options_paper_journal_entries, public.options_paper_journal_lines,
  public.options_paper_reconciliations from public, anon, authenticated, service_role;
grant select on table public.options_paper_controls, public.options_chain_entitlements,
  public.options_chain_scenarios to anon, authenticated;
grant select on table public.options_paper_accounts, public.options_paper_appropriateness_profiles,
  public.options_paper_strategies, public.options_paper_legs, public.options_paper_events,
  public.options_paper_journal_entries, public.options_paper_journal_lines,
  public.options_paper_reconciliations to authenticated;

create view public.options_paper_chain_catalog
with (security_invoker = true)
as
select
  chain.id as contract_id,
  listing.id as underlying_listing_id,
  listing.listing_key as underlying_listing_key,
  listing.display_symbol as underlying_symbol,
  listing.instrument_name as underlying_name,
  listing.quote_currency,
  underlying_quote.scenario_price as underlying_scenario_price,
  venue.mic_code,
  chain.contract_symbol,
  chain.option_type,
  chain.expires_on,
  chain.strike,
  chain.contract_multiplier,
  chain.bid,
  chain.ask,
  chain.volume,
  chain.open_interest,
  chain.implied_volatility,
  chain.delta,
  chain.gamma,
  chain.theta,
  chain.vega,
  chain.quote_observed_at,
  chain.freshness_status,
  chain.corporate_action_adjusted,
  chain.scenario_version,
  chain.simulation_only,
  entitlement.display_status,
  entitlement.educational_display_permitted,
  entitlement.live_display_rights_confirmed,
  controls.live_market_data_enabled,
  controls.live_options_routing_enabled,
  controls.broker_connectivity_enabled,
  controls.margin_enabled,
  controls.uncovered_short_options_enabled
from public.options_chain_scenarios chain
join public.global_instrument_listings listing on listing.id = chain.underlying_listing_id
join public.global_market_venues venue on venue.id = listing.venue_id
join public.international_paper_quotes underlying_quote on underlying_quote.listing_id = listing.id
join public.options_chain_entitlements entitlement on entitlement.id = chain.entitlement_id
cross join public.options_paper_controls controls
where entitlement.display_status = 'deterministic_education'
  and entitlement.educational_display_permitted
  and chain.freshness_status <> 'unavailable';

create view public.options_paper_strategy_history
with (security_invoker = true)
as
select
  strategy.id,
  strategy.user_id,
  strategy.portfolio_id,
  strategy.strategy_type,
  listing.listing_key as underlying_listing_key,
  listing.display_symbol as underlying_symbol,
  strategy.expires_on,
  strategy.contracts,
  strategy.net_debit_per_share,
  strategy.collateral_amount,
  strategy.max_profit,
  strategy.max_loss,
  strategy.break_even_price,
  strategy.profit_potential,
  strategy.loss_risk,
  strategy.lifecycle_status,
  strategy.realized_pnl,
  strategy.opened_at,
  count(leg.id)::integer as leg_count,
  count(leg.id) filter (where leg.side = 'short')::integer as protected_short_leg_count
from public.options_paper_strategies strategy
join public.global_instrument_listings listing on listing.id = strategy.underlying_listing_id
left join public.options_paper_legs leg on leg.strategy_id = strategy.id
group by strategy.id, listing.listing_key, listing.display_symbol;

grant select on public.options_paper_chain_catalog to anon, authenticated;
grant select on public.options_paper_strategy_history to authenticated;

create or replace function public.initialize_options_paper_account(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_starting_cash numeric,
  p_experience_level text,
  p_objective text,
  p_loss_tolerance text,
  p_jurisdiction_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_inserted integer := 0;
  v_journal_id uuid;
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Options paper accounts require the simulation service';
  end if;
  if p_starting_cash < 1000 or p_starting_cash > 1000000 then
    raise exception 'Invalid options virtual balance';
  end if;
  if p_experience_level not in ('none', 'beginner', 'intermediate', 'advanced')
    or p_objective not in ('education', 'hedging', 'income', 'growth')
    or p_loss_tolerance not in ('low', 'medium', 'high')
    or p_jurisdiction_code !~ '^[A-Z]{2}$' then
    raise exception 'Invalid options education assessment';
  end if;
  if not exists (
    select 1 from public.investment_portfolios
    where id = p_portfolio_id and user_id = p_user_id and portfolio_type = 'paper'
  ) then
    raise exception 'Paper portfolio not found';
  end if;

  insert into public.options_paper_accounts (
    portfolio_id, user_id, starting_cash, cash_balance
  ) values (
    p_portfolio_id, p_user_id, p_starting_cash, p_starting_cash
  ) on conflict (portfolio_id) do nothing;
  get diagnostics v_inserted = row_count;

  if not exists (
    select 1 from public.options_paper_accounts
    where portfolio_id = p_portfolio_id and user_id = p_user_id
  ) then
    raise exception 'Options paper account belongs to another user';
  end if;

  insert into public.options_paper_appropriateness_profiles (
    portfolio_id, user_id, experience_level, objective, loss_tolerance,
    jurisdiction_code
  ) values (
    p_portfolio_id, p_user_id, p_experience_level, p_objective,
    p_loss_tolerance, p_jurisdiction_code
  )
  on conflict (portfolio_id) do update set
    experience_level = excluded.experience_level,
    objective = excluded.objective,
    loss_tolerance = excluded.loss_tolerance,
    jurisdiction_code = excluded.jurisdiction_code,
    assessed_at = now();

  if v_inserted = 1 then
    insert into public.options_paper_journal_entries (
      user_id, portfolio_id, entry_type, correlation_id
    ) values (
      p_user_id, p_portfolio_id, 'initial_credit', 'options-initial-' || p_portfolio_id::text
    ) returning id into v_journal_id;
    insert into public.options_paper_journal_lines (journal_entry_id, account_code, amount)
    values
      (v_journal_id, 'virtual_cash', p_starting_cash),
      (v_journal_id, 'simulation_equity', -p_starting_cash);
  end if;

  return jsonb_build_object(
    'status', case when v_inserted = 1 then 'created' else 'updated' end,
    'assessmentStatus', 'education_only',
    'liveOptionsPermission', false
  );
end;
$$;

create or replace function public.create_options_paper_strategy(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_client_strategy_id text,
  p_strategy_type text,
  p_long_contract_id bigint,
  p_short_contract_id bigint,
  p_contracts integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_account public.options_paper_accounts%rowtype;
  v_long public.options_chain_scenarios%rowtype;
  v_short public.options_chain_scenarios%rowtype;
  v_existing uuid;
  v_strategy_id uuid;
  v_journal_id uuid;
  v_width numeric(20,8);
  v_debit numeric(20,8);
  v_max_loss numeric(24,8);
  v_max_profit numeric(24,8);
  v_break_even numeric(20,8);
  v_profit_potential text := 'bounded';
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Options paper strategies require the simulation service';
  end if;
  if char_length(coalesce(p_client_strategy_id, '')) not between 8 and 100
    or p_strategy_type not in ('long_call', 'long_put', 'bull_call_spread', 'bear_put_spread')
    or p_contracts not between 1 and 100 then
    raise exception 'Invalid options paper strategy';
  end if;

  select id into v_existing from public.options_paper_strategies
  where user_id = p_user_id and client_strategy_id = p_client_strategy_id;
  if v_existing is not null then
    return jsonb_build_object('status', 'open', 'strategyId', v_existing, 'idempotentReplay', true);
  end if;

  select * into v_account from public.options_paper_accounts
  where portfolio_id = p_portfolio_id and user_id = p_user_id for update;
  if v_account.portfolio_id is null or v_account.account_status <> 'active' then
    raise exception 'Options paper account is unavailable';
  end if;
  if not exists (
    select 1 from public.options_paper_appropriateness_profiles
    where portfolio_id = p_portfolio_id and user_id = p_user_id
      and assessment_status = 'education_only' and simulation_access_enabled
      and not live_options_permission_enabled and not forecast_permission_override_enabled
  ) then
    raise exception 'Options education assessment is unavailable';
  end if;

  select * into v_long from public.options_chain_scenarios where id = p_long_contract_id;
  if v_long.id is null or v_long.freshness_status <> 'scenario_current'
    or not v_long.simulation_only or v_long.source_type <> 'deterministic_fixture' then
    raise exception 'Selected options scenario is unavailable';
  end if;

  if p_strategy_type in ('long_call', 'long_put') then
    if p_short_contract_id is not null
      or (p_strategy_type = 'long_call' and v_long.option_type <> 'call')
      or (p_strategy_type = 'long_put' and v_long.option_type <> 'put') then
      raise exception 'Single-leg strategy contract mismatch';
    end if;
    v_debit := v_long.ask;
    v_max_loss := v_debit * v_long.contract_multiplier * p_contracts;
    v_break_even := case when v_long.option_type = 'call'
      then v_long.strike + v_debit else greatest(v_long.strike - v_debit, 0) end;
    if p_strategy_type = 'long_call' then
      v_max_profit := null;
      v_profit_potential := 'unbounded';
    else
      v_max_profit := greatest(v_long.strike - v_debit, 0) * v_long.contract_multiplier * p_contracts;
    end if;
  else
    select * into v_short from public.options_chain_scenarios where id = p_short_contract_id;
    if v_short.id is null
      or v_short.underlying_listing_id <> v_long.underlying_listing_id
      or v_short.expires_on <> v_long.expires_on
      or v_short.option_type <> v_long.option_type
      or v_short.contract_multiplier <> v_long.contract_multiplier then
      raise exception 'Defined-risk spread legs do not match';
    end if;
    if (p_strategy_type = 'bull_call_spread' and (
        v_long.option_type <> 'call' or v_long.strike >= v_short.strike
      )) or (p_strategy_type = 'bear_put_spread' and (
        v_long.option_type <> 'put' or v_long.strike <= v_short.strike
      )) then
      raise exception 'Spread direction is not defined risk';
    end if;
    v_width := abs(v_short.strike - v_long.strike);
    v_debit := v_long.ask - v_short.bid;
    if v_debit <= 0 or v_debit >= v_width then
      raise exception 'Spread premium does not preserve bounded risk';
    end if;
    v_max_loss := v_debit * v_long.contract_multiplier * p_contracts;
    v_max_profit := (v_width - v_debit) * v_long.contract_multiplier * p_contracts;
    v_break_even := case when p_strategy_type = 'bull_call_spread'
      then v_long.strike + v_debit else v_long.strike - v_debit end;
  end if;

  if v_account.cash_balance < v_max_loss then
    raise exception 'Insufficient options virtual cash';
  end if;

  insert into public.options_paper_strategies (
    user_id, portfolio_id, client_strategy_id, strategy_type,
    underlying_listing_id, expires_on, contracts, contract_multiplier,
    net_debit_per_share, collateral_amount, max_profit, max_loss,
    break_even_price, profit_potential
  ) values (
    p_user_id, p_portfolio_id, p_client_strategy_id, p_strategy_type,
    v_long.underlying_listing_id, v_long.expires_on, p_contracts, v_long.contract_multiplier,
    v_debit, v_max_loss, v_max_profit, v_max_loss,
    v_break_even, v_profit_potential
  ) returning id into v_strategy_id;

  insert into public.options_paper_legs (
    strategy_id, contract_id, side, opening_price, protective_long_leg_required
  ) values (v_strategy_id, v_long.id, 'long', v_long.ask, false);
  if v_short.id is not null then
    insert into public.options_paper_legs (
      strategy_id, contract_id, side, opening_price, protective_long_leg_required
    ) values (v_strategy_id, v_short.id, 'short', v_short.bid, true);
  end if;

  update public.options_paper_accounts
  set cash_balance = cash_balance - v_max_loss
  where portfolio_id = p_portfolio_id;

  insert into public.options_paper_journal_entries (
    user_id, portfolio_id, strategy_id, entry_type, correlation_id
  ) values (
    p_user_id, p_portfolio_id, v_strategy_id, 'strategy_open', p_client_strategy_id
  ) returning id into v_journal_id;
  insert into public.options_paper_journal_lines (journal_entry_id, account_code, amount)
  values
    (v_journal_id, 'virtual_cash', -v_max_loss),
    (v_journal_id, 'option_premium_asset', v_max_loss);

  return jsonb_build_object(
    'status', 'open', 'strategyId', v_strategy_id,
    'maxLoss', v_max_loss, 'maxProfit', v_max_profit,
    'breakEvenPrice', v_break_even, 'idempotentReplay', false
  );
end;
$$;

create or replace function public.simulate_options_paper_event(
  p_user_id uuid,
  p_portfolio_id uuid,
  p_strategy_id uuid,
  p_client_event_id text,
  p_event_type text,
  p_settlement_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_strategy public.options_paper_strategies%rowtype;
  v_existing uuid;
  v_event_id uuid;
  v_journal_id uuid;
  v_payoff_per_share numeric(24,8) := 0;
  v_cash_effect numeric(24,8) := 0;
  v_realized_pnl numeric(24,8);
  v_status text;
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Options paper events require the simulation service';
  end if;
  if char_length(coalesce(p_client_event_id, '')) not between 8 and 100
    or p_event_type not in ('expiration', 'exercise', 'assignment', 'early_assignment', 'corporate_action') then
    raise exception 'Invalid options paper event';
  end if;

  select id into v_existing from public.options_paper_events
  where user_id = p_user_id and client_event_id = p_client_event_id;
  if v_existing is not null then
    return jsonb_build_object('status', 'recorded', 'eventId', v_existing, 'idempotentReplay', true);
  end if;

  select * into v_strategy from public.options_paper_strategies
  where id = p_strategy_id and portfolio_id = p_portfolio_id and user_id = p_user_id for update;
  if v_strategy.id is null or v_strategy.lifecycle_status not in ('open', 'adjusted') then
    raise exception 'Options paper strategy is unavailable';
  end if;

  if p_event_type = 'corporate_action' then
    insert into public.options_paper_events (
      user_id, portfolio_id, strategy_id, client_event_id, event_type,
      settlement_price, cash_effect, event_note
    ) values (
      p_user_id, p_portfolio_id, p_strategy_id, p_client_event_id,
      p_event_type, null, 0, 'Deterministic corporate-action adjustment rehearsal; no real contract or position changed.'
    ) returning id into v_event_id;
    update public.options_paper_strategies set lifecycle_status = 'adjusted'
    where id = p_strategy_id;
    return jsonb_build_object('status', 'adjusted', 'eventId', v_event_id, 'cashEffect', 0, 'idempotentReplay', false);
  end if;

  if p_settlement_price is null or p_settlement_price < 0 then
    raise exception 'A non-negative scenario settlement price is required';
  end if;
  if p_event_type in ('assignment', 'early_assignment') and not exists (
    select 1 from public.options_paper_legs where strategy_id = p_strategy_id and side = 'short'
  ) then
    raise exception 'Assignment requires a protected short leg';
  end if;

  select coalesce(sum(
    (case
      when chain.option_type = 'call' then greatest(p_settlement_price - chain.strike, 0)
      else greatest(chain.strike - p_settlement_price, 0)
    end)
    * case when leg.side = 'long' then leg.ratio else -leg.ratio end
  ), 0)
  into v_payoff_per_share
  from public.options_paper_legs leg
  join public.options_chain_scenarios chain on chain.id = leg.contract_id
  where leg.strategy_id = p_strategy_id;

  v_cash_effect := greatest(v_payoff_per_share * v_strategy.contract_multiplier * v_strategy.contracts, 0);
  v_realized_pnl := v_cash_effect - v_strategy.max_loss;
  v_status := case p_event_type
    when 'expiration' then 'expired'
    when 'exercise' then 'exercised'
    when 'assignment' then 'assigned'
    when 'early_assignment' then 'early_assigned'
  end;

  insert into public.options_paper_events (
    user_id, portfolio_id, strategy_id, client_event_id, event_type,
    settlement_price, cash_effect, realized_pnl, event_note
  ) values (
    p_user_id, p_portfolio_id, p_strategy_id, p_client_event_id,
    p_event_type, p_settlement_price, v_cash_effect, v_realized_pnl,
    'Deterministic options lifecycle rehearsal with virtual cash settlement only.'
  ) returning id into v_event_id;

  if v_cash_effect > 0 then
    update public.options_paper_accounts set cash_balance = cash_balance + v_cash_effect
    where portfolio_id = p_portfolio_id and user_id = p_user_id;
    insert into public.options_paper_journal_entries (
      user_id, portfolio_id, strategy_id, event_id, entry_type, correlation_id
    ) values (
      p_user_id, p_portfolio_id, p_strategy_id, v_event_id,
      'virtual_settlement', p_client_event_id
    ) returning id into v_journal_id;
    insert into public.options_paper_journal_lines (journal_entry_id, account_code, amount)
    values
      (v_journal_id, 'virtual_cash', v_cash_effect),
      (v_journal_id, 'option_settlement', -v_cash_effect);
  end if;

  update public.options_paper_strategies
  set lifecycle_status = v_status, realized_pnl = v_realized_pnl
  where id = p_strategy_id;

  return jsonb_build_object(
    'status', v_status, 'eventId', v_event_id,
    'cashEffect', v_cash_effect, 'realizedPnl', v_realized_pnl,
    'idempotentReplay', false
  );
end;
$$;

create or replace function public.reconcile_options_paper_portfolio(
  p_user_id uuid,
  p_portfolio_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_unbalanced integer;
  v_uncovered integer;
  v_risk integer;
  v_cash integer;
  v_status text;
  v_expected numeric(24,8);
  v_actual numeric(24,8);
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Options reconciliation requires the simulation service';
  end if;
  select cash_balance, starting_cash into v_actual, v_expected
  from public.options_paper_accounts
  where portfolio_id = p_portfolio_id and user_id = p_user_id;
  if v_actual is null then raise exception 'Options paper account is unavailable'; end if;

  select count(*)::integer into v_unbalanced from (
    select line.journal_entry_id
    from public.options_paper_journal_lines line
    join public.options_paper_journal_entries journal on journal.id = line.journal_entry_id
    where journal.portfolio_id = p_portfolio_id and journal.user_id = p_user_id
    group by line.journal_entry_id, line.currency
    having abs(sum(line.amount)) > 0.00000001
  ) exceptions;

  select count(*)::integer into v_uncovered
  from public.options_paper_strategies strategy
  where strategy.portfolio_id = p_portfolio_id and strategy.user_id = p_user_id
    and exists (select 1 from public.options_paper_legs where strategy_id = strategy.id and side = 'short')
    and not exists (select 1 from public.options_paper_legs where strategy_id = strategy.id and side = 'long');

  select count(*)::integer into v_risk
  from public.options_paper_strategies
  where portfolio_id = p_portfolio_id and user_id = p_user_id
    and (not defined_risk or loss_risk <> 'bounded' or max_loss is null
      or collateral_amount < max_loss
      or (profit_potential = 'unbounded' and strategy_type <> 'long_call'));

  v_expected := v_expected
    - coalesce((select sum(max_loss) from public.options_paper_strategies
      where portfolio_id = p_portfolio_id and user_id = p_user_id), 0)
    + coalesce((select sum(cash_effect) from public.options_paper_events
      where portfolio_id = p_portfolio_id and user_id = p_user_id), 0);
  v_cash := case when abs(v_expected - v_actual) > 0.00000001 then 1 else 0 end;
  v_status := case when v_unbalanced + v_uncovered + v_risk + v_cash = 0 then 'passed' else 'exception' end;

  insert into public.options_paper_reconciliations (
    user_id, portfolio_id, status, unbalanced_journals,
    uncovered_short_legs, risk_boundary_exceptions, cash_mismatches
  ) values (
    p_user_id, p_portfolio_id, v_status, v_unbalanced,
    v_uncovered, v_risk, v_cash
  );
  return jsonb_build_object(
    'status', v_status, 'unbalancedJournals', v_unbalanced,
    'uncoveredShortLegs', v_uncovered, 'riskBoundaryExceptions', v_risk,
    'cashMismatches', v_cash
  );
end;
$$;

revoke all on function public.initialize_options_paper_account(uuid, uuid, numeric, text, text, text, text) from public, anon, authenticated;
revoke all on function public.create_options_paper_strategy(uuid, uuid, text, text, bigint, bigint, integer) from public, anon, authenticated;
revoke all on function public.simulate_options_paper_event(uuid, uuid, uuid, text, text, numeric) from public, anon, authenticated;
revoke all on function public.reconcile_options_paper_portfolio(uuid, uuid) from public, anon, authenticated;
grant execute on function public.initialize_options_paper_account(uuid, uuid, numeric, text, text, text, text) to service_role;
grant execute on function public.create_options_paper_strategy(uuid, uuid, text, text, bigint, bigint, integer) to service_role;
grant execute on function public.simulate_options_paper_event(uuid, uuid, uuid, text, text, numeric) to service_role;
grant execute on function public.reconcile_options_paper_portfolio(uuid, uuid) to service_role;

do $$
begin
  if exists (
    select 1 from public.options_paper_controls
    where live_market_data_enabled or live_options_routing_enabled
      or broker_connectivity_enabled or real_customer_funds_enabled
      or real_positions_enabled or custody_enabled or real_settlement_enabled
      or margin_enabled or uncovered_short_options_enabled
      or automatic_options_permission_enabled
  ) then
    raise exception 'Phase 8C options controls must remain fail-closed';
  end if;
  if to_regclass('public.live_options_orders') is not null
    or to_regclass('public.options_margin_accounts') is not null
    or to_regprocedure('public.route_live_options_order(jsonb)') is not null then
    raise exception 'Phase 8C cannot deploy with a live options execution path';
  end if;
end;
$$;

comment on table public.options_paper_controls is 'Phase 8C education and defined-risk simulation controls. Live options, margin and uncovered short options remain false.';
comment on table public.options_chain_scenarios is 'Deterministic educational option-chain fixtures; not live, delayed or executable quotes.';
comment on table public.options_paper_appropriateness_profiles is 'Private education assessment. It never grants options permission and forecast confidence cannot override it.';
comment on table public.options_paper_strategies is 'Single-leg long options and protected defined-risk spreads only; no live position is created.';
comment on function public.create_options_paper_strategy is 'Service-only defined-risk paper strategy builder with no broker, HTTP or live routing path.';
