-- TradePulse AI
-- Migration 048: Phase 8D global brokerage and custody orchestration
-- This is a fail-closed orchestration and rehearsal layer. It creates no live
-- broker, exchange, clearing, custody, market-data, funding or settlement path.

create table public.global_brokerage_custody_controls (
  control_key text primary key check (control_key = 'global-brokerage-custody'),
  orchestration_workspace_enabled boolean not null default true check (orchestration_workspace_enabled),
  launch_matrix_review_enabled boolean not null default true check (launch_matrix_review_enabled),
  onboarding_rehearsal_enabled boolean not null default true check (onboarding_rehearsal_enabled),
  non_executable_preview_enabled boolean not null default true check (non_executable_preview_enabled),
  reconciliation_rehearsal_enabled boolean not null default true check (reconciliation_rehearsal_enabled),
  activation_status text not null default 'blocked' check (activation_status = 'blocked'),
  live_broker_connectivity_enabled boolean not null default false check (not live_broker_connectivity_enabled),
  exchange_connectivity_enabled boolean not null default false check (not exchange_connectivity_enabled),
  clearing_connectivity_enabled boolean not null default false check (not clearing_connectivity_enabled),
  custody_accounts_enabled boolean not null default false check (not custody_accounts_enabled),
  customer_asset_safeguarding_enabled boolean not null default false check (not customer_asset_safeguarding_enabled),
  real_cash_ledger_enabled boolean not null default false check (not real_cash_ledger_enabled),
  real_position_ledger_enabled boolean not null default false check (not real_position_ledger_enabled),
  settlement_instructions_enabled boolean not null default false check (not settlement_instructions_enabled),
  market_data_credentials_enabled boolean not null default false check (not market_data_credentials_enabled),
  cross_border_funding_link_enabled boolean not null default false check (not cross_border_funding_link_enabled),
  live_order_routing_enabled boolean not null default false check (not live_order_routing_enabled),
  automatic_activation_enabled boolean not null default false check (not automatic_activation_enabled),
  manual_activation_review_required boolean not null default true check (manual_activation_review_required),
  policy_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.global_brokerage_partner_roles (
  role_key text primary key check (role_key in ('broker', 'exchange', 'clearing', 'custody', 'market_data')),
  display_name text not null,
  responsibility_summary text not null,
  assignment_status text not null default 'unassigned' check (assignment_status = 'unassigned'),
  due_diligence_status text not null default 'not_started' check (due_diligence_status = 'not_started'),
  credential_status text not null default 'absent' check (credential_status = 'absent'),
  production_enabled boolean not null default false check (not production_enabled),
  partner_identifier text,
  policy_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (partner_identifier is null)
);

create table public.global_brokerage_launch_matrix (
  id bigint generated by default as identity primary key,
  matrix_code text not null unique check (matrix_code ~ '^[A-Z0-9:_-]{8,80}$'),
  residency_country text not null references public.jurisdictions(country_code),
  execution_jurisdiction text not null references public.jurisdictions(country_code),
  customer_type text not null check (customer_type in ('individual', 'business')),
  investor_type text not null check (investor_type in ('retail', 'professional', 'institutional')),
  account_type text not null default 'cash' check (account_type = 'cash'),
  asset_class text not null check (asset_class in ('equity', 'etf', 'depositary_receipt')),
  venue_id bigint not null references public.global_market_venues(id),
  settlement_currency text not null check (settlement_currency ~ '^[A-Z]{3}$'),
  matrix_status text not null default 'blocked' check (matrix_status = 'blocked'),
  legal_approval_status text not null default 'missing' check (legal_approval_status = 'missing'),
  compliance_approval_status text not null default 'missing' check (compliance_approval_status = 'missing'),
  tax_approval_status text not null default 'missing' check (tax_approval_status = 'missing'),
  market_data_approval_status text not null default 'missing' check (market_data_approval_status = 'missing'),
  broker_approval_status text not null default 'missing' check (broker_approval_status = 'missing'),
  custody_approval_status text not null default 'missing' check (custody_approval_status = 'missing'),
  security_approval_status text not null default 'missing' check (security_approval_status = 'missing'),
  operations_approval_status text not null default 'missing' check (operations_approval_status = 'missing'),
  broker_assigned boolean not null default false check (not broker_assigned),
  exchange_access_assigned boolean not null default false check (not exchange_access_assigned),
  clearing_partner_assigned boolean not null default false check (not clearing_partner_assigned),
  custody_partner_assigned boolean not null default false check (not custody_partner_assigned),
  market_data_partner_assigned boolean not null default false check (not market_data_partner_assigned),
  onboarding_supported boolean not null default false check (not onboarding_supported),
  preview_rehearsal_supported boolean not null default true check (preview_rehearsal_supported),
  live_execution_enabled boolean not null default false check (not live_execution_enabled),
  source_name text not null,
  source_as_of date not null,
  matrix_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (residency_country, execution_jurisdiction, customer_type, investor_type, account_type, asset_class, venue_id)
);

create table public.global_brokerage_onboarding_requirements (
  requirement_key text primary key check (requirement_key ~ '^[a-z][a-z0-9_]{2,63}$'),
  domain text not null check (domain in ('identity', 'compliance', 'tax', 'customer', 'market_data', 'broker', 'custody', 'settlement')),
  title text not null check (char_length(title) between 3 and 120),
  summary text not null check (char_length(summary) between 10 and 500),
  identity_bound boolean not null default true check (identity_bound),
  evidence_expires boolean not null default true check (evidence_expires),
  raw_evidence_storage_enabled boolean not null default false check (not raw_evidence_storage_enabled),
  activation_blocking boolean not null default true check (activation_blocking),
  display_order integer not null unique check (display_order between 1 and 100),
  requirement_version text not null,
  created_at timestamptz not null default now()
);

create table public.global_brokerage_onboarding_cases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  client_case_id text not null check (char_length(client_case_id) between 8 and 100),
  launch_matrix_id bigint not null references public.global_brokerage_launch_matrix(id),
  base_currency text not null check (base_currency ~ '^[A-Z]{3}$'),
  case_status text not null default 'review_only' check (case_status = 'review_only'),
  evidence_status text not null default 'missing' check (evidence_status = 'missing'),
  activation_status text not null default 'blocked' check (activation_status = 'blocked'),
  identity_bound boolean not null default true check (identity_bound),
  simulation_only boolean not null default true check (simulation_only),
  live_brokerage_account_created boolean not null default false check (not live_brokerage_account_created),
  custody_account_created boolean not null default false check (not custody_account_created),
  funding_account_linked boolean not null default false check (not funding_account_linked),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  created_at timestamptz not null default now(),
  unique (user_id, client_case_id),
  check (expires_at > created_at)
);

create table public.global_brokerage_evidence_rehearsals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  onboarding_case_id uuid not null references public.global_brokerage_onboarding_cases(id) on delete cascade,
  client_evidence_id text not null check (char_length(client_evidence_id) between 8 and 100),
  requirement_key text not null references public.global_brokerage_onboarding_requirements(requirement_key),
  evidence_status text not null default 'rehearsal_recorded' check (evidence_status = 'rehearsal_recorded'),
  evidence_digest text not null check (evidence_digest ~ '^[0-9a-f]{64}$'),
  identity_bound boolean not null default true check (identity_bound),
  raw_evidence_stored boolean not null default false check (not raw_evidence_stored),
  simulation_only boolean not null default true check (simulation_only),
  approval_effect boolean not null default false check (not approval_effect),
  observed_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (user_id, client_evidence_id),
  unique (onboarding_case_id, requirement_key, evidence_digest),
  check (expires_at > observed_at)
);

create table public.global_brokerage_order_previews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  onboarding_case_id uuid not null references public.global_brokerage_onboarding_cases(id) on delete cascade,
  client_preview_id text not null check (char_length(client_preview_id) between 8 and 100),
  listing_id bigint not null references public.global_instrument_listings(id),
  side text not null check (side in ('buy', 'sell')),
  order_type text not null check (order_type in ('market', 'limit')),
  quantity numeric(24,8) not null check (quantity > 0 and quantity <= 1000000),
  limit_price numeric(20,8) check (limit_price is null or limit_price > 0),
  scenario_price numeric(20,8) not null check (scenario_price > 0),
  gross_notional numeric(24,8) not null check (gross_notional > 0),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  fx_rate_to_base numeric(24,10) not null check (fx_rate_to_base > 0),
  base_currency text not null check (base_currency ~ '^[A-Z]{3}$'),
  commission_amount numeric(24,8) not null check (commission_amount >= 0),
  venue_fee_amount numeric(24,8) not null check (venue_fee_amount >= 0),
  estimated_tax_amount numeric(24,8),
  tax_status text not null check (tax_status in ('modeled_scenario', 'unavailable')),
  estimated_total_base numeric(24,8) check (estimated_total_base is null or estimated_total_base > 0),
  buying_power_status text not null default 'unavailable' check (buying_power_status = 'unavailable'),
  buying_power_amount numeric(24,8),
  settlement_currency text not null check (settlement_currency ~ '^[A-Z]{3}$'),
  route_status text not null default 'unavailable' check (route_status = 'unavailable'),
  route_option_count integer not null default 0 check (route_option_count = 0),
  route_evidence jsonb not null check (jsonb_typeof(route_evidence) = 'array' and jsonb_array_length(route_evidence) > 0),
  funding_source_type text not null default 'separate_unconnected' check (funding_source_type = 'separate_unconnected'),
  cross_border_payment_linked boolean not null default false check (not cross_border_payment_linked),
  consent_status text not null default 'not_authorized' check (consent_status = 'not_authorized'),
  preview_status text not null default 'blocked' check (preview_status = 'blocked'),
  executable boolean not null default false check (not executable),
  partner_instruction_created boolean not null default false check (not partner_instruction_created),
  source_type text not null default 'deterministic_fixture' check (source_type = 'deterministic_fixture'),
  block_reasons jsonb not null check (jsonb_typeof(block_reasons) = 'array' and jsonb_array_length(block_reasons) > 0),
  policy_version text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, client_preview_id),
  check (order_type <> 'limit' or limit_price is not null),
  check (buying_power_amount is null),
  check ((tax_status = 'unavailable' and estimated_tax_amount is null) or (tax_status = 'modeled_scenario' and estimated_tax_amount is not null)),
  check (expires_at > created_at)
);

create table public.global_brokerage_reconciliation_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  onboarding_case_id uuid not null references public.global_brokerage_onboarding_cases(id) on delete cascade,
  client_reconciliation_id text not null check (char_length(client_reconciliation_id) between 8 and 100),
  reconciliation_status text not null default 'not_ready' check (reconciliation_status = 'not_ready'),
  domain_count integer not null default 5 check (domain_count = 5),
  blocking_domain_count integer not null default 5 check (blocking_domain_count = 5),
  partner_statement_count integer not null default 0 check (partner_statement_count = 0),
  signed_event_count integer not null default 0 check (signed_event_count = 0),
  production_effect boolean not null default false check (not production_effect),
  reconciliation_version text not null,
  created_at timestamptz not null default now(),
  unique (user_id, client_reconciliation_id)
);

create table public.global_brokerage_reconciliation_items (
  id bigint generated by default as identity primary key,
  reconciliation_run_id uuid not null references public.global_brokerage_reconciliation_runs(id) on delete cascade,
  domain text not null check (domain in ('order', 'allocation', 'cash', 'custody', 'settlement')),
  source_status text not null default 'unavailable' check (source_status = 'unavailable'),
  mismatch_count integer not null default 1 check (mismatch_count = 1),
  blocking boolean not null default true check (blocking),
  detail text not null,
  created_at timestamptz not null default now(),
  unique (reconciliation_run_id, domain)
);

create index idx_global_brokerage_matrix_scope
  on public.global_brokerage_launch_matrix(residency_country, venue_id, asset_class);
create index idx_global_brokerage_cases_user_created
  on public.global_brokerage_onboarding_cases(user_id, created_at desc);
create index idx_global_brokerage_evidence_case_created
  on public.global_brokerage_evidence_rehearsals(onboarding_case_id, created_at desc);
create index idx_global_brokerage_evidence_user_created
  on public.global_brokerage_evidence_rehearsals(user_id, created_at desc);
create index idx_global_brokerage_evidence_case_expiry
  on public.global_brokerage_evidence_rehearsals(onboarding_case_id, expires_at desc, requirement_key);
create index idx_global_brokerage_previews_case_created
  on public.global_brokerage_order_previews(onboarding_case_id, created_at desc);
create index idx_global_brokerage_previews_user_created
  on public.global_brokerage_order_previews(user_id, created_at desc);
create index idx_global_brokerage_reconciliation_case_created
  on public.global_brokerage_reconciliation_runs(onboarding_case_id, created_at desc);
create index idx_global_brokerage_reconciliation_user_created
  on public.global_brokerage_reconciliation_runs(user_id, created_at desc);

alter table public.global_brokerage_custody_controls enable row level security;
alter table public.global_brokerage_partner_roles enable row level security;
alter table public.global_brokerage_launch_matrix enable row level security;
alter table public.global_brokerage_onboarding_requirements enable row level security;
alter table public.global_brokerage_onboarding_cases enable row level security;
alter table public.global_brokerage_evidence_rehearsals enable row level security;
alter table public.global_brokerage_order_previews enable row level security;
alter table public.global_brokerage_reconciliation_runs enable row level security;
alter table public.global_brokerage_reconciliation_items enable row level security;

create policy "Public reads global brokerage locks"
  on public.global_brokerage_custody_controls for select to anon, authenticated using (true);
create policy "Public reads unassigned partner roles"
  on public.global_brokerage_partner_roles for select to anon, authenticated using (true);
create policy "Public reads blocked launch matrix"
  on public.global_brokerage_launch_matrix for select to anon, authenticated using (true);
create policy "Public reads onboarding requirement catalog"
  on public.global_brokerage_onboarding_requirements for select to anon, authenticated using (true);
create policy "Users read their global brokerage cases"
  on public.global_brokerage_onboarding_cases for select to authenticated using (user_id = auth.uid());
create policy "Users read their evidence rehearsals"
  on public.global_brokerage_evidence_rehearsals for select to authenticated using (user_id = auth.uid());
create policy "Users read their blocked global previews"
  on public.global_brokerage_order_previews for select to authenticated using (user_id = auth.uid());
create policy "Users read their global reconciliation runs"
  on public.global_brokerage_reconciliation_runs for select to authenticated using (user_id = auth.uid());
create policy "Users read their global reconciliation items"
  on public.global_brokerage_reconciliation_items for select to authenticated using (
    exists (
      select 1 from public.global_brokerage_reconciliation_runs run
      where run.id = global_brokerage_reconciliation_items.reconciliation_run_id
        and run.user_id = auth.uid()
    )
  );

create trigger global_brokerage_controls_set_updated_at before update on public.global_brokerage_custody_controls
  for each row execute function public.set_updated_at();
create trigger global_brokerage_partner_roles_set_updated_at before update on public.global_brokerage_partner_roles
  for each row execute function public.set_updated_at();
create trigger global_brokerage_launch_matrix_set_updated_at before update on public.global_brokerage_launch_matrix
  for each row execute function public.set_updated_at();

insert into public.global_brokerage_custody_controls (control_key, policy_version)
values ('global-brokerage-custody', 'global-brokerage-custody-v1');

insert into public.global_brokerage_partner_roles (
  role_key, display_name, responsibility_summary, policy_version
) values
  ('broker', 'Broker role unassigned', 'Future account carrying, order acceptance and customer protection responsibilities require a named approved broker.', 'global-partner-role-v1'),
  ('exchange', 'Exchange access role unassigned', 'Future venue access must be evidenced separately for each exact market and product.', 'global-partner-role-v1'),
  ('clearing', 'Clearing role unassigned', 'Future clearing, failed-trade and allocation responsibilities require a named approved clearing partner.', 'global-partner-role-v1'),
  ('custody', 'Custody role unassigned', 'Future segregation, safeguarding, books and records require a named approved custodian.', 'global-partner-role-v1'),
  ('market_data', 'Market-data role unassigned', 'Future realtime display and execution use require licensed entitlements and protected server credentials.', 'global-partner-role-v1');

insert into public.global_brokerage_launch_matrix (
  matrix_code, residency_country, execution_jurisdiction, customer_type,
  investor_type, account_type, asset_class, venue_id, settlement_currency,
  source_name, source_as_of, matrix_version
) values
  ('IN:XNSE:CASH:EQUITY', 'IN', 'IN', 'individual', 'retail', 'cash', 'equity', (select id from public.global_market_venues where mic_code = 'XNSE'), 'INR', 'Deterministic Phase 8D policy scenario', date '2026-09-09', 'global-launch-matrix-v1'),
  ('GB:XLON:CASH:EQUITY', 'GB', 'GB', 'individual', 'retail', 'cash', 'equity', (select id from public.global_market_venues where mic_code = 'XLON'), 'GBP', 'Deterministic Phase 8D policy scenario', date '2026-09-09', 'global-launch-matrix-v1'),
  ('US:XNAS:CASH:EQUITY', 'US', 'US', 'individual', 'retail', 'cash', 'equity', (select id from public.global_market_venues where mic_code = 'XNAS'), 'USD', 'Deterministic Phase 8D policy scenario', date '2026-09-09', 'global-launch-matrix-v1'),
  ('DE:XETR:CASH:ETF', 'DE', 'DE', 'individual', 'retail', 'cash', 'etf', (select id from public.global_market_venues where mic_code = 'XETR'), 'EUR', 'Deterministic Phase 8D policy scenario', date '2026-09-09', 'global-launch-matrix-v1');

insert into public.global_brokerage_onboarding_requirements (
  requirement_key, domain, title, summary, display_order, requirement_version
) values
  ('identity_kyc_kyb', 'identity', 'Identity and KYC/KYB', 'Identity, beneficial-owner and business verification must bind to the exact customer and expire under policy.', 1, 'global-onboarding-v1'),
  ('aml_sanctions', 'compliance', 'AML and sanctions', 'Sanctions, PEP, adverse-media and AML evidence must be current for the exact customer and launch scope.', 2, 'global-onboarding-v1'),
  ('tax_forms', 'tax', 'Tax forms', 'Residency and market-specific tax documentation must be reviewed without treating an unknown tax as zero.', 3, 'global-onboarding-v1'),
  ('risk_disclosures', 'customer', 'Risk disclosures', 'The exact product, market, fee, execution, custody and conflict disclosures must be versioned and acknowledged.', 4, 'global-onboarding-v1'),
  ('appropriateness_suitability', 'compliance', 'Appropriateness and suitability', 'Product governance must independently assess customer experience, objectives and loss tolerance.', 5, 'global-onboarding-v1'),
  ('customer_agreement', 'customer', 'Customer agreement', 'A jurisdiction-specific brokerage and custody agreement must be identity-bound and current.', 6, 'global-onboarding-v1'),
  ('market_data_subscription', 'market_data', 'Market-data subscription', 'Display and execution-use entitlements must be approved separately for the exact venue and audience.', 7, 'global-onboarding-v1'),
  ('broker_account', 'broker', 'Broker account', 'A named regulated broker must approve the exact account type and customer residency.', 8, 'global-onboarding-v1'),
  ('safeguarding_custody', 'custody', 'Safeguarding and custody', 'Customer assets, segregation, statements and books-and-records responsibilities must be approved.', 9, 'global-onboarding-v1'),
  ('settlement_clearing', 'settlement', 'Settlement and clearing', 'Settlement currency, clearing, allocation, failed-trade and recovery ownership must be approved.', 10, 'global-onboarding-v1');

revoke all on table public.global_brokerage_custody_controls,
  public.global_brokerage_partner_roles, public.global_brokerage_launch_matrix,
  public.global_brokerage_onboarding_requirements from anon, authenticated, service_role;
grant select on table public.global_brokerage_custody_controls,
  public.global_brokerage_partner_roles, public.global_brokerage_launch_matrix,
  public.global_brokerage_onboarding_requirements to anon, authenticated;

revoke all on table public.global_brokerage_onboarding_cases,
  public.global_brokerage_evidence_rehearsals, public.global_brokerage_order_previews,
  public.global_brokerage_reconciliation_runs, public.global_brokerage_reconciliation_items
  from anon, authenticated, service_role;
grant select on table public.global_brokerage_onboarding_cases,
  public.global_brokerage_evidence_rehearsals, public.global_brokerage_order_previews,
  public.global_brokerage_reconciliation_runs, public.global_brokerage_reconciliation_items
  to authenticated;

create view public.global_brokerage_launch_matrix_catalog
with (security_invoker = true)
as
select matrix.id as launch_matrix_id, matrix.matrix_code,
  matrix.residency_country, matrix.execution_jurisdiction,
  matrix.customer_type, matrix.investor_type, matrix.account_type,
  matrix.asset_class, venue.mic_code, venue.venue_name,
  matrix.settlement_currency, matrix.matrix_status,
  matrix.legal_approval_status, matrix.compliance_approval_status,
  matrix.tax_approval_status, matrix.market_data_approval_status,
  matrix.broker_approval_status, matrix.custody_approval_status,
  matrix.security_approval_status, matrix.operations_approval_status,
  8::integer as approval_gap_count,
  5::integer as partner_gap_count,
  (select count(*)::integer from public.global_brokerage_onboarding_requirements) as onboarding_requirement_count,
  false as onboarding_supported, true as preview_rehearsal_supported,
  false as live_execution_enabled, false as broker_connectivity_enabled,
  false as custody_enabled, false as settlement_enabled,
  false as cross_border_funding_link_enabled,
  matrix.source_name, matrix.source_as_of, matrix.matrix_version
from public.global_brokerage_launch_matrix matrix
join public.global_market_venues venue on venue.id = matrix.venue_id;

create view public.global_brokerage_orchestration_summary
with (security_invoker = true)
as
select control.policy_version,
  (select count(*)::integer from public.global_brokerage_launch_matrix) as launch_matrix_count,
  (select count(*)::integer from public.global_brokerage_launch_matrix where matrix_status = 'blocked') as blocked_matrix_count,
  (select count(*)::integer from public.global_brokerage_partner_roles) as partner_role_count,
  (select count(*)::integer from public.global_brokerage_partner_roles where assignment_status = 'unassigned') as unassigned_partner_role_count,
  (select count(*)::integer from public.global_brokerage_onboarding_requirements) as onboarding_requirement_count,
  control.activation_status, control.manual_activation_review_required,
  false as live_broker_connectivity_enabled, false as custody_accounts_enabled,
  false as real_cash_ledger_enabled, false as real_position_ledger_enabled,
  false as settlement_instructions_enabled, false as cross_border_funding_link_enabled,
  false as live_order_routing_enabled, false as automatic_activation_enabled
from public.global_brokerage_custody_controls control
where control.control_key = 'global-brokerage-custody';

create view public.global_brokerage_onboarding_progress
with (security_invoker = true)
as
select case_record.id, case_record.user_id, case_record.client_case_id,
  case_record.launch_matrix_id, matrix.matrix_code, matrix.residency_country,
  matrix.asset_class, venue.mic_code, case_record.base_currency,
  case_record.case_status, case_record.evidence_status,
  case_record.activation_status, case_record.expires_at, case_record.created_at,
  (select count(*)::integer from public.global_brokerage_onboarding_requirements) as requirement_count,
  (select count(distinct rehearsal.requirement_key)::integer
    from public.global_brokerage_evidence_rehearsals rehearsal
    where rehearsal.onboarding_case_id = case_record.id
      and rehearsal.expires_at > now()) as rehearsed_requirement_count,
  (select count(*)::integer from public.global_brokerage_onboarding_requirements) as blocking_requirement_count,
  false as live_brokerage_account_created, false as custody_account_created,
  false as funding_account_linked
from public.global_brokerage_onboarding_cases case_record
join public.global_brokerage_launch_matrix matrix on matrix.id = case_record.launch_matrix_id
join public.global_market_venues venue on venue.id = matrix.venue_id;

create view public.global_brokerage_preview_history
with (security_invoker = true)
as
select preview.id, preview.user_id, preview.onboarding_case_id,
  preview.client_preview_id, listing.listing_key, listing.display_symbol,
  listing.instrument_name, venue.mic_code, preview.side, preview.order_type,
  preview.quantity, preview.limit_price, preview.scenario_price,
  preview.gross_notional, preview.quote_currency, preview.fx_rate_to_base,
  preview.base_currency, preview.commission_amount, preview.venue_fee_amount,
  preview.estimated_tax_amount, preview.tax_status, preview.estimated_total_base,
  preview.buying_power_status, preview.buying_power_amount,
  preview.settlement_currency, preview.route_status, preview.route_option_count,
  preview.route_evidence, preview.funding_source_type,
  preview.cross_border_payment_linked, preview.consent_status,
  preview.preview_status, preview.executable, preview.partner_instruction_created,
  preview.block_reasons, preview.expires_at, preview.created_at
from public.global_brokerage_order_previews preview
join public.global_instrument_listings listing on listing.id = preview.listing_id
join public.global_market_venues venue on venue.id = listing.venue_id;

create view public.global_brokerage_reconciliation_history
with (security_invoker = true)
as
select run.id, run.user_id, run.onboarding_case_id,
  run.client_reconciliation_id, run.reconciliation_status,
  run.domain_count, run.blocking_domain_count, run.partner_statement_count,
  run.signed_event_count, run.production_effect, run.reconciliation_version,
  run.created_at,
  coalesce(jsonb_agg(jsonb_build_object(
    'domain', item.domain, 'sourceStatus', item.source_status,
    'mismatchCount', item.mismatch_count, 'blocking', item.blocking,
    'detail', item.detail
  ) order by item.domain) filter (where item.id is not null), '[]'::jsonb) as items
from public.global_brokerage_reconciliation_runs run
left join public.global_brokerage_reconciliation_items item
  on item.reconciliation_run_id = run.id
group by run.id;

grant select on public.global_brokerage_launch_matrix_catalog,
  public.global_brokerage_orchestration_summary to anon, authenticated;
grant select on public.global_brokerage_onboarding_progress,
  public.global_brokerage_preview_history,
  public.global_brokerage_reconciliation_history to authenticated;

create or replace function public.prevent_global_brokerage_orchestration_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Global brokerage orchestration evidence is append-only';
end;
$$;

revoke all on function public.prevent_global_brokerage_orchestration_mutation()
  from public, anon, authenticated;

create trigger global_brokerage_evidence_append_only
  before update or delete on public.global_brokerage_evidence_rehearsals
  for each row execute function public.prevent_global_brokerage_orchestration_mutation();
create trigger global_brokerage_preview_append_only
  before update or delete on public.global_brokerage_order_previews
  for each row execute function public.prevent_global_brokerage_orchestration_mutation();
create trigger global_brokerage_reconciliation_append_only
  before update or delete on public.global_brokerage_reconciliation_runs
  for each row execute function public.prevent_global_brokerage_orchestration_mutation();
create trigger global_brokerage_reconciliation_items_append_only
  before update or delete on public.global_brokerage_reconciliation_items
  for each row execute function public.prevent_global_brokerage_orchestration_mutation();

create or replace function public.initialize_global_brokerage_case(
  p_user_id uuid,
  p_client_case_id text,
  p_launch_matrix_id bigint,
  p_base_currency text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.global_brokerage_onboarding_cases%rowtype;
  v_case public.global_brokerage_onboarding_cases%rowtype;
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Global brokerage cases require the orchestration service';
  end if;
  if char_length(coalesce(p_client_case_id, '')) not between 8 and 100
    or p_base_currency !~ '^[A-Z]{3}$' then
    raise exception 'Invalid global brokerage case';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_user_id::text || ':' || p_client_case_id, 0)
  );
  select * into v_existing from public.global_brokerage_onboarding_cases
  where user_id = p_user_id and client_case_id = p_client_case_id;
  if v_existing.id is not null then
    if v_existing.launch_matrix_id <> p_launch_matrix_id
      or v_existing.base_currency <> p_base_currency then
      raise exception 'Global brokerage case id was reused with different input';
    end if;
    return jsonb_build_object('status', 'review_only', 'caseId', v_existing.id,
      'activationStatus', 'blocked', 'idempotentReplay', true);
  end if;

  if not exists (
    select 1 from public.global_brokerage_launch_matrix
    where id = p_launch_matrix_id and matrix_status = 'blocked'
      and preview_rehearsal_supported and not onboarding_supported
      and not live_execution_enabled
  ) then
    raise exception 'Global brokerage launch matrix is unavailable';
  end if;
  if not exists (select 1 from public.international_paper_fx_rates where currency_code = p_base_currency) then
    raise exception 'Base currency scenario is unavailable';
  end if;

  insert into public.global_brokerage_onboarding_cases (
    user_id, client_case_id, launch_matrix_id, base_currency
  ) values (p_user_id, p_client_case_id, p_launch_matrix_id, p_base_currency)
  returning * into v_case;

  return jsonb_build_object('status', 'review_only', 'caseId', v_case.id,
    'activationStatus', 'blocked', 'idempotentReplay', false);
end;
$$;

create or replace function public.record_global_brokerage_evidence_rehearsal(
  p_user_id uuid,
  p_onboarding_case_id uuid,
  p_client_evidence_id text,
  p_requirement_key text,
  p_evidence_digest text,
  p_observed_at timestamptz,
  p_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.global_brokerage_evidence_rehearsals%rowtype;
  v_evidence public.global_brokerage_evidence_rehearsals%rowtype;
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Global brokerage evidence rehearsals require the orchestration service';
  end if;
  if char_length(coalesce(p_client_evidence_id, '')) not between 8 and 100
    or p_evidence_digest !~ '^[0-9a-f]{64}$'
    or p_observed_at is null or p_expires_at is null
    or p_expires_at <= p_observed_at or p_expires_at > p_observed_at + interval '30 days' then
    raise exception 'Invalid global brokerage evidence rehearsal';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_user_id::text || ':' || p_client_evidence_id, 0)
  );
  select * into v_existing from public.global_brokerage_evidence_rehearsals
  where user_id = p_user_id and client_evidence_id = p_client_evidence_id;
  if v_existing.id is not null then
    if v_existing.onboarding_case_id <> p_onboarding_case_id
      or v_existing.requirement_key <> p_requirement_key
      or v_existing.evidence_digest <> p_evidence_digest then
      raise exception 'Evidence rehearsal id was reused with different input';
    end if;
    return jsonb_build_object('status', 'rehearsal_recorded', 'evidenceId', v_existing.id,
      'approvalGranted', false, 'idempotentReplay', true);
  end if;

  if not exists (
    select 1 from public.global_brokerage_onboarding_cases
    where id = p_onboarding_case_id and user_id = p_user_id
      and case_status = 'review_only' and activation_status = 'blocked'
      and expires_at > now()
  ) then
    raise exception 'Global brokerage onboarding case is unavailable';
  end if;
  if not exists (
    select 1 from public.global_brokerage_onboarding_requirements
    where requirement_key = p_requirement_key and activation_blocking
  ) then
    raise exception 'Global brokerage requirement is unavailable';
  end if;

  insert into public.global_brokerage_evidence_rehearsals (
    user_id, onboarding_case_id, client_evidence_id, requirement_key,
    evidence_digest, observed_at, expires_at
  ) values (
    p_user_id, p_onboarding_case_id, p_client_evidence_id, p_requirement_key,
    p_evidence_digest, p_observed_at, p_expires_at
  ) returning * into v_evidence;

  return jsonb_build_object('status', 'rehearsal_recorded', 'evidenceId', v_evidence.id,
    'approvalGranted', false, 'idempotentReplay', false);
end;
$$;

create or replace function public.create_global_brokerage_order_preview(
  p_user_id uuid,
  p_onboarding_case_id uuid,
  p_client_preview_id text,
  p_listing_id bigint,
  p_side text,
  p_order_type text,
  p_quantity numeric,
  p_limit_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.global_brokerage_order_previews%rowtype;
  v_case public.global_brokerage_onboarding_cases%rowtype;
  v_matrix public.global_brokerage_launch_matrix%rowtype;
  v_listing public.global_instrument_listings%rowtype;
  v_quote public.international_paper_quotes%rowtype;
  v_cost public.international_paper_cost_rules%rowtype;
  v_quote_fx public.international_paper_fx_rates%rowtype;
  v_base_fx public.international_paper_fx_rates%rowtype;
  v_preview_id uuid;
  v_price numeric(20,8);
  v_gross numeric(24,8);
  v_commission numeric(24,8);
  v_venue_fee numeric(24,8);
  v_tax numeric(24,8);
  v_fx numeric(24,10);
  v_total_base numeric(24,8);
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Global brokerage previews require the orchestration service';
  end if;
  if char_length(coalesce(p_client_preview_id, '')) not between 8 and 100
    or p_side not in ('buy', 'sell') or p_order_type not in ('market', 'limit')
    or p_quantity <= 0 or p_quantity > 1000000
    or (p_order_type = 'limit' and (p_limit_price is null or p_limit_price <= 0))
    or (p_order_type = 'market' and p_limit_price is not null) then
    raise exception 'Invalid global brokerage preview';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_user_id::text || ':' || p_client_preview_id, 0)
  );
  select * into v_existing from public.global_brokerage_order_previews
  where user_id = p_user_id and client_preview_id = p_client_preview_id;
  if v_existing.id is not null then
    if v_existing.onboarding_case_id <> p_onboarding_case_id
      or v_existing.listing_id <> p_listing_id or v_existing.side <> p_side
      or v_existing.order_type <> p_order_type or v_existing.quantity <> p_quantity
      or v_existing.limit_price is distinct from p_limit_price then
      raise exception 'Global brokerage preview id was reused with different input';
    end if;
    return jsonb_build_object('status', 'blocked', 'previewId', v_existing.id,
      'executable', false, 'idempotentReplay', true);
  end if;

  select * into v_case from public.global_brokerage_onboarding_cases
  where id = p_onboarding_case_id and user_id = p_user_id for update;
  if v_case.id is null or v_case.expires_at <= now()
    or v_case.case_status <> 'review_only' or v_case.activation_status <> 'blocked' then
    raise exception 'Global brokerage onboarding case is unavailable';
  end if;
  select * into v_matrix from public.global_brokerage_launch_matrix
  where id = v_case.launch_matrix_id;
  select * into v_listing from public.global_instrument_listings where id = p_listing_id;
  if v_listing.id is null or v_listing.venue_id <> v_matrix.venue_id
    or v_listing.instrument_type <> v_matrix.asset_class
    or v_listing.listing_status <> 'reference_only' then
    raise exception 'Listing is outside the blocked launch matrix';
  end if;

  select * into v_quote from public.international_paper_quotes
  where listing_id = p_listing_id and source_type = 'deterministic_fixture'
    and simulation_only and quote_status = 'available_scenario';
  select * into v_cost from public.international_paper_cost_rules
  where venue_id = v_listing.venue_id and instrument_type = v_listing.instrument_type
    and enabled and simulation_only;
  select * into v_quote_fx from public.international_paper_fx_rates
  where currency_code = v_listing.quote_currency and simulation_only;
  select * into v_base_fx from public.international_paper_fx_rates
  where currency_code = v_case.base_currency and simulation_only;
  if v_quote.id is null or v_cost.id is null
    or v_quote_fx.currency_code is null or v_base_fx.currency_code is null then
    raise exception 'Deterministic preview inputs are unavailable';
  end if;

  v_price := case when p_order_type = 'limit' then p_limit_price else v_quote.scenario_price end;
  v_gross := round(v_price * p_quantity, 8);
  v_commission := round(greatest(v_cost.minimum_commission, v_gross * v_cost.commission_bps / 10000), 8);
  v_venue_fee := round(v_gross * v_cost.exchange_fee_bps / 10000, 8);
  v_tax := case when v_cost.cost_status = 'modeled_scenario'
    then round(v_gross * v_cost.tax_assumption_bps / 10000, 8) else null end;
  v_fx := round(v_quote_fx.usd_value_per_unit / v_base_fx.usd_value_per_unit, 10);
  v_total_base := case when v_tax is null then null
    when p_side = 'buy' then round((v_gross + v_commission + v_venue_fee + v_tax) * v_fx, 8)
    else round((v_gross - v_commission - v_venue_fee - v_tax) * v_fx, 8) end;
  if v_total_base is not null and v_total_base <= 0 then
    raise exception 'Deterministic preview costs exceed the scenario notional';
  end if;

  insert into public.global_brokerage_order_previews (
    user_id, onboarding_case_id, client_preview_id, listing_id,
    side, order_type, quantity, limit_price, scenario_price, gross_notional,
    quote_currency, fx_rate_to_base, base_currency, commission_amount,
    venue_fee_amount, estimated_tax_amount, tax_status, estimated_total_base,
    settlement_currency, route_evidence, block_reasons, policy_version, expires_at
  ) values (
    p_user_id, p_onboarding_case_id, p_client_preview_id, p_listing_id,
    p_side, p_order_type, p_quantity,
    case when p_order_type = 'limit' then p_limit_price else null end,
    v_price, v_gross, v_listing.quote_currency, v_fx, v_case.base_currency,
    v_commission, v_venue_fee, v_tax,
    case when v_tax is null then 'unavailable' else 'modeled_scenario' end,
    v_total_base, v_matrix.settlement_currency,
    jsonb_build_array(
      jsonb_build_object('role', 'broker', 'status', 'unassigned'),
      jsonb_build_object('role', 'exchange', 'status', 'unassigned'),
      jsonb_build_object('role', 'clearing', 'status', 'unassigned'),
      jsonb_build_object('role', 'custody', 'status', 'unassigned'),
      jsonb_build_object('role', 'market_data', 'status', 'unassigned')
    ),
    jsonb_build_array(
      jsonb_build_object('code', 'GLOBAL_ACTIVATION_BLOCKED', 'owner', 'tradepulse', 'message', 'The exact launch matrix has no activation decision.'),
      jsonb_build_object('code', 'PARTNERS_UNASSIGNED', 'owner', 'operations', 'Broker, clearing, custody and market-data roles are unassigned.'),
      jsonb_build_object('code', 'ONBOARDING_UNAPPROVED', 'owner', 'compliance', 'Rehearsal evidence never satisfies onboarding approval.'),
      jsonb_build_object('code', 'BUYING_POWER_UNAVAILABLE', 'owner', 'broker', 'No real brokerage cash or buying power exists.'),
      jsonb_build_object('code', 'PAYMENT_FUNDING_SEPARATE', 'owner', 'payments', 'A payment quote cannot become brokerage cash.')
    ),
    'global-brokerage-custody-v1', now() + interval '5 minutes'
  ) returning id into v_preview_id;

  return jsonb_build_object('status', 'blocked', 'previewId', v_preview_id,
    'executable', false, 'estimatedTotalBase', v_total_base,
    'idempotentReplay', false);
end;
$$;

create or replace function public.reconcile_global_brokerage_case(
  p_user_id uuid,
  p_onboarding_case_id uuid,
  p_client_reconciliation_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing public.global_brokerage_reconciliation_runs%rowtype;
  v_run_id uuid;
begin
  if current_setting('request.jwt.claim.role', true) <> 'service_role' then
    raise exception 'Global brokerage reconciliation requires the orchestration service';
  end if;
  if char_length(coalesce(p_client_reconciliation_id, '')) not between 8 and 100 then
    raise exception 'Invalid global brokerage reconciliation';
  end if;
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_user_id::text || ':' || p_client_reconciliation_id, 0)
  );
  select * into v_existing from public.global_brokerage_reconciliation_runs
  where user_id = p_user_id and client_reconciliation_id = p_client_reconciliation_id;
  if v_existing.id is not null then
    if v_existing.onboarding_case_id <> p_onboarding_case_id then
      raise exception 'Global brokerage reconciliation id was reused with different input';
    end if;
    return jsonb_build_object('status', 'not_ready', 'reconciliationId', v_existing.id,
      'blockingDomains', 5, 'idempotentReplay', true);
  end if;
  if not exists (
    select 1 from public.global_brokerage_onboarding_cases
    where id = p_onboarding_case_id and user_id = p_user_id
      and case_status = 'review_only' and activation_status = 'blocked'
      and expires_at > now()
  ) then
    raise exception 'Global brokerage onboarding case is unavailable';
  end if;

  insert into public.global_brokerage_reconciliation_runs (
    user_id, onboarding_case_id, client_reconciliation_id,
    reconciliation_version
  ) values (
    p_user_id, p_onboarding_case_id, p_client_reconciliation_id,
    'global-brokerage-reconciliation-v1'
  ) returning id into v_run_id;

  insert into public.global_brokerage_reconciliation_items (
    reconciliation_run_id, domain, detail
  ) values
    (v_run_id, 'order', 'No signed broker order event is connected.'),
    (v_run_id, 'allocation', 'No signed allocation or clearing record is connected.'),
    (v_run_id, 'cash', 'No real brokerage cash ledger or buying-power source is connected.'),
    (v_run_id, 'custody', 'No custodian position or safeguarding statement is connected.'),
    (v_run_id, 'settlement', 'No clearing or settlement instruction source is connected.');

  return jsonb_build_object('status', 'not_ready', 'reconciliationId', v_run_id,
    'blockingDomains', 5, 'productionEffect', false, 'idempotentReplay', false);
end;
$$;

revoke all on function public.initialize_global_brokerage_case(uuid, text, bigint, text) from public, anon, authenticated;
revoke all on function public.record_global_brokerage_evidence_rehearsal(uuid, uuid, text, text, text, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function public.create_global_brokerage_order_preview(uuid, uuid, text, bigint, text, text, numeric, numeric) from public, anon, authenticated;
revoke all on function public.reconcile_global_brokerage_case(uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.initialize_global_brokerage_case(uuid, text, bigint, text) to service_role;
grant execute on function public.record_global_brokerage_evidence_rehearsal(uuid, uuid, text, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.create_global_brokerage_order_preview(uuid, uuid, text, bigint, text, text, numeric, numeric) to service_role;
grant execute on function public.reconcile_global_brokerage_case(uuid, uuid, text) to service_role;

do $$
begin
  if exists (
    select 1 from public.global_brokerage_custody_controls where
      activation_status <> 'blocked' or live_broker_connectivity_enabled
      or exchange_connectivity_enabled or clearing_connectivity_enabled
      or custody_accounts_enabled or customer_asset_safeguarding_enabled
      or real_cash_ledger_enabled or real_position_ledger_enabled
      or settlement_instructions_enabled or market_data_credentials_enabled
      or cross_border_funding_link_enabled or live_order_routing_enabled
      or automatic_activation_enabled or not manual_activation_review_required
  ) then
    raise exception 'Phase 8D controls must remain fail-closed';
  end if;
  if exists (
    select 1 from public.global_brokerage_launch_matrix
    where matrix_status <> 'blocked' or legal_approval_status <> 'missing'
      or compliance_approval_status <> 'missing' or tax_approval_status <> 'missing'
      or market_data_approval_status <> 'missing' or broker_approval_status <> 'missing'
      or custody_approval_status <> 'missing' or security_approval_status <> 'missing'
      or operations_approval_status <> 'missing' or broker_assigned
      or exchange_access_assigned or clearing_partner_assigned or custody_partner_assigned
      or market_data_partner_assigned or onboarding_supported or live_execution_enabled
  ) then
    raise exception 'Phase 8D launch matrix must remain blocked';
  end if;
  if to_regclass('public.global_live_brokerage_orders') is not null
    or to_regclass('public.production_custody_accounts') is not null
    or to_regprocedure('public.route_global_brokerage_order(jsonb)') is not null
    or to_regprocedure('public.link_payment_quote_to_brokerage_cash(jsonb)') is not null then
    raise exception 'Phase 8D cannot deploy with live execution, custody or funding paths';
  end if;
end;
$$;

comment on table public.global_brokerage_custody_controls is 'Phase 8D orchestration controls. All broker, custody, funding, settlement and live-order capabilities remain false.';
comment on table public.global_brokerage_launch_matrix is 'Exact residency, jurisdiction, account, asset and venue scenarios; every matrix is blocked with missing approvals.';
comment on table public.global_brokerage_evidence_rehearsals is 'Identity-bound expiring evidence rehearsals only. No raw evidence is stored and no approval effect exists.';
comment on table public.global_brokerage_order_previews is 'Append-only deterministic cost preview with unavailable buying power and route evidence; never executable.';
comment on function public.create_global_brokerage_order_preview is 'Service-only deterministic preview; contains no broker, custody, funding or HTTP integration.';
