-- TradePulse AI
-- Migration 050: Phase 8F global event intelligence engine
-- Structured intelligence and probabilistic scenarios only. No raw scraping, rumor
-- promotion, autonomous publishing, trading, funding, custody, or settlement.

create table public.global_event_intelligence_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_authenticity_required boolean not null default true check (source_authenticity_required),
  multi_source_corroboration_required boolean not null default true check (multi_source_corroboration_required),
  causal_impact_graph_enabled boolean not null default true check (causal_impact_graph_enabled),
  scenario_forecasting_enabled boolean not null default true check (scenario_forecasting_enabled),
  personalized_alerts_enabled boolean not null default true check (personalized_alerts_enabled),
  country_coverage_target integer not null default 195 check (country_coverage_target = 195),
  raw_web_scraping_enabled boolean not null default false check (not raw_web_scraping_enabled),
  credentialed_source_bypass_enabled boolean not null default false check (not credentialed_source_bypass_enabled),
  unlicensed_content_storage_enabled boolean not null default false check (not unlicensed_content_storage_enabled),
  automatic_verification_without_evidence_enabled boolean not null default false check (not automatic_verification_without_evidence_enabled),
  rumor_promotion_enabled boolean not null default false check (not rumor_promotion_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  production_provider_connectivity_enabled boolean not null default false check (not production_provider_connectivity_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  customer_funding_enabled boolean not null default false check (not customer_funding_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  settlement_enabled boolean not null default false check (not settlement_enabled),
  max_alert_policies_per_user integer not null default 12 check (max_alert_policies_per_user between 1 and 24),
  updated_at timestamptz not null default now()
);

insert into public.global_event_intelligence_controls (control_key, policy_version)
values ('global-event-intelligence', 'global-event-policy-v1');

create table public.global_event_source_registry (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  display_name text not null,
  source_class text not null check (source_class in (
    'synthetic_fixture', 'official_authority', 'regulator', 'exchange',
    'licensed_news', 'licensed_logistics', 'licensed_geoscience', 'research'
  )),
  rights_status text not null check (rights_status in ('synthetic', 'approved', 'pending', 'rejected')),
  authenticity_tier text not null check (authenticity_tier in ('reference', 'primary', 'corroborating', 'unapproved')),
  base_authenticity_score numeric(6,5) not null check (base_authenticity_score between 0 and 1),
  enabled boolean not null default false,
  provider_connectivity_enabled boolean not null default false check (not provider_connectivity_enabled),
  raw_content_storage_enabled boolean not null default false check (not raw_content_storage_enabled),
  source_reference text not null check (char_length(source_reference) between 8 and 240),
  review_status text not null check (review_status in ('synthetic_fixture', 'approved', 'review_required', 'rejected')),
  reviewed_at timestamptz,
  review_expires_at timestamptz,
  created_at timestamptz not null default now(),
  check (not enabled or rights_status in ('synthetic', 'approved')),
  check (not provider_connectivity_enabled or (enabled and rights_status = 'approved' and review_status = 'approved')),
  check (review_expires_at is null or reviewed_at is not null),
  check (review_expires_at is null or review_expires_at > reviewed_at)
);

insert into public.global_event_source_registry (
  source_key, display_name, source_class, rights_status, authenticity_tier,
  base_authenticity_score, enabled, provider_connectivity_enabled,
  source_reference, review_status
) values
  ('tradepulse-synthetic-event-lab', 'TradePulse synthetic event laboratory', 'synthetic_fixture', 'synthetic', 'reference', 0, true, false, 'synthetic://global-event-laboratory', 'synthetic_fixture'),
  ('official-authority-source-slot', 'Official authority source slot', 'official_authority', 'pending', 'unapproved', 0, false, false, 'pending://official-authority-review', 'review_required'),
  ('licensed-news-source-slot', 'Licensed global news source slot', 'licensed_news', 'pending', 'unapproved', 0, false, false, 'pending://licensed-news-rights-review', 'review_required'),
  ('licensed-logistics-source-slot', 'Licensed logistics source slot', 'licensed_logistics', 'pending', 'unapproved', 0, false, false, 'pending://licensed-logistics-review', 'review_required'),
  ('licensed-geoscience-source-slot', 'Licensed geoscience source slot', 'licensed_geoscience', 'pending', 'unapproved', 0, false, false, 'pending://licensed-geoscience-review', 'review_required');

create table public.global_country_intelligence_profiles (
  country_id bigint primary key references public.countries(id) on delete cascade,
  coverage_status text not null default 'catalogued' check (coverage_status in ('catalogued', 'partial', 'verified')),
  monitored_event_types text[] not null default array[
    'resource_discovery', 'energy_supply', 'logistics_disruption',
    'monetary_policy', 'geopolitics', 'extreme_weather', 'macro_data'
  ]::text[] check (cardinality(monitored_event_types) between 1 and 12),
  approved_source_count integer not null default 0 check (approved_source_count >= 0),
  provider_coverage_enabled boolean not null default false check (not provider_coverage_enabled),
  last_evaluated_at timestamptz,
  profile_version text not null default 'global-country-intelligence-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not provider_coverage_enabled or approved_source_count > 0)
);

insert into public.global_country_intelligence_profiles (country_id)
select id from public.countries
on conflict (country_id) do nothing;

create table public.global_event_records (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  source_id bigint not null references public.global_event_source_registry(id),
  origin_country_id bigint references public.countries(id),
  region_code text not null check (region_code ~ '^[A-Z]{2,12}$'),
  event_type text not null check (event_type in (
    'resource_discovery', 'energy_supply', 'logistics_disruption',
    'monetary_policy', 'geopolitics', 'extreme_weather', 'macro_data',
    'regulation', 'infrastructure', 'technology'
  )),
  normalized_summary text not null check (char_length(normalized_summary) between 20 and 500),
  source_reference text not null check (char_length(source_reference) between 8 and 240),
  input_digest text not null check (input_digest ~ '^[a-f0-9]{64}$'),
  source_published_at timestamptz not null,
  observed_at timestamptz not null default now(),
  expires_at timestamptz not null,
  authenticity_score numeric(6,5) not null check (authenticity_score between 0 and 1),
  corroboration_count integer not null default 0 check (corroboration_count between 0 and 20),
  verification_status text not null check (verification_status in ('synthetic', 'unverified', 'corroborated', 'verified', 'rejected')),
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  novelty_score numeric(6,5) not null check (novelty_score between 0 and 1),
  display_eligible boolean not null default false,
  model_eligible boolean not null default false,
  synthetic boolean not null default true,
  created_at timestamptz not null default now(),
  check (source_published_at <= observed_at),
  check (expires_at > observed_at),
  check (not synthetic or (verification_status = 'synthetic' and not model_eligible)),
  check (not display_eligible or verification_status in ('synthetic', 'corroborated', 'verified')),
  check (verification_status <> 'verified' or (not synthetic and corroboration_count >= 2 and authenticity_score >= 0.7)),
  check (not model_eligible or (
    not synthetic and verification_status in ('corroborated', 'verified')
      and corroboration_count >= 2 and authenticity_score >= 0.7
  ))
);

create index idx_global_event_records_country_time
  on public.global_event_records(origin_country_id, source_published_at desc)
  where display_eligible;
create index idx_global_event_records_type_time
  on public.global_event_records(event_type, source_published_at desc)
  where display_eligible;
create index idx_global_event_records_display_time
  on public.global_event_records(source_published_at desc, id desc)
  where display_eligible;
create index idx_global_event_records_model_cutoff
  on public.global_event_records(source_published_at, origin_country_id)
  where model_eligible and not synthetic;

create table public.global_event_entities (
  id bigint generated by default as identity primary key,
  entity_key text not null unique,
  entity_kind text not null check (entity_kind in (
    'country', 'commodity', 'currency', 'logistics_node', 'market_asset', 'sector'
  )),
  display_name text not null,
  country_id bigint references public.countries(id),
  market_asset_id bigint references public.market_assets(id),
  attributes jsonb not null default '{}'::jsonb check (jsonb_typeof(attributes) = 'object'),
  created_at timestamptz not null default now(),
  check ((entity_kind = 'country') = (country_id is not null)),
  check (entity_kind <> 'market_asset' or market_asset_id is not null)
);

create table public.global_event_entity_links (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.global_event_records(id) on delete cascade,
  entity_id bigint not null references public.global_event_entities(id),
  relationship text not null check (relationship in ('origin', 'affected', 'produces', 'consumes', 'transits', 'priced_in', 'policy_scope')),
  relevance_score numeric(6,5) not null check (relevance_score between 0 and 1),
  created_at timestamptz not null default now(),
  unique (event_id, entity_id, relationship)
);

create index idx_global_event_entity_links_entity
  on public.global_event_entity_links(entity_id, event_id);

create table public.global_event_impact_edges (
  id bigint generated by default as identity primary key,
  edge_key text not null unique,
  event_id bigint not null references public.global_event_records(id) on delete cascade,
  sequence_number smallint not null check (sequence_number between 1 and 8),
  from_entity_id bigint not null references public.global_event_entities(id),
  to_entity_id bigint not null references public.global_event_entities(id),
  mechanism text not null check (mechanism in ('supply', 'demand', 'logistics', 'currency', 'rates', 'risk_premium', 'trade', 'sentiment')),
  impact_direction text not null check (impact_direction in ('positive', 'negative', 'mixed', 'neutral')),
  probability numeric(6,5) not null check (probability between 0 and 1),
  confidence_score numeric(6,5) not null check (confidence_score between 0 and 1),
  horizon text not null check (horizon in ('1d', '1w', '1m', '3m', '1y')),
  lag_description text not null check (char_length(lag_description) between 3 and 80),
  rationale text not null check (char_length(rationale) between 20 and 500),
  assumptions jsonb not null default '[]'::jsonb check (jsonb_typeof(assumptions) = 'array'),
  target_asset_id bigint references public.market_assets(id),
  estimated_effect_low_pct numeric(8,4),
  estimated_effect_high_pct numeric(8,4),
  terminal_edge boolean not null default false,
  scenario_version text not null default 'global-event-scenario-v1',
  human_review_required boolean not null default true check (human_review_required),
  model_eligible boolean not null default false,
  synthetic boolean not null default true,
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (event_id, sequence_number, to_entity_id),
  check (from_entity_id <> to_entity_id),
  check (estimated_effect_low_pct is null or estimated_effect_high_pct is not null),
  check (estimated_effect_high_pct is null or estimated_effect_low_pct is not null),
  check (estimated_effect_low_pct is null or estimated_effect_low_pct <= estimated_effect_high_pct),
  check (not terminal_edge or target_asset_id is not null),
  check (not synthetic or not model_eligible)
);

create index idx_global_event_impact_edges_event_sequence
  on public.global_event_impact_edges(event_id, sequence_number);
create index idx_global_event_impact_edges_target
  on public.global_event_impact_edges(target_asset_id, horizon)
  where terminal_edge;

create table public.global_event_analysis_runs (
  id uuid primary key default gen_random_uuid(),
  run_key text not null unique,
  event_id bigint not null references public.global_event_records(id),
  engine_version text not null,
  status text not null check (status in ('completed', 'review_required', 'rejected', 'failed')),
  data_cutoff timestamptz not null,
  evidence_count integer not null check (evidence_count between 1 and 100),
  corroboration_count integer not null check (corroboration_count between 0 and 20),
  evidence_digest text not null check (evidence_digest ~ '^[a-f0-9]{64}$'),
  scenario_count integer not null check (scenario_count between 0 and 50),
  human_review_required boolean not null default true check (human_review_required),
  automatically_published boolean not null default false check (not automatically_published),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

create table public.user_global_event_alert_policies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  client_policy_id text not null check (char_length(client_policy_id) between 8 and 100),
  name text not null check (char_length(trim(name)) between 3 and 80),
  country_codes text[] not null default array['GLOBAL']::text[] check (cardinality(country_codes) between 1 and 12),
  event_types text[] not null check (cardinality(event_types) between 1 and 10),
  asset_symbols text[] not null default '{}'::text[] check (cardinality(asset_symbols) between 0 and 12),
  minimum_authenticity_score numeric(6,5) not null default 0.7 check (minimum_authenticity_score between 0 and 1),
  minimum_confidence_score numeric(6,5) not null default 0.6 check (minimum_confidence_score between 0 and 1),
  minimum_severity text not null default 'medium' check (minimum_severity in ('low', 'medium', 'high', 'critical')),
  delivery_channel text not null default 'in_app' check (delivery_channel = 'in_app'),
  active boolean not null default true,
  policy_version text not null default 'global-event-alert-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_policy_id)
);

create index idx_user_global_event_alert_policies_user
  on public.user_global_event_alert_policies(user_id, updated_at desc)
  where active;

insert into public.global_event_records (
  event_key, source_id, origin_country_id, region_code, event_type,
  normalized_summary, source_reference, input_digest, source_published_at,
  observed_at, expires_at, authenticity_score, corroboration_count,
  verification_status, severity, novelty_score, display_eligible,
  model_eligible, synthetic
)
select fixture.event_key, source.id, country.id, fixture.region_code,
  fixture.event_type, fixture.summary, fixture.reference,
  md5(fixture.event_key) || md5(fixture.event_key || ':phase8f'),
  '2026-09-12 08:00:00+00'::timestamptz,
  '2026-09-12 08:05:00+00'::timestamptz,
  '2036-09-19 08:05:00+00'::timestamptz,
  0, 0, 'synthetic', fixture.severity, fixture.novelty,
  true, false, true
from (values
  ('synthetic-india-gold-discovery', 'IN', 'IN', 'resource_discovery',
    'Synthetic discovery scenario tests how a material Indian gold reserve could affect supply expectations, imports, local producers and global gold pricing.',
    'synthetic://india-gold-discovery', 'high', 0.92000),
  ('synthetic-global-crude-supply-cut', null, 'GLOBAL', 'energy_supply',
    'Synthetic coordinated crude supply reduction tests the transmission from expected barrels to freight costs, inflation pressure and oil pricing.',
    'synthetic://global-crude-supply-cut', 'high', 0.88000),
  ('synthetic-maritime-chokepoint-delay', null, 'GLOBAL', 'logistics_disruption',
    'Synthetic maritime chokepoint delay tests longer routes, reduced capacity and cost pressure across energy and internationally traded goods.',
    'synthetic://maritime-chokepoint-delay', 'critical', 0.95000),
  ('synthetic-uk-rate-repricing', 'GB', 'GB', 'monetary_policy',
    'Synthetic United Kingdom rate-path repricing tests currency, funding-cost and risk-sentiment transmission without asserting a policy decision.',
    'synthetic://uk-rate-repricing', 'medium', 0.76000),
  ('synthetic-china-port-congestion', 'CN', 'CN', 'logistics_disruption',
    'Synthetic China port congestion tests export delays, inventory gaps and landed-cost pressure across dependent international supply chains.',
    'synthetic://china-port-congestion', 'high', 0.84000)
) as fixture(event_key, country_code, region_code, event_type, summary, reference, severity, novelty)
join public.global_event_source_registry source
  on source.source_key = 'tradepulse-synthetic-event-lab'
left join public.countries country on country.iso_code = fixture.country_code;

insert into public.global_event_entities (
  entity_key, entity_kind, display_name, country_id, market_asset_id, attributes
)
select fixture.entity_key, fixture.entity_kind, fixture.display_name,
  country.id, asset.id, fixture.attributes
from (values
  ('country-IN', 'country', 'India', 'IN', null, '{"scope":"country"}'::jsonb),
  ('country-GB', 'country', 'United Kingdom', 'GB', null, '{"scope":"country"}'::jsonb),
  ('country-CN', 'country', 'China', 'CN', null, '{"scope":"country"}'::jsonb),
  ('commodity-gold', 'commodity', 'Global gold supply', null, null, '{"unit":"supply expectation"}'::jsonb),
  ('commodity-crude', 'commodity', 'Global crude supply', null, null, '{"unit":"barrels"}'::jsonb),
  ('logistics-maritime-capacity', 'logistics_node', 'Maritime route capacity', null, null, '{"mode":"ocean"}'::jsonb),
  ('logistics-china-ports', 'logistics_node', 'China export ports', null, null, '{"mode":"ocean"}'::jsonb),
  ('currency-GBP', 'currency', 'Pound sterling', null, null, '{"iso":"GBP"}'::jsonb),
  ('asset-XAUUSD', 'market_asset', 'Gold / US Dollar', null, 'XAUUSD', '{}'::jsonb),
  ('asset-WTI', 'market_asset', 'West Texas Intermediate crude', null, 'WTI', '{}'::jsonb),
  ('asset-EURUSD', 'market_asset', 'Euro / US Dollar', null, 'EURUSD', '{}'::jsonb),
  ('asset-USDINR', 'market_asset', 'US Dollar / Indian Rupee', null, 'USDINR', '{}'::jsonb)
) as fixture(entity_key, entity_kind, display_name, country_code, asset_symbol, attributes)
left join public.countries country on country.iso_code = fixture.country_code
left join public.market_assets asset on asset.symbol = fixture.asset_symbol;

insert into public.global_event_entity_links (event_id, entity_id, relationship, relevance_score)
select event.id, entity.id, fixture.relationship, fixture.relevance
from (values
  ('synthetic-india-gold-discovery', 'country-IN', 'origin', 1.00000),
  ('synthetic-india-gold-discovery', 'commodity-gold', 'produces', 0.98000),
  ('synthetic-india-gold-discovery', 'asset-XAUUSD', 'affected', 0.90000),
  ('synthetic-india-gold-discovery', 'asset-USDINR', 'affected', 0.62000),
  ('synthetic-global-crude-supply-cut', 'commodity-crude', 'produces', 1.00000),
  ('synthetic-global-crude-supply-cut', 'asset-WTI', 'affected', 0.97000),
  ('synthetic-maritime-chokepoint-delay', 'logistics-maritime-capacity', 'transits', 1.00000),
  ('synthetic-maritime-chokepoint-delay', 'commodity-crude', 'affected', 0.86000),
  ('synthetic-maritime-chokepoint-delay', 'asset-WTI', 'affected', 0.82000),
  ('synthetic-uk-rate-repricing', 'country-GB', 'policy_scope', 1.00000),
  ('synthetic-uk-rate-repricing', 'currency-GBP', 'affected', 0.96000),
  ('synthetic-uk-rate-repricing', 'asset-EURUSD', 'affected', 0.52000),
  ('synthetic-china-port-congestion', 'country-CN', 'origin', 1.00000),
  ('synthetic-china-port-congestion', 'logistics-china-ports', 'transits', 0.98000),
  ('synthetic-china-port-congestion', 'asset-EURUSD', 'affected', 0.46000)
) as fixture(event_key, entity_key, relationship, relevance)
join public.global_event_records event on event.event_key = fixture.event_key
join public.global_event_entities entity on entity.entity_key = fixture.entity_key;

insert into public.global_event_impact_edges (
  edge_key, event_id, sequence_number, from_entity_id, to_entity_id,
  mechanism, impact_direction, probability, confidence_score, horizon,
  lag_description, rationale, assumptions, target_asset_id,
  estimated_effect_low_pct, estimated_effect_high_pct, terminal_edge,
  model_eligible, synthetic
)
select fixture.edge_key, event.id, fixture.sequence_number, from_entity.id,
  to_entity.id, fixture.mechanism, fixture.direction, fixture.probability,
  fixture.confidence, fixture.horizon, fixture.lag_description,
  fixture.rationale, fixture.assumptions, target_asset.id,
  fixture.effect_low, fixture.effect_high, fixture.terminal_edge, false, true
from (values
  ('india-gold-country-to-supply', 'synthetic-india-gold-discovery', 1, 'country-IN', 'commodity-gold', 'supply', 'positive', 0.68000, 0.48000, '1y', 'multi-year',
    'A commercially viable reserve could increase expected future supply, subject to grade, permits, capital and extraction timing.',
    '["commercial viability unknown","development approvals required"]'::jsonb, null, null, null, false),
  ('india-gold-supply-to-price', 'synthetic-india-gold-discovery', 2, 'commodity-gold', 'asset-XAUUSD', 'supply', 'negative', 0.63000, 0.42000, '1y', 'multi-year',
    'Higher expected supply can pressure global gold prices, while safe-haven demand and production timing may offset the effect.',
    '["other supply unchanged","demand response uncertain"]'::jsonb, 'XAUUSD', -3.5000, 0.5000, true),
  ('india-gold-import-channel', 'synthetic-india-gold-discovery', 3, 'country-IN', 'asset-USDINR', 'trade', 'mixed', 0.44000, 0.30000, '1y', 'multi-year',
    'Lower future gold imports could affect trade demand for foreign currency, but the macro impact depends on production scale and substitution.',
    '["reserve reaches production","import demand responds"]'::jsonb, 'USDINR', -0.8000, 0.8000, true),
  ('crude-cut-to-supply', 'synthetic-global-crude-supply-cut', 1, 'commodity-crude', 'asset-WTI', 'supply', 'positive', 0.79000, 0.61000, '1m', 'days to months',
    'A sustained supply reduction can increase crude price pressure when inventories and substitute supply do not fully offset it.',
    '["cut is implemented","demand remains stable"]'::jsonb, 'WTI', 1.5000, 8.0000, true),
  ('maritime-delay-to-crude', 'synthetic-maritime-chokepoint-delay', 1, 'logistics-maritime-capacity', 'commodity-crude', 'logistics', 'positive', 0.72000, 0.54000, '1w', 'days to weeks',
    'Reduced shipping capacity can increase voyage time and delivered energy cost before physical supply changes.',
    '["rerouting required","delay persists"]'::jsonb, null, null, null, false),
  ('maritime-crude-to-wti', 'synthetic-maritime-chokepoint-delay', 2, 'commodity-crude', 'asset-WTI', 'risk_premium', 'positive', 0.66000, 0.49000, '1w', 'days to weeks',
    'Transport uncertainty can add a temporary risk premium to crude benchmarks, with direction sensitive to inventories and demand.',
    '["inventory buffer limited","demand unchanged"]'::jsonb, 'WTI', 0.5000, 5.0000, true),
  ('uk-policy-to-pound', 'synthetic-uk-rate-repricing', 1, 'country-GB', 'currency-GBP', 'rates', 'mixed', 0.61000, 0.43000, '1m', 'hours to weeks',
    'A rate-path repricing can move sterling through yield differentials, but growth expectations and risk sentiment can reverse the direction.',
    '["market interpretation varies","policy outcome unconfirmed"]'::jsonb, null, null, null, false),
  ('uk-pound-to-eurusd', 'synthetic-uk-rate-repricing', 2, 'currency-GBP', 'asset-EURUSD', 'currency', 'mixed', 0.39000, 0.26000, '1m', 'hours to weeks',
    'Sterling repricing may spill into broader dollar and European currency positioning without determining EURUSD direction alone.',
    '["cross-currency spillover exists"]'::jsonb, 'EURUSD', -0.6000, 0.6000, true),
  ('china-port-to-global-fx', 'synthetic-china-port-congestion', 1, 'logistics-china-ports', 'asset-EURUSD', 'trade', 'negative', 0.47000, 0.33000, '1m', 'weeks',
    'Persistent export delays can weaken external demand expectations and increase dollar funding preference, but the FX effect is indirect.',
    '["congestion persists","inventory substitution limited"]'::jsonb, 'EURUSD', -1.2000, 0.3000, true)
) as fixture(
  edge_key, event_key, sequence_number, from_key, to_key, mechanism,
  direction, probability, confidence, horizon, lag_description, rationale,
  assumptions, target_symbol, effect_low, effect_high, terminal_edge
)
join public.global_event_records event on event.event_key = fixture.event_key
join public.global_event_entities from_entity on from_entity.entity_key = fixture.from_key
join public.global_event_entities to_entity on to_entity.entity_key = fixture.to_key
left join public.market_assets target_asset on target_asset.symbol = fixture.target_symbol;

insert into public.global_event_analysis_runs (
  run_key, event_id, engine_version, status, data_cutoff, evidence_count,
  corroboration_count, evidence_digest, scenario_count
)
select 'phase8f-synthetic-analysis-' || event.id::text, event.id,
  'global-event-causal-engine-v1.0.0', 'review_required',
  '2026-09-12 08:05:00+00'::timestamptz, 1, 0,
  md5(event.event_key || ':analysis') || md5(event.event_key || ':evidence'),
  (select count(*) from public.global_event_impact_edges edge where edge.event_id = event.id and edge.terminal_edge)
from public.global_event_records event
where event.synthetic;

alter table public.global_event_intelligence_controls enable row level security;
alter table public.global_event_source_registry enable row level security;
alter table public.global_country_intelligence_profiles enable row level security;
alter table public.global_event_records enable row level security;
alter table public.global_event_entities enable row level security;
alter table public.global_event_entity_links enable row level security;
alter table public.global_event_impact_edges enable row level security;
alter table public.global_event_analysis_runs enable row level security;
alter table public.user_global_event_alert_policies enable row level security;

create policy "Public reads global event controls"
  on public.global_event_intelligence_controls for select to anon, authenticated using (workspace_enabled);
create policy "Public reads enabled event sources"
  on public.global_event_source_registry for select to anon, authenticated using (enabled);
create policy "Public reads country intelligence coverage"
  on public.global_country_intelligence_profiles for select to anon, authenticated using (true);
create policy "Public reads display-eligible global events"
  on public.global_event_records for select to anon, authenticated using (
    display_eligible and expires_at > now() and exists (
      select 1 from public.global_event_source_registry source
      where source.id = global_event_records.source_id and source.enabled
    )
  );
create policy "Public reads event entities"
  on public.global_event_entities for select to anon, authenticated using (
    exists (
      select 1 from public.global_event_entity_links link
      join public.global_event_records event on event.id = link.event_id
      join public.global_event_source_registry source on source.id = event.source_id
      where link.entity_id = global_event_entities.id
        and event.display_eligible and event.expires_at > now() and source.enabled
    )
  );
create policy "Public reads display event entity links"
  on public.global_event_entity_links for select to anon, authenticated using (
    exists (
      select 1 from public.global_event_records event
      join public.global_event_source_registry source on source.id = event.source_id
      where event.id = global_event_entity_links.event_id
        and event.display_eligible and event.expires_at > now() and source.enabled
    )
  );
create policy "Public reads display event impact edges"
  on public.global_event_impact_edges for select to anon, authenticated using (
    exists (
      select 1 from public.global_event_records event
      join public.global_event_source_registry source on source.id = event.source_id
      where event.id = global_event_impact_edges.event_id
        and event.display_eligible and event.expires_at > now() and source.enabled
    )
  );
create policy "Public reads reviewable event analysis runs"
  on public.global_event_analysis_runs for select to anon, authenticated using (
    status in ('completed', 'review_required') and exists (
      select 1 from public.global_event_records event
      join public.global_event_source_registry source on source.id = event.source_id
      where event.id = global_event_analysis_runs.event_id
        and event.display_eligible and event.expires_at > now() and source.enabled
    )
  );
create policy "Users read their global event alert policies"
  on public.user_global_event_alert_policies for select to authenticated using (user_id = auth.uid());

revoke all on table public.global_event_intelligence_controls,
  public.global_event_source_registry, public.global_country_intelligence_profiles,
  public.global_event_records, public.global_event_entities,
  public.global_event_entity_links, public.global_event_impact_edges,
  public.global_event_analysis_runs, public.user_global_event_alert_policies
  from public, anon, authenticated, service_role;

grant select on table public.global_event_intelligence_controls,
  public.global_event_source_registry, public.global_country_intelligence_profiles,
  public.global_event_records, public.global_event_entities,
  public.global_event_entity_links, public.global_event_impact_edges,
  public.global_event_analysis_runs to anon, authenticated;
grant select on table public.user_global_event_alert_policies to authenticated;
grant select, insert, update on table public.global_event_intelligence_controls,
  public.global_event_source_registry, public.global_country_intelligence_profiles,
  public.global_event_entities to service_role;
grant select, insert on table public.global_event_records,
  public.global_event_entity_links, public.global_event_impact_edges,
  public.global_event_analysis_runs to service_role;
grant select, insert, update on table public.user_global_event_alert_policies to service_role;
grant usage, select on sequence public.global_event_intelligence_controls_id_seq,
  public.global_event_source_registry_id_seq, public.global_event_records_id_seq,
  public.global_event_entities_id_seq, public.global_event_entity_links_id_seq,
  public.global_event_impact_edges_id_seq to service_role;

create trigger global_country_intelligence_profiles_set_updated_at
  before update on public.global_country_intelligence_profiles
  for each row execute function public.set_updated_at();
create trigger user_global_event_alert_policies_set_updated_at
  before update on public.user_global_event_alert_policies
  for each row execute function public.set_updated_at();

create or replace function public.prevent_global_event_evidence_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Global event intelligence evidence is append-only';
end;
$$;

revoke all on function public.prevent_global_event_evidence_mutation() from public, anon, authenticated;

create trigger global_event_records_append_only
  before update or delete on public.global_event_records
  for each row execute function public.prevent_global_event_evidence_mutation();
create trigger global_event_entity_links_append_only
  before update or delete on public.global_event_entity_links
  for each row execute function public.prevent_global_event_evidence_mutation();
create trigger global_event_impact_edges_append_only
  before update or delete on public.global_event_impact_edges
  for each row execute function public.prevent_global_event_evidence_mutation();
create trigger global_event_analysis_runs_append_only
  before update or delete on public.global_event_analysis_runs
  for each row execute function public.prevent_global_event_evidence_mutation();

create or replace function public.save_global_event_alert_policy(
  p_client_policy_id text,
  p_name text,
  p_country_codes text[],
  p_event_types text[],
  p_asset_symbols text[],
  p_minimum_authenticity_score numeric,
  p_minimum_confidence_score numeric,
  p_minimum_severity text
)
returns public.user_global_event_alert_policies
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_policy public.user_global_event_alert_policies;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_client_policy_id !~ '^[A-Za-z0-9:_-]{8,100}$'
    or char_length(trim(p_name)) not between 3 and 80
    or cardinality(p_country_codes) not between 1 and 12
    or cardinality(p_event_types) not between 1 and 10
    or cardinality(p_asset_symbols) not between 0 and 12
    or p_minimum_authenticity_score not between 0 and 1
    or p_minimum_confidence_score not between 0 and 1
    or p_minimum_severity not in ('low', 'medium', 'high', 'critical') then
    raise exception 'Invalid global event alert policy';
  end if;
  if exists (
    select 1 from unnest(p_country_codes) code
    where code <> 'GLOBAL' and not exists (
      select 1 from public.countries country where country.iso_code = code
    )
  ) then
    raise exception 'Unsupported country code';
  end if;
  if exists (
    select 1 from unnest(p_event_types) event_type
    where event_type not in (
      'resource_discovery', 'energy_supply', 'logistics_disruption',
      'monetary_policy', 'geopolitics', 'extreme_weather', 'macro_data',
      'regulation', 'infrastructure', 'technology'
    )
  ) then
    raise exception 'Unsupported event type';
  end if;
  if exists (
    select 1 from unnest(p_asset_symbols) symbol
    where not exists (select 1 from public.market_assets asset where asset.symbol = symbol)
  ) then
    raise exception 'Unsupported market asset';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('global-event-alert-user:' || v_user_id::text, 0)
  );
  if not exists (
    select 1 from public.user_global_event_alert_policies
    where user_id = v_user_id and client_policy_id = p_client_policy_id and active
  ) and (
    select count(*) from public.user_global_event_alert_policies
    where user_id = v_user_id and active
  ) >= 12 then
    raise exception 'Global event alert policy limit reached';
  end if;

  insert into public.user_global_event_alert_policies (
    user_id, client_policy_id, name, country_codes, event_types,
    asset_symbols, minimum_authenticity_score, minimum_confidence_score,
    minimum_severity
  ) values (
    v_user_id, p_client_policy_id, trim(p_name), p_country_codes, p_event_types,
    p_asset_symbols, p_minimum_authenticity_score, p_minimum_confidence_score,
    p_minimum_severity
  )
  on conflict (user_id, client_policy_id) do update set
    name = excluded.name, country_codes = excluded.country_codes,
    event_types = excluded.event_types, asset_symbols = excluded.asset_symbols,
    minimum_authenticity_score = excluded.minimum_authenticity_score,
    minimum_confidence_score = excluded.minimum_confidence_score,
    minimum_severity = excluded.minimum_severity, active = true
  returning * into v_policy;
  return v_policy;
end;
$$;

revoke all on function public.save_global_event_alert_policy(text, text, text[], text[], text[], numeric, numeric, text)
  from public, anon, authenticated;
grant execute on function public.save_global_event_alert_policy(text, text, text[], text[], text[], numeric, numeric, text)
  to authenticated;

alter table public.agentic_run_steps
  drop constraint agentic_run_steps_agent_role_check;
alter table public.agentic_run_steps
  add constraint agentic_run_steps_agent_role_check check (agent_role in (
    'planner', 'news_analyst', 'event_intelligence_analyst', 'market_analyst',
    'forecast_analyst', 'risk_analyst', 'report_builder', 'safety_reviewer'
  ));

create view public.global_event_intelligence_status
with (security_invoker = true)
as
select control.control_key, control.policy_version, control.workspace_enabled,
  control.source_authenticity_required, control.multi_source_corroboration_required,
  control.causal_impact_graph_enabled, control.scenario_forecasting_enabled,
  control.personalized_alerts_enabled, control.country_coverage_target,
  (select count(*) from public.global_country_intelligence_profiles)::integer as catalogued_country_count,
  (select count(*) from public.global_event_records event
    join public.global_event_source_registry source on source.id = event.source_id
    where event.display_eligible and event.expires_at > now() and source.enabled)::integer as display_event_count,
  (select count(*) from public.global_event_impact_edges edge
    join public.global_event_records event on event.id = edge.event_id
    join public.global_event_source_registry source on source.id = event.source_id
    where edge.terminal_edge and event.display_eligible
      and event.expires_at > now() and source.enabled)::integer as scenario_count,
  control.raw_web_scraping_enabled, control.unlicensed_content_storage_enabled,
  control.automatic_verification_without_evidence_enabled,
  control.rumor_promotion_enabled, control.autonomous_publication_enabled,
  control.production_provider_connectivity_enabled,
  control.autonomous_trade_execution_enabled, control.customer_funding_enabled,
  control.custody_enabled, control.settlement_enabled,
  control.max_alert_policies_per_user, control.updated_at
from public.global_event_intelligence_controls control;

create view public.global_event_signal_catalog
with (security_invoker = true)
as
select event.id, event.event_key, country.iso_code as country_code,
  country.name as country_name, event.region_code, event.event_type,
  event.normalized_summary, event.source_reference, source.display_name as source_name,
  source.source_class, source.rights_status, source.authenticity_tier,
  event.authenticity_score, event.corroboration_count, event.verification_status,
  event.severity, event.novelty_score, event.source_published_at,
  event.observed_at, event.expires_at, event.synthetic, event.model_eligible
from public.global_event_records event
join public.global_event_source_registry source on source.id = event.source_id
left join public.countries country on country.id = event.origin_country_id
where event.display_eligible and event.expires_at > now() and source.enabled;

create view public.global_event_impact_graph
with (security_invoker = true)
as
select edge.id, edge.edge_key, event.id as event_id, event.event_key,
  event.event_type, event.normalized_summary as event_summary,
  country.iso_code as origin_country_code, event.region_code,
  edge.sequence_number, from_entity.entity_kind as from_entity_kind,
  from_entity.entity_key, from_entity.display_name as from_entity_name,
  to_entity.entity_kind as to_entity_kind, to_entity.entity_key as target_entity_key,
  to_entity.display_name as to_entity_name, edge.mechanism,
  edge.impact_direction, edge.probability, edge.confidence_score,
  edge.horizon, edge.lag_description, edge.rationale, edge.assumptions,
  edge.target_asset_id, asset.symbol as target_symbol, edge.estimated_effect_low_pct,
  edge.estimated_effect_high_pct, edge.terminal_edge,
  edge.scenario_version, edge.human_review_required,
  edge.synthetic, edge.production_effect, event.source_published_at
from public.global_event_impact_edges edge
join public.global_event_records event on event.id = edge.event_id
join public.global_event_source_registry source on source.id = event.source_id
join public.global_event_entities from_entity on from_entity.id = edge.from_entity_id
join public.global_event_entities to_entity on to_entity.id = edge.to_entity_id
left join public.countries country on country.id = event.origin_country_id
left join public.market_assets asset on asset.id = edge.target_asset_id
where event.display_eligible and event.expires_at > now() and source.enabled;

create view public.global_country_intelligence_coverage
with (security_invoker = true)
as
select country.iso_code as country_code, country.name as country_name,
  country.region, profile.coverage_status, profile.monitored_event_types,
  profile.approved_source_count, profile.provider_coverage_enabled,
  count(event.id)::integer as current_event_count,
  max(event.source_published_at) as latest_event_at,
  case
    when count(event.id) = 0 then 'catalogued_no_current_event'
    when bool_and(event.synthetic) then 'synthetic_scenario_only'
    else 'evidence_available'
  end as evidence_state,
  profile.last_evaluated_at, profile.profile_version
from public.global_country_intelligence_profiles profile
join public.countries country on country.id = profile.country_id
left join public.global_event_records event
  on event.origin_country_id = country.id
  and event.display_eligible and event.expires_at > now()
  and exists (
    select 1 from public.global_event_source_registry source
    where source.id = event.source_id and source.enabled
  )
group by country.iso_code, country.name, country.region,
  profile.coverage_status, profile.monitored_event_types,
  profile.approved_source_count, profile.provider_coverage_enabled,
  profile.last_evaluated_at, profile.profile_version;

grant select on public.global_event_intelligence_status,
  public.global_event_signal_catalog, public.global_event_impact_graph,
  public.global_country_intelligence_coverage to anon, authenticated, service_role;

do $$
begin
  if exists (
    select 1 from public.global_event_intelligence_controls
    where raw_web_scraping_enabled or credentialed_source_bypass_enabled
      or unlicensed_content_storage_enabled
      or automatic_verification_without_evidence_enabled or rumor_promotion_enabled
      or autonomous_publication_enabled or production_provider_connectivity_enabled
      or autonomous_trade_execution_enabled or customer_funding_enabled
      or custody_enabled or settlement_enabled
  ) then
    raise exception 'Phase 8F cannot deploy with unsafe ingestion, publication, execution, funding, custody, or settlement capabilities';
  end if;
  if exists (
    select 1 from public.global_event_records
    where (synthetic and model_eligible)
      or (verification_status = 'verified' and (corroboration_count < 2 or authenticity_score < 0.7))
  ) then
    raise exception 'Phase 8F event evidence violates authenticity or model-eligibility policy';
  end if;
  if exists (
    select 1 from public.global_event_impact_edges
    where production_effect or not human_review_required or (synthetic and model_eligible)
  ) then
    raise exception 'Phase 8F impact scenarios must remain review-only and non-executable';
  end if;
end;
$$;

comment on table public.global_event_intelligence_controls is 'Fail-closed Phase 8F policy for structured global event intelligence and probabilistic scenario analysis.';
comment on table public.global_event_records is 'Append-only normalized event records with source rights, authenticity, corroboration and time-cutoff evidence; raw content is not stored.';
comment on table public.global_event_impact_edges is 'Append-only causal graph edges and probabilistic impact ranges; every scenario requires human review and has no production effect.';
comment on table public.user_global_event_alert_policies is 'Private customer alert filters; delivery remains in-app and never authorizes a trade or payment.';
