-- TradePulse AI
-- Migration 052: Phase 8H global evidence corroboration operations
-- This is a fail-closed intake and review control plane. It connects no provider,
-- stores no raw licensed content, publishes no claim, trains no model, and cannot trade.

create table public.global_evidence_operations_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  country_coverage_target integer not null default 195 check (country_coverage_target = 195),
  immutable_provenance_required boolean not null default true check (immutable_provenance_required),
  source_rights_review_required boolean not null default true check (source_rights_review_required),
  independent_corroboration_required boolean not null default true check (independent_corroboration_required),
  conflict_review_required boolean not null default true check (conflict_review_required),
  human_publication_review_required boolean not null default true check (human_publication_review_required),
  minimum_independent_sources integer not null default 2 check (minimum_independent_sources between 2 and 5),
  connected_source_count integer not null default 0 check (connected_source_count = 0),
  raw_web_scraping_enabled boolean not null default false check (not raw_web_scraping_enabled),
  private_source_access_enabled boolean not null default false check (not private_source_access_enabled),
  credential_bypass_enabled boolean not null default false check (not credential_bypass_enabled),
  unlicensed_content_storage_enabled boolean not null default false check (not unlicensed_content_storage_enabled),
  automatic_verification_enabled boolean not null default false check (not automatic_verification_enabled),
  rumor_promotion_enabled boolean not null default false check (not rumor_promotion_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  production_ingestion_enabled boolean not null default false check (not production_ingestion_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_evidence_operations_controls (control_key, policy_version)
values ('global-evidence-operations', 'global-evidence-policy-v1');

create table public.global_evidence_source_lanes (
  id bigint generated by default as identity primary key,
  lane_key text not null unique,
  display_name text not null,
  source_class text not null check (source_class in (
    'official_authority', 'regulator_exchange', 'licensed_news',
    'licensed_logistics', 'licensed_geoscience'
  )),
  review_priority smallint not null check (review_priority between 1 and 5),
  supported_claim_classes text[] not null check (cardinality(supported_claim_classes) between 1 and 8),
  rights_status text not null default 'review_required' check (rights_status in ('review_required', 'approved', 'rejected')),
  authenticity_status text not null default 'review_required' check (authenticity_status in ('review_required', 'approved', 'rejected')),
  privacy_status text not null default 'review_required' check (privacy_status in ('review_required', 'approved', 'rejected')),
  security_status text not null default 'review_required' check (security_status in ('review_required', 'approved', 'rejected')),
  retention_status text not null default 'review_required' check (retention_status in ('review_required', 'approved', 'rejected')),
  connectivity_status text not null default 'disconnected' check (connectivity_status = 'disconnected'),
  ingestion_enabled boolean not null default false check (not ingestion_enabled),
  publication_enabled boolean not null default false check (not publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  raw_content_storage_enabled boolean not null default false check (not raw_content_storage_enabled),
  review_note text not null check (char_length(review_note) between 20 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.global_evidence_source_lanes (
  lane_key, display_name, source_class, review_priority,
  supported_claim_classes, review_note
) values
  ('official-authority-lane', 'Official authority evidence', 'official_authority', 1,
    array['macro_data','monetary_policy','resource_discovery','public_infrastructure'],
    'Named authorities require rights, authenticity, privacy, security and retention review before connection.'),
  ('regulator-exchange-lane', 'Regulator and exchange evidence', 'regulator_exchange', 1,
    array['regulation','market_structure','issuer_disclosure'],
    'Named regulators and exchanges require exact endpoint, usage-rights and publication review before connection.'),
  ('licensed-news-lane', 'Licensed global news evidence', 'licensed_news', 2,
    array['geopolitics','corporate_event','energy_supply','technology'],
    'Only contractually licensed news metadata may enter after provenance, retention and model-use rights are approved.'),
  ('licensed-logistics-lane', 'Licensed logistics evidence', 'licensed_logistics', 2,
    array['logistics_disruption','trade_flow','shipping_capacity'],
    'Logistics observations require licensed access, temporal alignment and independent corroboration before use.'),
  ('licensed-geoscience-lane', 'Licensed geoscience evidence', 'licensed_geoscience', 2,
    array['resource_discovery','extreme_weather','natural_hazard'],
    'Geoscience observations require authority attribution, location confidence and expert review before use.');

create table public.global_evidence_corroboration_policies (
  id bigint generated by default as identity primary key,
  claim_class text not null unique,
  display_name text not null,
  minimum_independent_sources smallint not null check (minimum_independent_sources between 2 and 5),
  minimum_primary_sources smallint not null check (minimum_primary_sources between 1 and minimum_independent_sources),
  maximum_source_age_hours integer not null check (maximum_source_age_hours between 1 and 8760),
  geographic_alignment_required boolean not null default true,
  temporal_alignment_required boolean not null default true check (temporal_alignment_required),
  conflict_resolution text not null check (conflict_resolution in ('hold_for_human_review', 'reject_until_resolved')),
  human_review_required boolean not null default true check (human_review_required),
  publication_enabled boolean not null default false check (not publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  policy_version text not null default 'corroboration-policy-v1',
  created_at timestamptz not null default now()
);

insert into public.global_evidence_corroboration_policies (
  claim_class, display_name, minimum_independent_sources,
  minimum_primary_sources, maximum_source_age_hours,
  geographic_alignment_required, conflict_resolution
) values
  ('resource_discovery', 'Resource discovery', 3, 1, 720, true, 'reject_until_resolved'),
  ('energy_supply', 'Energy supply change', 3, 1, 72, true, 'hold_for_human_review'),
  ('logistics_disruption', 'Logistics disruption', 2, 1, 24, true, 'hold_for_human_review'),
  ('monetary_policy', 'Monetary policy', 2, 1, 24, true, 'reject_until_resolved'),
  ('market_structure', 'Market structure or venue change', 2, 1, 24, false, 'reject_until_resolved'),
  ('extreme_weather', 'Extreme weather', 3, 1, 12, true, 'hold_for_human_review');

create table public.global_evidence_review_cases (
  id bigint generated by default as identity primary key,
  case_key text not null unique,
  claim_class text not null references public.global_evidence_corroboration_policies(claim_class),
  country_scope text not null check (country_scope = 'GLOBAL' or country_scope ~ '^[A-Z]{2}$'),
  rehearsal_summary text not null check (char_length(rehearsal_summary) between 30 and 500),
  evidence_digest text not null check (evidence_digest ~ '^[a-f0-9]{64}$'),
  independent_source_count smallint not null default 0 check (independent_source_count = 0),
  primary_source_count smallint not null default 0 check (primary_source_count = 0),
  rights_status text not null default 'evidence_missing' check (rights_status = 'evidence_missing'),
  authenticity_status text not null default 'evidence_missing' check (authenticity_status = 'evidence_missing'),
  corroboration_status text not null default 'evidence_missing' check (corroboration_status = 'evidence_missing'),
  conflict_status text not null default 'not_evaluated' check (conflict_status = 'not_evaluated'),
  review_status text not null default 'blocked' check (review_status = 'blocked'),
  synthetic boolean not null default true check (synthetic),
  display_eligible boolean not null default false check (not display_eligible),
  publication_eligible boolean not null default false check (not publication_eligible),
  model_eligible boolean not null default false check (not model_eligible),
  execution_effect boolean not null default false check (not execution_effect),
  observed_at timestamptz not null,
  created_at timestamptz not null default now()
);

insert into public.global_evidence_review_cases (
  case_key, claim_class, country_scope, rehearsal_summary,
  evidence_digest, observed_at
)
select fixture.case_key, fixture.claim_class, fixture.country_scope,
  fixture.summary, md5(fixture.case_key || ':phase8h') || md5(fixture.case_key || ':evidence'),
  '2026-09-15 08:00:00+00'::timestamptz
from (values
  ('rehearsal-resource-discovery', 'resource_discovery', 'IN',
    'Synthetic intake drill for a reported mineral discovery; no real discovery, source or country assertion is represented.'),
  ('rehearsal-energy-supply', 'energy_supply', 'GLOBAL',
    'Synthetic intake drill for a reported energy supply change; no real producer decision or supply movement is represented.'),
  ('rehearsal-logistics-disruption', 'logistics_disruption', 'GLOBAL',
    'Synthetic intake drill for a reported logistics disruption; no real route, shipment or facility condition is represented.'),
  ('rehearsal-monetary-policy', 'monetary_policy', 'GB',
    'Synthetic intake drill for a reported monetary policy change; no real central-bank decision or rate move is represented.'),
  ('rehearsal-extreme-weather', 'extreme_weather', 'US',
    'Synthetic intake drill for a reported severe weather event; no real forecast, location or economic impact is represented.')
) as fixture(case_key, claim_class, country_scope, summary);

create table public.global_evidence_review_stages (
  id bigint generated by default as identity primary key,
  review_case_id bigint not null references public.global_evidence_review_cases(id) on delete cascade,
  sequence_number smallint not null check (sequence_number between 1 and 8),
  stage_key text not null check (stage_key in (
    'source_rights', 'source_authenticity', 'extraction_integrity',
    'temporal_alignment', 'independent_corroboration', 'conflict_resolution',
    'editorial_approval', 'model_eligibility'
  )),
  stage_status text not null default 'evidence_missing' check (stage_status = 'evidence_missing'),
  requirement_note text not null check (char_length(requirement_note) between 20 and 300),
  human_review_required boolean not null default true check (human_review_required),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_case_id, stage_key),
  unique (review_case_id, sequence_number)
);

insert into public.global_evidence_review_stages (
  review_case_id, sequence_number, stage_key, requirement_note
)
select review_case.id, stage.sequence_number, stage.stage_key, stage.requirement_note
from public.global_evidence_review_cases review_case
cross join (values
  (1, 'source_rights', 'Verify access, storage, display, derivation and model-use rights for every exact source.'),
  (2, 'source_authenticity', 'Verify publisher identity, endpoint ownership, signatures and immutable provenance.'),
  (3, 'extraction_integrity', 'Reconcile normalized fields to the licensed source without storing prohibited raw content.'),
  (4, 'temporal_alignment', 'Prove publication, observation and processing times obey the no-future-data boundary.'),
  (5, 'independent_corroboration', 'Meet the claim-specific independent and primary-source thresholds.'),
  (6, 'conflict_resolution', 'Hold or reject conflicting material claims until a human resolves the evidence.'),
  (7, 'editorial_approval', 'Require an accountable human decision before customer-visible publication.'),
  (8, 'model_eligibility', 'Evaluate licensing, leakage, quality and bias separately before any training use.')
) as stage(sequence_number, stage_key, requirement_note);

create table public.global_evidence_decision_ledger (
  id bigint generated by default as identity primary key,
  review_case_id bigint not null references public.global_evidence_review_cases(id),
  decision_status text not null check (decision_status in ('blocked', 'rejected')),
  evidence_digest text not null check (evidence_digest ~ '^[a-f0-9]{64}$'),
  reviewer_reference_digest text,
  decision_note text not null check (char_length(decision_note) between 20 and 300),
  publication_effect boolean not null default false check (not publication_effect),
  model_effect boolean not null default false check (not model_effect),
  execution_effect boolean not null default false check (not execution_effect),
  decided_at timestamptz not null default now()
);

insert into public.global_evidence_decision_ledger (
  review_case_id, decision_status, evidence_digest, decision_note
)
select id, 'blocked', evidence_digest,
  'Synthetic rehearsal remains blocked because every external evidence stage is missing.'
from public.global_evidence_review_cases;

alter table public.global_evidence_operations_controls enable row level security;
alter table public.global_evidence_source_lanes enable row level security;
alter table public.global_evidence_corroboration_policies enable row level security;
alter table public.global_evidence_review_cases enable row level security;
alter table public.global_evidence_review_stages enable row level security;
alter table public.global_evidence_decision_ledger enable row level security;

create policy "Public reads evidence operation controls"
  on public.global_evidence_operations_controls for select to anon, authenticated using (workspace_enabled);
create policy "Public reads evidence source lanes"
  on public.global_evidence_source_lanes for select to anon, authenticated using (true);
create policy "Public reads corroboration policies"
  on public.global_evidence_corroboration_policies for select to anon, authenticated using (true);
create policy "Public reads synthetic evidence cases"
  on public.global_evidence_review_cases for select to anon, authenticated using (synthetic);
create policy "Public reads evidence review stages"
  on public.global_evidence_review_stages for select to anon, authenticated using (
    exists (
      select 1 from public.global_evidence_review_cases review_case
      where review_case.id = global_evidence_review_stages.review_case_id
        and review_case.synthetic
    )
  );

revoke all on table public.global_evidence_operations_controls,
  public.global_evidence_source_lanes, public.global_evidence_corroboration_policies,
  public.global_evidence_review_cases, public.global_evidence_review_stages,
  public.global_evidence_decision_ledger from public, anon, authenticated, service_role;

grant select on table public.global_evidence_operations_controls,
  public.global_evidence_source_lanes, public.global_evidence_corroboration_policies,
  public.global_evidence_review_stages
  to anon, authenticated, service_role;
grant select (
  id, case_key, claim_class, country_scope, rehearsal_summary,
  independent_source_count, primary_source_count, rights_status,
  authenticity_status, corroboration_status, conflict_status, review_status,
  synthetic, display_eligible, publication_eligible, model_eligible,
  observed_at, created_at
) on public.global_evidence_review_cases to anon, authenticated;
grant select on public.global_evidence_review_cases to service_role;
grant select, insert on table public.global_evidence_decision_ledger to service_role;
grant usage, select on sequence public.global_evidence_decision_ledger_id_seq to service_role;

create or replace function public.prevent_global_evidence_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global evidence review records are append-only';
end;
$$;

revoke all on function public.prevent_global_evidence_mutation() from public, anon, authenticated;
create trigger global_evidence_review_cases_append_only
  before update or delete on public.global_evidence_review_cases
  for each row execute function public.prevent_global_evidence_mutation();
create trigger global_evidence_review_stages_append_only
  before update or delete on public.global_evidence_review_stages
  for each row execute function public.prevent_global_evidence_mutation();
create trigger global_evidence_decisions_append_only
  before update or delete on public.global_evidence_decision_ledger
  for each row execute function public.prevent_global_evidence_mutation();

create view public.global_evidence_operations_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_evidence_source_lanes)::integer source_lane_count,
  (select count(*) from public.global_evidence_source_lanes where ingestion_enabled)::integer enabled_source_lane_count,
  (select count(*) from public.global_evidence_corroboration_policies)::integer corroboration_policy_count,
  (select count(*) from public.global_evidence_review_cases)::integer rehearsal_case_count,
  (select count(*) from public.global_evidence_review_cases where publication_eligible)::integer publication_eligible_case_count
from public.global_evidence_operations_controls control;

create view public.global_evidence_source_lane_catalog with (security_invoker=true) as
select id, lane_key, display_name, source_class, review_priority,
  supported_claim_classes, rights_status, authenticity_status, privacy_status,
  security_status, retention_status, connectivity_status, ingestion_enabled,
  publication_enabled, model_training_enabled, review_note
from public.global_evidence_source_lanes;

create view public.global_evidence_corroboration_catalog with (security_invoker=true) as
select id, claim_class, display_name, minimum_independent_sources,
  minimum_primary_sources, maximum_source_age_hours,
  geographic_alignment_required, temporal_alignment_required,
  conflict_resolution, human_review_required, publication_enabled,
  model_training_enabled, policy_version
from public.global_evidence_corroboration_policies;

create view public.global_evidence_review_queue_catalog with (security_invoker=true) as
select review_case.id, review_case.case_key, review_case.claim_class,
  policy.display_name claim_class_name, review_case.country_scope,
  review_case.rehearsal_summary, review_case.independent_source_count,
  policy.minimum_independent_sources required_independent_sources,
  review_case.primary_source_count, policy.minimum_primary_sources required_primary_sources,
  review_case.rights_status, review_case.authenticity_status,
  review_case.corroboration_status, review_case.conflict_status,
  review_case.review_status, review_case.synthetic, review_case.display_eligible,
  review_case.publication_eligible, review_case.model_eligible,
  review_case.observed_at,
  (select count(*) from public.global_evidence_review_stages stage
    where stage.review_case_id = review_case.id)::integer stage_count,
  (select count(*) from public.global_evidence_review_stages stage
    where stage.review_case_id = review_case.id and stage.stage_status = 'evidence_missing')::integer blocking_stage_count
from public.global_evidence_review_cases review_case
join public.global_evidence_corroboration_policies policy
  on policy.claim_class = review_case.claim_class;

create view public.global_evidence_review_stage_catalog with (security_invoker=true) as
select stage.id, stage.review_case_id, review_case.case_key,
  stage.sequence_number, stage.stage_key, stage.stage_status,
  stage.requirement_note, stage.human_review_required, stage.production_effect
from public.global_evidence_review_stages stage
join public.global_evidence_review_cases review_case on review_case.id = stage.review_case_id;

grant select on public.global_evidence_operations_status,
  public.global_evidence_source_lane_catalog,
  public.global_evidence_corroboration_catalog,
  public.global_evidence_review_queue_catalog,
  public.global_evidence_review_stage_catalog to anon, authenticated, service_role;

do $$
begin
  if exists (
    select 1 from public.global_evidence_operations_controls
    where connected_source_count <> 0 or raw_web_scraping_enabled
      or private_source_access_enabled or credential_bypass_enabled
      or unlicensed_content_storage_enabled or automatic_verification_enabled
      or rumor_promotion_enabled or autonomous_publication_enabled
      or production_ingestion_enabled or model_training_enabled
      or autonomous_trade_execution_enabled
  ) then
    raise exception 'Phase 8H evidence operations must remain fail-closed';
  end if;
  if exists (
    select 1 from public.global_evidence_source_lanes
    where connectivity_status <> 'disconnected' or ingestion_enabled
      or publication_enabled or model_training_enabled or raw_content_storage_enabled
  ) or exists (
    select 1 from public.global_evidence_review_cases
    where not synthetic or review_status <> 'blocked' or display_eligible
      or publication_eligible or model_eligible or execution_effect
  ) then
    raise exception 'Phase 8H source or review boundary changed';
  end if;
end;
$$;

comment on table public.global_evidence_operations_controls is
  'Fail-closed Phase 8H evidence intake policy; connecting a provider requires a later reviewed migration.';
comment on table public.global_evidence_review_cases is
  'Synthetic review drills only; raw source content and real claims are not stored by Phase 8H.';
comment on table public.global_evidence_decision_ledger is
  'Restricted append-only decision evidence with no publication, model or execution effect.';
