begin;

-- Migration 053: Phase 8I global country intelligence coverage fabric
-- Reference identities and explicit evidence gaps only. No live provider, generated
-- country fact, model-training, publication or execution path is introduced here.

create table public.global_country_coverage_controls (
  control_key text primary key check (control_key = 'global-country-coverage'),
  policy_version text not null check (policy_version = 'global-country-coverage-v1'),
  workspace_enabled boolean not null default true check (workspace_enabled),
  sovereign_country_target integer not null default 195 check (sovereign_country_target = 195),
  intelligence_domain_target integer not null default 8 check (intelligence_domain_target = 8),
  sovereign_reference_catalog_enabled boolean not null default true check (sovereign_reference_catalog_enabled),
  explicit_evidence_gaps_required boolean not null default true check (explicit_evidence_gaps_required),
  source_rights_review_required boolean not null default true check (source_rights_review_required),
  independent_corroboration_required boolean not null default true check (independent_corroboration_required),
  temporal_freshness_required boolean not null default true check (temporal_freshness_required),
  human_release_review_required boolean not null default true check (human_release_review_required),
  live_provider_connectivity_enabled boolean not null default false check (not live_provider_connectivity_enabled),
  generated_fact_fill_enabled boolean not null default false check (not generated_fact_fill_enabled),
  automatic_country_scoring_enabled boolean not null default false check (not automatic_country_scoring_enabled),
  production_ingestion_enabled boolean not null default false check (not production_ingestion_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_country_coverage_controls (control_key, policy_version)
values ('global-country-coverage', 'global-country-coverage-v1');

create table public.global_sovereign_country_reference (
  id bigint generated by default as identity primary key,
  country_code text not null unique check (country_code ~ '^[A-Z]{2}$'),
  country_name text not null unique check (char_length(country_name) between 2 and 80),
  region_group text not null check (region_group in ('Africa', 'Americas', 'Asia', 'Europe', 'Oceania')),
  existing_country_id bigint references public.countries(id),
  reference_status text not null default 'reference_only' check (reference_status = 'reference_only'),
  approved_source_count integer not null default 0 check (approved_source_count = 0),
  current_observation_count integer not null default 0 check (current_observation_count = 0),
  completeness_status text not null default 'evidence_missing' check (completeness_status = 'evidence_missing'),
  synthetic_fact_count integer not null default 0 check (synthetic_fact_count = 0),
  publication_eligible boolean not null default false check (not publication_eligible),
  model_eligible boolean not null default false check (not model_eligible),
  execution_effect boolean not null default false check (not execution_effect),
  created_at timestamptz not null default now()
);

insert into public.global_sovereign_country_reference (
  country_code, country_name, region_group, existing_country_id
)
select fixture.country_code, fixture.country_name, fixture.region_group, country.id
from (values
  ('DZ','Algeria','Africa'),('AO','Angola','Africa'),('BJ','Benin','Africa'),('BW','Botswana','Africa'),
  ('BF','Burkina Faso','Africa'),('BI','Burundi','Africa'),('CV','Cabo Verde','Africa'),('CM','Cameroon','Africa'),
  ('CF','Central African Republic','Africa'),('TD','Chad','Africa'),('KM','Comoros','Africa'),
  ('CD','Democratic Republic of the Congo','Africa'),('CG','Republic of the Congo','Africa'),
  ('CI','Côte d''Ivoire','Africa'),('DJ','Djibouti','Africa'),('EG','Egypt','Africa'),
  ('GQ','Equatorial Guinea','Africa'),('ER','Eritrea','Africa'),('SZ','Eswatini','Africa'),
  ('ET','Ethiopia','Africa'),('GA','Gabon','Africa'),('GM','Gambia','Africa'),('GH','Ghana','Africa'),
  ('GN','Guinea','Africa'),('GW','Guinea-Bissau','Africa'),('KE','Kenya','Africa'),('LS','Lesotho','Africa'),
  ('LR','Liberia','Africa'),('LY','Libya','Africa'),('MG','Madagascar','Africa'),('MW','Malawi','Africa'),
  ('ML','Mali','Africa'),('MR','Mauritania','Africa'),('MU','Mauritius','Africa'),('MA','Morocco','Africa'),
  ('MZ','Mozambique','Africa'),('NA','Namibia','Africa'),('NE','Niger','Africa'),('NG','Nigeria','Africa'),
  ('RW','Rwanda','Africa'),('ST','São Tomé and Príncipe','Africa'),('SN','Senegal','Africa'),
  ('SC','Seychelles','Africa'),('SL','Sierra Leone','Africa'),('SO','Somalia','Africa'),
  ('ZA','South Africa','Africa'),('SS','South Sudan','Africa'),('SD','Sudan','Africa'),
  ('TZ','Tanzania','Africa'),('TG','Togo','Africa'),('TN','Tunisia','Africa'),('UG','Uganda','Africa'),
  ('ZM','Zambia','Africa'),('ZW','Zimbabwe','Africa'),
  ('AG','Antigua and Barbuda','Americas'),('AR','Argentina','Americas'),('BS','Bahamas','Americas'),
  ('BB','Barbados','Americas'),('BZ','Belize','Americas'),('BO','Bolivia','Americas'),
  ('BR','Brazil','Americas'),('CA','Canada','Americas'),('CL','Chile','Americas'),('CO','Colombia','Americas'),
  ('CR','Costa Rica','Americas'),('CU','Cuba','Americas'),('DM','Dominica','Americas'),
  ('DO','Dominican Republic','Americas'),('EC','Ecuador','Americas'),('SV','El Salvador','Americas'),
  ('GD','Grenada','Americas'),('GT','Guatemala','Americas'),('GY','Guyana','Americas'),('HT','Haiti','Americas'),
  ('HN','Honduras','Americas'),('JM','Jamaica','Americas'),('MX','Mexico','Americas'),
  ('NI','Nicaragua','Americas'),('PA','Panama','Americas'),('PY','Paraguay','Americas'),('PE','Peru','Americas'),
  ('KN','Saint Kitts and Nevis','Americas'),('LC','Saint Lucia','Americas'),
  ('VC','Saint Vincent and the Grenadines','Americas'),('SR','Suriname','Americas'),
  ('TT','Trinidad and Tobago','Americas'),('US','United States','Americas'),('UY','Uruguay','Americas'),
  ('VE','Venezuela','Americas'),
  ('AF','Afghanistan','Asia'),('AM','Armenia','Asia'),('AZ','Azerbaijan','Asia'),('BH','Bahrain','Asia'),
  ('BD','Bangladesh','Asia'),('BT','Bhutan','Asia'),('BN','Brunei','Asia'),('KH','Cambodia','Asia'),
  ('CN','China','Asia'),('CY','Cyprus','Asia'),('GE','Georgia','Asia'),('IN','India','Asia'),
  ('ID','Indonesia','Asia'),('IR','Iran','Asia'),('IQ','Iraq','Asia'),('IL','Israel','Asia'),
  ('JP','Japan','Asia'),('JO','Jordan','Asia'),('KZ','Kazakhstan','Asia'),('KW','Kuwait','Asia'),
  ('KG','Kyrgyzstan','Asia'),('LA','Laos','Asia'),('LB','Lebanon','Asia'),('MY','Malaysia','Asia'),
  ('MV','Maldives','Asia'),('MN','Mongolia','Asia'),('MM','Myanmar','Asia'),('NP','Nepal','Asia'),
  ('KP','North Korea','Asia'),('OM','Oman','Asia'),('PK','Pakistan','Asia'),('PS','State of Palestine','Asia'),
  ('PH','Philippines','Asia'),('QA','Qatar','Asia'),('SA','Saudi Arabia','Asia'),('SG','Singapore','Asia'),
  ('KR','South Korea','Asia'),('LK','Sri Lanka','Asia'),('SY','Syria','Asia'),('TJ','Tajikistan','Asia'),
  ('TH','Thailand','Asia'),('TL','Timor-Leste','Asia'),('TR','Türkiye','Asia'),('TM','Turkmenistan','Asia'),
  ('AE','United Arab Emirates','Asia'),('UZ','Uzbekistan','Asia'),('VN','Vietnam','Asia'),('YE','Yemen','Asia'),
  ('AL','Albania','Europe'),('AD','Andorra','Europe'),('AT','Austria','Europe'),('BY','Belarus','Europe'),
  ('BE','Belgium','Europe'),('BA','Bosnia and Herzegovina','Europe'),('BG','Bulgaria','Europe'),
  ('HR','Croatia','Europe'),('CZ','Czechia','Europe'),('DK','Denmark','Europe'),('EE','Estonia','Europe'),
  ('FI','Finland','Europe'),('FR','France','Europe'),('DE','Germany','Europe'),('GR','Greece','Europe'),
  ('VA','Holy See','Europe'),('HU','Hungary','Europe'),('IS','Iceland','Europe'),('IE','Ireland','Europe'),
  ('IT','Italy','Europe'),('LV','Latvia','Europe'),('LI','Liechtenstein','Europe'),('LT','Lithuania','Europe'),
  ('LU','Luxembourg','Europe'),('MT','Malta','Europe'),('MD','Moldova','Europe'),('MC','Monaco','Europe'),
  ('ME','Montenegro','Europe'),('NL','Netherlands','Europe'),('MK','North Macedonia','Europe'),
  ('NO','Norway','Europe'),('PL','Poland','Europe'),('PT','Portugal','Europe'),('RO','Romania','Europe'),
  ('RU','Russian Federation','Europe'),('SM','San Marino','Europe'),('RS','Serbia','Europe'),
  ('SK','Slovakia','Europe'),('SI','Slovenia','Europe'),('ES','Spain','Europe'),('SE','Sweden','Europe'),
  ('CH','Switzerland','Europe'),('UA','Ukraine','Europe'),('GB','United Kingdom','Europe'),
  ('AU','Australia','Oceania'),('FJ','Fiji','Oceania'),('KI','Kiribati','Oceania'),
  ('MH','Marshall Islands','Oceania'),('FM','Micronesia','Oceania'),('NR','Nauru','Oceania'),
  ('NZ','New Zealand','Oceania'),('PW','Palau','Oceania'),('PG','Papua New Guinea','Oceania'),
  ('WS','Samoa','Oceania'),('SB','Solomon Islands','Oceania'),('TO','Tonga','Oceania'),
  ('TV','Tuvalu','Oceania'),('VU','Vanuatu','Oceania')
) as fixture(country_code, country_name, region_group)
left join public.countries country on country.iso_code = fixture.country_code;

create table public.global_country_intelligence_domains (
  id bigint generated by default as identity primary key,
  domain_key text not null unique check (domain_key in (
    'macro_economy','currency_monetary','resources_commodities','trade_flows',
    'logistics_supply_chain','markets_corporates','climate_weather','geopolitics_regulation'
  )),
  display_name text not null unique,
  coverage_question text not null check (char_length(coverage_question) between 30 and 240),
  minimum_independent_sources smallint not null check (minimum_independent_sources between 2 and 4),
  maximum_source_age_hours integer not null check (maximum_source_age_hours between 6 and 8760),
  primary_source_required boolean not null default true check (primary_source_required),
  human_review_required boolean not null default true check (human_review_required),
  provider_connected boolean not null default false check (not provider_connected),
  automatic_fill_enabled boolean not null default false check (not automatic_fill_enabled),
  publication_enabled boolean not null default false check (not publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_country_intelligence_domains (
  domain_key, display_name, coverage_question, minimum_independent_sources, maximum_source_age_hours
) values
  ('macro_economy','Macro economy','What verified growth, inflation, labour, fiscal and public-finance evidence is current for this country?',2,744),
  ('currency_monetary','Currency and monetary policy','What official currency, rates, reserves and monetary-policy evidence is current and independently reconciled?',2,168),
  ('resources_commodities','Resources and commodities','What licensed evidence supports resource reserves, discoveries, production, imports, exports and substitution risk?',3,8760),
  ('trade_flows','Trade flows','What official bilateral trade, tariff and product-flow evidence is complete for the current reporting period?',2,1488),
  ('logistics_supply_chain','Logistics and supply chain','What licensed port, route, capacity, transit-time and landed-cost evidence is fresh enough to use?',3,24),
  ('markets_corporates','Markets and corporates','What exchange, issuer, filing, corporate-action and market-rights evidence is approved for display?',2,24),
  ('climate_weather','Climate and weather','What authoritative hazard, forecast and observed-impact evidence is geographically and temporally aligned?',2,6),
  ('geopolitics_regulation','Geopolitics and regulation','What official policy, sanctions, election, conflict and regulatory evidence has completed human review?',3,24);

create table public.global_country_intelligence_coverage_matrix (
  id bigint generated by default as identity primary key,
  country_reference_id bigint not null references public.global_sovereign_country_reference(id),
  intelligence_domain_id bigint not null references public.global_country_intelligence_domains(id),
  coverage_status text not null default 'evidence_missing' check (coverage_status = 'evidence_missing'),
  approved_source_count integer not null default 0 check (approved_source_count = 0),
  approved_observation_count integer not null default 0 check (approved_observation_count = 0),
  latest_verified_at timestamptz check (latest_verified_at is null),
  provenance_digest text check (provenance_digest is null),
  gap_reason text not null default 'No approved source observation has completed the Phase 8H evidence workflow.'
    check (char_length(gap_reason) between 20 and 220),
  publication_eligible boolean not null default false check (not publication_eligible),
  model_eligible boolean not null default false check (not model_eligible),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (country_reference_id, intelligence_domain_id)
);

insert into public.global_country_intelligence_coverage_matrix (
  country_reference_id, intelligence_domain_id
)
select country.id, domain.id
from public.global_sovereign_country_reference country
cross join public.global_country_intelligence_domains domain;

create table public.global_country_coverage_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  gate_key text not null unique check (gate_key in (
    'source_rights','country_identity','temporal_freshness','cross_source_reconciliation',
    'dependency_validation','uncertainty_calibration','human_release'
  )),
  display_name text not null unique,
  requirement_note text not null check (char_length(requirement_note) between 30 and 260),
  blocks_publication boolean not null default true check (blocks_publication),
  blocks_model_use boolean not null default true check (blocks_model_use),
  automatic_approval_enabled boolean not null default false check (not automatic_approval_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_country_coverage_gate_templates (
  sequence_number, gate_key, display_name, requirement_note
) values
  (1,'source_rights','Source rights','Approve the exact provider, endpoint, display, retention, derivation and model-use rights.'),
  (2,'country_identity','Country identity','Reconcile sovereign, territory, market, currency and reporting identities without silently merging scopes.'),
  (3,'temporal_freshness','Temporal freshness','Prove publication, observation and processing timestamps satisfy the domain-specific freshness window.'),
  (4,'cross_source_reconciliation','Cross-source reconciliation','Meet the domain-specific independent and primary-source thresholds and retain conflicts as unresolved.'),
  (5,'dependency_validation','Dependency validation','Review commodity, trade, logistics, currency and market dependencies before calculating any impact path.'),
  (6,'uncertainty_calibration','Uncertainty calibration','Measure coverage, revision, bias and scenario uncertainty without converting missing evidence into a score.'),
  (7,'human_release','Human release','Require an accountable human decision before display, publication, model use or downstream analysis.' );

alter table public.global_country_coverage_controls enable row level security;
alter table public.global_sovereign_country_reference enable row level security;
alter table public.global_country_intelligence_domains enable row level security;
alter table public.global_country_intelligence_coverage_matrix enable row level security;
alter table public.global_country_coverage_gate_templates enable row level security;

create policy "Public reads country coverage controls" on public.global_country_coverage_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads sovereign country references" on public.global_sovereign_country_reference
  for select to anon, authenticated using (reference_status = 'reference_only');
create policy "Public reads country intelligence domains" on public.global_country_intelligence_domains
  for select to anon, authenticated using (true);
create policy "Public reads explicit country evidence gaps" on public.global_country_intelligence_coverage_matrix
  for select to anon, authenticated using (coverage_status = 'evidence_missing');
create policy "Public reads country coverage gates" on public.global_country_coverage_gate_templates
  for select to anon, authenticated using (true);

revoke all on table public.global_country_coverage_controls,
  public.global_sovereign_country_reference, public.global_country_intelligence_domains,
  public.global_country_intelligence_coverage_matrix,
  public.global_country_coverage_gate_templates from public, anon, authenticated, service_role;
grant select on table public.global_country_coverage_controls,
  public.global_sovereign_country_reference, public.global_country_intelligence_domains,
  public.global_country_intelligence_coverage_matrix,
  public.global_country_coverage_gate_templates to anon, authenticated, service_role;

create or replace function public.prevent_global_country_coverage_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global country coverage reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_country_coverage_mutation() from public, anon, authenticated;

create trigger global_sovereign_country_reference_append_only
  before update or delete on public.global_sovereign_country_reference
  for each row execute function public.prevent_global_country_coverage_mutation();
create trigger global_country_intelligence_domains_append_only
  before update or delete on public.global_country_intelligence_domains
  for each row execute function public.prevent_global_country_coverage_mutation();
create trigger global_country_coverage_matrix_append_only
  before update or delete on public.global_country_intelligence_coverage_matrix
  for each row execute function public.prevent_global_country_coverage_mutation();
create trigger global_country_coverage_gates_append_only
  before update or delete on public.global_country_coverage_gate_templates
  for each row execute function public.prevent_global_country_coverage_mutation();

create view public.global_country_coverage_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_sovereign_country_reference)::integer reference_country_count,
  (select count(*) from public.global_sovereign_country_reference where existing_country_id is not null)::integer mapped_product_country_count,
  (select count(*) from public.global_sovereign_country_reference where approved_source_count > 0)::integer evidenced_country_count,
  (select count(*) from public.global_country_intelligence_domains)::integer intelligence_domain_count,
  (select count(*) from public.global_country_intelligence_coverage_matrix)::integer coverage_cell_count,
  (select count(*) from public.global_country_intelligence_coverage_matrix where coverage_status = 'evidence_missing')::integer evidence_gap_count,
  (select count(*) from public.global_country_coverage_gate_templates)::integer review_gate_count
from public.global_country_coverage_controls control;

create view public.global_sovereign_country_catalog with (security_invoker=true) as
select country.id, country.country_code, country.country_name, country.region_group,
  country.existing_country_id, country.reference_status, country.approved_source_count,
  country.current_observation_count, country.completeness_status,
  count(matrix.id)::integer intelligence_domain_count,
  count(matrix.id) filter (where matrix.coverage_status = 'evidence_missing')::integer missing_domain_count,
  array_agg(domain.domain_key order by domain.id) filter (where matrix.coverage_status = 'evidence_missing') missing_domain_keys,
  country.publication_eligible, country.model_eligible
from public.global_sovereign_country_reference country
join public.global_country_intelligence_coverage_matrix matrix on matrix.country_reference_id = country.id
join public.global_country_intelligence_domains domain on domain.id = matrix.intelligence_domain_id
group by country.id;

create view public.global_country_intelligence_domain_catalog with (security_invoker=true) as
select domain.id, domain.domain_key, domain.display_name, domain.coverage_question,
  domain.minimum_independent_sources, domain.maximum_source_age_hours,
  domain.primary_source_required, domain.human_review_required,
  domain.provider_connected, domain.automatic_fill_enabled,
  count(matrix.id)::integer country_count,
  count(matrix.id) filter (where matrix.coverage_status = 'evidence_missing')::integer missing_country_count
from public.global_country_intelligence_domains domain
join public.global_country_intelligence_coverage_matrix matrix on matrix.intelligence_domain_id = domain.id
group by domain.id;

create view public.global_country_coverage_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, display_name, requirement_note,
  blocks_publication, blocks_model_use, automatic_approval_enabled
from public.global_country_coverage_gate_templates;

grant select on public.global_country_coverage_status,
  public.global_sovereign_country_catalog,
  public.global_country_intelligence_domain_catalog,
  public.global_country_coverage_gate_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_sovereign_country_reference) <> 195
    or (select count(*) from public.global_country_intelligence_domains) <> 8
    or (select count(*) from public.global_country_intelligence_coverage_matrix) <> 1560
    or (select count(*) from public.global_country_coverage_gate_templates) <> 7 then
    raise exception 'Phase 8I country coverage reference counts changed';
  end if;
  if exists (
    select 1 from public.global_country_coverage_controls
    where live_provider_connectivity_enabled or generated_fact_fill_enabled
      or automatic_country_scoring_enabled or production_ingestion_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_sovereign_country_reference
    where approved_source_count <> 0 or current_observation_count <> 0
      or synthetic_fact_count <> 0 or completeness_status <> 'evidence_missing'
      or publication_eligible or model_eligible or execution_effect
  ) or exists (
    select 1 from public.global_country_intelligence_coverage_matrix
    where coverage_status <> 'evidence_missing' or approved_source_count <> 0
      or approved_observation_count <> 0 or latest_verified_at is not null
      or provenance_digest is not null or publication_eligible
      or model_eligible or production_effect
  ) then
    raise exception 'Phase 8I country coverage must remain an explicit-gap reference fabric';
  end if;
end;
$$;

comment on table public.global_sovereign_country_reference is
  'Phase 8I reference identities for 193 UN members plus the Holy See and State of Palestine; not evidence of country conditions.';
comment on table public.global_country_intelligence_coverage_matrix is
  'Explicit country-domain evidence gaps. Missing values cannot be filled with generated facts.';
comment on table public.global_country_coverage_gate_templates is
  'Seven human-governed gates required before later releases may attach approved country observations.';

commit;
