-- TradePulse AI
-- Migration 054: Phase 8J global dependency and transmission readiness fabric
-- Evidence requirements and mechanism templates only. No inferred relationships,
-- generated country facts, autonomous publication, model training, or execution.

begin;

create table public.global_dependency_transmission_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  sovereign_country_target integer not null default 195 check (sovereign_country_target = 195),
  dependency_domain_target integer not null default 8 check (dependency_domain_target = 8),
  explicit_relationship_gaps_required boolean not null default true check (explicit_relationship_gaps_required),
  directed_relationship_evidence_required boolean not null default true check (directed_relationship_evidence_required),
  temporal_alignment_required boolean not null default true check (temporal_alignment_required),
  exposure_magnitude_required boolean not null default true check (exposure_magnitude_required),
  substitute_path_review_required boolean not null default true check (substitute_path_review_required),
  human_release_review_required boolean not null default true check (human_release_review_required),
  live_provider_connectivity_enabled boolean not null default false check (not live_provider_connectivity_enabled),
  automatic_relationship_inference_enabled boolean not null default false check (not automatic_relationship_inference_enabled),
  generated_dependency_fill_enabled boolean not null default false check (not generated_dependency_fill_enabled),
  automatic_impact_scoring_enabled boolean not null default false check (not automatic_impact_scoring_enabled),
  production_scenario_promotion_enabled boolean not null default false check (not production_scenario_promotion_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_dependency_transmission_controls (control_key, policy_version)
values ('global-dependency-transmission', 'global-dependency-transmission-v1');

create table public.global_dependency_intelligence_domains (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  domain_key text not null unique check (domain_key in (
    'bilateral_trade','commodity_supply','energy_flows','logistics_routes',
    'currency_funding','monetary_policy','corporate_supply_chain','climate_regulatory'
  )),
  display_name text not null unique,
  relationship_question text not null check (char_length(relationship_question) between 30 and 260),
  transmission_mechanism text not null check (transmission_mechanism in (
    'trade','supply','energy','logistics','currency','rates','corporate','climate_policy'
  )),
  required_evidence_classes text[] not null check (cardinality(required_evidence_classes) between 2 and 6),
  minimum_independent_sources smallint not null check (minimum_independent_sources between 2 and 4),
  maximum_source_age_hours integer not null check (maximum_source_age_hours between 6 and 8760),
  directional_evidence_required boolean not null default true check (directional_evidence_required),
  magnitude_evidence_required boolean not null default true check (magnitude_evidence_required),
  substitution_review_required boolean not null default true check (substitution_review_required),
  provider_connected boolean not null default false check (not provider_connected),
  automatic_inference_enabled boolean not null default false check (not automatic_inference_enabled),
  publication_enabled boolean not null default false check (not publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_dependency_intelligence_domains (
  sequence_number, domain_key, display_name, relationship_question,
  transmission_mechanism, required_evidence_classes,
  minimum_independent_sources, maximum_source_age_hours
) values
  (1,'bilateral_trade','Bilateral trade','Which directed product and service flows connect two economies, in what units, period and reporting scope?','trade',array['official_trade','customs_or_statistics','classification_mapping'],2,1488),
  (2,'commodity_supply','Commodity supply','Which verified reserves, production, processing, consumption and substitution links transmit a commodity shock?','supply',array['official_geoscience','production_statistics','licensed_market_data'],3,8760),
  (3,'energy_flows','Energy flows','Which origin, transit, storage, refining and destination evidence supports a directed energy dependency?','energy',array['official_energy','licensed_flow_data','infrastructure_reference'],3,168),
  (4,'logistics_routes','Logistics routes','Which ports, corridors, modes, capacity, transit-time and alternate-route evidence supports a logistics path?','logistics',array['licensed_logistics','port_authority','route_reference'],3,24),
  (5,'currency_funding','Currency and funding','Which invoicing, reserve, settlement, FX and cross-border funding evidence supports a currency exposure?','currency',array['central_bank','official_balance_data','licensed_market_data'],2,24),
  (6,'monetary_policy','Monetary policy transmission','Which official rate, liquidity, inflation and funding evidence supports a cross-market policy transmission path?','rates',array['central_bank','official_statistics','licensed_market_data'],2,24),
  (7,'corporate_supply_chain','Corporate supply chain','Which filing, supplier, customer, geography and concentration evidence supports a corporate dependency?','corporate',array['issuer_filing','licensed_corporate_data','product_mapping'],3,168),
  (8,'climate_regulatory','Climate and regulatory','Which authoritative hazard, physical exposure, policy and legal-scope evidence supports a climate or regulatory path?','climate_policy',array['official_hazard','regulator_or_law','geospatial_reference'],3,24);

create table public.global_country_dependency_readiness (
  id bigint generated by default as identity primary key,
  country_reference_id bigint not null references public.global_sovereign_country_reference(id),
  dependency_domain_id bigint not null references public.global_dependency_intelligence_domains(id),
  readiness_status text not null default 'relationship_evidence_missing'
    check (readiness_status = 'relationship_evidence_missing'),
  approved_source_count integer not null default 0 check (approved_source_count = 0),
  verified_relationship_count integer not null default 0 check (verified_relationship_count = 0),
  upstream_link_count integer not null default 0 check (upstream_link_count = 0),
  downstream_link_count integer not null default 0 check (downstream_link_count = 0),
  latest_verified_at timestamptz check (latest_verified_at is null),
  provenance_digest text check (provenance_digest is null),
  gap_reason text not null default 'No directed dependency relationship has completed rights, corroboration, magnitude, substitution and human review.'
    check (char_length(gap_reason) between 30 and 240),
  scenario_eligible boolean not null default false check (not scenario_eligible),
  model_eligible boolean not null default false check (not model_eligible),
  publication_eligible boolean not null default false check (not publication_eligible),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (country_reference_id, dependency_domain_id)
);

insert into public.global_country_dependency_readiness (
  country_reference_id, dependency_domain_id
)
select country.id, domain.id
from public.global_sovereign_country_reference country
cross join public.global_dependency_intelligence_domains domain;

create table public.global_transmission_mechanism_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 6),
  template_key text not null unique check (template_key in (
    'supply_expansion','route_disruption','currency_repricing',
    'rate_change','climate_shock','regulatory_change'
  )),
  display_name text not null unique,
  origin_state text not null check (char_length(origin_state) between 10 and 120),
  intermediary_state text not null check (char_length(intermediary_state) between 10 and 160),
  downstream_state text not null check (char_length(downstream_state) between 10 and 160),
  explanation text not null check (char_length(explanation) between 40 and 320),
  template_status text not null default 'template_only' check (template_status = 'template_only'),
  probability numeric(6,5) check (probability is null),
  confidence_score numeric(6,5) check (confidence_score is null),
  estimated_effect_low_pct numeric(8,4) check (estimated_effect_low_pct is null),
  estimated_effect_high_pct numeric(8,4) check (estimated_effect_high_pct is null),
  evidence_required boolean not null default true check (evidence_required),
  human_review_required boolean not null default true check (human_review_required),
  automatic_scenario_generation_enabled boolean not null default false check (not automatic_scenario_generation_enabled),
  model_eligible boolean not null default false check (not model_eligible),
  publication_eligible boolean not null default false check (not publication_eligible),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_transmission_mechanism_templates (
  sequence_number, template_key, display_name, origin_state,
  intermediary_state, downstream_state, explanation
) values
  (1,'supply_expansion','Supply expansion','Verified change in available supply','Reconciled production, inventory, substitution and time-to-market path','Conditional availability, trade-balance and price-pressure scenarios','A discovery or production change becomes analyzable only after commercial timing, quality, substitution and cross-border flow evidence are verified.'),
  (2,'route_disruption','Route disruption','Verified capacity or access disruption','Alternate-route capacity, delay, insurance and inventory absorption','Conditional freight, landed-cost, margin and inflation scenarios','A route event must be traced through measured capacity and feasible substitutes instead of assuming every market receives the same shock.'),
  (3,'currency_repricing','Currency repricing','Verified currency or funding repricing','Invoicing currency, hedge coverage, settlement timing and import exposure','Conditional cost, margin, inflation and valuation scenarios','FX movement is not treated as a uniform country impact; contractual currency, hedging, timing and pass-through evidence are required.'),
  (4,'rate_change','Rate change','Verified policy or market-rate change','Funding structure, duration, liquidity and transmission lag','Conditional currency, credit, demand and valuation scenarios','A policy-rate event requires evidence for the actual funding channels and lags before it can support a market-impact scenario.'),
  (5,'climate_shock','Climate shock','Verified physical hazard and affected geography','Asset exposure, duration, inventories, insurance and replacement capacity','Conditional output, logistics, supply and price scenarios','Hazard evidence must be geographically aligned with verified economic exposure and feasible recovery paths before impact analysis.'),
  (6,'regulatory_change','Regulatory change','Verified rule, sanction or legal-scope change','Effective date, jurisdiction, entity, product and compliance pathway','Conditional access, cost, trade-flow and corporate scenarios','Policy headlines do not establish exposure; the exact legal scope, effective date and affected relationship must complete human review.' );

create table public.global_dependency_release_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique check (gate_key in (
    'source_rights','directed_identity','unit_scope','temporal_alignment',
    'exposure_magnitude','substitution_path','uncertainty_calibration','human_release'
  )),
  display_name text not null unique,
  requirement_note text not null check (char_length(requirement_note) between 30 and 280),
  blocks_scenario_use boolean not null default true check (blocks_scenario_use),
  blocks_model_use boolean not null default true check (blocks_model_use),
  blocks_publication boolean not null default true check (blocks_publication),
  automatic_approval_enabled boolean not null default false check (not automatic_approval_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_dependency_release_gate_templates (
  sequence_number, gate_key, display_name, requirement_note
) values
  (1,'source_rights','Source rights','Approve the exact source, endpoint, field, display, retention, derivation and model-use rights.'),
  (2,'directed_identity','Directed identity','Verify origin, destination, entity, product, currency, route and legal scope without reversing the relationship.'),
  (3,'unit_scope','Unit and scope','Reconcile units, classifications, nominal or real basis, gross or net scope and aggregation boundaries.'),
  (4,'temporal_alignment','Temporal alignment','Align observation, publication, revision, effective and market timestamps within the domain freshness window.'),
  (5,'exposure_magnitude','Exposure magnitude','Require an approved quantity, denominator, concentration and materiality basis before calculating sensitivity.'),
  (6,'substitution_path','Substitution path','Review alternate suppliers, routes, currencies, inventories, hedges and implementation delays.'),
  (7,'uncertainty_calibration','Uncertainty calibration','Separate evidence quality, relationship stability, scenario probability and impact range without filling a gap.'),
  (8,'human_release','Human release','Require an accountable decision before any dependency supports a scenario, model, publication or downstream analysis.');

alter table public.global_dependency_transmission_controls enable row level security;
alter table public.global_dependency_intelligence_domains enable row level security;
alter table public.global_country_dependency_readiness enable row level security;
alter table public.global_transmission_mechanism_templates enable row level security;
alter table public.global_dependency_release_gate_templates enable row level security;

create policy "Public reads dependency controls" on public.global_dependency_transmission_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads dependency domains" on public.global_dependency_intelligence_domains
  for select to anon, authenticated using (true);
create policy "Public reads dependency readiness gaps" on public.global_country_dependency_readiness
  for select to anon, authenticated using (readiness_status = 'relationship_evidence_missing');
create policy "Public reads transmission templates" on public.global_transmission_mechanism_templates
  for select to anon, authenticated using (template_status = 'template_only');
create policy "Public reads dependency gates" on public.global_dependency_release_gate_templates
  for select to anon, authenticated using (true);

revoke all on table public.global_dependency_transmission_controls,
  public.global_dependency_intelligence_domains, public.global_country_dependency_readiness,
  public.global_transmission_mechanism_templates,
  public.global_dependency_release_gate_templates from public, anon, authenticated, service_role;
grant select on table public.global_dependency_transmission_controls,
  public.global_dependency_intelligence_domains, public.global_country_dependency_readiness,
  public.global_transmission_mechanism_templates,
  public.global_dependency_release_gate_templates to anon, authenticated, service_role;

create or replace function public.prevent_global_dependency_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global dependency transmission reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_dependency_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_dependency_domains_append_only
  before update or delete on public.global_dependency_intelligence_domains
  for each row execute function public.prevent_global_dependency_reference_mutation();
create trigger global_country_dependency_readiness_append_only
  before update or delete on public.global_country_dependency_readiness
  for each row execute function public.prevent_global_dependency_reference_mutation();
create trigger global_transmission_templates_append_only
  before update or delete on public.global_transmission_mechanism_templates
  for each row execute function public.prevent_global_dependency_reference_mutation();
create trigger global_dependency_gates_append_only
  before update or delete on public.global_dependency_release_gate_templates
  for each row execute function public.prevent_global_dependency_reference_mutation();

create view public.global_dependency_transmission_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_sovereign_country_reference)::integer reference_country_count,
  (select count(*) from public.global_dependency_intelligence_domains)::integer dependency_domain_count,
  (select count(*) from public.global_country_dependency_readiness)::integer readiness_cell_count,
  (select count(*) from public.global_country_dependency_readiness where readiness_status = 'relationship_evidence_missing')::integer relationship_gap_count,
  (select coalesce(sum(verified_relationship_count), 0) from public.global_country_dependency_readiness)::integer verified_relationship_count,
  (select count(*) from public.global_transmission_mechanism_templates)::integer mechanism_template_count,
  (select count(*) from public.global_dependency_release_gate_templates)::integer review_gate_count
from public.global_dependency_transmission_controls control;

create view public.global_dependency_domain_catalog with (security_invoker=true) as
select domain.id, domain.sequence_number, domain.domain_key, domain.display_name,
  domain.relationship_question, domain.transmission_mechanism,
  domain.required_evidence_classes, domain.minimum_independent_sources,
  domain.maximum_source_age_hours, domain.directional_evidence_required,
  domain.magnitude_evidence_required, domain.substitution_review_required,
  domain.provider_connected, domain.automatic_inference_enabled,
  count(readiness.id)::integer country_count,
  count(readiness.id) filter (where readiness.readiness_status = 'relationship_evidence_missing')::integer missing_country_count
from public.global_dependency_intelligence_domains domain
join public.global_country_dependency_readiness readiness on readiness.dependency_domain_id = domain.id
group by domain.id;

create view public.global_country_dependency_readiness_catalog with (security_invoker=true) as
select country.id, country.country_code, country.country_name, country.region_group,
  count(readiness.id)::integer dependency_domain_count,
  count(readiness.id) filter (where readiness.readiness_status = 'relationship_evidence_missing')::integer missing_domain_count,
  array_agg(domain.domain_key order by domain.sequence_number)
    filter (where readiness.readiness_status = 'relationship_evidence_missing') missing_domain_keys,
  sum(readiness.verified_relationship_count)::integer verified_relationship_count,
  sum(readiness.upstream_link_count)::integer upstream_link_count,
  sum(readiness.downstream_link_count)::integer downstream_link_count,
  bool_or(readiness.scenario_eligible) scenario_eligible,
  bool_or(readiness.model_eligible) model_eligible,
  bool_or(readiness.publication_eligible) publication_eligible
from public.global_sovereign_country_reference country
join public.global_country_dependency_readiness readiness on readiness.country_reference_id = country.id
join public.global_dependency_intelligence_domains domain on domain.id = readiness.dependency_domain_id
group by country.id;

create view public.global_transmission_mechanism_catalog with (security_invoker=true) as
select id, sequence_number, template_key, display_name, origin_state,
  intermediary_state, downstream_state, explanation, template_status,
  probability, confidence_score, estimated_effect_low_pct,
  estimated_effect_high_pct, evidence_required, human_review_required,
  automatic_scenario_generation_enabled, model_eligible,
  publication_eligible, production_effect
from public.global_transmission_mechanism_templates;

create view public.global_dependency_release_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, display_name, requirement_note,
  blocks_scenario_use, blocks_model_use, blocks_publication,
  automatic_approval_enabled
from public.global_dependency_release_gate_templates;

grant select on public.global_dependency_transmission_status,
  public.global_dependency_domain_catalog,
  public.global_country_dependency_readiness_catalog,
  public.global_transmission_mechanism_catalog,
  public.global_dependency_release_gate_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_dependency_intelligence_domains) <> 8
    or (select count(*) from public.global_country_dependency_readiness) <> 1560
    or (select count(*) from public.global_transmission_mechanism_templates) <> 6
    or (select count(*) from public.global_dependency_release_gate_templates) <> 8 then
    raise exception 'Phase 8J dependency transmission reference counts changed';
  end if;
  if exists (
    select 1 from public.global_dependency_transmission_controls
    where live_provider_connectivity_enabled or automatic_relationship_inference_enabled
      or generated_dependency_fill_enabled or automatic_impact_scoring_enabled
      or production_scenario_promotion_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_country_dependency_readiness
    where readiness_status <> 'relationship_evidence_missing'
      or approved_source_count <> 0 or verified_relationship_count <> 0
      or upstream_link_count <> 0 or downstream_link_count <> 0
      or latest_verified_at is not null or provenance_digest is not null
      or scenario_eligible or model_eligible or publication_eligible or production_effect
  ) or exists (
    select 1 from public.global_transmission_mechanism_templates
    where probability is not null or confidence_score is not null
      or estimated_effect_low_pct is not null or estimated_effect_high_pct is not null
      or automatic_scenario_generation_enabled or model_eligible
      or publication_eligible or production_effect
  ) then
    raise exception 'Phase 8J dependency transmission fabric must remain evidence-empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_country_coverage_controls
    where live_provider_connectivity_enabled or generated_fact_fill_enabled
      or automatic_country_scoring_enabled or production_ingestion_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_event_intelligence_controls
    where raw_web_scraping_enabled or automatic_verification_without_evidence_enabled
      or rumor_promotion_enabled or production_provider_connectivity_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'An earlier country, evidence or execution lock changed';
  end if;
end;
$$;

comment on table public.global_country_dependency_readiness is
  'Phase 8J explicit relationship-evidence gaps for 195 countries across eight dependency domains; no relationship is inferred.';
comment on table public.global_transmission_mechanism_templates is
  'Evidence-empty transmission templates. They contain no country fact, probability, confidence, price effect or production action.';
comment on table public.global_dependency_release_gate_templates is
  'Eight human-governed gates required before a dependency may support scenarios, models or publication.';

commit;
