-- TradePulse AI
-- Migration 055: Phase 8K global observation provenance and quarantine fabric
-- Contract and readiness metadata only. No provider is connected, no observation
-- is ingested or released, and no fact, model, score, publication or execution is enabled.

begin;

create table public.global_observation_intake_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  normalization_contract_target integer not null default 9 check (normalization_contract_target = 9),
  quarantine_lane_target integer not null default 8 check (quarantine_lane_target = 8),
  immutable_provenance_required boolean not null default true check (immutable_provenance_required),
  source_rights_required boolean not null default true check (source_rights_required),
  schema_validation_required boolean not null default true check (schema_validation_required),
  unit_normalization_required boolean not null default true check (unit_normalization_required),
  temporal_lineage_required boolean not null default true check (temporal_lineage_required),
  independent_corroboration_required boolean not null default true check (independent_corroboration_required),
  conflict_quarantine_required boolean not null default true check (conflict_quarantine_required),
  human_release_review_required boolean not null default true check (human_release_review_required),
  live_provider_connectivity_enabled boolean not null default false check (not live_provider_connectivity_enabled),
  production_ingestion_enabled boolean not null default false check (not production_ingestion_enabled),
  automatic_normalization_approval_enabled boolean not null default false check (not automatic_normalization_approval_enabled),
  automatic_conflict_resolution_enabled boolean not null default false check (not automatic_conflict_resolution_enabled),
  automatic_release_enabled boolean not null default false check (not automatic_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_observation_intake_controls (control_key, policy_version)
values ('global-observation-provenance-quarantine', 'global-observation-provenance-quarantine-v1');

create table public.global_observation_source_connectors (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  source_family_key text not null unique check (source_family_key in (
    'official_statistics','central_bank','regulator_law','issuer_filing',
    'licensed_market_data','licensed_news','licensed_logistics','official_geoscience_hazard'
  )),
  display_name text not null unique,
  source_class text not null check (source_class in ('authoritative','regulated','issuer','licensed_commercial')),
  intended_observation_scope text not null check (char_length(intended_observation_scope) between 30 and 260),
  required_rights text[] not null check (cardinality(required_rights) between 3 and 8),
  required_provenance_fields text[] not null check (cardinality(required_provenance_fields) between 5 and 12),
  connector_status text not null default 'not_connected' check (connector_status = 'not_connected'),
  endpoint_approved boolean not null default false check (not endpoint_approved),
  credentials_configured boolean not null default false check (not credentials_configured),
  retention_approved boolean not null default false check (not retention_approved),
  display_rights_approved boolean not null default false check (not display_rights_approved),
  derivation_rights_approved boolean not null default false check (not derivation_rights_approved),
  model_use_rights_approved boolean not null default false check (not model_use_rights_approved),
  production_ingestion_enabled boolean not null default false check (not production_ingestion_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_observation_source_connectors (
  sequence_number, source_family_key, display_name, source_class,
  intended_observation_scope, required_rights, required_provenance_fields
) values
  (1,'official_statistics','Official statistics','authoritative','National and multilateral economic, demographic, trade and production observations published by accountable statistical authorities.',array['endpoint_access','display','retention','derivation'],array['publisher','dataset','series','observation_time','publication_time','revision','license']),
  (2,'central_bank','Central banks','regulated','Official rates, balance-sheet, reserve, liquidity, inflation and financial-system observations from monetary authorities.',array['endpoint_access','display','retention','derivation'],array['authority','release','series','observation_time','publication_time','revision','unit','license']),
  (3,'regulator_law','Regulators and law','regulated','Rules, sanctions, decisions and legal-scope observations with jurisdiction, effective date and authoritative text lineage.',array['endpoint_access','display','retention','quotation'],array['authority','instrument','jurisdiction','publication_time','effective_time','revision','license']),
  (4,'issuer_filing','Issuer filings','issuer','Company-reported financial, operational, geographic and risk observations tied to an exact filing and reporting period.',array['endpoint_access','display','retention','derivation'],array['issuer','filing','field','period','publication_time','revision','unit','license']),
  (5,'licensed_market_data','Licensed market data','licensed_commercial','Prices, rates, curves, reference data and corporate-action observations covered by explicit display and derivation rights.',array['endpoint_access','display','retention','derivation','model_use'],array['provider','feed','instrument','venue','observation_time','publication_time','revision','unit','license']),
  (6,'licensed_news','Licensed news','licensed_commercial','News metadata and permitted content fragments with publisher, timestamp, correction and downstream-use lineage.',array['endpoint_access','display','retention','quotation','model_use'],array['provider','publisher','item','publication_time','correction','language','license']),
  (7,'licensed_logistics','Licensed logistics','licensed_commercial','Port, route, vessel, freight, capacity and delay observations with geographic and temporal scope.',array['endpoint_access','display','retention','derivation','model_use'],array['provider','route','location','observation_time','publication_time','revision','unit','license']),
  (8,'official_geoscience_hazard','Official geoscience and hazard','authoritative','Geology, reserves, weather, climate and physical-hazard observations from accountable scientific authorities.',array['endpoint_access','display','retention','derivation'],array['authority','dataset','location','observation_time','publication_time','revision','unit','license']);

create table public.global_observation_normalization_contracts (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 9),
  contract_key text not null unique check (contract_key in (
    'source_identity','subject_identity','field_semantics','value_representation',
    'unit_currency','geography_scope','observation_time','publication_revision_lineage','license_lineage'
  )),
  display_name text not null unique,
  canonical_requirement text not null check (char_length(canonical_requirement) between 30 and 280),
  invalid_example text not null check (char_length(invalid_example) between 15 and 180),
  required_for_quarantine_entry boolean not null default true check (required_for_quarantine_entry),
  required_for_release boolean not null default true check (required_for_release),
  null_fabrication_forbidden boolean not null default true check (null_fabrication_forbidden),
  automatic_approval_enabled boolean not null default false check (not automatic_approval_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_observation_normalization_contracts (
  sequence_number, contract_key, display_name, canonical_requirement, invalid_example
) values
  (1,'source_identity','Source identity','Bind every candidate to the exact provider, publisher, endpoint, dataset and source record identifier.','A provider name without an endpoint, dataset or source record.'),
  (2,'subject_identity','Subject identity','Resolve the exact country, entity, instrument, product, route or legal instrument without fuzzy substitution.','A country or company name inferred from free text.'),
  (3,'field_semantics','Field semantics','Map the source field definition, population, aggregation, adjustment and sign convention to a versioned canonical field.','Treating similarly named fields as equivalent without definitions.'),
  (4,'value_representation','Value representation','Preserve source value, missingness, precision, scale and valid categorical domain before any normalized representation.','Replacing unavailable, suppressed or nil values with zero.'),
  (5,'unit_currency','Unit and currency','Declare unit, currency, price basis, multiplier, nominal or real basis and conversion lineage for every numeric value.','Comparing thousands of local currency with raw US dollars.'),
  (6,'geography_scope','Geography and scope','Attach authoritative geography, venue, route, jurisdiction and inclusion boundaries without widening the source scope.','Promoting a city, port or subsidiary observation to a country fact.'),
  (7,'observation_time','Observation time','Preserve the event or measurement time, period bounds and source time zone independently from receipt time.','Using ingestion time as the time of the measured event.'),
  (8,'publication_revision_lineage','Publication and revision lineage','Preserve publication, effective, correction and revision timestamps plus the replaced-record lineage.','Overwriting a prior vintage without a revision reference.'),
  (9,'license_lineage','License lineage','Attach approved access, display, retention, derivation and model-use rights to the exact source field and use case.','Assuming endpoint access grants redistribution or model rights.');

create table public.global_observation_quarantine_lanes (
  id bigint generated by default as identity primary key,
  source_connector_id bigint not null unique references public.global_observation_source_connectors(id),
  lane_status text not null default 'provider_not_connected' check (lane_status = 'provider_not_connected'),
  candidate_observation_count integer not null default 0 check (candidate_observation_count = 0),
  schema_valid_count integer not null default 0 check (schema_valid_count = 0),
  corroborated_count integer not null default 0 check (corroborated_count = 0),
  conflict_count integer not null default 0 check (conflict_count = 0),
  released_observation_count integer not null default 0 check (released_observation_count = 0),
  latest_received_at timestamptz check (latest_received_at is null),
  latest_released_at timestamptz check (latest_released_at is null),
  provenance_digest text check (provenance_digest is null),
  gap_reason text not null default 'No provider, endpoint or field is approved; the quarantine lane contains no candidate or released observation.'
    check (char_length(gap_reason) between 30 and 220),
  publication_eligible boolean not null default false check (not publication_eligible),
  model_eligible boolean not null default false check (not model_eligible),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_observation_quarantine_lanes (source_connector_id)
select id from public.global_observation_source_connectors;

create table public.global_observation_release_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique check (gate_key in (
    'source_rights','origin_authenticity','subject_field_identity','unit_scope_normalization',
    'temporal_revision_lineage','schema_quality','independent_corroboration','conflict_human_release'
  )),
  display_name text not null unique,
  requirement_note text not null check (char_length(requirement_note) between 30 and 280),
  blocks_publication boolean not null default true check (blocks_publication),
  blocks_model_use boolean not null default true check (blocks_model_use),
  blocks_downstream_analysis boolean not null default true check (blocks_downstream_analysis),
  automatic_approval_enabled boolean not null default false check (not automatic_approval_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_observation_release_gate_templates (
  sequence_number, gate_key, display_name, requirement_note
) values
  (1,'source_rights','Source rights','Approve endpoint access, display, retention, derivation, quotation and model-use rights for the exact source field and use case.'),
  (2,'origin_authenticity','Origin authenticity','Verify publisher identity, endpoint ownership, source record identity, signatures or other authoritative origin evidence.'),
  (3,'subject_field_identity','Subject and field identity','Resolve the exact subject and canonical field definition without fuzzy substitution or silent scope widening.'),
  (4,'unit_scope_normalization','Unit and scope normalization','Reconcile unit, currency, scale, price basis, geography, classification, aggregation and missing-value semantics.'),
  (5,'temporal_revision_lineage','Temporal and revision lineage','Preserve observation, period, publication, effective, correction, revision and receipt times without future-data leakage.'),
  (6,'schema_quality','Schema and quality','Validate required fields, types, ranges, null semantics, duplicate identity and deterministic normalization outcomes.'),
  (7,'independent_corroboration','Independent corroboration','Require the domain-specific independent evidence threshold and retain explicit disagreement instead of averaging it away.'),
  (8,'conflict_human_release','Conflict and human release','Keep conflicts quarantined until an accountable reviewer records a bounded release decision with immutable evidence.');

alter table public.global_observation_intake_controls enable row level security;
alter table public.global_observation_source_connectors enable row level security;
alter table public.global_observation_normalization_contracts enable row level security;
alter table public.global_observation_quarantine_lanes enable row level security;
alter table public.global_observation_release_gate_templates enable row level security;

create policy "Public reads observation intake controls" on public.global_observation_intake_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads observation source contracts" on public.global_observation_source_connectors
  for select to anon, authenticated using (connector_status = 'not_connected');
create policy "Public reads normalization contracts" on public.global_observation_normalization_contracts
  for select to anon, authenticated using (true);
create policy "Public reads empty quarantine lanes" on public.global_observation_quarantine_lanes
  for select to anon, authenticated using (lane_status = 'provider_not_connected');
create policy "Public reads observation release gates" on public.global_observation_release_gate_templates
  for select to anon, authenticated using (true);

revoke all on table public.global_observation_intake_controls,
  public.global_observation_source_connectors, public.global_observation_normalization_contracts,
  public.global_observation_quarantine_lanes,
  public.global_observation_release_gate_templates from public, anon, authenticated, service_role;
grant select on table public.global_observation_intake_controls,
  public.global_observation_source_connectors, public.global_observation_normalization_contracts,
  public.global_observation_quarantine_lanes,
  public.global_observation_release_gate_templates to anon, authenticated, service_role;

create or replace function public.prevent_global_observation_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global observation provenance reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_observation_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_observation_sources_append_only before update or delete on public.global_observation_source_connectors
  for each row execute function public.prevent_global_observation_reference_mutation();
create trigger global_observation_contracts_append_only before update or delete on public.global_observation_normalization_contracts
  for each row execute function public.prevent_global_observation_reference_mutation();
create trigger global_observation_lanes_append_only before update or delete on public.global_observation_quarantine_lanes
  for each row execute function public.prevent_global_observation_reference_mutation();
create trigger global_observation_gates_append_only before update or delete on public.global_observation_release_gate_templates
  for each row execute function public.prevent_global_observation_reference_mutation();

create view public.global_observation_intake_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_observation_source_connectors)::integer source_family_count,
  (select count(*) from public.global_observation_source_connectors where connector_status = 'not_connected')::integer disconnected_source_count,
  (select count(*) from public.global_observation_normalization_contracts)::integer normalization_contract_count,
  (select count(*) from public.global_observation_quarantine_lanes)::integer quarantine_lane_count,
  (select coalesce(sum(candidate_observation_count),0) from public.global_observation_quarantine_lanes)::integer candidate_observation_count,
  (select coalesce(sum(released_observation_count),0) from public.global_observation_quarantine_lanes)::integer released_observation_count,
  (select count(*) from public.global_observation_release_gate_templates)::integer release_gate_count
from public.global_observation_intake_controls control;

create view public.global_observation_source_catalog with (security_invoker=true) as
select source.id, source.sequence_number, source.source_family_key, source.display_name,
  source.source_class, source.intended_observation_scope, source.required_rights,
  source.required_provenance_fields, source.connector_status,
  source.endpoint_approved, source.credentials_configured, source.retention_approved,
  source.display_rights_approved, source.derivation_rights_approved,
  source.model_use_rights_approved, source.production_ingestion_enabled,
  lane.lane_status, lane.candidate_observation_count, lane.schema_valid_count,
  lane.corroborated_count, lane.conflict_count, lane.released_observation_count,
  lane.gap_reason, lane.publication_eligible, lane.model_eligible, lane.production_effect
from public.global_observation_source_connectors source
join public.global_observation_quarantine_lanes lane on lane.source_connector_id = source.id;

create view public.global_observation_normalization_catalog with (security_invoker=true) as
select id, sequence_number, contract_key, display_name, canonical_requirement,
  invalid_example, required_for_quarantine_entry, required_for_release,
  null_fabrication_forbidden, automatic_approval_enabled
from public.global_observation_normalization_contracts;

create view public.global_observation_release_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, display_name, requirement_note,
  blocks_publication, blocks_model_use, blocks_downstream_analysis,
  automatic_approval_enabled
from public.global_observation_release_gate_templates;

grant select on public.global_observation_intake_status,
  public.global_observation_source_catalog,
  public.global_observation_normalization_catalog,
  public.global_observation_release_gate_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_observation_source_connectors) <> 8
    or (select count(*) from public.global_observation_normalization_contracts) <> 9
    or (select count(*) from public.global_observation_quarantine_lanes) <> 8
    or (select count(*) from public.global_observation_release_gate_templates) <> 8 then
    raise exception 'Phase 8K observation provenance reference counts changed';
  end if;
  if exists (
    select 1 from public.global_observation_intake_controls
    where live_provider_connectivity_enabled or production_ingestion_enabled
      or automatic_normalization_approval_enabled or automatic_conflict_resolution_enabled
      or automatic_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_observation_source_connectors
    where connector_status <> 'not_connected' or endpoint_approved
      or credentials_configured or retention_approved or display_rights_approved
      or derivation_rights_approved or model_use_rights_approved
      or production_ingestion_enabled
  ) or exists (
    select 1 from public.global_observation_quarantine_lanes
    where lane_status <> 'provider_not_connected' or candidate_observation_count <> 0
      or schema_valid_count <> 0 or corroborated_count <> 0 or conflict_count <> 0
      or released_observation_count <> 0 or latest_received_at is not null
      or latest_released_at is not null or provenance_digest is not null
      or publication_eligible or model_eligible or production_effect
  ) then
    raise exception 'Phase 8K observation provenance fabric must remain empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_dependency_transmission_controls
    where live_provider_connectivity_enabled or automatic_relationship_inference_enabled
      or generated_dependency_fill_enabled or automatic_impact_scoring_enabled
      or production_scenario_promotion_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'An earlier dependency or execution lock changed';
  end if;
end;
$$;

comment on table public.global_observation_source_connectors is
  'Eight disconnected source-family contracts. No endpoint, credential, right or ingestion path is approved.';
comment on table public.global_observation_quarantine_lanes is
  'Phase 8K explicit empty quarantine lanes; no candidate or released observation exists.';
comment on table public.global_observation_release_gate_templates is
  'Eight human-governed gates required before a later release may admit an observation to downstream use.';

commit;
