-- TradePulse AI
-- Migration 056: Phase 8L provider certification and isolated intake readiness
-- Readiness metadata only. No provider is selected, connected or tested; no
-- credential, payload, candidate observation, release or production effect exists.

begin;

create table public.global_provider_certification_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  certification_gate_target integer not null default 10 check (certification_gate_target = 10),
  isolation_profile_target integer not null default 8 check (isolation_profile_target = 8),
  failure_drill_target integer not null default 6 check (failure_drill_target = 6),
  named_legal_owner_required boolean not null default true check (named_legal_owner_required),
  source_rights_review_required boolean not null default true check (source_rights_review_required),
  privacy_security_review_required boolean not null default true check (privacy_security_review_required),
  versioned_schema_contract_required boolean not null default true check (versioned_schema_contract_required),
  bounded_isolation_required boolean not null default true check (bounded_isolation_required),
  accountable_human_activation_required boolean not null default true check (accountable_human_activation_required),
  provider_selection_enabled boolean not null default false check (not provider_selection_enabled),
  endpoint_testing_enabled boolean not null default false check (not endpoint_testing_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  candidate_intake_enabled boolean not null default false check (not candidate_intake_enabled),
  production_ingestion_enabled boolean not null default false check (not production_ingestion_enabled),
  automatic_certification_enabled boolean not null default false check (not automatic_certification_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_certification_controls (control_key, policy_version)
values ('global-provider-certification-isolated-intake', 'global-provider-certification-isolated-intake-v1');

create table public.global_provider_certification_profiles (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  source_connector_id bigint not null unique references public.global_observation_source_connectors(id),
  source_family_key text not null unique,
  certification_status text not null default 'provider_unselected' check (certification_status = 'provider_unselected'),
  provider_legal_name text check (provider_legal_name is null),
  endpoint_domain text check (endpoint_domain is null),
  contract_reference text check (contract_reference is null),
  credential_reference text check (credential_reference is null),
  rights_review_status text not null default 'not_started' check (rights_review_status = 'not_started'),
  privacy_security_review_status text not null default 'not_started' check (privacy_security_review_status = 'not_started'),
  schema_review_status text not null default 'not_started' check (schema_review_status = 'not_started'),
  provenance_review_status text not null default 'not_started' check (provenance_review_status = 'not_started'),
  resilience_review_status text not null default 'not_started' check (resilience_review_status = 'not_started'),
  accountable_owner_assigned boolean not null default false check (not accountable_owner_assigned),
  certification_approved boolean not null default false check (not certification_approved),
  isolated_intake_approved boolean not null default false check (not isolated_intake_approved),
  production_effect boolean not null default false check (not production_effect),
  gap_reason text not null default 'No provider has been selected; contractual, security, schema, provenance and resilience reviews have not started.'
    check (char_length(gap_reason) between 40 and 220),
  created_at timestamptz not null default now()
);

insert into public.global_provider_certification_profiles (
  sequence_number, source_connector_id, source_family_key
)
select sequence_number, id, source_family_key
from public.global_observation_source_connectors
order by sequence_number;

create table public.global_provider_certification_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 10),
  gate_key text not null unique check (gate_key in (
    'legal_identity_ownership','contract_access_rights','display_retention_rights',
    'derivation_model_rights','privacy_data_protection','security_secret_handling',
    'endpoint_schema_certification','availability_rate_limits','revision_change_management',
    'accountable_human_signoff'
  )),
  display_name text not null unique,
  certification_requirement text not null check (char_length(certification_requirement) between 35 and 300),
  evidence_class text not null check (evidence_class in ('legal','rights','privacy','security','technical','operations','governance')),
  blocks_endpoint_test boolean not null default true check (blocks_endpoint_test),
  blocks_candidate_intake boolean not null default true check (blocks_candidate_intake),
  blocks_release boolean not null default true check (blocks_release),
  automatic_approval_enabled boolean not null default false check (not automatic_approval_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_provider_certification_gate_templates (
  sequence_number, gate_key, display_name, certification_requirement, evidence_class
) values
  (1,'legal_identity_ownership','Legal identity and source ownership','Verify the contracting entity, publisher authority, beneficial ownership where relevant and accountable source ownership.','legal'),
  (2,'contract_access_rights','Contract and access rights','Approve the exact products, endpoints, environments, territories, users and access methods covered by a signed agreement.','rights'),
  (3,'display_retention_rights','Display and retention rights','Record field-level display, caching, historical retention, deletion and customer redistribution permissions.','rights'),
  (4,'derivation_model_rights','Derivation and model-use rights','Record whether each field may support derived analytics, embeddings, model features, training, evaluation or customer outputs.','rights'),
  (5,'privacy_data_protection','Privacy and data protection','Complete data classification, lawful-basis, residency, processor, subprocessor, deletion and incident-notification review.','privacy'),
  (6,'security_secret_handling','Security and secret handling','Approve authentication, least privilege, rotation, encryption, audit, breach response and credential isolation controls.','security'),
  (7,'endpoint_schema_certification','Endpoint and schema certification','Certify endpoint ownership, protocol, versioned fields, null semantics, units, timestamps, revisions and deterministic fixtures.','technical'),
  (8,'availability_rate_limits','Availability and rate limits','Document service objectives, quotas, backoff, outage behavior, recovery evidence and fail-closed degradation rules.','operations'),
  (9,'revision_change_management','Revision and change management','Require notice, compatibility review, lineage preservation and rollback for source, contract, endpoint or schema changes.','operations'),
  (10,'accountable_human_signoff','Accountable human sign-off','Require named legal, privacy, security, data and product owners to approve a narrowly bounded non-production test.','governance');

create table public.global_isolated_intake_profiles (
  id bigint generated by default as identity primary key,
  certification_profile_id bigint not null unique references public.global_provider_certification_profiles(id),
  environment_status text not null default 'not_provisioned' check (environment_status = 'not_provisioned'),
  environment_reference text check (environment_reference is null),
  network_egress_enabled boolean not null default false check (not network_egress_enabled),
  credential_access_enabled boolean not null default false check (not credential_access_enabled),
  payload_storage_enabled boolean not null default false check (not payload_storage_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  maximum_candidate_rows integer not null default 0 check (maximum_candidate_rows = 0),
  destructive_test_data_only boolean not null default true check (destructive_test_data_only),
  quarantine_release_enabled boolean not null default false check (not quarantine_release_enabled),
  downstream_read_enabled boolean not null default false check (not downstream_read_enabled),
  publication_eligible boolean not null default false check (not publication_eligible),
  model_eligible boolean not null default false check (not model_eligible),
  production_effect boolean not null default false check (not production_effect),
  latest_tested_at timestamptz check (latest_tested_at is null),
  created_at timestamptz not null default now()
);

insert into public.global_isolated_intake_profiles (certification_profile_id)
select id from public.global_provider_certification_profiles;

create table public.global_provider_failure_drill_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 6),
  drill_key text not null unique check (drill_key in (
    'credential_exposure','source_spoofing','schema_drift','duplicate_replay',
    'rights_revocation','provider_outage_revision'
  )),
  display_name text not null unique,
  drill_requirement text not null check (char_length(drill_requirement) between 35 and 300),
  expected_safe_state text not null check (char_length(expected_safe_state) between 25 and 220),
  observed_drill_count integer not null default 0 check (observed_drill_count = 0),
  automatic_pass_enabled boolean not null default false check (not automatic_pass_enabled),
  manual_evidence_required boolean not null default true check (manual_evidence_required),
  blocks_certification boolean not null default true check (blocks_certification),
  created_at timestamptz not null default now()
);

insert into public.global_provider_failure_drill_templates (
  sequence_number, drill_key, display_name, drill_requirement, expected_safe_state
) values
  (1,'credential_exposure','Credential exposure','Rehearse immediate secret revocation, access-log review, incident escalation and evidence-preserving recovery.','No credential remains usable and no candidate or production observation is admitted.'),
  (2,'source_spoofing','Source spoofing','Rehearse certificate, signature, publisher identity and source-record validation failure at the intake boundary.','The source is rejected before storage and the provider profile remains uncertified.'),
  (3,'schema_drift','Schema drift','Rehearse missing fields, changed types, unit shifts, timestamp changes and incompatible enumerations.','The payload is rejected or isolated without defaulting, coercion or downstream propagation.'),
  (4,'duplicate_replay','Duplicate and replay','Rehearse duplicate source identifiers, replayed timestamps and retry storms under deterministic idempotency controls.','No duplicate candidate is created and no counter or downstream state is inflated.'),
  (5,'rights_revocation','Rights revocation','Rehearse immediate suspension when access, display, retention, derivation or model-use rights are withdrawn.','Connectivity stays disabled and affected data remains unavailable to publication and models.'),
  (6,'provider_outage_revision','Outage and revision','Rehearse stale feeds, corrections, revision chains and provider recovery without substituting fabricated observations.','Missingness and prior vintages remain explicit; no stale value is promoted as current.');

alter table public.global_provider_certification_controls enable row level security;
alter table public.global_provider_certification_profiles enable row level security;
alter table public.global_provider_certification_gate_templates enable row level security;
alter table public.global_isolated_intake_profiles enable row level security;
alter table public.global_provider_failure_drill_templates enable row level security;

create policy "Public reads provider certification controls" on public.global_provider_certification_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads unselected provider profiles" on public.global_provider_certification_profiles
  for select to anon, authenticated using (certification_status = 'provider_unselected');
create policy "Public reads certification gates" on public.global_provider_certification_gate_templates
  for select to anon, authenticated using (true);
create policy "Public reads unprovisioned isolation profiles" on public.global_isolated_intake_profiles
  for select to anon, authenticated using (environment_status = 'not_provisioned');
create policy "Public reads provider failure drills" on public.global_provider_failure_drill_templates
  for select to anon, authenticated using (true);

revoke all on table public.global_provider_certification_controls,
  public.global_provider_certification_profiles,
  public.global_provider_certification_gate_templates,
  public.global_isolated_intake_profiles,
  public.global_provider_failure_drill_templates from public, anon, authenticated, service_role;
grant select on table public.global_provider_certification_controls,
  public.global_provider_certification_profiles,
  public.global_provider_certification_gate_templates,
  public.global_isolated_intake_profiles,
  public.global_provider_failure_drill_templates to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_certification_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider certification reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_certification_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_profiles_append_only before update or delete on public.global_provider_certification_profiles
  for each row execute function public.prevent_global_provider_certification_reference_mutation();
create trigger global_provider_gates_append_only before update or delete on public.global_provider_certification_gate_templates
  for each row execute function public.prevent_global_provider_certification_reference_mutation();
create trigger global_isolated_intake_profiles_append_only before update or delete on public.global_isolated_intake_profiles
  for each row execute function public.prevent_global_provider_certification_reference_mutation();
create trigger global_provider_drills_append_only before update or delete on public.global_provider_failure_drill_templates
  for each row execute function public.prevent_global_provider_certification_reference_mutation();

create view public.global_provider_certification_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_certification_profiles)::integer source_family_count,
  (select count(*) from public.global_provider_certification_profiles where certification_status = 'provider_unselected')::integer unselected_provider_count,
  (select count(*) from public.global_provider_certification_profiles where certification_approved)::integer certified_provider_count,
  (select count(*) from public.global_provider_certification_gate_templates)::integer certification_gate_count,
  (select count(*) from public.global_isolated_intake_profiles)::integer isolation_profile_count,
  (select count(*) from public.global_isolated_intake_profiles where environment_status = 'not_provisioned')::integer unprovisioned_isolation_count,
  (select count(*) from public.global_provider_failure_drill_templates)::integer failure_drill_count,
  (select coalesce(sum(observed_drill_count),0) from public.global_provider_failure_drill_templates)::integer observed_drill_count
from public.global_provider_certification_controls control;

create view public.global_provider_certification_catalog with (security_invoker=true) as
select profile.id, profile.sequence_number, profile.source_family_key,
  source.display_name source_family_name, source.source_class,
  profile.certification_status, profile.rights_review_status,
  profile.privacy_security_review_status, profile.schema_review_status,
  profile.provenance_review_status, profile.resilience_review_status,
  profile.accountable_owner_assigned, profile.certification_approved,
  profile.isolated_intake_approved, profile.production_effect, profile.gap_reason
from public.global_provider_certification_profiles profile
join public.global_observation_source_connectors source on source.id = profile.source_connector_id;

create view public.global_provider_certification_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, display_name, certification_requirement,
  evidence_class, blocks_endpoint_test, blocks_candidate_intake, blocks_release,
  automatic_approval_enabled
from public.global_provider_certification_gate_templates;

create view public.global_isolated_intake_catalog with (security_invoker=true) as
select isolation.id, profile.sequence_number, profile.source_family_key,
  isolation.environment_status, isolation.network_egress_enabled,
  isolation.credential_access_enabled, isolation.payload_storage_enabled,
  isolation.candidate_write_enabled, isolation.maximum_candidate_rows,
  isolation.destructive_test_data_only, isolation.quarantine_release_enabled,
  isolation.downstream_read_enabled, isolation.publication_eligible,
  isolation.model_eligible, isolation.production_effect
from public.global_isolated_intake_profiles isolation
join public.global_provider_certification_profiles profile on profile.id = isolation.certification_profile_id;

create view public.global_provider_failure_drill_catalog with (security_invoker=true) as
select id, sequence_number, drill_key, display_name, drill_requirement,
  expected_safe_state, observed_drill_count, automatic_pass_enabled,
  manual_evidence_required, blocks_certification
from public.global_provider_failure_drill_templates;

grant select on public.global_provider_certification_status,
  public.global_provider_certification_catalog,
  public.global_provider_certification_gate_catalog,
  public.global_isolated_intake_catalog,
  public.global_provider_failure_drill_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_certification_profiles) <> 8
    or (select count(*) from public.global_provider_certification_gate_templates) <> 10
    or (select count(*) from public.global_isolated_intake_profiles) <> 8
    or (select count(*) from public.global_provider_failure_drill_templates) <> 6 then
    raise exception 'Phase 8L provider certification reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_certification_controls
    where provider_selection_enabled or endpoint_testing_enabled
      or credential_storage_enabled or candidate_intake_enabled
      or production_ingestion_enabled or automatic_certification_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_certification_profiles
    where certification_status <> 'provider_unselected' or provider_legal_name is not null
      or endpoint_domain is not null or contract_reference is not null
      or credential_reference is not null or accountable_owner_assigned
      or certification_approved or isolated_intake_approved or production_effect
  ) or exists (
    select 1 from public.global_isolated_intake_profiles
    where environment_status <> 'not_provisioned' or environment_reference is not null
      or network_egress_enabled or credential_access_enabled or payload_storage_enabled
      or candidate_write_enabled or maximum_candidate_rows <> 0
      or quarantine_release_enabled or downstream_read_enabled
      or publication_eligible or model_eligible or production_effect
      or latest_tested_at is not null
  ) then
    raise exception 'Phase 8L provider certification fabric must remain disconnected and fail-closed';
  end if;
  if exists (
    select 1 from public.global_observation_intake_controls
    where live_provider_connectivity_enabled or production_ingestion_enabled
      or automatic_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'An earlier observation or execution lock changed';
  end if;
end;
$$;

comment on table public.global_provider_certification_profiles is
  'Eight provider-family certification gaps. No provider name, endpoint, contract or credential is recorded.';
comment on table public.global_isolated_intake_profiles is
  'Unprovisioned isolation boundaries with zero candidate capacity and no downstream effect.';
comment on table public.global_provider_failure_drill_templates is
  'Six evidence-empty failure drills required before a future provider certification decision.';

commit;
