-- TradePulse AI
-- Migration 057: Phase 8M provider-neutral contract-test laboratory
-- Specification metadata only. No provider is selected, no endpoint or credential
-- is available, no payload is stored and no contract test is represented as run.

begin;

create table public.global_provider_contract_test_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  contract_suite_target integer not null default 8 check (contract_suite_target = 8),
  assertion_target integer not null default 10 check (assertion_target = 10),
  synthetic_fixture_target integer not null default 24 check (synthetic_fixture_target = 24),
  deterministic_fixture_required boolean not null default true check (deterministic_fixture_required),
  explicit_missingness_required boolean not null default true check (explicit_missingness_required),
  schema_version_required boolean not null default true check (schema_version_required),
  fail_closed_disposition_required boolean not null default true check (fail_closed_disposition_required),
  provider_selection_enabled boolean not null default false check (not provider_selection_enabled),
  endpoint_execution_enabled boolean not null default false check (not endpoint_execution_enabled),
  credential_access_enabled boolean not null default false check (not credential_access_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  synthetic_fixture_execution_enabled boolean not null default false check (not synthetic_fixture_execution_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  automatic_conformance_approval_enabled boolean not null default false check (not automatic_conformance_approval_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_contract_test_controls (control_key, policy_version)
values ('global-provider-contract-test-lab', 'global-provider-contract-test-lab-v1');

create table public.global_provider_contract_test_suites (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  certification_profile_id bigint not null unique references public.global_provider_certification_profiles(id),
  source_family_key text not null unique,
  suite_status text not null default 'specification_only' check (suite_status = 'specification_only'),
  schema_contract_version text not null default 'provider-neutral-v1' check (schema_contract_version = 'provider-neutral-v1'),
  provider_legal_name text check (provider_legal_name is null),
  endpoint_domain text check (endpoint_domain is null),
  credential_reference text check (credential_reference is null),
  external_payload_reference text check (external_payload_reference is null),
  executed_test_count integer not null default 0 check (executed_test_count = 0),
  passed_test_count integer not null default 0 check (passed_test_count = 0),
  conformance_approved boolean not null default false check (not conformance_approved),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  release_enabled boolean not null default false check (not release_enabled),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_contract_test_suites (
  sequence_number, certification_profile_id, source_family_key
)
select sequence_number, id, source_family_key
from public.global_provider_certification_profiles
order by sequence_number;

create table public.global_provider_contract_assertion_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 10),
  assertion_key text not null unique check (assertion_key in (
    'source_identity','subject_identity','schema_version','required_fields','field_types',
    'null_semantics','unit_currency','event_time_revision','provenance_rights',
    'deterministic_idempotency'
  )),
  display_name text not null unique,
  assertion_requirement text not null check (char_length(assertion_requirement) between 35 and 300),
  failure_disposition text not null check (failure_disposition in ('reject','quarantine')),
  blocks_external_execution boolean not null default true check (blocks_external_execution),
  blocks_candidate_write boolean not null default true check (blocks_candidate_write),
  blocks_release boolean not null default true check (blocks_release),
  automatic_pass_enabled boolean not null default false check (not automatic_pass_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_provider_contract_assertion_templates (
  sequence_number, assertion_key, display_name, assertion_requirement, failure_disposition
) values
  (1,'source_identity','Source identity','Require a stable source-family identity without naming, connecting or impersonating an external provider.','reject'),
  (2,'subject_identity','Subject identity','Require an explicit canonical subject key and reject ambiguous country, instrument, commodity or entity mappings.','reject'),
  (3,'schema_version','Schema version','Require an explicit version marker and reject unknown, missing or silently substituted schema versions.','reject'),
  (4,'required_fields','Required fields','Require every contract field marked mandatory and preserve absence as a validation failure rather than a default.','reject'),
  (5,'field_types','Field types','Require exact scalar, collection and enumeration types without lossy coercion or inferred replacements.','reject'),
  (6,'null_semantics','Null and missingness semantics','Distinguish missing, unavailable, not applicable and intentionally withheld values without fabrication.','quarantine'),
  (7,'unit_currency','Units and currency','Require explicit units, scale, currency and conversion basis wherever quantitative values could be misread.','reject'),
  (8,'event_time_revision','Event time and revisions','Require event time, observation time, timezone, revision identity and vintage lineage to remain distinct.','quarantine'),
  (9,'provenance_rights','Provenance and rights lineage','Require source lineage and field-level rights classifications before any future payload could leave isolation.','quarantine'),
  (10,'deterministic_idempotency','Deterministic idempotency','Require repeatable canonical identifiers and stable duplicate disposition for equivalent synthetic inputs.','reject');

create table public.global_provider_synthetic_fixture_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 24),
  contract_suite_id bigint not null references public.global_provider_contract_test_suites(id),
  source_family_key text not null,
  fixture_key text not null,
  fixture_class text not null check (fixture_class in ('valid_minimal','missing_required','schema_drift')),
  specification text not null check (char_length(specification) between 35 and 300),
  expected_disposition text not null check (expected_disposition in ('accept_to_ephemeral_test','reject_before_test')),
  provider_neutral boolean not null default true check (provider_neutral),
  contains_external_data boolean not null default false check (not contains_external_data),
  contains_real_world_observation boolean not null default false check (not contains_real_world_observation),
  execution_count integer not null default 0 check (execution_count = 0),
  latest_executed_at timestamptz check (latest_executed_at is null),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  release_enabled boolean not null default false check (not release_enabled),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (source_family_key, fixture_key)
);

insert into public.global_provider_synthetic_fixture_templates (
  sequence_number, contract_suite_id, source_family_key, fixture_key,
  fixture_class, specification, expected_disposition
)
select
  ((suite.sequence_number - 1) * 3 + fixture.ordinality)::smallint,
  suite.id,
  suite.source_family_key,
  suite.source_family_key || '-' || fixture.fixture_class,
  fixture.fixture_class,
  case fixture.fixture_class
    when 'valid_minimal' then 'Specify the smallest provider-neutral shape satisfying canonical identity, version, field, unit, time and lineage requirements.'
    when 'missing_required' then 'Specify a provider-neutral shape with one required field absent so missingness is rejected without defaulting or fabrication.'
    else 'Specify a provider-neutral shape with an incompatible version or field type so schema drift is rejected deterministically.'
  end,
  case fixture.fixture_class
    when 'valid_minimal' then 'accept_to_ephemeral_test'
    else 'reject_before_test'
  end
from public.global_provider_contract_test_suites suite
cross join lateral (
  values ('valid_minimal', 1), ('missing_required', 2), ('schema_drift', 3)
) as fixture(fixture_class, ordinality)
order by suite.sequence_number, fixture.ordinality;

alter table public.global_provider_contract_test_controls enable row level security;
alter table public.global_provider_contract_test_suites enable row level security;
alter table public.global_provider_contract_assertion_templates enable row level security;
alter table public.global_provider_synthetic_fixture_templates enable row level security;

create policy "Public reads provider contract-test controls" on public.global_provider_contract_test_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads provider-neutral contract suites" on public.global_provider_contract_test_suites
  for select to anon, authenticated using (suite_status = 'specification_only');
create policy "Public reads contract assertions" on public.global_provider_contract_assertion_templates
  for select to anon, authenticated using (true);
create policy "Public reads synthetic fixture specifications" on public.global_provider_synthetic_fixture_templates
  for select to anon, authenticated using (provider_neutral and not contains_external_data);

revoke all on table public.global_provider_contract_test_controls,
  public.global_provider_contract_test_suites,
  public.global_provider_contract_assertion_templates,
  public.global_provider_synthetic_fixture_templates from public, anon, authenticated, service_role;
grant select on table public.global_provider_contract_test_controls,
  public.global_provider_contract_test_suites,
  public.global_provider_contract_assertion_templates,
  public.global_provider_synthetic_fixture_templates to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_contract_test_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider contract-test reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_contract_test_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_contract_controls_append_only before update or delete on public.global_provider_contract_test_controls
  for each row execute function public.prevent_global_provider_contract_test_reference_mutation();
create trigger global_provider_contract_suites_append_only before update or delete on public.global_provider_contract_test_suites
  for each row execute function public.prevent_global_provider_contract_test_reference_mutation();
create trigger global_provider_contract_assertions_append_only before update or delete on public.global_provider_contract_assertion_templates
  for each row execute function public.prevent_global_provider_contract_test_reference_mutation();
create trigger global_provider_synthetic_fixtures_append_only before update or delete on public.global_provider_synthetic_fixture_templates
  for each row execute function public.prevent_global_provider_contract_test_reference_mutation();

create view public.global_provider_contract_test_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_contract_test_suites)::integer contract_suite_count,
  (select count(*) from public.global_provider_contract_test_suites where suite_status = 'specification_only')::integer specification_only_suite_count,
  (select coalesce(sum(executed_test_count),0) from public.global_provider_contract_test_suites)::integer executed_test_count,
  (select coalesce(sum(passed_test_count),0) from public.global_provider_contract_test_suites)::integer passed_test_count,
  (select count(*) from public.global_provider_contract_assertion_templates)::integer assertion_count,
  (select count(*) from public.global_provider_synthetic_fixture_templates)::integer synthetic_fixture_count,
  (select coalesce(sum(execution_count),0) from public.global_provider_synthetic_fixture_templates)::integer fixture_execution_count
from public.global_provider_contract_test_controls control;

create view public.global_provider_contract_suite_catalog with (security_invoker=true) as
select suite.id, suite.sequence_number, suite.source_family_key,
  source.display_name source_family_name, source.source_class,
  suite.suite_status, suite.schema_contract_version, suite.executed_test_count,
  suite.passed_test_count, suite.conformance_approved, suite.candidate_write_enabled,
  suite.release_enabled, suite.production_effect
from public.global_provider_contract_test_suites suite
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id;

create view public.global_provider_contract_assertion_catalog with (security_invoker=true) as
select id, sequence_number, assertion_key, display_name, assertion_requirement,
  failure_disposition, blocks_external_execution, blocks_candidate_write,
  blocks_release, automatic_pass_enabled
from public.global_provider_contract_assertion_templates;

create view public.global_provider_synthetic_fixture_catalog with (security_invoker=true) as
select fixture.id, fixture.sequence_number, fixture.source_family_key,
  suite.sequence_number suite_sequence_number, fixture.fixture_key,
  fixture.fixture_class, fixture.specification, fixture.expected_disposition,
  fixture.provider_neutral, fixture.contains_external_data,
  fixture.contains_real_world_observation, fixture.execution_count,
  fixture.candidate_write_enabled, fixture.release_enabled, fixture.production_effect
from public.global_provider_synthetic_fixture_templates fixture
join public.global_provider_contract_test_suites suite on suite.id = fixture.contract_suite_id;

grant select on public.global_provider_contract_test_status,
  public.global_provider_contract_suite_catalog,
  public.global_provider_contract_assertion_catalog,
  public.global_provider_synthetic_fixture_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_contract_test_suites) <> 8
    or (select count(*) from public.global_provider_contract_assertion_templates) <> 10
    or (select count(*) from public.global_provider_synthetic_fixture_templates) <> 24 then
    raise exception 'Phase 8M provider contract-test reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_contract_test_controls
    where provider_selection_enabled or endpoint_execution_enabled
      or credential_access_enabled or external_payload_intake_enabled
      or synthetic_fixture_execution_enabled or candidate_write_enabled
      or automatic_conformance_approval_enabled or observation_release_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_contract_test_suites
    where suite_status <> 'specification_only' or provider_legal_name is not null
      or endpoint_domain is not null or credential_reference is not null
      or external_payload_reference is not null or executed_test_count <> 0
      or passed_test_count <> 0 or conformance_approved or candidate_write_enabled
      or release_enabled or production_effect
  ) or exists (
    select 1 from public.global_provider_synthetic_fixture_templates
    where not provider_neutral or contains_external_data or contains_real_world_observation
      or execution_count <> 0 or latest_executed_at is not null
      or candidate_write_enabled or release_enabled or production_effect
  ) then
    raise exception 'Phase 8M provider contract-test laboratory must remain specification-only and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_certification_controls
    where provider_selection_enabled or endpoint_testing_enabled
      or credential_storage_enabled or candidate_intake_enabled
      or production_ingestion_enabled or automatic_certification_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8L provider certification boundary changed';
  end if;
end;
$$;

comment on table public.global_provider_contract_test_suites is
  'Eight provider-neutral contract-suite specifications with no provider, endpoint, credential, payload or execution.';
comment on table public.global_provider_contract_assertion_templates is
  'Ten canonical fail-closed assertions for a future provider-specific adapter review.';
comment on table public.global_provider_synthetic_fixture_templates is
  'Twenty-four synthetic fixture specifications; they contain no external data and have never been executed.';

commit;
