-- TradePulse AI
-- Migration 058: Phase 8N provider-candidate evidence review foundation
-- Sanitized review requirements only. No provider candidate, endpoint, credential,
-- evidence document, payload or executed test is stored or implied.

begin;

create table public.global_provider_candidate_review_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  review_packet_target integer not null default 8 check (review_packet_target = 8),
  evidence_requirement_target integer not null default 12 check (evidence_requirement_target = 12),
  review_matrix_target integer not null default 96 check (review_matrix_target = 96),
  manual_review_required boolean not null default true check (manual_review_required),
  signed_evidence_reference_required boolean not null default true check (signed_evidence_reference_required),
  versioned_field_mapping_required boolean not null default true check (versioned_field_mapping_required),
  observed_failure_drill_required boolean not null default true check (observed_failure_drill_required),
  provider_candidate_selection_enabled boolean not null default false check (not provider_candidate_selection_enabled),
  review_packet_open_enabled boolean not null default false check (not review_packet_open_enabled),
  evidence_submission_enabled boolean not null default false check (not evidence_submission_enabled),
  evidence_document_storage_enabled boolean not null default false check (not evidence_document_storage_enabled),
  endpoint_connectivity_enabled boolean not null default false check (not endpoint_connectivity_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  fixture_execution_enabled boolean not null default false check (not fixture_execution_enabled),
  conformance_approval_enabled boolean not null default false check (not conformance_approval_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_candidate_review_controls (control_key, policy_version)
values ('global-provider-candidate-evidence-review', 'global-provider-candidate-evidence-review-v1');

create table public.global_provider_candidate_review_profiles (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  contract_suite_id bigint not null unique references public.global_provider_contract_test_suites(id),
  source_family_key text not null unique,
  review_status text not null default 'not_opened' check (review_status = 'not_opened'),
  conformance_state text not null default 'blocked' check (conformance_state = 'blocked'),
  provider_candidate_name text check (provider_candidate_name is null),
  provider_legal_entity text check (provider_legal_entity is null),
  endpoint_domain text check (endpoint_domain is null),
  credential_reference text check (credential_reference is null),
  evidence_document_reference text check (evidence_document_reference is null),
  external_payload_reference text check (external_payload_reference is null),
  review_packet_opened_at timestamptz check (review_packet_opened_at is null),
  submitted_requirement_count integer not null default 0 check (submitted_requirement_count = 0),
  approved_requirement_count integer not null default 0 check (approved_requirement_count = 0),
  executed_fixture_count integer not null default 0 check (executed_fixture_count = 0),
  passed_fixture_count integer not null default 0 check (passed_fixture_count = 0),
  accountable_activation_approved boolean not null default false check (not accountable_activation_approved),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  release_enabled boolean not null default false check (not release_enabled),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_candidate_review_profiles (
  sequence_number, contract_suite_id, source_family_key
)
select sequence_number, id, source_family_key
from public.global_provider_contract_test_suites
order by sequence_number;

create table public.global_provider_candidate_evidence_requirements (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 12),
  requirement_key text not null unique,
  review_domain text not null check (review_domain in ('legal','rights','privacy','security','data_contract','testing','operations','governance')),
  display_name text not null unique,
  evidence_requirement text not null check (char_length(evidence_requirement) between 40 and 320),
  blocks_endpoint_execution boolean not null default true check (blocks_endpoint_execution),
  blocks_candidate_write boolean not null default true check (blocks_candidate_write),
  blocks_release boolean not null default true check (blocks_release),
  automatic_pass_enabled boolean not null default false check (not automatic_pass_enabled),
  created_at timestamptz not null default now()
);

insert into public.global_provider_candidate_evidence_requirements (
  sequence_number, requirement_key, review_domain, display_name, evidence_requirement
) values
  (1,'legal_identity_owner','legal','Legal identity and owner','Require the named contracting entity, accountable internal owner and review authority before a provider candidate can be opened.'),
  (2,'access_license_rights','rights','Access and license rights','Require signed evidence for API access, permitted use, territories, users and every restriction before any endpoint test.'),
  (3,'display_retention_rights','rights','Display and retention rights','Require approved display, caching, retention, deletion and audit obligations for every intended product surface.'),
  (4,'derivation_model_rights','rights','Derivation and model-use rights','Require explicit approval for derived analytics, forecasting features and model evaluation without assuming training rights.'),
  (5,'privacy_data_protection','privacy','Privacy and data protection','Require documented data categories, controller roles, transfer basis, minimization, retention and data-subject handling.'),
  (6,'security_secret_isolation','security','Security and secret isolation','Require threat review, isolated secret custody, network boundaries, rotation, revocation and incident ownership evidence.'),
  (7,'endpoint_schema_mapping','data_contract','Versioned endpoint and schema mapping','Require a versioned provider-to-canonical field map with units, missingness, time, revisions and provenance semantics.'),
  (8,'deterministic_fixture_pack','testing','Deterministic fixture pack','Require provider-specific synthetic fixtures derived without external payloads and mapped to every canonical contract assertion.'),
  (9,'negative_drift_evidence','testing','Negative and schema-drift evidence','Require observed fail-closed results for missing fields, invalid types, unknown versions, replay and incompatible schema drift.'),
  (10,'failure_drill_evidence','testing','Observed failure-drill evidence','Require reviewed credential rejection, rights withdrawal, isolation escape, staleness and conflicting-evidence drill results.'),
  (11,'availability_change_control','operations','Availability and change control','Require rate-limit, quota, freshness, outage, version-change, rollback, monitoring and accountable escalation evidence.'),
  (12,'accountable_activation_decision','governance','Accountable activation decision','Require a signed human decision that names scope, expiry, residual risks and rollback before any bounded activation.');

create table public.global_provider_candidate_review_matrix (
  id bigint generated by default as identity primary key,
  review_profile_id bigint not null references public.global_provider_candidate_review_profiles(id),
  requirement_id bigint not null references public.global_provider_candidate_evidence_requirements(id),
  evidence_status text not null default 'not_submitted' check (evidence_status = 'not_submitted'),
  evidence_reference text check (evidence_reference is null),
  reviewer_identity text check (reviewer_identity is null),
  reviewed_at timestamptz check (reviewed_at is null),
  expires_at timestamptz check (expires_at is null),
  human_approved boolean not null default false check (not human_approved),
  endpoint_execution_effect boolean not null default false check (not endpoint_execution_effect),
  candidate_write_effect boolean not null default false check (not candidate_write_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_profile_id, requirement_id)
);

insert into public.global_provider_candidate_review_matrix (review_profile_id, requirement_id)
select profile.id, requirement.id
from public.global_provider_candidate_review_profiles profile
cross join public.global_provider_candidate_evidence_requirements requirement
order by profile.sequence_number, requirement.sequence_number;

alter table public.global_provider_candidate_review_controls enable row level security;
alter table public.global_provider_candidate_review_profiles enable row level security;
alter table public.global_provider_candidate_evidence_requirements enable row level security;
alter table public.global_provider_candidate_review_matrix enable row level security;

create policy "Public reads candidate-review controls" on public.global_provider_candidate_review_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads unopened candidate profiles" on public.global_provider_candidate_review_profiles
  for select to anon, authenticated using (review_status = 'not_opened' and provider_candidate_name is null);
create policy "Public reads candidate evidence requirements" on public.global_provider_candidate_evidence_requirements
  for select to anon, authenticated using (true);
create policy "Public reads empty candidate review matrix" on public.global_provider_candidate_review_matrix
  for select to anon, authenticated using (evidence_status = 'not_submitted' and evidence_reference is null);

revoke all on table public.global_provider_candidate_review_controls,
  public.global_provider_candidate_review_profiles,
  public.global_provider_candidate_evidence_requirements,
  public.global_provider_candidate_review_matrix from public, anon, authenticated, service_role;
grant select on table public.global_provider_candidate_review_controls,
  public.global_provider_candidate_review_profiles,
  public.global_provider_candidate_evidence_requirements,
  public.global_provider_candidate_review_matrix to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_candidate_review_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider candidate-review reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_candidate_review_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_candidate_review_controls_append_only before update or delete on public.global_provider_candidate_review_controls
  for each row execute function public.prevent_global_provider_candidate_review_reference_mutation();
create trigger global_provider_candidate_review_profiles_append_only before update or delete on public.global_provider_candidate_review_profiles
  for each row execute function public.prevent_global_provider_candidate_review_reference_mutation();
create trigger global_provider_candidate_requirements_append_only before update or delete on public.global_provider_candidate_evidence_requirements
  for each row execute function public.prevent_global_provider_candidate_review_reference_mutation();
create trigger global_provider_candidate_matrix_append_only before update or delete on public.global_provider_candidate_review_matrix
  for each row execute function public.prevent_global_provider_candidate_review_reference_mutation();

create view public.global_provider_candidate_review_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_candidate_review_profiles)::integer review_packet_count,
  (select count(*) from public.global_provider_candidate_review_profiles where review_status = 'not_opened')::integer unopened_review_packet_count,
  (select count(*) from public.global_provider_candidate_review_profiles where provider_candidate_name is not null)::integer selected_candidate_count,
  (select count(*) from public.global_provider_candidate_evidence_requirements)::integer evidence_requirement_count,
  (select count(*) from public.global_provider_candidate_review_matrix)::integer review_matrix_count,
  (select count(*) from public.global_provider_candidate_review_matrix where evidence_status = 'not_submitted')::integer missing_evidence_count,
  (select count(*) from public.global_provider_candidate_review_matrix where human_approved)::integer approved_evidence_count
from public.global_provider_candidate_review_controls control;

create view public.global_provider_candidate_review_catalog with (security_invoker=true) as
select profile.id, profile.sequence_number, profile.source_family_key,
  suite.sequence_number contract_suite_sequence_number,
  source.display_name source_family_name, source.source_class,
  profile.review_status, profile.conformance_state,
  profile.submitted_requirement_count, profile.approved_requirement_count,
  profile.executed_fixture_count, profile.passed_fixture_count,
  profile.accountable_activation_approved, profile.candidate_write_enabled,
  profile.release_enabled, profile.production_effect
from public.global_provider_candidate_review_profiles profile
join public.global_provider_contract_test_suites suite on suite.id = profile.contract_suite_id
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id;

create view public.global_provider_candidate_evidence_catalog with (security_invoker=true) as
select id, sequence_number, requirement_key, review_domain, display_name,
  evidence_requirement, blocks_endpoint_execution, blocks_candidate_write,
  blocks_release, automatic_pass_enabled
from public.global_provider_candidate_evidence_requirements;

create view public.global_provider_candidate_review_matrix_catalog with (security_invoker=true) as
select matrix.id, profile.source_family_key, requirement.requirement_key,
  requirement.sequence_number requirement_sequence_number,
  matrix.evidence_status, matrix.human_approved,
  matrix.endpoint_execution_effect, matrix.candidate_write_effect,
  matrix.release_effect, matrix.production_effect
from public.global_provider_candidate_review_matrix matrix
join public.global_provider_candidate_review_profiles profile on profile.id = matrix.review_profile_id
join public.global_provider_candidate_evidence_requirements requirement on requirement.id = matrix.requirement_id;

grant select on public.global_provider_candidate_review_status,
  public.global_provider_candidate_review_catalog,
  public.global_provider_candidate_evidence_catalog,
  public.global_provider_candidate_review_matrix_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_candidate_review_profiles) <> 8
    or (select count(*) from public.global_provider_candidate_evidence_requirements) <> 12
    or (select count(*) from public.global_provider_candidate_review_matrix) <> 96 then
    raise exception 'Phase 8N provider candidate-review reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_candidate_review_controls
    where provider_candidate_selection_enabled or review_packet_open_enabled
      or evidence_submission_enabled or evidence_document_storage_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_candidate_review_profiles
    where review_status <> 'not_opened' or conformance_state <> 'blocked'
      or provider_candidate_name is not null or provider_legal_entity is not null
      or endpoint_domain is not null or credential_reference is not null
      or evidence_document_reference is not null or external_payload_reference is not null
      or review_packet_opened_at is not null or submitted_requirement_count <> 0
      or approved_requirement_count <> 0 or executed_fixture_count <> 0
      or passed_fixture_count <> 0 or accountable_activation_approved
      or candidate_write_enabled or release_enabled or production_effect
  ) or exists (
    select 1 from public.global_provider_candidate_review_matrix
    where evidence_status <> 'not_submitted' or evidence_reference is not null
      or reviewer_identity is not null or reviewed_at is not null or expires_at is not null
      or human_approved or endpoint_execution_effect or candidate_write_effect
      or release_effect or production_effect
  ) then
    raise exception 'Phase 8N candidate-review workspace must remain empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_contract_test_controls
    where provider_selection_enabled or endpoint_execution_enabled
      or credential_access_enabled or external_payload_intake_enabled
      or synthetic_fixture_execution_enabled or candidate_write_enabled
      or automatic_conformance_approval_enabled or observation_release_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8M provider contract-test boundary changed';
  end if;
end;
$$;

comment on table public.global_provider_candidate_review_profiles is
  'Eight unopened, provider-empty review profiles; no provider identity, endpoint, credential, payload or approval is stored.';
comment on table public.global_provider_candidate_evidence_requirements is
  'Twelve human-review evidence requirements that all block endpoint execution, candidate writes and release.';
comment on table public.global_provider_candidate_review_matrix is
  'Ninety-six missing-evidence placeholders with no document, reviewer, approval or production effect.';

commit;
