-- TradePulse AI
-- Migration 059: Phase 8P provider review-governance foundation
-- Role templates and evidence-lifecycle controls only. No person, provider,
-- evidence document, custody location, endpoint, credential or payload is stored.

begin;

create table public.global_provider_review_governance_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  role_template_target integer not null default 8 check (role_template_target = 8),
  responsibility_target integer not null default 64 check (responsibility_target = 64),
  lifecycle_stage_target integer not null default 7 check (lifecycle_stage_target = 7),
  independent_review_required boolean not null default true check (independent_review_required),
  separation_of_duties_required boolean not null default true check (separation_of_duties_required),
  least_privilege_custody_required boolean not null default true check (least_privilege_custody_required),
  dual_control_activation_required boolean not null default true check (dual_control_activation_required),
  expiry_and_revocation_required boolean not null default true check (expiry_and_revocation_required),
  role_assignment_enabled boolean not null default false check (not role_assignment_enabled),
  reviewer_identity_storage_enabled boolean not null default false check (not reviewer_identity_storage_enabled),
  evidence_receipt_enabled boolean not null default false check (not evidence_receipt_enabled),
  evidence_document_storage_enabled boolean not null default false check (not evidence_document_storage_enabled),
  custody_location_provisioning_enabled boolean not null default false check (not custody_location_provisioning_enabled),
  provider_candidate_selection_enabled boolean not null default false check (not provider_candidate_selection_enabled),
  review_packet_open_enabled boolean not null default false check (not review_packet_open_enabled),
  evidence_submission_enabled boolean not null default false check (not evidence_submission_enabled),
  endpoint_connectivity_enabled boolean not null default false check (not endpoint_connectivity_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  fixture_execution_enabled boolean not null default false check (not fixture_execution_enabled),
  conformance_approval_enabled boolean not null default false check (not conformance_approval_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_review_governance_controls (control_key, policy_version)
values ('global-provider-review-governance', 'global-provider-review-governance-v1');

create table public.global_provider_review_role_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  role_key text not null unique,
  review_domain text not null check (review_domain in ('governance','legal','rights','privacy','security','data_contract','testing_operations')),
  display_name text not null unique,
  responsibility text not null check (char_length(responsibility) between 40 and 320),
  assignment_status text not null default 'unassigned' check (assignment_status = 'unassigned'),
  assigned_identity text check (assigned_identity is null),
  blocks_packet_opening boolean not null default true check (blocks_packet_opening),
  blocks_endpoint_access boolean not null default true check (blocks_endpoint_access),
  blocks_release boolean not null default true check (blocks_release),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.global_provider_review_role_templates (
  sequence_number, role_key, review_domain, display_name, responsibility
) values
  (1,'candidate_accountable_owner','governance','Candidate accountable owner','Own the bounded review purpose, scope, decision record and escalation path without selecting or activating a provider.'),
  (2,'legal_entity_reviewer','legal','Legal entity reviewer','Verify contracting identity, authority and accountable legal ownership before any real candidate packet can be opened.'),
  (3,'licensing_rights_reviewer','rights','Licensing and rights reviewer','Assess access, display, retention, derivation and permitted-use evidence before any endpoint or product use.'),
  (4,'privacy_data_protection_reviewer','privacy','Privacy and data-protection reviewer','Assess data categories, transfer basis, minimization, retention and data-subject obligations before intake.'),
  (5,'security_evidence_custodian','security','Security and evidence custodian','Control least-privilege evidence handling, secret isolation, auditability, expiry, revocation and incident ownership.'),
  (6,'schema_data_contract_reviewer','data_contract','Schema and data-contract reviewer','Review versioned field mappings, units, time semantics, provenance, missingness and fail-closed drift behavior.'),
  (7,'conformance_operations_reviewer','testing_operations','Conformance and operations reviewer','Review deterministic fixtures, failure drills, monitoring, rollback, quota, freshness and escalation evidence.'),
  (8,'activation_authority','governance','Activation authority','Provide a separate signed, expiring decision only after every required reviewer has approved the bounded scope.');

create table public.global_provider_evidence_lifecycle_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  stage_key text not null unique,
  display_name text not null unique,
  stage_definition text not null check (char_length(stage_definition) between 40 and 320),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  storage_location text check (storage_location is null),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_action_required boolean not null default true check (human_action_required),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_evidence_lifecycle_templates (
  sequence_number, stage_key, display_name, stage_definition
) values
  (1,'not_received','Not received','No evidence has been received, referenced or stored; the review remains closed and every downstream action is blocked.'),
  (2,'received_sealed','Received sealed','A future controlled process may acknowledge sealed receipt without exposing content or granting review, endpoint or release authority.'),
  (3,'triaged','Triaged','A future custodian may validate scope, classification, integrity and authorized recipients before controlled review begins.'),
  (4,'under_review','Under review','Assigned independent reviewers may evaluate only their authorized domains while separation of duties remains enforced.'),
  (5,'needs_remediation','Needs remediation','Any evidence gap, ambiguity, rights conflict, drift or failed drill returns the candidate to a blocked remediation state.'),
  (6,'accepted_until_expiry','Accepted until expiry','A future signed decision may accept a bounded scope only until its explicit expiry, with revocation and rollback controls.'),
  (7,'expired_or_revoked','Expired or revoked','Expired, withdrawn or invalidated evidence immediately blocks endpoint access, writes, release and further reliance.');

create table public.global_provider_review_responsibility_matrix (
  id bigint generated by default as identity primary key,
  review_profile_id bigint not null references public.global_provider_candidate_review_profiles(id),
  role_template_id bigint not null references public.global_provider_review_role_templates(id),
  responsibility_status text not null default 'unassigned' check (responsibility_status = 'unassigned'),
  reviewer_identity text check (reviewer_identity is null),
  custody_location text check (custody_location is null),
  assigned_at timestamptz check (assigned_at is null),
  authorized_at timestamptz check (authorized_at is null),
  expires_at timestamptz check (expires_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  packet_open_effect boolean not null default false check (not packet_open_effect),
  endpoint_access_effect boolean not null default false check (not endpoint_access_effect),
  candidate_write_effect boolean not null default false check (not candidate_write_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_profile_id, role_template_id)
);

insert into public.global_provider_review_responsibility_matrix (review_profile_id, role_template_id)
select profile.id, role.id
from public.global_provider_candidate_review_profiles profile
cross join public.global_provider_review_role_templates role
order by profile.sequence_number, role.sequence_number;

alter table public.global_provider_review_governance_controls enable row level security;
alter table public.global_provider_review_role_templates enable row level security;
alter table public.global_provider_evidence_lifecycle_templates enable row level security;
alter table public.global_provider_review_responsibility_matrix enable row level security;

create policy "Public reads provider-review governance controls" on public.global_provider_review_governance_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads unassigned provider-review roles" on public.global_provider_review_role_templates
  for select to anon, authenticated using (assignment_status = 'unassigned' and assigned_identity is null);
create policy "Public reads evidence lifecycle templates" on public.global_provider_evidence_lifecycle_templates
  for select to anon, authenticated using (not real_evidence_present and storage_location is null);
create policy "Public reads unassigned provider responsibilities" on public.global_provider_review_responsibility_matrix
  for select to anon, authenticated using (responsibility_status = 'unassigned' and reviewer_identity is null);

revoke all on table public.global_provider_review_governance_controls,
  public.global_provider_review_role_templates,
  public.global_provider_evidence_lifecycle_templates,
  public.global_provider_review_responsibility_matrix from public, anon, authenticated, service_role;
grant select on table public.global_provider_review_governance_controls,
  public.global_provider_review_role_templates,
  public.global_provider_evidence_lifecycle_templates,
  public.global_provider_review_responsibility_matrix to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_review_governance_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider review-governance reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_review_governance_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_review_governance_controls_append_only before update or delete on public.global_provider_review_governance_controls
  for each row execute function public.prevent_global_provider_review_governance_reference_mutation();
create trigger global_provider_review_role_templates_append_only before update or delete on public.global_provider_review_role_templates
  for each row execute function public.prevent_global_provider_review_governance_reference_mutation();
create trigger global_provider_evidence_lifecycle_templates_append_only before update or delete on public.global_provider_evidence_lifecycle_templates
  for each row execute function public.prevent_global_provider_review_governance_reference_mutation();
create trigger global_provider_review_responsibility_matrix_append_only before update or delete on public.global_provider_review_responsibility_matrix
  for each row execute function public.prevent_global_provider_review_governance_reference_mutation();

create view public.global_provider_review_governance_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_candidate_review_profiles)::integer source_family_count,
  (select count(*) from public.global_provider_review_role_templates)::integer role_template_count,
  (select count(*) from public.global_provider_review_role_templates where assignment_status = 'unassigned')::integer unassigned_role_count,
  (select count(*) from public.global_provider_evidence_lifecycle_templates)::integer lifecycle_stage_count,
  (select count(*) from public.global_provider_review_responsibility_matrix)::integer responsibility_count,
  (select count(*) from public.global_provider_review_responsibility_matrix where responsibility_status = 'unassigned')::integer unassigned_responsibility_count,
  (select count(*) from public.global_provider_review_responsibility_matrix where human_authorized)::integer authorized_responsibility_count
from public.global_provider_review_governance_controls control;

create view public.global_provider_review_role_catalog with (security_invoker=true) as
select id, sequence_number, role_key, review_domain, display_name, responsibility,
  assignment_status, blocks_packet_opening, blocks_endpoint_access, blocks_release,
  human_authorized
from public.global_provider_review_role_templates;

create view public.global_provider_evidence_lifecycle_catalog with (security_invoker=true) as
select id, sequence_number, stage_key, display_name, stage_definition,
  real_evidence_present, automatic_transition_enabled, human_action_required,
  production_effect
from public.global_provider_evidence_lifecycle_templates;

create view public.global_provider_review_responsibility_catalog with (security_invoker=true) as
select matrix.id, profile.source_family_key, source.display_name source_family_name,
  role.role_key, role.sequence_number role_sequence_number, role.display_name role_name,
  role.review_domain, matrix.responsibility_status, matrix.human_authorized,
  matrix.packet_open_effect, matrix.endpoint_access_effect,
  matrix.candidate_write_effect, matrix.release_effect, matrix.production_effect
from public.global_provider_review_responsibility_matrix matrix
join public.global_provider_candidate_review_profiles profile on profile.id = matrix.review_profile_id
join public.global_provider_contract_test_suites suite on suite.id = profile.contract_suite_id
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id
join public.global_provider_review_role_templates role on role.id = matrix.role_template_id;

grant select on public.global_provider_review_governance_status,
  public.global_provider_review_role_catalog,
  public.global_provider_evidence_lifecycle_catalog,
  public.global_provider_review_responsibility_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_review_role_templates) <> 8
    or (select count(*) from public.global_provider_evidence_lifecycle_templates) <> 7
    or (select count(*) from public.global_provider_review_responsibility_matrix) <> 64 then
    raise exception 'Phase 8P provider review-governance reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_review_governance_controls
    where role_assignment_enabled or reviewer_identity_storage_enabled
      or evidence_receipt_enabled or evidence_document_storage_enabled
      or custody_location_provisioning_enabled or provider_candidate_selection_enabled
      or review_packet_open_enabled or evidence_submission_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_review_role_templates
    where assignment_status <> 'unassigned' or assigned_identity is not null
      or not blocks_packet_opening or not blocks_endpoint_access or not blocks_release
      or human_authorized
  ) or exists (
    select 1 from public.global_provider_evidence_lifecycle_templates
    where real_evidence_present or storage_location is not null
      or automatic_transition_enabled or not human_action_required or production_effect
  ) or exists (
    select 1 from public.global_provider_review_responsibility_matrix
    where responsibility_status <> 'unassigned' or reviewer_identity is not null
      or custody_location is not null or assigned_at is not null
      or authorized_at is not null or expires_at is not null
      or human_authorized or packet_open_effect or endpoint_access_effect
      or candidate_write_effect or release_effect or production_effect
  ) then
    raise exception 'Phase 8P provider review-governance workspace must remain unassigned and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_candidate_review_controls
    where provider_candidate_selection_enabled or review_packet_open_enabled
      or evidence_submission_enabled or evidence_document_storage_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8N provider candidate-review boundary changed';
  end if;
end;
$$;

commit;
