-- TradePulse AI
-- Migration 060: Phase 8Q provider review decision-control foundation
-- Decision states, mandatory gates and readiness placeholders only. No person,
-- provider, evidence, approval, signature, endpoint, credential or payload is stored.

begin;

create table public.global_provider_review_decision_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  decision_gate_target integer not null default 8 check (decision_gate_target = 8),
  readiness_cell_target integer not null default 64 check (readiness_cell_target = 64),
  decision_state_target integer not null default 7 check (decision_state_target = 7),
  independent_decision_required boolean not null default true check (independent_decision_required),
  dual_control_quorum_required boolean not null default true check (dual_control_quorum_required),
  immutable_audit_required boolean not null default true check (immutable_audit_required),
  explicit_reason_code_required boolean not null default true check (explicit_reason_code_required),
  expiry_and_revocation_required boolean not null default true check (expiry_and_revocation_required),
  conflict_of_interest_review_required boolean not null default true check (conflict_of_interest_review_required),
  decision_recording_enabled boolean not null default false check (not decision_recording_enabled),
  reviewer_signature_storage_enabled boolean not null default false check (not reviewer_signature_storage_enabled),
  evidence_linkage_enabled boolean not null default false check (not evidence_linkage_enabled),
  automated_quorum_evaluation_enabled boolean not null default false check (not automated_quorum_evaluation_enabled),
  provider_candidate_selection_enabled boolean not null default false check (not provider_candidate_selection_enabled),
  review_packet_open_enabled boolean not null default false check (not review_packet_open_enabled),
  endpoint_connectivity_enabled boolean not null default false check (not endpoint_connectivity_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  fixture_execution_enabled boolean not null default false check (not fixture_execution_enabled),
  conformance_approval_enabled boolean not null default false check (not conformance_approval_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_review_decision_controls (control_key, policy_version)
values ('global-provider-review-decision-controls', 'global-provider-review-decision-controls-v1');

create table public.global_provider_review_decision_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 320),
  real_decision_present boolean not null default false check (not real_decision_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_decision_required boolean not null default true check (human_decision_required),
  endpoint_access_effect boolean not null default false check (not endpoint_access_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_review_decision_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'not_assessed','Not assessed','No authorized review decision exists; every provider, endpoint, write, release and downstream use remains blocked.'),
  (2,'awaiting_independent_reviews','Awaiting independent reviews','A future controlled process may wait for independently assigned domain reviews without granting authority or access.'),
  (3,'blocked_by_gap','Blocked by gap','Any missing, stale, conflicting or unverifiable evidence keeps the candidate blocked and requires a recorded remediation path.'),
  (4,'remediation_required','Remediation required','A future accountable owner may request bounded remediation while all candidate, endpoint and release effects remain disabled.'),
  (5,'decision_ready','Decision ready','A future packet may become eligible for separate human decision only after every mandatory gate is independently satisfied.'),
  (6,'accepted_until_expiry','Accepted until expiry','A future dual-controlled decision may be time bounded, scope bounded, revocable and ineffective outside its signed authorization.'),
  (7,'expired_or_revoked','Expired or revoked','Expiry, withdrawal, conflict or invalidation immediately blocks access, writes, release and further reliance.');

create table public.global_provider_review_decision_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique,
  review_domain text not null check (review_domain in ('governance','legal','rights','privacy','security','data_contract','testing_operations')),
  display_name text not null unique,
  gate_definition text not null check (char_length(gate_definition) between 40 and 320),
  gate_status text not null default 'unmet' check (gate_status = 'unmet'),
  evidence_present boolean not null default false check (not evidence_present),
  reviewer_assigned boolean not null default false check (not reviewer_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.global_provider_review_decision_gate_templates (
  sequence_number, gate_key, review_domain, display_name, gate_definition
) values
  (1,'accountable_scope','governance','Accountable scope','Confirm a bounded purpose, source family, permitted use, escalation owner and decision scope before any review can advance.'),
  (2,'legal_entity_authority','legal','Legal entity authority','Confirm contracting identity, decision authority, governing terms and accountable legal ownership for the bounded scope.'),
  (3,'licensing_and_rights','rights','Licensing and rights','Confirm access, display, retention, derivation, redistribution and model-use rights with explicit restrictions.'),
  (4,'privacy_and_transfer','privacy','Privacy and transfer','Confirm data categories, minimization, transfer basis, retention, deletion and data-subject obligations.'),
  (5,'security_and_custody','security','Security and custody','Confirm evidence custody, secret isolation, least privilege, audit retention, incident ownership, expiry and revocation.'),
  (6,'schema_and_provenance','data_contract','Schema and provenance','Confirm versioned field mapping, units, time semantics, provenance, missingness and fail-closed drift controls.'),
  (7,'conformance_and_operations','testing_operations','Conformance and operations','Confirm deterministic fixtures, negative tests, failure drills, monitoring, rollback, quotas and freshness evidence.'),
  (8,'independent_dual_control','governance','Independent dual control','Confirm independent reviews, conflict handling, reason codes, explicit expiry and a separate activation authority.');

create table public.global_provider_review_decision_readiness_matrix (
  id bigint generated by default as identity primary key,
  review_profile_id bigint not null references public.global_provider_candidate_review_profiles(id),
  decision_gate_template_id bigint not null references public.global_provider_review_decision_gate_templates(id),
  readiness_status text not null default 'unmet' check (readiness_status = 'unmet'),
  evidence_reference text check (evidence_reference is null),
  reviewer_identity text check (reviewer_identity is null),
  decision_reason_code text check (decision_reason_code is null),
  reviewer_signature text check (reviewer_signature is null),
  assessed_at timestamptz check (assessed_at is null),
  authorized_at timestamptz check (authorized_at is null),
  expires_at timestamptz check (expires_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  packet_open_effect boolean not null default false check (not packet_open_effect),
  endpoint_access_effect boolean not null default false check (not endpoint_access_effect),
  candidate_write_effect boolean not null default false check (not candidate_write_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_profile_id, decision_gate_template_id)
);

insert into public.global_provider_review_decision_readiness_matrix (review_profile_id, decision_gate_template_id)
select profile.id, gate.id
from public.global_provider_candidate_review_profiles profile
cross join public.global_provider_review_decision_gate_templates gate
order by profile.sequence_number, gate.sequence_number;

alter table public.global_provider_review_decision_controls enable row level security;
alter table public.global_provider_review_decision_state_templates enable row level security;
alter table public.global_provider_review_decision_gate_templates enable row level security;
alter table public.global_provider_review_decision_readiness_matrix enable row level security;

create policy "Public reads provider-review decision controls" on public.global_provider_review_decision_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads provider-review decision states" on public.global_provider_review_decision_state_templates
  for select to anon, authenticated using (not real_decision_present);
create policy "Public reads unmet provider-review decision gates" on public.global_provider_review_decision_gate_templates
  for select to anon, authenticated using (gate_status = 'unmet' and not human_authorized);
create policy "Public reads unmet provider-review readiness" on public.global_provider_review_decision_readiness_matrix
  for select to anon, authenticated using (readiness_status = 'unmet' and not human_authorized);

revoke all on table public.global_provider_review_decision_controls,
  public.global_provider_review_decision_state_templates,
  public.global_provider_review_decision_gate_templates,
  public.global_provider_review_decision_readiness_matrix from public, anon, authenticated, service_role;
grant select on table public.global_provider_review_decision_controls,
  public.global_provider_review_decision_state_templates,
  public.global_provider_review_decision_gate_templates,
  public.global_provider_review_decision_readiness_matrix to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_review_decision_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider review decision-control reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_review_decision_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_review_decision_controls_append_only before update or delete on public.global_provider_review_decision_controls
  for each row execute function public.prevent_global_provider_review_decision_reference_mutation();
create trigger global_provider_review_decision_states_append_only before update or delete on public.global_provider_review_decision_state_templates
  for each row execute function public.prevent_global_provider_review_decision_reference_mutation();
create trigger global_provider_review_decision_gates_append_only before update or delete on public.global_provider_review_decision_gate_templates
  for each row execute function public.prevent_global_provider_review_decision_reference_mutation();
create trigger global_provider_review_decision_readiness_append_only before update or delete on public.global_provider_review_decision_readiness_matrix
  for each row execute function public.prevent_global_provider_review_decision_reference_mutation();

create view public.global_provider_review_decision_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_candidate_review_profiles)::integer source_family_count,
  (select count(*) from public.global_provider_review_decision_gate_templates)::integer decision_gate_count,
  (select count(*) from public.global_provider_review_decision_state_templates)::integer decision_state_count,
  (select count(*) from public.global_provider_review_decision_readiness_matrix)::integer readiness_cell_count,
  (select count(*) from public.global_provider_review_decision_readiness_matrix where readiness_status = 'unmet')::integer unmet_readiness_cell_count,
  (select count(*) from public.global_provider_review_decision_readiness_matrix where human_authorized)::integer authorized_readiness_cell_count
from public.global_provider_review_decision_controls control;

create view public.global_provider_review_decision_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  real_decision_present, automatic_transition_enabled, human_decision_required,
  endpoint_access_effect, release_effect, production_effect
from public.global_provider_review_decision_state_templates;

create view public.global_provider_review_decision_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, review_domain, display_name, gate_definition,
  gate_status, evidence_present, reviewer_assigned, human_authorized
from public.global_provider_review_decision_gate_templates;

create view public.global_provider_review_decision_readiness_catalog with (security_invoker=true) as
select matrix.id, profile.source_family_key, source.display_name source_family_name,
  gate.gate_key, gate.sequence_number gate_sequence_number, gate.display_name gate_name,
  gate.review_domain, matrix.readiness_status, matrix.human_authorized,
  matrix.packet_open_effect, matrix.endpoint_access_effect,
  matrix.candidate_write_effect, matrix.release_effect, matrix.production_effect
from public.global_provider_review_decision_readiness_matrix matrix
join public.global_provider_candidate_review_profiles profile on profile.id = matrix.review_profile_id
join public.global_provider_contract_test_suites suite on suite.id = profile.contract_suite_id
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id
join public.global_provider_review_decision_gate_templates gate on gate.id = matrix.decision_gate_template_id;

grant select on public.global_provider_review_decision_status,
  public.global_provider_review_decision_state_catalog,
  public.global_provider_review_decision_gate_catalog,
  public.global_provider_review_decision_readiness_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_review_decision_state_templates) <> 7
    or (select count(*) from public.global_provider_review_decision_gate_templates) <> 8
    or (select count(*) from public.global_provider_review_decision_readiness_matrix) <> 64 then
    raise exception 'Phase 8Q provider review decision-control reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_review_decision_controls
    where decision_recording_enabled or reviewer_signature_storage_enabled
      or evidence_linkage_enabled or automated_quorum_evaluation_enabled
      or provider_candidate_selection_enabled or review_packet_open_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_review_decision_state_templates
    where real_decision_present or automatic_transition_enabled or not human_decision_required
      or endpoint_access_effect or release_effect or production_effect
  ) or exists (
    select 1 from public.global_provider_review_decision_gate_templates
    where gate_status <> 'unmet' or evidence_present or reviewer_assigned or human_authorized
  ) or exists (
    select 1 from public.global_provider_review_decision_readiness_matrix
    where readiness_status <> 'unmet' or evidence_reference is not null
      or reviewer_identity is not null or decision_reason_code is not null
      or reviewer_signature is not null or assessed_at is not null
      or authorized_at is not null or expires_at is not null
      or human_authorized or packet_open_effect or endpoint_access_effect
      or candidate_write_effect or release_effect or production_effect
  ) then
    raise exception 'Phase 8Q provider review decision controls must remain empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_review_governance_controls
    where role_assignment_enabled or reviewer_identity_storage_enabled
      or evidence_receipt_enabled or evidence_document_storage_enabled
      or custody_location_provisioning_enabled or provider_candidate_selection_enabled
      or review_packet_open_enabled or evidence_submission_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8P provider review-governance boundary changed';
  end if;
end;
$$;

commit;
