-- TradePulse AI
-- Migration 061: Phase 8R provider decision recovery-control foundation
-- Exception, expiry, revocation and rollback-rehearsal references only. No real
-- decision, event, person, evidence, provider, endpoint or recovery action exists.

begin;

create table public.global_provider_decision_recovery_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  recovery_trigger_target integer not null default 8 check (recovery_trigger_target = 8),
  recovery_cell_target integer not null default 64 check (recovery_cell_target = 64),
  recovery_state_target integer not null default 7 check (recovery_state_target = 7),
  immediate_fail_closed_freeze_required boolean not null default true check (immediate_fail_closed_freeze_required),
  independent_recovery_review_required boolean not null default true check (independent_recovery_review_required),
  rollback_rehearsal_required boolean not null default true check (rollback_rehearsal_required),
  immutable_recovery_audit_required boolean not null default true check (immutable_recovery_audit_required),
  explicit_recovery_reason_required boolean not null default true check (explicit_recovery_reason_required),
  expiry_and_revocation_enforced boolean not null default true check (expiry_and_revocation_enforced),
  exception_recording_enabled boolean not null default false check (not exception_recording_enabled),
  decision_challenge_recording_enabled boolean not null default false check (not decision_challenge_recording_enabled),
  investigator_identity_storage_enabled boolean not null default false check (not investigator_identity_storage_enabled),
  recovery_evidence_linkage_enabled boolean not null default false check (not recovery_evidence_linkage_enabled),
  automated_freeze_enabled boolean not null default false check (not automated_freeze_enabled),
  rollback_execution_enabled boolean not null default false check (not rollback_execution_enabled),
  decision_revocation_enabled boolean not null default false check (not decision_revocation_enabled),
  provider_candidate_selection_enabled boolean not null default false check (not provider_candidate_selection_enabled),
  review_packet_open_enabled boolean not null default false check (not review_packet_open_enabled),
  endpoint_connectivity_enabled boolean not null default false check (not endpoint_connectivity_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  fixture_execution_enabled boolean not null default false check (not fixture_execution_enabled),
  conformance_approval_enabled boolean not null default false check (not conformance_approval_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_decision_recovery_controls (control_key, policy_version)
values ('global-provider-decision-recovery-controls', 'global-provider-decision-recovery-controls-v1');

create table public.global_provider_decision_recovery_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 320),
  real_recovery_event_present boolean not null default false check (not real_recovery_event_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_recovery_review_required boolean not null default true check (human_recovery_review_required),
  freeze_effect boolean not null default false check (not freeze_effect),
  rollback_effect boolean not null default false check (not rollback_effect),
  revocation_effect boolean not null default false check (not revocation_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_decision_recovery_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'monitoring_inactive','Monitoring inactive','No real provider decision or recovery event exists; all exception, freeze, rollback and revocation actions remain unavailable.'),
  (2,'exception_reported','Exception reported','A future controlled process may acknowledge a bounded challenge or expiry signal without changing any provider or decision state.'),
  (3,'protective_freeze_required','Protective freeze required','A future verified trigger must fail closed before investigation, while this template itself has no automated freeze effect.'),
  (4,'independent_review_required','Independent review required','A future recovery packet must receive independent domain review and conflict handling without granting operational authority.'),
  (5,'rollback_rehearsal_required','Rollback rehearsal required','A future isolated rehearsal must prove containment and restoration paths without connecting endpoints or affecting production.'),
  (6,'revocation_required','Revocation required','A future dual-controlled revocation may remove a bounded authorization, but no decision or revocation exists in this phase.'),
  (7,'recovery_closed_without_effect','Recovery closed without effect','A future accountable closeout must retain reasoned immutable evidence while granting no release or production effect.');

create table public.global_provider_decision_recovery_trigger_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  trigger_key text not null unique,
  recovery_domain text not null check (recovery_domain in ('governance','legal','rights','privacy','security','data_contract','operations')),
  display_name text not null unique,
  trigger_definition text not null check (char_length(trigger_definition) between 40 and 320),
  trigger_status text not null default 'unobserved' check (trigger_status = 'unobserved'),
  real_event_present boolean not null default false check (not real_event_present),
  investigator_assigned boolean not null default false check (not investigator_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.global_provider_decision_recovery_trigger_templates (
  sequence_number, trigger_key, recovery_domain, display_name, trigger_definition
) values
  (1,'authority_or_scope_change','governance','Authority or scope change','Detect future loss of accountable authority, purpose limitation, approved scope or separation of duties and fail closed.'),
  (2,'legal_status_change','legal','Legal status change','Detect future contracting, jurisdiction, regulatory or enforceability changes requiring independent legal reassessment.'),
  (3,'rights_withdrawal_or_expiry','rights','Rights withdrawal or expiry','Detect future withdrawal, expiry or conflict in access, display, retention, redistribution or model-use rights.'),
  (4,'privacy_or_transfer_change','privacy','Privacy or transfer change','Detect future changes to data categories, transfer basis, retention, deletion or data-subject obligations.'),
  (5,'security_or_custody_incident','security','Security or custody incident','Detect future credential, custody, access-control, audit-retention or incident-response failures and contain access.'),
  (6,'schema_or_provenance_breach','data_contract','Schema or provenance breach','Detect future schema, unit, timing, provenance, missingness or drift failures that invalidate bounded reliance.'),
  (7,'conformance_or_operations_regression','operations','Conformance or operations regression','Detect future test, monitoring, freshness, quota, recovery or operational-readiness regression and block release.'),
  (8,'conflict_quorum_or_expiry_failure','governance','Conflict, quorum or expiry failure','Detect future reviewer conflict, quorum loss, stale decision, missed expiry or failed revocation and require rollback review.');

create table public.global_provider_decision_recovery_matrix (
  id bigint generated by default as identity primary key,
  review_profile_id bigint not null references public.global_provider_candidate_review_profiles(id),
  recovery_trigger_template_id bigint not null references public.global_provider_decision_recovery_trigger_templates(id),
  recovery_status text not null default 'blocked' check (recovery_status = 'blocked'),
  exception_reference text check (exception_reference is null),
  challenge_reference text check (challenge_reference is null),
  recovery_evidence_reference text check (recovery_evidence_reference is null),
  investigator_identity text check (investigator_identity is null),
  recovery_reason_code text check (recovery_reason_code is null),
  recovery_signature text check (recovery_signature is null),
  detected_at timestamptz check (detected_at is null),
  frozen_at timestamptz check (frozen_at is null),
  revoked_at timestamptz check (revoked_at is null),
  resolved_at timestamptz check (resolved_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  automated_freeze_effect boolean not null default false check (not automated_freeze_effect),
  rollback_effect boolean not null default false check (not rollback_effect),
  revocation_effect boolean not null default false check (not revocation_effect),
  endpoint_access_effect boolean not null default false check (not endpoint_access_effect),
  candidate_write_effect boolean not null default false check (not candidate_write_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_profile_id, recovery_trigger_template_id)
);

insert into public.global_provider_decision_recovery_matrix (review_profile_id, recovery_trigger_template_id)
select profile.id, trigger.id
from public.global_provider_candidate_review_profiles profile
cross join public.global_provider_decision_recovery_trigger_templates trigger
order by profile.sequence_number, trigger.sequence_number;

alter table public.global_provider_decision_recovery_controls enable row level security;
alter table public.global_provider_decision_recovery_state_templates enable row level security;
alter table public.global_provider_decision_recovery_trigger_templates enable row level security;
alter table public.global_provider_decision_recovery_matrix enable row level security;

create policy "Public reads provider decision-recovery controls" on public.global_provider_decision_recovery_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads provider decision-recovery states" on public.global_provider_decision_recovery_state_templates
  for select to anon, authenticated using (not real_recovery_event_present);
create policy "Public reads unobserved provider decision-recovery triggers" on public.global_provider_decision_recovery_trigger_templates
  for select to anon, authenticated using (trigger_status = 'unobserved' and not real_event_present);
create policy "Public reads blocked provider decision-recovery matrix" on public.global_provider_decision_recovery_matrix
  for select to anon, authenticated using (recovery_status = 'blocked' and not human_authorized);

revoke all on table public.global_provider_decision_recovery_controls,
  public.global_provider_decision_recovery_state_templates,
  public.global_provider_decision_recovery_trigger_templates,
  public.global_provider_decision_recovery_matrix from public, anon, authenticated, service_role;
grant select on table public.global_provider_decision_recovery_controls,
  public.global_provider_decision_recovery_state_templates,
  public.global_provider_decision_recovery_trigger_templates,
  public.global_provider_decision_recovery_matrix to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_decision_recovery_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider decision recovery-control reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_decision_recovery_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_decision_recovery_controls_append_only before update or delete on public.global_provider_decision_recovery_controls
  for each row execute function public.prevent_global_provider_decision_recovery_reference_mutation();
create trigger global_provider_decision_recovery_states_append_only before update or delete on public.global_provider_decision_recovery_state_templates
  for each row execute function public.prevent_global_provider_decision_recovery_reference_mutation();
create trigger global_provider_decision_recovery_triggers_append_only before update or delete on public.global_provider_decision_recovery_trigger_templates
  for each row execute function public.prevent_global_provider_decision_recovery_reference_mutation();
create trigger global_provider_decision_recovery_matrix_append_only before update or delete on public.global_provider_decision_recovery_matrix
  for each row execute function public.prevent_global_provider_decision_recovery_reference_mutation();

create view public.global_provider_decision_recovery_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_candidate_review_profiles)::integer source_family_count,
  (select count(*) from public.global_provider_decision_recovery_trigger_templates)::integer recovery_trigger_count,
  (select count(*) from public.global_provider_decision_recovery_state_templates)::integer recovery_state_count,
  (select count(*) from public.global_provider_decision_recovery_matrix)::integer recovery_cell_count,
  (select count(*) from public.global_provider_decision_recovery_matrix where recovery_status = 'blocked')::integer blocked_recovery_cell_count,
  (select count(*) from public.global_provider_decision_recovery_matrix where human_authorized)::integer authorized_recovery_cell_count
from public.global_provider_decision_recovery_controls control;

create view public.global_provider_decision_recovery_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  real_recovery_event_present, automatic_transition_enabled, human_recovery_review_required,
  freeze_effect, rollback_effect, revocation_effect, production_effect
from public.global_provider_decision_recovery_state_templates;

create view public.global_provider_decision_recovery_trigger_catalog with (security_invoker=true) as
select id, sequence_number, trigger_key, recovery_domain, display_name, trigger_definition,
  trigger_status, real_event_present, investigator_assigned, human_authorized
from public.global_provider_decision_recovery_trigger_templates;

create view public.global_provider_decision_recovery_catalog with (security_invoker=true) as
select matrix.id, profile.source_family_key, source.display_name source_family_name,
  trigger.trigger_key, trigger.sequence_number trigger_sequence_number,
  trigger.display_name trigger_name, trigger.recovery_domain,
  matrix.recovery_status, matrix.human_authorized, matrix.automated_freeze_effect,
  matrix.rollback_effect, matrix.revocation_effect, matrix.endpoint_access_effect,
  matrix.candidate_write_effect, matrix.release_effect, matrix.production_effect
from public.global_provider_decision_recovery_matrix matrix
join public.global_provider_candidate_review_profiles profile on profile.id = matrix.review_profile_id
join public.global_provider_contract_test_suites suite on suite.id = profile.contract_suite_id
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id
join public.global_provider_decision_recovery_trigger_templates trigger on trigger.id = matrix.recovery_trigger_template_id;

grant select on public.global_provider_decision_recovery_status,
  public.global_provider_decision_recovery_state_catalog,
  public.global_provider_decision_recovery_trigger_catalog,
  public.global_provider_decision_recovery_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_decision_recovery_state_templates) <> 7
    or (select count(*) from public.global_provider_decision_recovery_trigger_templates) <> 8
    or (select count(*) from public.global_provider_decision_recovery_matrix) <> 64 then
    raise exception 'Phase 8R provider decision recovery-control reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_decision_recovery_controls
    where exception_recording_enabled or decision_challenge_recording_enabled
      or investigator_identity_storage_enabled or recovery_evidence_linkage_enabled
      or automated_freeze_enabled or rollback_execution_enabled or decision_revocation_enabled
      or provider_candidate_selection_enabled or review_packet_open_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_decision_recovery_state_templates
    where real_recovery_event_present or automatic_transition_enabled
      or not human_recovery_review_required or freeze_effect or rollback_effect
      or revocation_effect or production_effect
  ) or exists (
    select 1 from public.global_provider_decision_recovery_trigger_templates
    where trigger_status <> 'unobserved' or real_event_present
      or investigator_assigned or human_authorized
  ) or exists (
    select 1 from public.global_provider_decision_recovery_matrix
    where recovery_status <> 'blocked' or exception_reference is not null
      or challenge_reference is not null or recovery_evidence_reference is not null
      or investigator_identity is not null or recovery_reason_code is not null
      or recovery_signature is not null or detected_at is not null
      or frozen_at is not null or revoked_at is not null or resolved_at is not null
      or human_authorized or automated_freeze_effect or rollback_effect
      or revocation_effect or endpoint_access_effect or candidate_write_effect
      or release_effect or production_effect
  ) then
    raise exception 'Phase 8R provider decision recovery controls must remain empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_review_decision_controls
    where decision_recording_enabled or automated_quorum_evaluation_enabled
      or provider_candidate_selection_enabled or review_packet_open_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8Q provider review-decision boundary changed';
  end if;
end;
$$;

commit;
