-- TradePulse AI
-- Migration 062: Phase 8S provider activation authorization and change-control readiness
-- Reference controls only. No real provider, change packet, authorization,
-- endpoint, credential, payload or activation exists.

begin;

create table public.global_provider_activation_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  activation_gate_target integer not null default 8 check (activation_gate_target = 8),
  readiness_cell_target integer not null default 64 check (readiness_cell_target = 64),
  activation_state_target integer not null default 7 check (activation_state_target = 7),
  independent_activation_authorization_required boolean not null default true check (independent_activation_authorization_required),
  dual_control_activation_required boolean not null default true check (dual_control_activation_required),
  bounded_maintenance_window_required boolean not null default true check (bounded_maintenance_window_required),
  pre_activation_snapshot_required boolean not null default true check (pre_activation_snapshot_required),
  tested_abort_and_restoration_required boolean not null default true check (tested_abort_and_restoration_required),
  post_activation_verification_required boolean not null default true check (post_activation_verification_required),
  immutable_change_audit_required boolean not null default true check (immutable_change_audit_required),
  expiry_and_revocation_enforced boolean not null default true check (expiry_and_revocation_enforced),
  activation_request_recording_enabled boolean not null default false check (not activation_request_recording_enabled),
  activation_authorization_recording_enabled boolean not null default false check (not activation_authorization_recording_enabled),
  maintenance_window_scheduling_enabled boolean not null default false check (not maintenance_window_scheduling_enabled),
  provider_candidate_selection_enabled boolean not null default false check (not provider_candidate_selection_enabled),
  endpoint_connectivity_enabled boolean not null default false check (not endpoint_connectivity_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  fixture_execution_enabled boolean not null default false check (not fixture_execution_enabled),
  conformance_approval_enabled boolean not null default false check (not conformance_approval_enabled),
  provider_activation_enabled boolean not null default false check (not provider_activation_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_activation_controls (control_key, policy_version)
values ('global-provider-activation-readiness-controls', 'global-provider-activation-readiness-controls-v1');

create table public.global_provider_activation_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 320),
  real_activation_present boolean not null default false check (not real_activation_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_activation_authorization_required boolean not null default true check (human_activation_authorization_required),
  endpoint_access_effect boolean not null default false check (not endpoint_access_effect),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  activation_effect boolean not null default false check (not activation_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_activation_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'activation_not_requested','Activation not requested','No real provider candidate or activation request exists; all connectivity, credential, write and release capabilities remain unavailable.'),
  (2,'change_packet_required','Change packet required','A future activation must begin with a bounded, evidence-linked change packet without selecting a provider or scheduling a change.'),
  (3,'independent_authorization_required','Independent authorization required','A future activation packet must receive conflict-free, independent authorization and separate dual control before any access.'),
  (4,'pre_activation_snapshot_required','Pre-activation snapshot required','A future controlled change must preserve verified configuration, rights, schema and recovery baselines before a bounded attempt.'),
  (5,'bounded_window_required','Bounded window required','A future activation must use an approved maintenance window with expiry, abort thresholds and no authority beyond its scope.'),
  (6,'abort_and_verification_required','Abort and verification required','A future attempt must prove fail-closed abort, restoration and post-change verification without implying activation in this phase.'),
  (7,'closed_without_activation','Closed without activation','A future accountable closeout must retain immutable evidence and reason codes while granting no endpoint, write or production effect.');

create table public.global_provider_activation_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique,
  activation_domain text not null check (activation_domain in ('governance','identity','legal','rights','privacy_security','data_contract','operations')),
  display_name text not null unique,
  gate_definition text not null check (char_length(gate_definition) between 40 and 320),
  gate_status text not null default 'unmet' check (gate_status = 'unmet'),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  reviewer_assigned boolean not null default false check (not reviewer_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.global_provider_activation_gate_templates (
  sequence_number, gate_key, activation_domain, display_name, gate_definition
) values
  (1,'decision_and_recovery_ready','governance','Decision and recovery readiness','Require a current bounded decision, verified recovery controls, unexpired authority and no unresolved exception before activation review.'),
  (2,'provider_identity_and_scope_bound','identity','Provider identity and scope bound','Require verified provider identity, accountable ownership, purpose limitation and a narrowly defined source-family scope.'),
  (3,'legal_authority_current','legal','Legal authority current','Require current contracting, jurisdiction, regulatory and enforceability evidence for the exact proposed activation scope.'),
  (4,'rights_and_use_limits_current','rights','Rights and use limits current','Require unexpired access, display, retention, redistribution, derivation and model-use rights with explicit restrictions.'),
  (5,'privacy_security_and_custody_ready','privacy_security','Privacy, security and custody ready','Require approved data handling, transfers, retention, deletion, access control, secrets custody and incident containment.'),
  (6,'endpoint_schema_and_version_pinned','data_contract','Endpoint, schema and version pinned','Require an isolated endpoint, pinned schema and deterministic field, unit, time, lineage and idempotency contracts.'),
  (7,'abort_restore_and_verification_rehearsed','operations','Abort, restore and verification rehearsed','Require observed fail-closed abort, restoration, monitoring and post-change verification evidence before any bounded attempt.'),
  (8,'independent_dual_control_authorized','governance','Independent dual control authorized','Require separate accountable authorizers, conflict review, explicit reason codes, expiry and revocation for one bounded window.');

create table public.global_provider_activation_readiness_matrix (
  id bigint generated by default as identity primary key,
  review_profile_id bigint not null references public.global_provider_candidate_review_profiles(id),
  activation_gate_template_id bigint not null references public.global_provider_activation_gate_templates(id),
  readiness_status text not null default 'blocked' check (readiness_status = 'blocked'),
  change_packet_reference text check (change_packet_reference is null),
  decision_reference text check (decision_reference is null),
  recovery_plan_reference text check (recovery_plan_reference is null),
  authorizer_identity text check (authorizer_identity is null),
  activation_reason_code text check (activation_reason_code is null),
  activation_signature text check (activation_signature is null),
  maintenance_window_start timestamptz check (maintenance_window_start is null),
  maintenance_window_end timestamptz check (maintenance_window_end is null),
  activated_at timestamptz check (activated_at is null),
  verified_at timestamptz check (verified_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  endpoint_access_effect boolean not null default false check (not endpoint_access_effect),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  activation_effect boolean not null default false check (not activation_effect),
  candidate_write_effect boolean not null default false check (not candidate_write_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_profile_id, activation_gate_template_id)
);

insert into public.global_provider_activation_readiness_matrix (review_profile_id, activation_gate_template_id)
select profile.id, gate.id
from public.global_provider_candidate_review_profiles profile
cross join public.global_provider_activation_gate_templates gate
order by profile.sequence_number, gate.sequence_number;

alter table public.global_provider_activation_controls enable row level security;
alter table public.global_provider_activation_state_templates enable row level security;
alter table public.global_provider_activation_gate_templates enable row level security;
alter table public.global_provider_activation_readiness_matrix enable row level security;

create policy "Public reads provider activation controls" on public.global_provider_activation_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads provider activation states" on public.global_provider_activation_state_templates
  for select to anon, authenticated using (not real_activation_present);
create policy "Public reads unmet provider activation gates" on public.global_provider_activation_gate_templates
  for select to anon, authenticated using (gate_status = 'unmet' and not real_evidence_present);
create policy "Public reads blocked provider activation matrix" on public.global_provider_activation_readiness_matrix
  for select to anon, authenticated using (readiness_status = 'blocked' and not human_authorized);

revoke all on table public.global_provider_activation_controls,
  public.global_provider_activation_state_templates,
  public.global_provider_activation_gate_templates,
  public.global_provider_activation_readiness_matrix from public, anon, authenticated, service_role;
grant select on table public.global_provider_activation_controls,
  public.global_provider_activation_state_templates,
  public.global_provider_activation_gate_templates,
  public.global_provider_activation_readiness_matrix to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_activation_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider activation-readiness reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_activation_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_activation_controls_append_only before update or delete on public.global_provider_activation_controls
  for each row execute function public.prevent_global_provider_activation_reference_mutation();
create trigger global_provider_activation_states_append_only before update or delete on public.global_provider_activation_state_templates
  for each row execute function public.prevent_global_provider_activation_reference_mutation();
create trigger global_provider_activation_gates_append_only before update or delete on public.global_provider_activation_gate_templates
  for each row execute function public.prevent_global_provider_activation_reference_mutation();
create trigger global_provider_activation_matrix_append_only before update or delete on public.global_provider_activation_readiness_matrix
  for each row execute function public.prevent_global_provider_activation_reference_mutation();

create view public.global_provider_activation_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_candidate_review_profiles)::integer source_family_count,
  (select count(*) from public.global_provider_activation_gate_templates)::integer activation_gate_count,
  (select count(*) from public.global_provider_activation_state_templates)::integer activation_state_count,
  (select count(*) from public.global_provider_activation_readiness_matrix)::integer readiness_cell_count,
  (select count(*) from public.global_provider_activation_readiness_matrix where readiness_status = 'blocked')::integer blocked_readiness_cell_count,
  (select count(*) from public.global_provider_activation_readiness_matrix where human_authorized)::integer authorized_readiness_cell_count
from public.global_provider_activation_controls control;

create view public.global_provider_activation_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  real_activation_present, automatic_transition_enabled, human_activation_authorization_required,
  endpoint_access_effect, credential_access_effect, activation_effect, production_effect
from public.global_provider_activation_state_templates;

create view public.global_provider_activation_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, activation_domain, display_name, gate_definition,
  gate_status, real_evidence_present, reviewer_assigned, human_authorized
from public.global_provider_activation_gate_templates;

create view public.global_provider_activation_readiness_catalog with (security_invoker=true) as
select matrix.id, profile.source_family_key, source.display_name source_family_name,
  gate.gate_key, gate.sequence_number gate_sequence_number,
  gate.display_name gate_name, gate.activation_domain,
  matrix.readiness_status, matrix.human_authorized, matrix.endpoint_access_effect,
  matrix.credential_access_effect, matrix.activation_effect, matrix.candidate_write_effect,
  matrix.release_effect, matrix.production_effect
from public.global_provider_activation_readiness_matrix matrix
join public.global_provider_candidate_review_profiles profile on profile.id = matrix.review_profile_id
join public.global_provider_contract_test_suites suite on suite.id = profile.contract_suite_id
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id
join public.global_provider_activation_gate_templates gate on gate.id = matrix.activation_gate_template_id;

grant select on public.global_provider_activation_status,
  public.global_provider_activation_state_catalog,
  public.global_provider_activation_gate_catalog,
  public.global_provider_activation_readiness_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_activation_state_templates) <> 7
    or (select count(*) from public.global_provider_activation_gate_templates) <> 8
    or (select count(*) from public.global_provider_activation_readiness_matrix) <> 64 then
    raise exception 'Phase 8S provider activation-readiness reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_activation_controls
    where activation_request_recording_enabled or activation_authorization_recording_enabled
      or maintenance_window_scheduling_enabled or provider_candidate_selection_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or provider_activation_enabled
      or candidate_write_enabled or observation_release_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_activation_state_templates
    where real_activation_present or automatic_transition_enabled
      or not human_activation_authorization_required or endpoint_access_effect
      or credential_access_effect or activation_effect or production_effect
  ) or exists (
    select 1 from public.global_provider_activation_gate_templates
    where gate_status <> 'unmet' or real_evidence_present
      or reviewer_assigned or human_authorized
  ) or exists (
    select 1 from public.global_provider_activation_readiness_matrix
    where readiness_status <> 'blocked' or change_packet_reference is not null
      or decision_reference is not null or recovery_plan_reference is not null
      or authorizer_identity is not null or activation_reason_code is not null
      or activation_signature is not null or maintenance_window_start is not null
      or maintenance_window_end is not null or activated_at is not null
      or verified_at is not null or human_authorized or endpoint_access_effect
      or credential_access_effect or activation_effect or candidate_write_effect
      or release_effect or production_effect
  ) then
    raise exception 'Phase 8S provider activation readiness must remain empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_decision_recovery_controls
    where exception_recording_enabled or decision_challenge_recording_enabled
      or automated_freeze_enabled or rollback_execution_enabled
      or decision_revocation_enabled or endpoint_connectivity_enabled
      or candidate_write_enabled or observation_release_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8R recovery boundary changed';
  end if;
end;
$$;

commit;
