-- TradePulse AI
-- Migration 063: Phase 8T provider activation rehearsal and rollback verification
-- Reference controls only. No real provider, rehearsal plan, environment,
-- endpoint, credential, payload, drill or activation exists.

begin;

create table public.global_provider_activation_rehearsal_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  source_family_target integer not null default 8 check (source_family_target = 8),
  rehearsal_gate_target integer not null default 8 check (rehearsal_gate_target = 8),
  rehearsal_cell_target integer not null default 64 check (rehearsal_cell_target = 64),
  rehearsal_state_target integer not null default 7 check (rehearsal_state_target = 7),
  isolated_nonproduction_environment_required boolean not null default true check (isolated_nonproduction_environment_required),
  synthetic_only_inputs_required boolean not null default true check (synthetic_only_inputs_required),
  outbound_egress_allowlist_required boolean not null default true check (outbound_egress_allowlist_required),
  ephemeral_secret_custody_required boolean not null default true check (ephemeral_secret_custody_required),
  pre_rehearsal_snapshot_required boolean not null default true check (pre_rehearsal_snapshot_required),
  tested_abort_and_restoration_required boolean not null default true check (tested_abort_and_restoration_required),
  post_rehearsal_verification_required boolean not null default true check (post_rehearsal_verification_required),
  independent_closeout_required boolean not null default true check (independent_closeout_required),
  immutable_rehearsal_audit_required boolean not null default true check (immutable_rehearsal_audit_required),
  expiry_and_revocation_enforced boolean not null default true check (expiry_and_revocation_enforced),
  rehearsal_request_recording_enabled boolean not null default false check (not rehearsal_request_recording_enabled),
  rehearsal_window_scheduling_enabled boolean not null default false check (not rehearsal_window_scheduling_enabled),
  isolated_egress_test_enabled boolean not null default false check (not isolated_egress_test_enabled),
  synthetic_credential_binding_enabled boolean not null default false check (not synthetic_credential_binding_enabled),
  synthetic_payload_execution_enabled boolean not null default false check (not synthetic_payload_execution_enabled),
  abort_drill_execution_enabled boolean not null default false check (not abort_drill_execution_enabled),
  restoration_drill_execution_enabled boolean not null default false check (not restoration_drill_execution_enabled),
  reconciliation_execution_enabled boolean not null default false check (not reconciliation_execution_enabled),
  provider_candidate_selection_enabled boolean not null default false check (not provider_candidate_selection_enabled),
  endpoint_connectivity_enabled boolean not null default false check (not endpoint_connectivity_enabled),
  credential_storage_enabled boolean not null default false check (not credential_storage_enabled),
  external_payload_intake_enabled boolean not null default false check (not external_payload_intake_enabled),
  fixture_execution_enabled boolean not null default false check (not fixture_execution_enabled),
  conformance_approval_enabled boolean not null default false check (not conformance_approval_enabled),
  provider_activation_enabled boolean not null default false check (not provider_activation_enabled),
  candidate_write_enabled boolean not null default false check (not candidate_write_enabled),
  observation_release_enabled boolean not null default false check (not observation_release_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  autonomous_trade_execution_enabled boolean not null default false check (not autonomous_trade_execution_enabled),
  updated_at timestamptz not null default now()
);

insert into public.global_provider_activation_rehearsal_controls (control_key, policy_version)
values ('global-provider-activation-rehearsal-controls', 'global-provider-activation-rehearsal-controls-v1');

create table public.global_provider_activation_rehearsal_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 320),
  real_rehearsal_present boolean not null default false check (not real_rehearsal_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_rehearsal_authorization_required boolean not null default true check (human_rehearsal_authorization_required),
  egress_access_effect boolean not null default false check (not egress_access_effect),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  activation_effect boolean not null default false check (not activation_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.global_provider_activation_rehearsal_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'rehearsal_not_requested','Rehearsal not requested','No real provider or rehearsal request exists; external egress, credentials, payload execution, writes and activation remain unavailable.'),
  (2,'runbook_required','Runbook required','A future rehearsal must begin with an approved provider-specific runbook, bounded scope and accountable ownership without enabling access.'),
  (3,'isolation_and_synthetic_inputs_required','Isolation and synthetic inputs required','A future rehearsal must use an isolated non-production environment, allowlisted egress and synthetic-only identities, secrets and payloads.'),
  (4,'pre_rehearsal_snapshot_required','Pre-rehearsal snapshot required','A future rehearsal must preserve verified configuration, schema, access, observability and restoration baselines before a bounded attempt.'),
  (5,'bounded_rehearsal_window_required','Bounded rehearsal window required','A future rehearsal must use an expiring authorized window with stop conditions, no production authority and no scope inheritance.'),
  (6,'abort_restore_and_verify_required','Abort, restore and verify required','A future rehearsal must prove fail-closed abort, restoration, reconciliation and post-rehearsal verification without activating a provider.'),
  (7,'closed_without_activation','Closed without activation','A future independent closeout must retain immutable evidence and revoke temporary authority while granting no endpoint, write or production effect.');

create table public.global_provider_activation_rehearsal_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique,
  rehearsal_domain text not null check (rehearsal_domain in ('governance','isolation','identity','data_contract','observability','recovery','verification')),
  display_name text not null unique,
  gate_definition text not null check (char_length(gate_definition) between 40 and 320),
  gate_status text not null default 'unmet' check (gate_status = 'unmet'),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  reviewer_assigned boolean not null default false check (not reviewer_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.global_provider_activation_rehearsal_gate_templates (
  sequence_number, gate_key, rehearsal_domain, display_name, gate_definition
) values
  (1,'activation_readiness_current','governance','Activation readiness current','Require the Phase 8S decision, recovery, rights and activation-readiness evidence to remain current, bounded, unexpired and exception-free.'),
  (2,'isolated_environment_and_egress_bounded','isolation','Isolated environment and egress bounded','Require a non-production environment with denied-by-default outbound access, an exact allowlist, resource limits and automatic expiry.'),
  (3,'synthetic_identity_secrets_and_payloads_only','identity','Synthetic identity, secrets and payloads only','Require non-customer synthetic identities, ephemeral non-production secrets and deterministic fixtures with no provider or personal data.'),
  (4,'endpoint_schema_and_rate_limits_pinned','data_contract','Endpoint, schema and rate limits pinned','Require a non-production endpoint contract, pinned schema, deterministic mappings, idempotency and bounded quota assumptions before rehearsal.'),
  (5,'observability_alerting_and_stop_controls_ready','observability','Observability, alerting and stop controls ready','Require traces, metrics, logs, freshness checks, alerts, stop thresholds and accountable observation without storing sensitive payloads.'),
  (6,'abort_restoration_and_reconciliation_rehearsed','recovery','Abort, restoration and reconciliation rehearsed','Require observed fail-closed abort, deterministic restoration, zero residual authority and reconciliation of every simulated effect.'),
  (7,'post_rehearsal_verification_complete','verification','Post-rehearsal verification complete','Require independent verification of isolation, secret revocation, egress closure, restored baselines and absence of production effects.'),
  (8,'independent_closeout_and_expiry_authorized','governance','Independent closeout and expiry authorized','Require separate accountable closeout, explicit reason codes, immutable audit, expiry and revocation without granting activation authority.');

create table public.global_provider_activation_rehearsal_matrix (
  id bigint generated by default as identity primary key,
  review_profile_id bigint not null references public.global_provider_candidate_review_profiles(id),
  rehearsal_gate_template_id bigint not null references public.global_provider_activation_rehearsal_gate_templates(id),
  rehearsal_status text not null default 'blocked' check (rehearsal_status = 'blocked'),
  rehearsal_plan_reference text check (rehearsal_plan_reference is null),
  activation_readiness_reference text check (activation_readiness_reference is null),
  environment_reference text check (environment_reference is null),
  synthetic_secret_reference text check (synthetic_secret_reference is null),
  snapshot_reference text check (snapshot_reference is null),
  abort_report_reference text check (abort_report_reference is null),
  restoration_report_reference text check (restoration_report_reference is null),
  verification_report_reference text check (verification_report_reference is null),
  closeout_authorizer_identity text check (closeout_authorizer_identity is null),
  rehearsal_window_start timestamptz check (rehearsal_window_start is null),
  rehearsal_window_end timestamptz check (rehearsal_window_end is null),
  rehearsed_at timestamptz check (rehearsed_at is null),
  closed_at timestamptz check (closed_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  egress_access_effect boolean not null default false check (not egress_access_effect),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  fixture_execution_effect boolean not null default false check (not fixture_execution_effect),
  abort_execution_effect boolean not null default false check (not abort_execution_effect),
  restoration_execution_effect boolean not null default false check (not restoration_execution_effect),
  activation_effect boolean not null default false check (not activation_effect),
  candidate_write_effect boolean not null default false check (not candidate_write_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (review_profile_id, rehearsal_gate_template_id)
);

insert into public.global_provider_activation_rehearsal_matrix (review_profile_id, rehearsal_gate_template_id)
select profile.id, gate.id
from public.global_provider_candidate_review_profiles profile
cross join public.global_provider_activation_rehearsal_gate_templates gate
order by profile.sequence_number, gate.sequence_number;

alter table public.global_provider_activation_rehearsal_controls enable row level security;
alter table public.global_provider_activation_rehearsal_state_templates enable row level security;
alter table public.global_provider_activation_rehearsal_gate_templates enable row level security;
alter table public.global_provider_activation_rehearsal_matrix enable row level security;

create policy "Public reads provider activation rehearsal controls" on public.global_provider_activation_rehearsal_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads provider activation rehearsal states" on public.global_provider_activation_rehearsal_state_templates
  for select to anon, authenticated using (not real_rehearsal_present);
create policy "Public reads unmet provider activation rehearsal gates" on public.global_provider_activation_rehearsal_gate_templates
  for select to anon, authenticated using (gate_status = 'unmet' and not real_evidence_present);
create policy "Public reads blocked provider activation rehearsal matrix" on public.global_provider_activation_rehearsal_matrix
  for select to anon, authenticated using (rehearsal_status = 'blocked' and not human_authorized);

revoke all on table public.global_provider_activation_rehearsal_controls,
  public.global_provider_activation_rehearsal_state_templates,
  public.global_provider_activation_rehearsal_gate_templates,
  public.global_provider_activation_rehearsal_matrix from public, anon, authenticated, service_role;
grant select on table public.global_provider_activation_rehearsal_controls,
  public.global_provider_activation_rehearsal_state_templates,
  public.global_provider_activation_rehearsal_gate_templates,
  public.global_provider_activation_rehearsal_matrix to anon, authenticated, service_role;

create or replace function public.prevent_global_provider_activation_rehearsal_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Global provider activation-rehearsal reference records are append-only';
end;
$$;
revoke all on function public.prevent_global_provider_activation_rehearsal_reference_mutation() from public, anon, authenticated, service_role;

create trigger global_provider_activation_rehearsal_controls_append_only before update or delete on public.global_provider_activation_rehearsal_controls
  for each row execute function public.prevent_global_provider_activation_rehearsal_reference_mutation();
create trigger global_provider_activation_rehearsal_states_append_only before update or delete on public.global_provider_activation_rehearsal_state_templates
  for each row execute function public.prevent_global_provider_activation_rehearsal_reference_mutation();
create trigger global_provider_activation_rehearsal_gates_append_only before update or delete on public.global_provider_activation_rehearsal_gate_templates
  for each row execute function public.prevent_global_provider_activation_rehearsal_reference_mutation();
create trigger global_provider_activation_rehearsal_matrix_append_only before update or delete on public.global_provider_activation_rehearsal_matrix
  for each row execute function public.prevent_global_provider_activation_rehearsal_reference_mutation();

create view public.global_provider_activation_rehearsal_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.global_provider_candidate_review_profiles)::integer source_family_count,
  (select count(*) from public.global_provider_activation_rehearsal_gate_templates)::integer rehearsal_gate_count,
  (select count(*) from public.global_provider_activation_rehearsal_state_templates)::integer rehearsal_state_count,
  (select count(*) from public.global_provider_activation_rehearsal_matrix)::integer rehearsal_cell_count,
  (select count(*) from public.global_provider_activation_rehearsal_matrix where rehearsal_status = 'blocked')::integer blocked_rehearsal_cell_count,
  (select count(*) from public.global_provider_activation_rehearsal_matrix where human_authorized)::integer authorized_rehearsal_cell_count
from public.global_provider_activation_rehearsal_controls control;

create view public.global_provider_activation_rehearsal_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  real_rehearsal_present, automatic_transition_enabled, human_rehearsal_authorization_required,
  egress_access_effect, credential_access_effect, activation_effect, production_effect
from public.global_provider_activation_rehearsal_state_templates;

create view public.global_provider_activation_rehearsal_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, rehearsal_domain, display_name, gate_definition,
  gate_status, real_evidence_present, reviewer_assigned, human_authorized
from public.global_provider_activation_rehearsal_gate_templates;

create view public.global_provider_activation_rehearsal_catalog with (security_invoker=true) as
select matrix.id, profile.source_family_key, source.display_name source_family_name,
  gate.gate_key, gate.sequence_number gate_sequence_number,
  gate.display_name gate_name, gate.rehearsal_domain,
  matrix.rehearsal_status, matrix.human_authorized, matrix.egress_access_effect,
  matrix.credential_access_effect, matrix.fixture_execution_effect,
  matrix.abort_execution_effect, matrix.restoration_execution_effect,
  matrix.activation_effect, matrix.candidate_write_effect,
  matrix.release_effect, matrix.production_effect
from public.global_provider_activation_rehearsal_matrix matrix
join public.global_provider_candidate_review_profiles profile on profile.id = matrix.review_profile_id
join public.global_provider_contract_test_suites suite on suite.id = profile.contract_suite_id
join public.global_provider_certification_profiles certification on certification.id = suite.certification_profile_id
join public.global_observation_source_connectors source on source.id = certification.source_connector_id
join public.global_provider_activation_rehearsal_gate_templates gate on gate.id = matrix.rehearsal_gate_template_id;

grant select on public.global_provider_activation_rehearsal_status,
  public.global_provider_activation_rehearsal_state_catalog,
  public.global_provider_activation_rehearsal_gate_catalog,
  public.global_provider_activation_rehearsal_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.global_provider_activation_rehearsal_state_templates) <> 7
    or (select count(*) from public.global_provider_activation_rehearsal_gate_templates) <> 8
    or (select count(*) from public.global_provider_activation_rehearsal_matrix) <> 64 then
    raise exception 'Phase 8T provider activation-rehearsal reference counts changed';
  end if;
  if exists (
    select 1 from public.global_provider_activation_rehearsal_controls
    where rehearsal_request_recording_enabled or rehearsal_window_scheduling_enabled
      or isolated_egress_test_enabled or synthetic_credential_binding_enabled
      or synthetic_payload_execution_enabled or abort_drill_execution_enabled
      or restoration_drill_execution_enabled or reconciliation_execution_enabled
      or provider_candidate_selection_enabled or endpoint_connectivity_enabled
      or credential_storage_enabled or external_payload_intake_enabled
      or fixture_execution_enabled or conformance_approval_enabled
      or provider_activation_enabled or candidate_write_enabled
      or observation_release_enabled or model_training_enabled
      or autonomous_publication_enabled or autonomous_trade_execution_enabled
  ) or exists (
    select 1 from public.global_provider_activation_rehearsal_state_templates
    where real_rehearsal_present or automatic_transition_enabled
      or not human_rehearsal_authorization_required or egress_access_effect
      or credential_access_effect or activation_effect or production_effect
  ) or exists (
    select 1 from public.global_provider_activation_rehearsal_gate_templates
    where gate_status <> 'unmet' or real_evidence_present
      or reviewer_assigned or human_authorized
  ) or exists (
    select 1 from public.global_provider_activation_rehearsal_matrix
    where rehearsal_status <> 'blocked' or rehearsal_plan_reference is not null
      or activation_readiness_reference is not null or environment_reference is not null
      or synthetic_secret_reference is not null or snapshot_reference is not null
      or abort_report_reference is not null or restoration_report_reference is not null
      or verification_report_reference is not null or closeout_authorizer_identity is not null
      or rehearsal_window_start is not null or rehearsal_window_end is not null
      or rehearsed_at is not null or closed_at is not null or human_authorized
      or egress_access_effect or credential_access_effect or fixture_execution_effect
      or abort_execution_effect or restoration_execution_effect or activation_effect
      or candidate_write_effect or release_effect or production_effect
  ) then
    raise exception 'Phase 8T provider activation rehearsal must remain empty and fail-closed';
  end if;
  if exists (
    select 1 from public.global_provider_activation_controls
    where activation_request_recording_enabled or activation_authorization_recording_enabled
      or maintenance_window_scheduling_enabled or provider_candidate_selection_enabled
      or endpoint_connectivity_enabled or credential_storage_enabled
      or external_payload_intake_enabled or fixture_execution_enabled
      or conformance_approval_enabled or provider_activation_enabled
      or candidate_write_enabled or observation_release_enabled
      or model_training_enabled or autonomous_publication_enabled
      or autonomous_trade_execution_enabled
  ) then
    raise exception 'The Phase 8S activation boundary changed';
  end if;
end;
$$;

commit;
