-- TradePulse AI
-- Migration 064: Phase 8U external audience production launch readiness
-- Reference controls only. No external audience, public signup, live provider,
-- customer data intake, production launch, financial execution or payment exists.

begin;

create table public.external_audience_launch_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  audience_surface_target integer not null default 8 check (audience_surface_target = 8),
  launch_gate_target integer not null default 8 check (launch_gate_target = 8),
  readiness_cell_target integer not null default 64 check (readiness_cell_target = 64),
  launch_state_target integer not null default 7 check (launch_state_target = 7),
  protected_production_domain_required boolean not null default true check (protected_production_domain_required),
  exact_auth_origin_and_redirects_required boolean not null default true check (exact_auth_origin_and_redirects_required),
  custom_auth_delivery_and_abuse_controls_required boolean not null default true check (custom_auth_delivery_and_abuse_controls_required),
  published_legal_privacy_risk_support_required boolean not null default true check (published_legal_privacy_risk_support_required),
  production_monitoring_on_call_incident_required boolean not null default true check (production_monitoring_on_call_incident_required),
  approved_external_cohort_and_feedback_required boolean not null default true check (approved_external_cohort_and_feedback_required),
  accessibility_performance_capacity_evidence_required boolean not null default true check (accessibility_performance_capacity_evidence_required),
  data_rights_freshness_and_labels_required boolean not null default true check (data_rights_freshness_and_labels_required),
  release_rollback_expiry_required boolean not null default true check (release_rollback_expiry_required),
  independent_human_launch_authorization_required boolean not null default true check (independent_human_launch_authorization_required),
  public_signup_enabled boolean not null default false check (not public_signup_enabled),
  unrestricted_discovery_enabled boolean not null default false check (not unrestricted_discovery_enabled),
  automated_tester_provisioning_enabled boolean not null default false check (not automated_tester_provisioning_enabled),
  external_audience_activation_enabled boolean not null default false check (not external_audience_activation_enabled),
  live_provider_connectivity_enabled boolean not null default false check (not live_provider_connectivity_enabled),
  production_credential_storage_enabled boolean not null default false check (not production_credential_storage_enabled),
  production_payload_intake_enabled boolean not null default false check (not production_payload_intake_enabled),
  unrestricted_customer_data_collection_enabled boolean not null default false check (not unrestricted_customer_data_collection_enabled),
  autonomous_publication_enabled boolean not null default false check (not autonomous_publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  live_order_routing_enabled boolean not null default false check (not live_order_routing_enabled),
  payment_execution_enabled boolean not null default false check (not payment_execution_enabled),
  money_movement_enabled boolean not null default false check (not money_movement_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  settlement_enabled boolean not null default false check (not settlement_enabled),
  updated_at timestamptz not null default now()
);

insert into public.external_audience_launch_controls (control_key, policy_version)
values ('external-audience-launch-controls', 'external-audience-launch-controls-v1');

create table public.external_audience_launch_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 360),
  real_audience_present boolean not null default false check (not real_audience_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_launch_authorization_required boolean not null default true check (human_launch_authorization_required),
  public_access_effect boolean not null default false check (not public_access_effect),
  customer_data_effect boolean not null default false check (not customer_data_effect),
  financial_execution_effect boolean not null default false check (not financial_execution_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.external_audience_launch_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'launch_not_requested','Launch not requested','No external-audience launch request or approved cohort exists; public signup, production access and every financial action remain unavailable.'),
  (2,'operational_evidence_required','Operational evidence required','A future launch requires exact domain, identity, legal, support, monitoring, data-rights, capacity and rollback evidence without enabling access.'),
  (3,'remediation_required','Remediation required','Any missing, stale, conflicting or failed control must return the affected surface to remediation with no inherited approval or customer exposure.'),
  (4,'independent_verification_required','Independent verification required','A reviewer separate from implementation must verify each evidence item, expiry, customer label and fail-closed result before launch review.'),
  (5,'bounded_cohort_authorization_required','Bounded cohort authorization required','A future external cohort must have exact identities, jurisdiction, consent, capacity, support ownership, duration and revocation approved manually.'),
  (6,'monitored_launch_window_required','Monitored launch window required','A future launch must use a bounded window with live monitoring, stop thresholds, staffed response and tested rollback without financial execution.'),
  (7,'closed_or_revoked','Closed or revoked','Independent closeout must remove temporary authority, preserve immutable evidence and confirm no residual customer access or production side effect.');

create table public.external_audience_launch_surface_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  surface_key text not null unique,
  display_name text not null unique,
  surface_definition text not null check (char_length(surface_definition) between 40 and 360),
  audience_access_status text not null default 'unavailable' check (audience_access_status = 'unavailable'),
  real_audience_present boolean not null default false check (not real_audience_present),
  customer_data_enabled boolean not null default false check (not customer_data_enabled),
  financial_execution_enabled boolean not null default false check (not financial_execution_enabled),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.external_audience_launch_surface_templates (
  sequence_number, surface_key, display_name, surface_definition
) values
  (1,'public_market_dashboard','Public market dashboard','Market summaries and freshness labels must be safe, licensed or synthetic, accessible and explicit about unavailable or delayed information.'),
  (2,'equity_research_and_watchlists','Equity research and watchlists','Research, evidence, watchlists and alerts must preserve provenance, uncertainty, account isolation and non-advice boundaries.'),
  (3,'agentic_analysis_and_reports','Agentic analysis and reports','AI analysis and reusable reports must remain grounded, cited, bounded, privacy-safe and unable to trade, publish or self-promote models.'),
  (4,'country_event_and_dependency_intelligence','Country, event and dependency intelligence','Global intelligence must expose evidence gaps, rights, freshness and uncertainty without fabricated coverage or autonomous publication.'),
  (5,'paper_trading_and_education','Paper trading and education','Simulation and education must remain clearly virtual, deterministic, reconciled and isolated from brokers, funding, custody and settlement.'),
  (6,'account_security_and_privacy','Account security and privacy','Identity, session, privacy and security recovery must be invite-only, rate-limited, customer-safe and independently supported.'),
  (7,'support_feedback_and_incidents','Support, feedback and incidents','Private support, feedback, incident intake and escalation must have staffed ownership, response targets, privacy controls and abuse limits.'),
  (8,'beta_operations_and_status','Beta operations and status','Launch status, onboarding, cohort controls, monitoring, stop decisions and rollback evidence must remain manual, bounded and auditable.');

create table public.external_audience_launch_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique,
  launch_domain text not null check (launch_domain in ('hosting','identity','legal','operations','cohort','quality','data','release')),
  display_name text not null unique,
  gate_definition text not null check (char_length(gate_definition) between 40 and 360),
  gate_status text not null default 'unmet' check (gate_status = 'unmet'),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  reviewer_assigned boolean not null default false check (not reviewer_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.external_audience_launch_gate_templates (
  sequence_number, gate_key, launch_domain, display_name, gate_definition
) values
  (1,'production_domain_tls_and_routing_verified','hosting','Domain, TLS and routing verified','Require an approved production domain, HTTPS, SPA routing, security headers, caching, asset integrity and tested hosting rollback.'),
  (2,'auth_redirect_email_and_abuse_controls_verified','identity','Authentication and abuse controls verified','Require exact origins and redirects, custom mail delivery, uniform identity responses, CAPTCHA, rate limits, notifications and revocation.'),
  (3,'legal_privacy_risk_and_support_published','legal','Legal, privacy, risk and support published','Require the accountable entity, terms, privacy, risk boundaries, data handling, complaints route and staffed support contacts to be published.'),
  (4,'monitoring_on_call_and_incident_drill_verified','operations','Monitoring and incident response verified','Require production telemetry, privacy-safe alerts, accountable on-call coverage, escalation, status communication and an observed recovery drill.'),
  (5,'cohort_jurisdiction_consent_and_feedback_approved','cohort','Cohort, jurisdiction and consent approved','Require a bounded named cohort, supported jurisdictions, current consent, feedback and incident ownership, capacity, expiry and revocation.'),
  (6,'accessibility_performance_and_capacity_verified','quality','Accessibility, performance and capacity verified','Require desktop and mobile accessibility, browser compatibility, performance budgets, capacity limits and graceful degraded-state evidence.'),
  (7,'data_rights_freshness_and_customer_labels_verified','data','Data rights, freshness and labels verified','Require licensed, public-domain or synthetic data provenance, entitlements, freshness, unavailable states, uncertainty labels and no hidden live-data claim.'),
  (8,'rollback_expiry_and_independent_launch_review_approved','release','Rollback and launch review approved','Require immutable release evidence, independent review, explicit reason codes, bounded launch window, stop thresholds, rollback, expiry and closeout.');

create table public.external_audience_launch_readiness_matrix (
  id bigint generated by default as identity primary key,
  surface_template_id bigint not null references public.external_audience_launch_surface_templates(id),
  gate_template_id bigint not null references public.external_audience_launch_gate_templates(id),
  readiness_status text not null default 'blocked' check (readiness_status = 'blocked'),
  evidence_reference text check (evidence_reference is null),
  reviewer_identity text check (reviewer_identity is null),
  authorization_reference text check (authorization_reference is null),
  cohort_reference text check (cohort_reference is null),
  rollback_reference text check (rollback_reference is null),
  verified_at timestamptz check (verified_at is null),
  expires_at timestamptz check (expires_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  public_access_effect boolean not null default false check (not public_access_effect),
  account_provisioning_effect boolean not null default false check (not account_provisioning_effect),
  customer_data_effect boolean not null default false check (not customer_data_effect),
  live_provider_effect boolean not null default false check (not live_provider_effect),
  publication_effect boolean not null default false check (not publication_effect),
  financial_execution_effect boolean not null default false check (not financial_execution_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (surface_template_id, gate_template_id)
);

insert into public.external_audience_launch_readiness_matrix (surface_template_id, gate_template_id)
select surface.id, gate.id
from public.external_audience_launch_surface_templates surface
cross join public.external_audience_launch_gate_templates gate
order by surface.sequence_number, gate.sequence_number;

alter table public.external_audience_launch_controls enable row level security;
alter table public.external_audience_launch_state_templates enable row level security;
alter table public.external_audience_launch_surface_templates enable row level security;
alter table public.external_audience_launch_gate_templates enable row level security;
alter table public.external_audience_launch_readiness_matrix enable row level security;

create policy "Public reads external audience launch controls" on public.external_audience_launch_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads external audience launch states" on public.external_audience_launch_state_templates
  for select to anon, authenticated using (not real_audience_present);
create policy "Public reads unavailable audience surfaces" on public.external_audience_launch_surface_templates
  for select to anon, authenticated using (audience_access_status = 'unavailable' and not real_audience_present);
create policy "Public reads unmet external audience launch gates" on public.external_audience_launch_gate_templates
  for select to anon, authenticated using (gate_status = 'unmet' and not real_evidence_present);
create policy "Public reads blocked external audience matrix" on public.external_audience_launch_readiness_matrix
  for select to anon, authenticated using (readiness_status = 'blocked' and not human_authorized);

revoke all on table public.external_audience_launch_controls,
  public.external_audience_launch_state_templates,
  public.external_audience_launch_surface_templates,
  public.external_audience_launch_gate_templates,
  public.external_audience_launch_readiness_matrix from public, anon, authenticated, service_role;
grant select on table public.external_audience_launch_controls,
  public.external_audience_launch_state_templates,
  public.external_audience_launch_surface_templates,
  public.external_audience_launch_gate_templates,
  public.external_audience_launch_readiness_matrix to anon, authenticated, service_role;

create or replace function public.prevent_external_audience_launch_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'External audience launch-readiness reference records are append-only';
end;
$$;
revoke all on function public.prevent_external_audience_launch_reference_mutation() from public, anon, authenticated, service_role;

create trigger external_audience_launch_controls_append_only before update or delete on public.external_audience_launch_controls
  for each row execute function public.prevent_external_audience_launch_reference_mutation();
create trigger external_audience_launch_states_append_only before update or delete on public.external_audience_launch_state_templates
  for each row execute function public.prevent_external_audience_launch_reference_mutation();
create trigger external_audience_launch_surfaces_append_only before update or delete on public.external_audience_launch_surface_templates
  for each row execute function public.prevent_external_audience_launch_reference_mutation();
create trigger external_audience_launch_gates_append_only before update or delete on public.external_audience_launch_gate_templates
  for each row execute function public.prevent_external_audience_launch_reference_mutation();
create trigger external_audience_launch_matrix_append_only before update or delete on public.external_audience_launch_readiness_matrix
  for each row execute function public.prevent_external_audience_launch_reference_mutation();

create view public.external_audience_launch_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.external_audience_launch_surface_templates)::integer audience_surface_count,
  (select count(*) from public.external_audience_launch_gate_templates)::integer launch_gate_count,
  (select count(*) from public.external_audience_launch_state_templates)::integer launch_state_count,
  (select count(*) from public.external_audience_launch_readiness_matrix)::integer readiness_cell_count,
  (select count(*) from public.external_audience_launch_readiness_matrix where readiness_status = 'blocked')::integer blocked_readiness_cell_count,
  (select count(*) from public.external_audience_launch_readiness_matrix where human_authorized)::integer authorized_readiness_cell_count
from public.external_audience_launch_controls control;

create view public.external_audience_launch_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  real_audience_present, automatic_transition_enabled, human_launch_authorization_required,
  public_access_effect, customer_data_effect, financial_execution_effect, production_effect
from public.external_audience_launch_state_templates;

create view public.external_audience_launch_surface_catalog with (security_invoker=true) as
select id, sequence_number, surface_key, display_name, surface_definition,
  audience_access_status, real_audience_present, customer_data_enabled,
  financial_execution_enabled, production_effect
from public.external_audience_launch_surface_templates;

create view public.external_audience_launch_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, launch_domain, display_name, gate_definition,
  gate_status, real_evidence_present, reviewer_assigned, human_authorized
from public.external_audience_launch_gate_templates;

create view public.external_audience_launch_readiness_catalog with (security_invoker=true) as
select matrix.id, surface.surface_key, surface.sequence_number surface_sequence_number,
  surface.display_name surface_name, gate.gate_key, gate.sequence_number gate_sequence_number,
  gate.display_name gate_name, gate.launch_domain, matrix.readiness_status,
  matrix.human_authorized, matrix.public_access_effect, matrix.account_provisioning_effect,
  matrix.customer_data_effect, matrix.live_provider_effect, matrix.publication_effect,
  matrix.financial_execution_effect, matrix.release_effect, matrix.production_effect
from public.external_audience_launch_readiness_matrix matrix
join public.external_audience_launch_surface_templates surface on surface.id = matrix.surface_template_id
join public.external_audience_launch_gate_templates gate on gate.id = matrix.gate_template_id;

grant select on public.external_audience_launch_status,
  public.external_audience_launch_state_catalog,
  public.external_audience_launch_surface_catalog,
  public.external_audience_launch_gate_catalog,
  public.external_audience_launch_readiness_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.external_audience_launch_state_templates) <> 7
    or (select count(*) from public.external_audience_launch_surface_templates) <> 8
    or (select count(*) from public.external_audience_launch_gate_templates) <> 8
    or (select count(*) from public.external_audience_launch_readiness_matrix) <> 64 then
    raise exception 'Phase 8U external audience launch-readiness reference counts changed';
  end if;
  if exists (
    select 1 from public.external_audience_launch_controls
    where public_signup_enabled or unrestricted_discovery_enabled
      or automated_tester_provisioning_enabled or external_audience_activation_enabled
      or live_provider_connectivity_enabled or production_credential_storage_enabled
      or production_payload_intake_enabled or unrestricted_customer_data_collection_enabled
      or autonomous_publication_enabled or model_training_enabled or live_order_routing_enabled
      or payment_execution_enabled or money_movement_enabled or custody_enabled or settlement_enabled
  ) or exists (
    select 1 from public.external_audience_launch_state_templates
    where real_audience_present or automatic_transition_enabled
      or not human_launch_authorization_required or public_access_effect
      or customer_data_effect or financial_execution_effect or production_effect
  ) or exists (
    select 1 from public.external_audience_launch_surface_templates
    where audience_access_status <> 'unavailable' or real_audience_present
      or customer_data_enabled or financial_execution_enabled or production_effect
  ) or exists (
    select 1 from public.external_audience_launch_gate_templates
    where gate_status <> 'unmet' or real_evidence_present or reviewer_assigned or human_authorized
  ) or exists (
    select 1 from public.external_audience_launch_readiness_matrix
    where readiness_status <> 'blocked' or evidence_reference is not null
      or reviewer_identity is not null or authorization_reference is not null
      or cohort_reference is not null or rollback_reference is not null
      or verified_at is not null or expires_at is not null or human_authorized
      or public_access_effect or account_provisioning_effect or customer_data_effect
      or live_provider_effect or publication_effect or financial_execution_effect
      or release_effect or production_effect
  ) then
    raise exception 'Phase 8U external audience launch readiness must remain empty and fail-closed';
  end if;
end;
$$;

commit;
