-- TradePulse AI
-- Migration 065: Phase 8V licensed live-data integration foundation
-- Reference controls only. No provider, credential, payload, live display,
-- external audience, production launch, financial execution or payment exists.

begin;

create table public.licensed_live_data_integration_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  feed_class_target integer not null default 8 check (feed_class_target = 8),
  integration_gate_target integer not null default 8 check (integration_gate_target = 8),
  readiness_cell_target integer not null default 64 check (readiness_cell_target = 64),
  integration_state_target integer not null default 7 check (integration_state_target = 7),
  executed_data_license_required boolean not null default true check (executed_data_license_required),
  permitted_display_and_derived_use_required boolean not null default true check (permitted_display_and_derived_use_required),
  jurisdiction_and_audience_entitlements_required boolean not null default true check (jurisdiction_and_audience_entitlements_required),
  credential_vault_and_egress_controls_required boolean not null default true check (credential_vault_and_egress_controls_required),
  schema_identity_and_corporate_action_mapping_required boolean not null default true check (schema_identity_and_corporate_action_mapping_required),
  freshness_clock_quality_and_gap_controls_required boolean not null default true check (freshness_clock_quality_and_gap_controls_required),
  quota_backpressure_replay_and_failover_required boolean not null default true check (quota_backpressure_replay_and_failover_required),
  observability_cost_incident_and_rollback_required boolean not null default true check (observability_cost_incident_and_rollback_required),
  independent_human_integration_authorization_required boolean not null default true check (independent_human_integration_authorization_required),
  provider_selected boolean not null default false check (not provider_selected),
  live_provider_connectivity_enabled boolean not null default false check (not live_provider_connectivity_enabled),
  production_credential_storage_enabled boolean not null default false check (not production_credential_storage_enabled),
  production_payload_intake_enabled boolean not null default false check (not production_payload_intake_enabled),
  live_data_display_enabled boolean not null default false check (not live_data_display_enabled),
  derived_data_publication_enabled boolean not null default false check (not derived_data_publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  external_audience_activation_enabled boolean not null default false check (not external_audience_activation_enabled),
  public_signup_enabled boolean not null default false check (not public_signup_enabled),
  live_order_routing_enabled boolean not null default false check (not live_order_routing_enabled),
  payment_execution_enabled boolean not null default false check (not payment_execution_enabled),
  money_movement_enabled boolean not null default false check (not money_movement_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  settlement_enabled boolean not null default false check (not settlement_enabled),
  updated_at timestamptz not null default now()
);

insert into public.licensed_live_data_integration_controls (control_key, policy_version)
values ('licensed-live-data-integration-controls', 'licensed-live-data-integration-controls-v1');

create table public.licensed_live_data_integration_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 360),
  provider_present boolean not null default false check (not provider_present),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_integration_authorization_required boolean not null default true check (human_integration_authorization_required),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  payload_intake_effect boolean not null default false check (not payload_intake_effect),
  live_display_effect boolean not null default false check (not live_display_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.licensed_live_data_integration_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'integration_not_requested','Integration not requested','No licensed live-data integration request or provider selection exists; credentials, payloads, display and every production effect remain unavailable.'),
  (2,'license_evidence_required','License evidence required','A future integration requires executed license terms covering the exact products, venues, fields, audience, jurisdictions, display, derivation, retention and model use.'),
  (3,'entitlement_mapping_required','Entitlement mapping required','Every future account, audience, geography and product must map to explicit display and non-display entitlements with fail-closed unavailable states.'),
  (4,'isolated_certification_required','Isolated certification required','A provider-specific adapter must pass isolated schema, identity, clock, freshness, gap, replay, quota and failure drills using approved non-customer fixtures.'),
  (5,'production_canary_authorization_required','Production canary authorization required','A bounded canary requires independent approval, vaulted credentials, restricted egress, zero customer exposure, stop thresholds and tested rollback.'),
  (6,'monitored_live_data_window_required','Monitored live-data window required','A future live-data window must be time-bounded and staffed with freshness, quality, entitlement, quota, cost and incident monitoring before display.'),
  (7,'suspended_or_revoked','Suspended or revoked','Expired rights, stale evidence, quality failure, entitlement conflict or incident must revoke access, stop intake, preserve evidence and confirm no residual display.');

create table public.licensed_live_data_feed_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  feed_key text not null unique,
  display_name text not null unique,
  feed_definition text not null check (char_length(feed_definition) between 40 and 360),
  availability_status text not null default 'unavailable' check (availability_status = 'unavailable'),
  provider_selected boolean not null default false check (not provider_selected),
  rights_evidence_present boolean not null default false check (not rights_evidence_present),
  credential_present boolean not null default false check (not credential_present),
  real_payload_present boolean not null default false check (not real_payload_present),
  live_display_enabled boolean not null default false check (not live_display_enabled),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.licensed_live_data_feed_templates (
  sequence_number, feed_key, display_name, feed_definition
) values
  (1,'instrument_reference_master','Instrument reference master','Canonical instrument, listing, identifier, currency and lifecycle records require licensed source rights and deterministic identity reconciliation.'),
  (2,'venue_calendars_and_sessions','Venue calendars and sessions','Trading sessions, holidays, phases, time zones and exceptional closures require authoritative rights, clock controls and explicit unavailable states.'),
  (3,'quotes_and_top_of_book','Quotes and top of book','Bid, ask, size and quote-condition data require venue-level display entitlements, freshness thresholds, stale labels, throttling and gap handling.'),
  (4,'trades_and_aggregated_bars','Trades and aggregated bars','Trades, corrections, cancellations and derived bars require permitted use, sequence handling, replay safety and transparent latency labels.'),
  (5,'corporate_actions_and_identifiers','Corporate actions and identifiers','Splits, dividends, symbol changes, mergers and identifier histories require effective-date reconciliation and independent adjustment verification.'),
  (6,'fundamentals_and_company_reference','Fundamentals and company reference','Issuer, filing, fundamental and classification fields require source-level rights, point-in-time semantics, restatement handling and provenance.'),
  (7,'fx_rates_and_cross_asset_reference','FX rates and cross-asset reference','FX, rates and cross-asset reference values require source attribution, timestamp and tenor semantics, conversion controls and no executable-price claim.'),
  (8,'news_events_and_source_metadata','News, events and source metadata','Licensed news and event metadata require source rights, attribution, correction, embargo, retention and non-publication controls for every item.');

create table public.licensed_live_data_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique,
  integration_domain text not null check (integration_domain in ('legal','entitlement','security','mapping','quality','resilience','operations','release')),
  display_name text not null unique,
  gate_definition text not null check (char_length(gate_definition) between 40 and 360),
  gate_status text not null default 'unmet' check (gate_status = 'unmet'),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  reviewer_assigned boolean not null default false check (not reviewer_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.licensed_live_data_gate_templates (
  sequence_number, gate_key, integration_domain, display_name, gate_definition
) values
  (1,'executed_license_and_permitted_use_verified','legal','License and permitted use verified','Require executed terms for the exact product, venue, field, display, derivation, redistribution, retention, audit, model-use and termination rights.'),
  (2,'jurisdiction_audience_and_entitlements_verified','entitlement','Audience and entitlements verified','Require explicit audience, account, jurisdiction, venue and display or non-display entitlements with deny-by-default enforcement and expiry.'),
  (3,'vault_egress_and_secret_rotation_verified','security','Vault, egress and secret rotation verified','Require approved secret custody, least privilege, provider host allowlists, certificate validation, rotation, revocation and zero browser exposure.'),
  (4,'schema_identity_and_corporate_action_mapping_verified','mapping','Schema and identity mapping verified','Require versioned field mapping, canonical identifiers, listing identity, currencies, units, conditions, corporate actions and conflict quarantine.'),
  (5,'freshness_clock_quality_gap_and_stale_state_verified','quality','Freshness and quality controls verified','Require clock synchronization, latency budgets, ordering, duplicates, corrections, gaps, stale-state labels, quality thresholds and deterministic fallback.'),
  (6,'quota_backpressure_replay_idempotency_and_failover_verified','resilience','Resilience and replay controls verified','Require rate and cost ceilings, backpressure, reconnect, replay, idempotency, recovery-point evidence, provider outage handling and fail-closed failover.'),
  (7,'observability_cost_support_and_incident_ownership_verified','operations','Operations and incident ownership verified','Require privacy-safe telemetry, freshness and entitlement alerts, cost monitoring, staffed ownership, provider escalation, status communication and incident drills.'),
  (8,'bounded_canary_rollback_expiry_and_independent_review_approved','release','Canary and rollback review approved','Require an isolated bounded canary, independent review, zero customer exposure, stop thresholds, rollback, expiry, closeout and explicit production authorization.');

create table public.licensed_live_data_readiness_matrix (
  id bigint generated by default as identity primary key,
  feed_template_id bigint not null references public.licensed_live_data_feed_templates(id),
  gate_template_id bigint not null references public.licensed_live_data_gate_templates(id),
  readiness_status text not null default 'blocked' check (readiness_status = 'blocked'),
  provider_reference text check (provider_reference is null),
  evidence_reference text check (evidence_reference is null),
  entitlement_reference text check (entitlement_reference is null),
  credential_reference text check (credential_reference is null),
  adapter_reference text check (adapter_reference is null),
  reviewer_identity text check (reviewer_identity is null),
  authorization_reference text check (authorization_reference is null),
  rollback_reference text check (rollback_reference is null),
  verified_at timestamptz check (verified_at is null),
  expires_at timestamptz check (expires_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  provider_egress_effect boolean not null default false check (not provider_egress_effect),
  payload_intake_effect boolean not null default false check (not payload_intake_effect),
  live_display_effect boolean not null default false check (not live_display_effect),
  audience_effect boolean not null default false check (not audience_effect),
  publication_effect boolean not null default false check (not publication_effect),
  financial_execution_effect boolean not null default false check (not financial_execution_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (feed_template_id, gate_template_id)
);

insert into public.licensed_live_data_readiness_matrix (feed_template_id, gate_template_id)
select feed.id, gate.id
from public.licensed_live_data_feed_templates feed
cross join public.licensed_live_data_gate_templates gate
order by feed.sequence_number, gate.sequence_number;

alter table public.licensed_live_data_integration_controls enable row level security;
alter table public.licensed_live_data_integration_state_templates enable row level security;
alter table public.licensed_live_data_feed_templates enable row level security;
alter table public.licensed_live_data_gate_templates enable row level security;
alter table public.licensed_live_data_readiness_matrix enable row level security;

create policy "Public reads licensed live-data integration controls" on public.licensed_live_data_integration_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads licensed live-data integration states" on public.licensed_live_data_integration_state_templates
  for select to anon, authenticated using (not provider_present and not real_evidence_present);
create policy "Public reads unavailable licensed feed classes" on public.licensed_live_data_feed_templates
  for select to anon, authenticated using (availability_status = 'unavailable' and not provider_selected and not real_payload_present);
create policy "Public reads unmet licensed live-data gates" on public.licensed_live_data_gate_templates
  for select to anon, authenticated using (gate_status = 'unmet' and not real_evidence_present);
create policy "Public reads blocked licensed live-data matrix" on public.licensed_live_data_readiness_matrix
  for select to anon, authenticated using (readiness_status = 'blocked' and not human_authorized);

revoke all on table public.licensed_live_data_integration_controls,
  public.licensed_live_data_integration_state_templates,
  public.licensed_live_data_feed_templates,
  public.licensed_live_data_gate_templates,
  public.licensed_live_data_readiness_matrix from public, anon, authenticated, service_role;
grant select on table public.licensed_live_data_integration_controls,
  public.licensed_live_data_integration_state_templates,
  public.licensed_live_data_feed_templates,
  public.licensed_live_data_gate_templates,
  public.licensed_live_data_readiness_matrix to anon, authenticated, service_role;

create or replace function public.prevent_licensed_live_data_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Licensed live-data integration reference records are append-only';
end;
$$;
revoke all on function public.prevent_licensed_live_data_reference_mutation() from public, anon, authenticated, service_role;

create trigger licensed_live_data_controls_append_only before update or delete on public.licensed_live_data_integration_controls
  for each row execute function public.prevent_licensed_live_data_reference_mutation();
create trigger licensed_live_data_states_append_only before update or delete on public.licensed_live_data_integration_state_templates
  for each row execute function public.prevent_licensed_live_data_reference_mutation();
create trigger licensed_live_data_feeds_append_only before update or delete on public.licensed_live_data_feed_templates
  for each row execute function public.prevent_licensed_live_data_reference_mutation();
create trigger licensed_live_data_gates_append_only before update or delete on public.licensed_live_data_gate_templates
  for each row execute function public.prevent_licensed_live_data_reference_mutation();
create trigger licensed_live_data_matrix_append_only before update or delete on public.licensed_live_data_readiness_matrix
  for each row execute function public.prevent_licensed_live_data_reference_mutation();

create view public.licensed_live_data_integration_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.licensed_live_data_feed_templates)::integer feed_class_count,
  (select count(*) from public.licensed_live_data_gate_templates)::integer integration_gate_count,
  (select count(*) from public.licensed_live_data_integration_state_templates)::integer integration_state_count,
  (select count(*) from public.licensed_live_data_readiness_matrix)::integer readiness_cell_count,
  (select count(*) from public.licensed_live_data_readiness_matrix where readiness_status = 'blocked')::integer blocked_readiness_cell_count,
  (select count(*) from public.licensed_live_data_readiness_matrix where human_authorized)::integer authorized_readiness_cell_count
from public.licensed_live_data_integration_controls control;

create view public.licensed_live_data_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  provider_present, real_evidence_present, automatic_transition_enabled,
  human_integration_authorization_required, credential_access_effect,
  payload_intake_effect, live_display_effect, production_effect
from public.licensed_live_data_integration_state_templates;

create view public.licensed_live_data_feed_catalog with (security_invoker=true) as
select id, sequence_number, feed_key, display_name, feed_definition,
  availability_status, provider_selected, rights_evidence_present, credential_present,
  real_payload_present, live_display_enabled, production_effect
from public.licensed_live_data_feed_templates;

create view public.licensed_live_data_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, integration_domain, display_name, gate_definition,
  gate_status, real_evidence_present, reviewer_assigned, human_authorized
from public.licensed_live_data_gate_templates;

create view public.licensed_live_data_readiness_catalog with (security_invoker=true) as
select matrix.id, feed.feed_key, feed.sequence_number feed_sequence_number,
  feed.display_name feed_name, gate.gate_key, gate.sequence_number gate_sequence_number,
  gate.display_name gate_name, gate.integration_domain, matrix.readiness_status,
  matrix.human_authorized, matrix.credential_access_effect, matrix.provider_egress_effect,
  matrix.payload_intake_effect, matrix.live_display_effect, matrix.audience_effect,
  matrix.publication_effect, matrix.financial_execution_effect, matrix.release_effect,
  matrix.production_effect
from public.licensed_live_data_readiness_matrix matrix
join public.licensed_live_data_feed_templates feed on feed.id = matrix.feed_template_id
join public.licensed_live_data_gate_templates gate on gate.id = matrix.gate_template_id;

grant select on public.licensed_live_data_integration_status,
  public.licensed_live_data_state_catalog,
  public.licensed_live_data_feed_catalog,
  public.licensed_live_data_gate_catalog,
  public.licensed_live_data_readiness_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.licensed_live_data_integration_state_templates) <> 7
    or (select count(*) from public.licensed_live_data_feed_templates) <> 8
    or (select count(*) from public.licensed_live_data_gate_templates) <> 8
    or (select count(*) from public.licensed_live_data_readiness_matrix) <> 64 then
    raise exception 'Phase 8V licensed live-data integration reference counts changed';
  end if;
  if exists (
    select 1 from public.licensed_live_data_integration_controls
    where provider_selected or live_provider_connectivity_enabled
      or production_credential_storage_enabled or production_payload_intake_enabled
      or live_data_display_enabled or derived_data_publication_enabled or model_training_enabled
      or external_audience_activation_enabled or public_signup_enabled or live_order_routing_enabled
      or payment_execution_enabled or money_movement_enabled or custody_enabled or settlement_enabled
  ) or exists (
    select 1 from public.licensed_live_data_integration_state_templates
    where provider_present or real_evidence_present or automatic_transition_enabled
      or not human_integration_authorization_required or credential_access_effect
      or payload_intake_effect or live_display_effect or production_effect
  ) or exists (
    select 1 from public.licensed_live_data_feed_templates
    where availability_status <> 'unavailable' or provider_selected or rights_evidence_present
      or credential_present or real_payload_present or live_display_enabled or production_effect
  ) or exists (
    select 1 from public.licensed_live_data_gate_templates
    where gate_status <> 'unmet' or real_evidence_present or reviewer_assigned or human_authorized
  ) or exists (
    select 1 from public.licensed_live_data_readiness_matrix
    where readiness_status <> 'blocked' or provider_reference is not null
      or evidence_reference is not null or entitlement_reference is not null
      or credential_reference is not null or adapter_reference is not null
      or reviewer_identity is not null or authorization_reference is not null
      or rollback_reference is not null or verified_at is not null or expires_at is not null
      or human_authorized or credential_access_effect or provider_egress_effect
      or payload_intake_effect or live_display_effect or audience_effect
      or publication_effect or financial_execution_effect or release_effect or production_effect
  ) then
    raise exception 'Phase 8V licensed live-data integration must remain empty and fail-closed';
  end if;
end;
$$;

commit;
