-- TradePulse AI
-- Migration 066: Phase 8W licensed-provider commercial-readiness foundation
-- Reference controls only. No provider shortlist, quote acceptance, signature,
-- purchase order, credential, payload, live display or production effect exists.

begin;

create table public.licensed_provider_commercial_readiness_controls (
  id bigint generated by default as identity primary key,
  control_key text not null unique,
  policy_version text not null,
  workspace_enabled boolean not null default true check (workspace_enabled),
  commercial_domain_target integer not null default 8 check (commercial_domain_target = 8),
  commercial_gate_target integer not null default 8 check (commercial_gate_target = 8),
  readiness_cell_target integer not null default 64 check (readiness_cell_target = 64),
  commercial_state_target integer not null default 7 check (commercial_state_target = 7),
  corporate_identity_and_beneficial_ownership_required boolean not null default true check (corporate_identity_and_beneficial_ownership_required),
  product_coverage_and_rights_schedule_required boolean not null default true check (product_coverage_and_rights_schedule_required),
  entitlement_and_redistribution_terms_required boolean not null default true check (entitlement_and_redistribution_terms_required),
  commercial_pricing_and_cost_ceiling_required boolean not null default true check (commercial_pricing_and_cost_ceiling_required),
  security_privacy_and_subprocessor_review_required boolean not null default true check (security_privacy_and_subprocessor_review_required),
  service_level_support_and_incident_terms_required boolean not null default true check (service_level_support_and_incident_terms_required),
  implementation_acceptance_and_change_control_required boolean not null default true check (implementation_acceptance_and_change_control_required),
  exit_portability_deletion_and_termination_required boolean not null default true check (exit_portability_deletion_and_termination_required),
  independent_human_commercial_authorization_required boolean not null default true check (independent_human_commercial_authorization_required),
  provider_shortlisted boolean not null default false check (not provider_shortlisted),
  pricing_quote_accepted boolean not null default false check (not pricing_quote_accepted),
  contract_signed boolean not null default false check (not contract_signed),
  purchase_order_issued boolean not null default false check (not purchase_order_issued),
  provider_selected boolean not null default false check (not provider_selected),
  live_provider_connectivity_enabled boolean not null default false check (not live_provider_connectivity_enabled),
  production_credential_storage_enabled boolean not null default false check (not production_credential_storage_enabled),
  production_payload_intake_enabled boolean not null default false check (not production_payload_intake_enabled),
  live_data_display_enabled boolean not null default false check (not live_data_display_enabled),
  derived_data_publication_enabled boolean not null default false check (not derived_data_publication_enabled),
  model_training_enabled boolean not null default false check (not model_training_enabled),
  external_audience_activation_enabled boolean not null default false check (not external_audience_activation_enabled),
  public_signup_enabled boolean not null default false check (not public_signup_enabled),
  live_order_routing_enabled boolean not null default false check (not live_order_routing_enabled),
  payment_execution_enabled boolean not null default false check (not payment_execution_enabled),
  money_movement_enabled boolean not null default false check (not money_movement_enabled),
  custody_enabled boolean not null default false check (not custody_enabled),
  settlement_enabled boolean not null default false check (not settlement_enabled),
  updated_at timestamptz not null default now()
);

insert into public.licensed_provider_commercial_readiness_controls (control_key, policy_version)
values ('licensed-provider-commercial-readiness-controls', 'licensed-provider-commercial-readiness-controls-v1');

create table public.licensed_provider_commercial_readiness_state_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 7),
  state_key text not null unique,
  display_name text not null unique,
  state_definition text not null check (char_length(state_definition) between 40 and 360),
  provider_present boolean not null default false check (not provider_present),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  automatic_transition_enabled boolean not null default false check (not automatic_transition_enabled),
  human_commercial_authorization_required boolean not null default true check (human_commercial_authorization_required),
  provider_selection_effect boolean not null default false check (not provider_selection_effect),
  commercial_commitment_effect boolean not null default false check (not commercial_commitment_effect),
  contract_signature_effect boolean not null default false check (not contract_signature_effect),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  payload_intake_effect boolean not null default false check (not payload_intake_effect),
  live_display_effect boolean not null default false check (not live_display_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.licensed_provider_commercial_readiness_state_templates (
  sequence_number, state_key, display_name, state_definition
) values
  (1,'commercial_review_not_requested','Commercial review not requested','No provider shortlist, quote, commercial review, signature request or purchase commitment exists; every downstream capability remains unavailable.'),
  (2,'corporate_due_diligence_required','Corporate due diligence required','A future review requires verified legal identity, beneficial ownership, sanctions screening, financial stability, insurance and accountable contracting authority.'),
  (3,'rights_and_entitlements_schedule_required','Rights and entitlements schedule required','Exact products, venues, fields, jurisdictions, audiences, devices, display, non-display, derivation, model-use and redistribution rights must be explicit.'),
  (4,'security_and_operational_terms_required','Security and operational terms required','Security, privacy, subprocessors, audit, service levels, support, incident response, change control, acceptance and remedies must be independently reviewed.'),
  (5,'commercial_model_approval_required','Commercial model approval required','Currency, taxes, minimum commitments, user and device metrics, overages, audit exposure, forecast usage and a hard total-cost ceiling require approval.'),
  (6,'signature_readiness_review_required','Signature readiness review required','A signature-ready package requires reconciled schedules, redlines, accountable owners, implementation acceptance, exit protections and independent authorization.'),
  (7,'withdrawn_expired_or_rejected','Withdrawn, expired or rejected','Stale evidence, unacceptable rights, security risk, cost breach, unresolved redlines or failed ownership must close review without selection or commitment.');

create table public.licensed_provider_commercial_domain_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  domain_key text not null unique,
  display_name text not null unique,
  domain_definition text not null check (char_length(domain_definition) between 40 and 360),
  availability_status text not null default 'unavailable' check (availability_status = 'unavailable'),
  provider_shortlisted boolean not null default false check (not provider_shortlisted),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  quote_present boolean not null default false check (not quote_present),
  contract_present boolean not null default false check (not contract_present),
  commercial_commitment_enabled boolean not null default false check (not commercial_commitment_enabled),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now()
);

insert into public.licensed_provider_commercial_domain_templates (
  sequence_number, domain_key, display_name, domain_definition
) values
  (1,'corporate_ownership_and_financial_stability','Corporate ownership and financial stability','Verify the contracting entity, beneficial ownership, sanctions position, audited financial resilience, insurance and authority to provide the proposed service.'),
  (2,'product_venue_and_geography_coverage','Product, venue and geography coverage','Reconcile instruments, venues, regions, fields, history, latency classes, roadmap exclusions and dependencies against the approved product requirement.'),
  (3,'display_derived_and_redistribution_rights','Display, derived and redistribution rights','Define end-user display, derived works, caching, redistribution, screenshots, exports, research publication, retention and termination treatment.'),
  (4,'entitlement_user_device_and_non_display_scope','Entitlement, user, device and non-display scope','Define users, organizations, devices, environments, geography, applications, non-display processing, metering, reporting, audit and expiry obligations.'),
  (5,'pricing_minimums_overage_and_total_cost','Pricing, minimums, overage and total cost','Model currency, tax, minimum commitments, tiers, user and device counts, request or symbol overages, support fees, audit exposure and exit costs.'),
  (6,'security_privacy_subprocessors_and_audit','Security, privacy, subprocessors and audit','Review assurance reports, data handling, subprocessors, breach notice, vulnerability ownership, access controls, deletion, audit and regulatory cooperation.'),
  (7,'service_levels_support_incident_and_change','Service levels, support, incident and change','Define availability, latency, support tiers, escalation, incident communications, maintenance, deprecation, change notice, remedies and operational ownership.'),
  (8,'termination_portability_deletion_and_transition','Termination, portability, deletion and transition','Define renewal, termination, data return, deletion evidence, credential revocation, migration assistance, continuing rights and orderly provider replacement.');

create table public.licensed_provider_commercial_gate_templates (
  id bigint generated by default as identity primary key,
  sequence_number smallint not null unique check (sequence_number between 1 and 8),
  gate_key text not null unique,
  review_domain text not null check (review_domain in ('corporate','rights','entitlement','commercial','security','operations','implementation','exit')),
  display_name text not null unique,
  gate_definition text not null check (char_length(gate_definition) between 40 and 360),
  gate_status text not null default 'unmet' check (gate_status = 'unmet'),
  real_evidence_present boolean not null default false check (not real_evidence_present),
  reviewer_assigned boolean not null default false check (not reviewer_assigned),
  human_authorized boolean not null default false check (not human_authorized),
  created_at timestamptz not null default now()
);

insert into public.licensed_provider_commercial_gate_templates (
  sequence_number, gate_key, review_domain, display_name, gate_definition
) values
  (1,'corporate_identity_ownership_sanctions_and_stability_verified','corporate','Corporate diligence verified','Require verified contracting identity, beneficial ownership, sanctions checks, financial stability, insurance and accountable signature authority.'),
  (2,'product_coverage_rights_and_roadmap_verified','rights','Coverage and rights schedule verified','Require reconciled products, venues, fields, history, geography, display, derivation, redistribution, retention, model-use and roadmap commitments.'),
  (3,'entitlement_metering_reporting_and_audit_terms_verified','entitlement','Entitlement terms verified','Require explicit user, device, organization, environment, jurisdiction, non-display, metering, reporting, audit, expiry and revocation terms.'),
  (4,'pricing_commit_overage_currency_tax_and_cost_ceiling_approved','commercial','Commercial model approved','Require approved currency, tax, minimum commitment, tiers, overages, support fees, forecast usage, audit exposure, exit costs and total-cost ceiling.'),
  (5,'security_privacy_subprocessors_and_assurance_verified','security','Security and privacy terms verified','Require assurance evidence, privacy terms, subprocessors, breach notice, access controls, vulnerability ownership, deletion and regulatory cooperation.'),
  (6,'sla_support_incident_change_and_remedies_verified','operations','Service and support terms verified','Require measurable availability and latency, support and escalation, incident communication, maintenance, deprecation, change notice and remedies.'),
  (7,'implementation_acceptance_ownership_and_change_control_verified','implementation','Implementation acceptance verified','Require named owners, delivery plan, acceptance criteria, environment boundaries, change control, rollback responsibility and no activation by contract alone.'),
  (8,'termination_portability_deletion_transition_and_independent_review_approved','exit','Exit protection review approved','Require termination rights, portability, deletion evidence, credential revocation, migration assistance, continuing-use limits and independent approval.');

create table public.licensed_provider_commercial_readiness_matrix (
  id bigint generated by default as identity primary key,
  domain_template_id bigint not null references public.licensed_provider_commercial_domain_templates(id),
  gate_template_id bigint not null references public.licensed_provider_commercial_gate_templates(id),
  readiness_status text not null default 'blocked' check (readiness_status = 'blocked'),
  provider_reference text check (provider_reference is null),
  evidence_reference text check (evidence_reference is null),
  quote_reference text check (quote_reference is null),
  contract_reference text check (contract_reference is null),
  pricing_reference text check (pricing_reference is null),
  security_review_reference text check (security_review_reference is null),
  reviewer_identity text check (reviewer_identity is null),
  authorization_reference text check (authorization_reference is null),
  exit_plan_reference text check (exit_plan_reference is null),
  verified_at timestamptz check (verified_at is null),
  expires_at timestamptz check (expires_at is null),
  human_authorized boolean not null default false check (not human_authorized),
  provider_selection_effect boolean not null default false check (not provider_selection_effect),
  commercial_commitment_effect boolean not null default false check (not commercial_commitment_effect),
  contract_signature_effect boolean not null default false check (not contract_signature_effect),
  credential_access_effect boolean not null default false check (not credential_access_effect),
  provider_egress_effect boolean not null default false check (not provider_egress_effect),
  payload_intake_effect boolean not null default false check (not payload_intake_effect),
  live_display_effect boolean not null default false check (not live_display_effect),
  audience_effect boolean not null default false check (not audience_effect),
  publication_effect boolean not null default false check (not publication_effect),
  financial_execution_effect boolean not null default false check (not financial_execution_effect),
  release_effect boolean not null default false check (not release_effect),
  production_effect boolean not null default false check (not production_effect),
  created_at timestamptz not null default now(),
  unique (domain_template_id, gate_template_id)
);

insert into public.licensed_provider_commercial_readiness_matrix (domain_template_id, gate_template_id)
select domain.id, gate.id
from public.licensed_provider_commercial_domain_templates domain
cross join public.licensed_provider_commercial_gate_templates gate
order by domain.sequence_number, gate.sequence_number;

alter table public.licensed_provider_commercial_readiness_controls enable row level security;
alter table public.licensed_provider_commercial_readiness_state_templates enable row level security;
alter table public.licensed_provider_commercial_domain_templates enable row level security;
alter table public.licensed_provider_commercial_gate_templates enable row level security;
alter table public.licensed_provider_commercial_readiness_matrix enable row level security;

create policy "Public reads licensed provider commercial controls" on public.licensed_provider_commercial_readiness_controls
  for select to anon, authenticated using (workspace_enabled);
create policy "Public reads licensed provider commercial states" on public.licensed_provider_commercial_readiness_state_templates
  for select to anon, authenticated using (not provider_present and not real_evidence_present);
create policy "Public reads unavailable licensed provider commercial domains" on public.licensed_provider_commercial_domain_templates
  for select to anon, authenticated using (availability_status = 'unavailable' and not provider_shortlisted and not real_evidence_present);
create policy "Public reads unmet licensed provider commercial gates" on public.licensed_provider_commercial_gate_templates
  for select to anon, authenticated using (gate_status = 'unmet' and not real_evidence_present);
create policy "Public reads blocked licensed provider commercial matrix" on public.licensed_provider_commercial_readiness_matrix
  for select to anon, authenticated using (readiness_status = 'blocked' and not human_authorized);

revoke all on table public.licensed_provider_commercial_readiness_controls,
  public.licensed_provider_commercial_readiness_state_templates,
  public.licensed_provider_commercial_domain_templates,
  public.licensed_provider_commercial_gate_templates,
  public.licensed_provider_commercial_readiness_matrix from public, anon, authenticated, service_role;
grant select on table public.licensed_provider_commercial_readiness_controls,
  public.licensed_provider_commercial_readiness_state_templates,
  public.licensed_provider_commercial_domain_templates,
  public.licensed_provider_commercial_gate_templates,
  public.licensed_provider_commercial_readiness_matrix to anon, authenticated, service_role;

create or replace function public.prevent_licensed_provider_commercial_reference_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'Licensed provider commercial-readiness reference records are append-only';
end;
$$;
revoke all on function public.prevent_licensed_provider_commercial_reference_mutation() from public, anon, authenticated, service_role;

create trigger licensed_provider_commercial_controls_append_only before update or delete on public.licensed_provider_commercial_readiness_controls
  for each row execute function public.prevent_licensed_provider_commercial_reference_mutation();
create trigger licensed_provider_commercial_states_append_only before update or delete on public.licensed_provider_commercial_readiness_state_templates
  for each row execute function public.prevent_licensed_provider_commercial_reference_mutation();
create trigger licensed_provider_commercial_domains_append_only before update or delete on public.licensed_provider_commercial_domain_templates
  for each row execute function public.prevent_licensed_provider_commercial_reference_mutation();
create trigger licensed_provider_commercial_gates_append_only before update or delete on public.licensed_provider_commercial_gate_templates
  for each row execute function public.prevent_licensed_provider_commercial_reference_mutation();
create trigger licensed_provider_commercial_matrix_append_only before update or delete on public.licensed_provider_commercial_readiness_matrix
  for each row execute function public.prevent_licensed_provider_commercial_reference_mutation();

create view public.licensed_provider_commercial_readiness_status with (security_invoker=true) as
select control.*,
  (select count(*) from public.licensed_provider_commercial_domain_templates)::integer commercial_domain_count,
  (select count(*) from public.licensed_provider_commercial_gate_templates)::integer commercial_gate_count,
  (select count(*) from public.licensed_provider_commercial_readiness_state_templates)::integer commercial_state_count,
  (select count(*) from public.licensed_provider_commercial_readiness_matrix)::integer readiness_cell_count,
  (select count(*) from public.licensed_provider_commercial_readiness_matrix where readiness_status = 'blocked')::integer blocked_readiness_cell_count,
  (select count(*) from public.licensed_provider_commercial_readiness_matrix where human_authorized)::integer authorized_readiness_cell_count
from public.licensed_provider_commercial_readiness_controls control;

create view public.licensed_provider_commercial_state_catalog with (security_invoker=true) as
select id, sequence_number, state_key, display_name, state_definition,
  provider_present, real_evidence_present, automatic_transition_enabled,
  human_commercial_authorization_required, provider_selection_effect,
  commercial_commitment_effect, contract_signature_effect, credential_access_effect,
  payload_intake_effect, live_display_effect, production_effect
from public.licensed_provider_commercial_readiness_state_templates;

create view public.licensed_provider_commercial_domain_catalog with (security_invoker=true) as
select id, sequence_number, domain_key, display_name, domain_definition,
  availability_status, provider_shortlisted, real_evidence_present, quote_present,
  contract_present, commercial_commitment_enabled, production_effect
from public.licensed_provider_commercial_domain_templates;

create view public.licensed_provider_commercial_gate_catalog with (security_invoker=true) as
select id, sequence_number, gate_key, review_domain, display_name, gate_definition,
  gate_status, real_evidence_present, reviewer_assigned, human_authorized
from public.licensed_provider_commercial_gate_templates;

create view public.licensed_provider_commercial_readiness_catalog with (security_invoker=true) as
select matrix.id, domain.domain_key, domain.sequence_number domain_sequence_number,
  domain.display_name domain_name, gate.gate_key, gate.sequence_number gate_sequence_number,
  gate.display_name gate_name, gate.review_domain, matrix.readiness_status,
  matrix.human_authorized, matrix.provider_selection_effect,
  matrix.commercial_commitment_effect, matrix.contract_signature_effect,
  matrix.credential_access_effect, matrix.provider_egress_effect,
  matrix.payload_intake_effect, matrix.live_display_effect, matrix.audience_effect,
  matrix.publication_effect, matrix.financial_execution_effect, matrix.release_effect,
  matrix.production_effect
from public.licensed_provider_commercial_readiness_matrix matrix
join public.licensed_provider_commercial_domain_templates domain on domain.id = matrix.domain_template_id
join public.licensed_provider_commercial_gate_templates gate on gate.id = matrix.gate_template_id;

grant select on public.licensed_provider_commercial_readiness_status,
  public.licensed_provider_commercial_state_catalog,
  public.licensed_provider_commercial_domain_catalog,
  public.licensed_provider_commercial_gate_catalog,
  public.licensed_provider_commercial_readiness_catalog to anon, authenticated, service_role;

do $$
begin
  if (select count(*) from public.licensed_provider_commercial_readiness_state_templates) <> 7
    or (select count(*) from public.licensed_provider_commercial_domain_templates) <> 8
    or (select count(*) from public.licensed_provider_commercial_gate_templates) <> 8
    or (select count(*) from public.licensed_provider_commercial_readiness_matrix) <> 64 then
    raise exception 'Phase 8W licensed provider commercial-readiness reference counts changed';
  end if;
  if exists (
    select 1 from public.licensed_provider_commercial_readiness_controls
    where provider_shortlisted or pricing_quote_accepted or contract_signed
      or purchase_order_issued or provider_selected or live_provider_connectivity_enabled
      or production_credential_storage_enabled or production_payload_intake_enabled
      or live_data_display_enabled or derived_data_publication_enabled or model_training_enabled
      or external_audience_activation_enabled or public_signup_enabled or live_order_routing_enabled
      or payment_execution_enabled or money_movement_enabled or custody_enabled or settlement_enabled
  ) or exists (
    select 1 from public.licensed_provider_commercial_readiness_state_templates
    where provider_present or real_evidence_present or automatic_transition_enabled
      or not human_commercial_authorization_required or provider_selection_effect
      or commercial_commitment_effect or contract_signature_effect or credential_access_effect
      or payload_intake_effect or live_display_effect or production_effect
  ) or exists (
    select 1 from public.licensed_provider_commercial_domain_templates
    where availability_status <> 'unavailable' or provider_shortlisted or real_evidence_present
      or quote_present or contract_present or commercial_commitment_enabled or production_effect
  ) or exists (
    select 1 from public.licensed_provider_commercial_gate_templates
    where gate_status <> 'unmet' or real_evidence_present or reviewer_assigned or human_authorized
  ) or exists (
    select 1 from public.licensed_provider_commercial_readiness_matrix
    where readiness_status <> 'blocked' or provider_reference is not null
      or evidence_reference is not null or quote_reference is not null
      or contract_reference is not null or pricing_reference is not null
      or security_review_reference is not null
      or reviewer_identity is not null or authorization_reference is not null
      or exit_plan_reference is not null or verified_at is not null or expires_at is not null
      or human_authorized or provider_selection_effect or commercial_commitment_effect
      or contract_signature_effect or credential_access_effect or provider_egress_effect
      or payload_intake_effect or live_display_effect or audience_effect
      or publication_effect or financial_execution_effect or release_effect or production_effect
  ) then
    raise exception 'Phase 8W licensed provider commercial readiness must remain empty and fail-closed';
  end if;
end;
$$;

commit;
